Scille/parsec-cloud

parsec/crypto.py, tests/test_crypto.py
Je n'ai pas conservé l'API d'Antoine car elle retournait les éléments de chiffrements [les uns séparés des atures](https://github.com/Scille/parsec-cloud/blob/pubkeyservice-in-backend/parsec/crypto/crypto.py#L38), c'est beaucoup plus intéressant de cacher ça dans l'implémentation  et de retourner un `bytes` standard.
=> Add AESKey to crypto module, RSAPrivateKey supports long text encryption

parsec/ui/fuse.py
Added st_blocks in fuse.getattr to display the correct size when executing du -sh on mountpoint
=> Fix du -sh displaying 0

.gitignore, .pre-commit-config.yaml
Pre-commit can be installed using:
```console
$ pip install pre-commit
$ pre-commit install
```
Then black will run before each commit, but only on the staged chunks.
=> Add pre-commit config

parsec/cli.py, tests/test_cli.py
Usage:
```
$ parsec --version
parsec, version 0.8.3
```
=>  Add version option to parsec cli 

Procfile, parsec/backend/cli.py, tests/test_cli.py
For more consistency with the `parsec backend init` command.
=>  Rename --store option to --db in parsec backend run command

misc/initialize_test_organization.py, misc/run_test_environment.sh, parsec/core/backend_connection/event_listener.py
This script create a temporary environment and initialize a test setup for parsec.
Example:
```console
$ misc/run_test_environment.sh
Configure your test environment with the following variables:
export XDG_CACHE_HOME=/tmp/tmp.JOO4qgQJtY/cache
export XDG_DATA_HOME=/tmp/tmp.JOO4qgQJtY/share
export XDG_CONFIG_HOME=/tmp/tmp.JOO4qgQJtY/config
Starting Parsec Backend on 127.0.0.1:6888 (db=MOCKED, blockstore=MOCKED)
Mount alice and bob drives using:
$ parsec core run -P test -D alice@laptop
$ parsec core run -P test -D alice@pc
$ parsec core run -P test -D bob@laptop
$ export XDG_CACHE_HOME=/tmp/tmp.JOO4qgQJtY/cache 
$ export XDG_DATA_HOME=/tmp/tmp.JOO4qgQJtY/share
$ export XDG_CONFIG_HOME=/tmp/tmp.JOO4qgQJtY/config
$ parsec core run -P test -D alice@laptop
alice@laptop's drive mounted at …
```
=>  Add misc/run_test_environment.sh script 

parsec/core/cli/run.py, parsec/core/logged_core.py, parsec/core/mountpoint/manager.py, parsec/core/mountpoint/not_available.py, parsec/core/mountpoint/thread.py, tests/core/mountpoint/test_fuse_mount.py
Fuse mountpoint on linux can be unmounted using `fusermount -u`. More generally, the mountpoint manager should be able to manage an unmounting operation coming from the OS. This PR refactors the mountpoint manager a bit to be more consistent with this use-case. 
It also integrates this use-case into the `parsec core run` command:
```console
$ source misc/run_test_environment.sh
[...]
$ parsec core run -P test -D corp:alice@laptop
alice@laptop's drive mounted at ~/parsec_mnt/alice@laptop
[...]
```
In another console
```console
$ fusermount -u ~/parsec_mnt/alice@laptop
```
The `parsec core run` command should then stop.
Some extra refactoring has been made on #145.
=> Make the fuse mountpoint manager joinable 

tests/core/test_devices_manager.py
Fix #169 
Il semblerait que la feature était déjà implémenté par 08200c2ed77d90a9c58605210efd3bd0fe7a093a
Du coup j'ai juste ajouté un test
=> Add test_same_device_id_different_orginazations

parsec/core/backend_connection/event_listener.py, parsec/core/base.py, parsec/core/gui/bootstrap_organization_widget.py, parsec/core/gui/claim_device_widget.py, parsec/core/gui/claim_user_widget.py, parsec/core/gui/register_device_dialog.py, parsec/core/gui/register_user_dialog.py, parsec/core/messages_monitor.py, parsec/core/mountpoint/thread.py, parsec/core/sync_monitor.py
https://github.com/python-trio/trio/issues/607
https://github.com/python-trio/trio-asyncio/commit/4990c61421486c24095099a961c5b6a7f4110cdc
Doesn't change anything, I just don't like warnings :p
=> Switched from trio.open_cancel_scope() (deprecated) to trio.CancelScope()

parsec/backend/app.py, parsec/backend/events.py, parsec/backend/user.py, parsec/core/backend_connection/event_listener.py, parsec/core/backend_connection/monitor.py, parsec/core/beacons_monitor.py, parsec/core/messages_monitor.py, parsec/core/sync_monitor.py, parsec/event_bus.py, tests/backend/test_events.py, tests/core/test_cross_cores_sync.py, tests/event_bus_spy.py, tests/test_event_bus.py
J'ai eu un bug très bizarre sous windows: la configuration de structlog semble sauvegarder des frames (j'imagine que c'est en rapport avec pytest qui garde en cache les logs, ceux-ci n'étant pas formattés en string à ce moment...)
De fait si la frame de `EventsComponent.api_events_subscribe` se fait enregistrée, elle garde une référence sur les callbacks des events. Du coup si on essait de remplacer ces callbacks, ceux-ci restent vivant...
config:
```
Python 3.6.5
pytest==4.2.0
pytest-cov==2.6.0
pytest-forked==0.2
pytest-logbook==1.2.0
pytest-trio==0.5.1
pytest-xdist==1.24.1
pip freeze | grep structlog
structlog==18.2.0
```
Au final pas sûr que cette PR doit être mergée (je n'ai corrigé que les events sur backend car c'est ceux qui provoquent le bug, mais il y a aussi des weak refs dans …
=> Event weakref clash with logging

parsec/core/fs/fs.py, parsec/core/fs/local_folder_fs.py, tests/core/fs/test_local_folder_fs.py
As decided [here](https://github.com/Scille/parsec-cloud/issues/120#issuecomment-465519751), `copy` should not be part of the filesystem API.
=> Remove copy from filesystem api

misc/initialize_test_organization.py, parsec/api/protocole/__init__.py, parsec/api/protocole/handshake.py, parsec/backend/app.py, parsec/backend/config.py, parsec/core/backend_connection/__init__.py, parsec/core/backend_connection/porcelain.py, parsec/core/backend_connection/transport.py, parsec/core/cli/create_organization.py, tests/backend/test_handshake.py, tests/backend/test_organization.py, tests/conftest.py, tests/core/backend_connection/test_base.py, tests/test_cli.py, tests/test_handshake.py
divide between anonymous/authenticated/administration on authentications
Le système d'authentification manquait de clarté dans certains cas: le token d'administration été passé comme si c'était un organization_id, du coup si le token configuré n'a pas le format d'un OrganizationID (si il est trop long typiquement), on se retrouve avec des erreurs vraiment pas clair:
```
(venv) ~/projects/parsec-cloud rework-blockstore ⇈6±29*90 ♦ parsec core create_organization Org42 --addr ws://localhost:6777 -T <bad-token>
Creating organization in backend ⠦2019-02-28 10:33:45 [warning  ] Handshake failed               [parsec.api.transport] conn_id=035e7a6055224b21ba311a8da3738ca5 reason=InvalidMessageError("Bad `result` handshake: bad_format ({'organization_id': ['Invalid organization ID']})",)
Creating …
```
=> Rework handshake

parsec/api/protocole/user.py, parsec/backend/app.py, parsec/backend/drivers/memory/user.py, parsec/backend/drivers/postgresql/user.py, parsec/backend/drivers/postgresql/user_init.sql, parsec/backend/user.py, parsec/core/backend_connection/cmds.py, parsec/core/gui/devices_widget.py, parsec/core/gui/users_widget.py, parsec/core/gui/workspaces_widget.py, parsec/core/types/remote_device.py, parsec/trustchain.py, tests/backend/user/test_access.py, tests/backend/user/test_device_revoke.py, tests/core/test_schemas.py, tests/test_trustchain.py
cf. https://en.wiktionary.org/wiki/revoke#English vs https://en.wiktionary.org/wiki/revocate#English
=> Correct misspelling revocated -> revoked

parsec/core/mountpoint/fuse_runner.py
Fix issue #292.
Sadly doesn't fix the `fuse: fuse_remove_signal_handlers: unknown session` error message in `stderr`.
=> Reset fuse signal handlers after a fuse instance has started

parsec/event_bus.py
The event logging disappeared after the following changes:
- https://github.com/Scille/parsec-cloud/commit/2a4f90dec04791f6c4d161e0d1ee7f21fb942909#diff-106a4d5f45c3f7d1b5ecc9f3adcab10fR83
- https://github.com/Scille/parsec-cloud/commit/8f66f733f567f7be1200ab01dbdb1e578f0acc7a#diff-106a4d5f45c3f7d1b5ecc9f3adcab10f
Now every the events are logged as "debug", and the meta events (`event.connected` and `event.disconnected`) are not logged at all.
=> Restore event logging

parsec/core/fs/file_syncer.py, parsec/core/fs/local_folder_fs.py, tests/core/fs/test_local_file_fs.py, tests/core/mountpoint/test_fuse.py
=>  Check manifest status (clean/dirty) before setting them in local storage

parsec/core/gui/main_window.py, parsec/core/gui/tr/parsec_en.ts, parsec/core/gui/tr/parsec_fr.ts, parsec/core/gui/workspaces_widget.py
Premier draft (faudrait régénérer les fichiers de traduction dont les lignes sont décalées).
=> Remount mountpoint at workspace renaming

parsec/core/gui/file_table.py, parsec/core/gui/files_widget.py, parsec/core/gui/forms/sharing_widget.ui, parsec/core/gui/forms/workspace_sharing_dialog.ui, parsec/core/gui/mount_widget.py, parsec/core/gui/workspace_button.py, parsec/core/gui/workspace_sharing_dialog.py, parsec/core/gui/workspaces_widget.py
- Updated the GUI to user roles instead of permissions
- Fixed a few bugs (like the destruction of the underlying Qt object in some cases)
- Restricted the permissions for a user to add/delete/rename items in a workspace if they're only readers
- Handle permissions update signals correctly, so the GUI should react correctly when the role of a user changes
=> [GUI] Updated workspace sharing to use roles

misc/run_test_environment.sh, parsec/core/fs/file_syncer.py, parsec/core/fs/folder_syncer.py, parsec/core/fs/remote_loader.py, parsec/core/fs/sync_base.py, parsec/core/fs/userfs/userfs.py, parsec/core/fs/workspacefs/entry_transactions.py, parsec/core/local_storage.py, parsec/core/logged_core.py, parsec/core/persistent_storage.py, parsec/core/types/remote_manifests.py, tests/common.py, tests/core/conftest.py, tests/core/fs/test_bootstrap.py, tests/core/fs/test_fs_online_concurrent_tree_and_sync.py, tests/core/fs/test_fs_online_concurrent_user.py, tests/core/fs/test_fs_sync.py, tests/core/fs/test_local_folder_fs.py, tests/core/fs/userfs/test_sharing.py, tests/core/fs/userfs/test_sync.py, tests/core/mountpoint/test_fuse.py, tests/core/test_local_storage.py
Also fix the authorship for manifests:
- `remote_manifest.author` is the id of the device uploading the manifest
- `local_manifest.author` is the id of of the device working on the manifest
=> Store both the base and local manifests in the local storage

parsec/core/gui/main_window.py, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po
Le truc pas top c'est que la popup créée par `show_error()` ne possède n'a pas d'ascenseur pour afficher une grosse quantité de texte comme un stacktrace... du coup c'est assez illisible en l'état :'(
=> Improve unhandled errors display in GUI

parsec/core/remote_devices_manager.py, tests/core/test_invite_claim.py
- fixed popitem order from _verify_devices in both get_device_invitation_creator and get_user_invitation_creator in remote_devices_mangaer.py : Fixes #523 
- added a test for the creation of 3 chained users from one another in test_invite_claim.py, as this caused a previously unnoticed bug since the introduction of signature verification when claiming a new user or device
=> Fix trustchain issue when inviting new user

parsec/core/fs/remote_loader.py, tests/core/fs/workspacefs/test_file_transactions.py
I think there was no test for reading file with blocs not found in local storage.
Plus another small commit since the return value of `load_block` is never used.
=> Add test load remote block

parsec/core/fs/workspacefs/sync_transactions.py, parsec/core/types/local_manifests.py, tests/core/test_local_storage.py
96a8d9fb5331b broke the `misc/run_test_environment.sh` script
=>  Fix local workspace manifest schema

parsec/core/local_storage.py
local_storage.py : timestamped version now uses the parent constructor, but with an empty key and path, as we will use the parent local_storage instead
=> LocalStorageTimestamped - use parent constructor

parsec/core/persistent_storage.py, tests/core/gui/conftest.py, tests/core/test_persistent_storage.py
- configure sqlite with WAL mode, isolation=None and synchronous=OFF
- blocks are stored in sqlite
- Use integer for accessed_on column (faster than text in db + time.time() much faster than pendulum.now())
before:
after:
Bench is done on a copy of a 10mo file, getting a ~30% improvement
[profs.zip](https://github.com/Scille/parsec-cloud/files/3444084/profs.zip)
=> Optimize persistant storage & add garbage collector test

parsec/core/fs/remote_loader.py, parsec/core/fs/workspacefs/file_transactions.py, parsec/core/fs/workspacefs/sync_transactions.py
See #553.
No reason to do this concurrently though, as the blocks (except for the last one) are 512KB large
=> Move load_blocks logic to the remote loader

parsec/core/fs/local_storage.py, tests/core/fs/test_local_storage.py
`_check_lock_status` now raises `RuntimeError` instead of doing an assert to make it more readable in the tests (`pytest.raises(AssertionError)` feels weird...)
=> Improve local storage tests

parsec/core/fs/local_storage.py, parsec/core/fs/workspacefs/entry_transactions.py, parsec/core/fs/workspacefs/file_transactions.py, parsec/core/fs/workspacefs/sync_transactions.py, parsec/core/fs/workspacefs/workspacefs.py, parsec/core/fs/workspacefs/workspacefs_timestamped.py, parsec/core/mountpoint/fuse_operations.py, parsec/core/mountpoint/thread_fs_access.py, tests/core/fs/conftest.py, tests/core/fs/workspacefs/test_sync_transactions.py, tests/core/fs/workspacefs/test_workspace_fs.py, tests/core/fs/workspacefs_timestamped/test_entry_transactions_timestamped.py, tests/core/fs/workspacefs_timestamped/test_file_transactions_timestamped.py
Use inheritance for transaction classes. This allows for a simpler implementation of two fixes:
- Preventing file manifest to get stuck in a sync loop while being written 
- Adding the `file_resize` atomic transaction (see #553)
=> Refactor transactions

parsec/core/fs/workspacefs/file_operations.py, parsec/core/fs/workspacefs/file_transactions.py, parsec/core/types/access.py, parsec/core/types/local_manifests.py, tests/core/fs/workspacefs/test_file_operations.py
Writing files by chunks of `DEFAULT_BLOCK_SIZE` minimizes the amount of reshape operations required. The qt application can take advantage of this, making this writing pattern a nominal use case.
This PR implements two optimizations that should make a significant difference for this use case.
=> Improve performance when writing blocks

parsec/_version.py, parsec/api/protocol/__init__.py, parsec/api/protocol/base.py, parsec/api/protocol/handshake.py, parsec/api/transport.py, parsec/backend/app.py, parsec/backend/utils.py, parsec/core/backend_connection/cmds.py, parsec/core/backend_connection/transport.py, parsec/serde/fields.py, tests/backend/test_handshake.py, tests/test_handshake.py
A few changes:
- The api version checking is done on both side during the handshake
- At this point, only the major versions should match
- The peer version can then be used on both side using the transport object
Example:
```python
transport.handshake.client_api_version
transport.handshake.backend_api_version
```
=> New api versioning scheme

parsec/core/fs/realm_storage.py
Hotfix for:
```
2019-09-09 07:59:53 [error    ] Sync monitor has crashed       [parsec.core.sync_monitor] workspace_id=EntryID('b93ddaac-783c-4c42-a414-1cc371209efb')
Traceback (most recent call last):
File "/home/max/work/parsec-cloud/parsec/core/sync_monitor.py", line 334, in _ctx_tick
return await ctx.tick()
File "/home/max/work/parsec-cloud/parsec/core/sync_monitor.py", line 222, in tick
self._get_local_storage().run_vacuum()
AttributeError: 'RealmStorage' object has no attribute 'run_vacuum'
```
=> Add run_vacuum method to real storage

tests/core/fs/workspacefs_timestamped/conftest.py
Modified workspacefs_timestamped/conftest.py so the different timestamped workspaces are instanciated from one another, checking to_timestamp method is also working from timestamped workspacefs.
=> Check to_timestamp method is working from WorkspaceFSTimestamped

parsec/core/mountpoint/fuse_runner.py, tests/core/mountpoint/test_fuse.py
=> Fix mountpoint dir removal on cancelled coroutine teardown

parsec/core/fs/storage/manifest_storage.py, parsec/core/fs/storage/workspace_storage.py, parsec/core/fs/workspacefs/file_operations.py, parsec/core/fs/workspacefs/file_transactions.py, tests/core/fs/storage/test_workspace_storage.py, tests/core/fs/test_bootstrap.py, tests/core/fs/workspacefs/test_file_operations.py, tests/core/fs/workspacefs/test_file_transactions.py
Taken from 4a57172:
> Before this change, there was a risk of data corruption.
For instance, chunks might be cleaned up in the current sqlite
transaction, waiting for the next manifest flush to be committed.
But if a commit occurs before the flushing the current manifest,
the system enters a risky state: the chunk is cleared from the disk
but the current version of the manifest is still in memory. If a
crash happens at this point, the database will stay in its current
state, i.e with a manifest referencing non-existing blocks.
> This is solved by adding the IDs of the chunks to cleanup to the
data structure that keeps track of the unwritten manifests. This
way, the cleanup can occur in between the writing of the manifests
and the committing of the transaction.
=> Fix chunk corruption

parsec/core/fs/storage/local_database.py, setup.py, tests/conftest.py
The sqlite3 commit statement after the reshaping of a large file can take more than one second. We cannot allow the trio loop to get frozen for that long, so one solution is to run the costy statements in a dedicated thread.
Note 1: It's not worth running all statements in the dedicated thread since the thread sync overhead is ususally greater that the statement execution.
Note 2: We could simply use `trio.run_sync_in_worker_thread` (see 4b11469) instead of a thread pool (see b0e94fa), but this would mean creating a new thread for every commit. Would that be an issue? More info [here](https://github.com/python-trio/trio/blob/c5497c5ac4f6c457e3390c69cb8b5b62eca41979/trio/_threads.py#L32-L128).
=> Run sqlite3 commit and vacuum statements in a dedicated thread

parsec/backend/memory/vlob.py, parsec/backend/postgresql/vlob.py, parsec/backend/vlob.py, parsec/core/backend_connection/exceptions.py, parsec/core/fs/exceptions.py, parsec/core/fs/remote_loader.py, tests/core/fs/test_fs_sync.py, tests/core/fs/workspacefs/test_invalid_data.py
Backend now checks if timestamp is not inferior of existant on vlob update, if it is, send an error to client which goes offline to avoid the handling of this event in a retry loop
=> Backend checks EntryID timestamp consistency

misc/run_test_environment.sh
Also add an `--empty` (or `-e`) argument that may be used to bypass the initialization of the
test environment:
$ source misc/run_test_environment.sh --empty
This can be used to perform a user or device enrollment on the same machine.
For instance, consider the following scenario:
$ source misc/run_test_environment.sh
$ parsec core gui
Then, in a second terminal
$ source misc/run_test_environment.sh --empty
$ xdg-open "<paste the URL here>"  # Or
$ firefox --no-remote "<paste the URL here>"
=> Add support for parsec:// mime type in run_test_environment script

setup.py
setup.py : enforce OS check for PKCS11 installation as it tried to install on Windows with 'pip install -e .[all]'
=> Fix PKCS11 dependency trying to install on Windows

newsfragments/784.feature.rst, parsec/core/fs/workspacefs/versioning_helpers.py, parsec/core/fs/workspacefs/workspacefs.py, parsec/core/gui/file_history_dialog.py, parsec/core/gui/lang.py, parsec/core/gui/versions_table.py, tests/core/fs/workspacefs_timestamped/conftest.py, tests/core/fs/workspacefs_timestamped/test_workspacefs.py
Updated list_versions algorithm to ignore both what can be detected as a mocked manifest, and redundant entries gotten from updates of the manifests constituting the parent path.
Resolves #766
=> Remove duplicates in list_versions

parsec/service_nursery.py, setup.py
trio_typing depends on mypy, which add up a lot to the final build:
```shell
$ du -sh /snap/parsec/current/lib/python3.6/site-packages/mypy*
7,2M    /snap/parsec/current/lib/python3.6/site-packages/mypy
3,5K    /snap/parsec/current/lib/python3.6/site-packages/mypy-0.740.dist-info
4,5K    /snap/parsec/current/lib/python3.6/site-packages/mypy_extensions-0.4.3.dist-info
5,0K    /snap/parsec/current/lib/python3.6/site-packages/mypy_extensions.py
1,3M    /snap/parsec/current/lib/python3.6/site-packages/mypyc
75M    /snap/parsec/current/lib/python3.6/site-packages/mypyc_73ace4c88000b89b158a.cpython-36m-x86_64-linux-gnu.so
```
=> Remove trio_typing dep

newsfragments/827.misc.rst, parsec/core/mountpoint/fuse_operations.py, parsec/core/mountpoint/fuse_runner.py, tests/core/mountpoint/test_base.py
Also use EINVAL as fallback error code in fuse operations.
=>  Provide fusepy with the file system encoding

tests/monitor.py
example:
```
Trio Monitor: 12 tasks running
Type help for commands
trio > tree
<init> (id=0, status=waiting)
|- pytest_trio.plugin._trio_test_runner_factory.<locals>._bootstrap_fixtures_and_run_test (id=1, status=waiting)
|  |- <fixture 'backend'> (id=4, status=waiting)
|  |  |_ (nested nursery)
|  |     |_ parsec.backend.memory.factory.components_factory.<locals>._dispatch_event (id=9, status=waiting)
|  |- <fixture 'backend_factory'> (id=5, status=waiting)
|  |- <test 'test_user_invite_claim_cancel_invitation'> (id=3, status=waiting)
|  |  |_ (nested nursery)
|  |     |_ tests.core.test_invite_claim.test_user_invite_claim_cancel_invitation.<locals>._from_alice (id=10, status=waiting)
|  |- <fixture 'asyncio_loop'> (id=6, status=waiting)
|  |  |_ (nested nursery)
|  |     |_ …
```
=> Improve test monitor display

.travis.yml, tests/scripts/run_testenv.sh, tests/test_scripts.py
... and prevent appveyor from getting stuck.
=> Improve the testing of test scripts

setup.py
Require hypothesis-trio v0.5.0 release: https://github.com/python-trio/hypothesis-trio/pull/6
=> Update to hypothesis 5

parsec/__init__.py, parsec/core/gui/trio_thread.py, parsec/service_nursery.py, parsec/utils.py, tests/test_nursery.py
Following up on #1027 
As it turns out, `trio.Cancelled()` exceptions require a bit of attention.
=> Multi error refactoring

.azure-pipelines.yml, tests/test_cli.py
Also fixes some inconsistent tests. In particular, this first test can take a bit of time to run:
https://dev.azure.com/Scille/parsec/_build/results?buildId=146&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=85724bb3-46c9-5fad-b9a2-5b861fe1fc50&l=48
`6.62s call     tests/test_cli.py::test_gui_with_diagnose_option[Standard environement]`
A 10 seconds timeout was a bit low.
=> Increase verbosity and add duration reports for CI tests

.azure-pipelines.yml, newsfragments/1069.empty.rst
Fixed checking on newsfragment from origin/master as it seems master wasn't automatically fetched on CI.
Also now uses stderr instead of exit 1 as it now prints the error message in CI logs more obviously.
=> Fix check newsfragment

parsec/core/fs/exceptions.py, parsec/core/gui/trio_thread.py, parsec/core/gui/workspaces_widget.py, parsec/core/mountpoint/manager.py, parsec/core/mountpoint/winfsp_runner.py, tests/core/gui/conftest.py, tests/core/gui/test_files.py, tests/core/mountpoint/test_winfstest.py
The following pattern should be more robust than the current signal approach:
```python
def is_workspace_button_ready():
workspace_button = workspaces_widget.layout_workspaces.itemAt(0).widget()
if isinstance(wk_button, QtWidgets.QLabel):
return False
return workspace_button
workspace_button = await aqtbot.wait_for(is_workspace_button_ready)
assert workspace_button.name == "Workspace"
```
=> Implement conditional waiting in GUI tests

newsfragments/1188.bugfix.rst, parsec/core/gui/files_widget.py
=> Fix trio deadlock when importing a file from a parsec workspace

newsfragments/1205.bugfix.rst, parsec/core/gui/central_widget.py, parsec/core/gui/devices_widget.py, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po, parsec/core/gui/users_widget.py, tests/core/gui/test_revoked_user.py
Widgets that require to fetch information from `get_user_and_devices` can get a `RemoteDevicesManagerError` if the user has been revoked. This error is not handle in `devices_widget`.
This PR try to change how this error is handled. Now, no popup is displayed by the `users_widgets` or the `devices_widget`  if the exception is raised and the devices (or users ) list is filled with an error message. 
There is now a popup saying that the user is revoked when the event bus get the revoked user notification. (This popup is displayed also after logging in).
Also `devices_widget` and `users_widget` are not filled after logging anymore (when the widget is instantiated)  but on display time (only the first time)
linked issue #1191
=> Gui revoked user logging

parsec/core/gui/workspaces_widget.py, tests/core/gui/test_workspaces.py
Migrate qt signal from `str` to `CoreEvent` to avoid:
```
TypeError: WorkspacesWidget.fs_synced_qt[str, UUID].emit(): argument 1 has unexpected type 'CoreEvent'
```
=> Fix wrong qt signal type

newsfragments/1246.misc.rst, parsec/backend/cli/run.py, parsec/backend/config.py, tests/conftest.py
This option has never done anything and it wasn't part of the documentation so I guess it's safe to remove it entirely for the moment ;-)
=> Remove useless --db-drop-deleted-data option from backend run command

parsec/backend/postgresql/handler.py, tests/backend/test_postgres_db.py
Tests for https://github.com/Scille/parsec-cloud/pull/1258#pullrequestreview-445963430
=> Test retry of failed initial db connection

parsec/core/gui/custom_dialogs.py
This allows to display the traceback of the exceptions in the `__cause__` chain
=> [GUI] Display full traceback in error widget

newsfragments/1270.bugfix.rst, parsec/core/gui/file_history_widget.py, parsec/core/gui/files_widget.py, tests/core/gui/conftest.py, tests/core/gui/test_file_history.py
=> Fix gui file history name

newsfragments/1303.misc.rst, packaging/win32/installer.nsi, parsec/core/mountpoint/winfsp_operations.py, tests/core/gui/test_file_history.py
Fix #1301.
Also fix the following trace:
```
Traceback (most recent call last):
File "d:\projects\parsec-cloud\parsec\core\mountpoint\winfsp_operations.py", line 41, in translate_error
yield
File "d:\projects\parsec-cloud\parsec\core\mountpoint\winfsp_operations.py", line 136, in wrapper
return func.__get__(self)(arg, *args, **kwargs)
File "d:\projects\parsec-cloud\parsec\core\mountpoint\winfsp_operations.py", line 361, in cleanup
file_name = _winpath_to_parsec(file_name)
File "d:\projects\parsec-cloud\parsec\core\mountpoint\winfsp_operations.py", line 31, in _winpath_to_parsec
return FsPath(unwinify_entry_name(path.replace("\\", "/")))
AttributeError: 'NoneType' object has no attribute 'replace'
[2m2020-07-24 10:23:03[0m [[31m[1mexception[0m] [1mUnhandled exception in winfsp …
```
=> Run parsec without elevated priviledges at the end of the windows installation

parsec/core/gui/custom_dialogs.py, parsec/core/gui/login_widget.py
The numpad `Enter` key did nothing in the gui, this PR fixes it.
=> Add Enter key on top of Return in GUI

setup.py
Address https://github.com/Scille/parsec-cloud/issues/1309#issuecomment-666334980:
> And related to this matter, I suggest to define the pyQt5-sip version to 12.8.0, in the relevant place (setup.py?). This would avoid breaking change issue in the future.
=> Pin pyqt5-sip dependency to avoid issues in the future

newsfragments/1363.bugfix.rst, parsec/core/gui/claim_device_widget.py, parsec/core/gui/claim_user_widget.py
Do not restart invitation process if `InvitationAlreadyUsedError` is raised
This solved issue #1362 : 
our cancel test expects on step2 to get a failure on `wait_peer` job because the communication channel is supposed to be closed by the backend:
In fact there is nothing that grantee that the communication channel will be closed before `wait_peer` returns an `InvitationAlreadyUsedError` due to the cancellation.
Maybe `InvitationNotFoundError` should also not trigger a re connection ?
=> Do not restart invitation process on InvitationAlreadyUsedError

newsfragments/1366.misc.rst, parsec/core/local_device.py, parsec/core/types/local_device.py, tests/core/test_local_device.py
Key files used to be stored in a directory named after the device slug in a file also named after the same device slug. The total length is more than 160 characters depending on the organization name.
Key files are now stored directly in the devices directory using the device slughash and the `.keys` extension. The total length is 37
characters.
This fixes issue #1356.
=> Devices keys filenames are no longer meaningful

newsfragments/1365.bugfix.rst, parsec/backend/app.py, parsec/backend/handshake.py, parsec/backend/invite.py, parsec/core/backend_connection/__init__.py, parsec/core/backend_connection/exceptions.py, parsec/core/backend_connection/invited.py, parsec/core/backend_connection/transport.py, parsec/core/gui/claim_device_widget.py, parsec/core/gui/claim_user_widget.py, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po, tests/backend/invite/test_base.py, tests/backend/invite/test_exchange_bad_access.py, tests/core/backend_connection/test_invited_cmds.py, tests/core/gui/devices_widget/test_claim.py, tests/core/gui/users_widget/test_claim.py, tests/core/test_invite.py
Always close connection, never returns, when an invitation is cancelled after the invitation handshake.
Add a retrier on the client side on BackendNotAvailable for invitation commands.
=> Invitation: inconsistent backend replies

newsfragments/1401.misc.rst, parsec/core/mountpoint/fuse_operations.py, parsec/core/mountpoint/winfsp_operations.py
The winfsp and fuse mountpoints now always report 0 MB used over a 1 TB capacity. 
Those values are arbitrary but useful to the operating system, especially OSX.
=> Fuse and winfsp mountpoints now report 0 MB used over 1 TB

newsfragments/1400.bugfix.rst, parsec/backend/invite.py, parsec/backend/templates/__init__.py, parsec/backend/templates/invitation_mail.txt, tests/backend/invite/test_base.py
There was a mismatch between the placeholder variable names in the templates and in the provided arguments in the code.
=> Fix email user invite generation

newsfragments/1206.feature.rst, parsec/backend/app.py, parsec/backend/backend_events.py, parsec/backend/events.py, parsec/backend/handshake.py, parsec/backend/memory/factory.py, parsec/backend/memory/organization.py, parsec/backend/organization.py, parsec/backend/postgresql/factory.py, parsec/backend/postgresql/organization.py, parsec/core/gui/central_widget.py, tests/backend/test_apiv1_organization_status.py, tests/backend/test_handshake.py, tests/core/backend_connection/test_apiv1_anonymous_cmds.py, tests/core/backend_connection/test_apiv1_authenticated_cmds.py, tests/core/backend_connection/test_authenticated_cmds.py, tests/core/backend_connection/test_invited_cmds.py, tests/core/gui/test_expired_organization.py
#1206 
Like a user can be revoked, there is now an event to notify that a backend organization has expired.
When this event is triggered, all the current client connections on this organization id are closed.
This event can be emited:
- When a client logging to the organization (there in the handshake we check if the organization is expired).
- When the organization expiration date is set.
=> Expired organization 

parsec/core/gui/login_widget.py
Added the numpad enter key to validate password in the new login widget.
=> Use both enter keys for new login widget

parsec/core/gui/instance_widget.py, parsec/core/gui/login_widget.py, tests/core/gui/conftest.py, tests/core/gui/test_create_organization.py, tests/core/gui/test_workspaces.py
Try to fix ci errors:
[Reset error](https://dev.azure.com/Scille/parsec/_build/results?buildId=3487&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=98a05ba0-83e8-5985-e9d7-1cce7a13f66e)
[No core](https://dev.azure.com/Scille/parsec/_build/results?buildId=3382&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=98a05ba0-83e8-5985-e9d7-1cce7a13f66e)
[Invitation widget timeout](https://dev.azure.com/Scille/parsec/_build/results?buildId=3603&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=98a05ba0-83e8-5985-e9d7-1cce7a13f66e)
[increase mountpoint timeout](https://dev.azure.com/Scille/parsec/_build/results?buildId=3611&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=98a05ba0-83e8-5985-e9d7-1cce7a13f66e)
Gui tests ran 10 times without failure there: …
=> Flaky gui test event bus none

tests/core/gui/test_workspaces.py
Assert workspaces are mounted after gui operation
=> GUI test_workspace: Assert workspaces are mounted after gui operation

.azure-pipelines.yml, parsec/core/fs/exceptions.py, parsec/core/fs/storage/chunk_storage.py, parsec/core/fs/storage/local_database.py, parsec/core/fs/storage/manifest_storage.py, parsec/core/fs/workspacefs/file_transactions.py, parsec/core/fs/workspacefs/workspacefile.py, setup.cfg, tests/conftest.py, tests/core/fs/storage/test_workspace_storage.py, tests/core/fs/test_disk_full.py, tests/fuse_loopback.py
Fix issue #1537 and add more tests to detect database corruption after a failed write operation in a local sqlite database.
=> Fix database corruption and add tests for disk full errors on sqlite operations

newsfragments/1538.bugfix.rst, parsec/core/gui/custom_dialogs.py, tests/core/gui/conftest.py
=> [GUI] Fixed crash on MacOS when resetting a greyed dialog parent

packaging/snap/snap/snapcraft.yaml
closes #1472 
Snap output tested on xubuntu.
snap test artifact: https://dev.azure.com/Scille/parsec/_build/results?buildId=4717&view=artifacts&type=publishedArtifacts
=> Add missing snap dependency libxkbcommon-x11-0 (required for xubuntu)

packaging/macOS/parsec.spec
If not mentioned, the displayed version of the macOS app will be 0.0.0 instead of the current one.
=> Show version in macos app

newsfragments/1644.bugfix.rst, parsec/core/mountpoint/fuse_runner.py, parsec/core/mountpoint/manager.py
This can prevent errors during login after a crash, or in various situations where a mountpoint can't unmount without it (when a terminal's cwd is inside the mountpoint for instance)
=> Add force option to diskutil unmount calls

newsfragments/1663.bugfix.rst, parsec/core/gui/workspaces_widget.py
A `Cancelled` exception was showed in a dialog with the confusing message:
> Reencryption failed for unknown reason 
when a user logs out with an on-going reencryption.
=> Fix confusing dialog when logging out with an on-going reencryption

tests/conftest.py
Tested with `tests/backend/test_organization_stats.py::test_organization_stats`.
Measurements of lowest non-failing timeout on my machine:
- memory backend: 65-70 ms
- postgresql 10 backend: 220-230 ms
- postgresql 12 backend: 680-700 ms
Reproduce with:
```bash
while PGINSTALLATION=/usr/lib/postgresql/10/bin pytest --postgresql tests/backend/test_organization_stats.py; do :; done;
```
=> Increase timeout for running_backend fixture

newsfragments/1519.bugfix.rst, parsec/core/gui/app.py, parsec/core/gui/main_window.py, parsec/core/gui/parsec_application.py
This aims at enhancing the app's behaviour to be more like usual Mac apps:
- Clicking the red X on Mac apps closes the window and leaves the process running in background. In this situation, clicking the Dock icon should pop the window back up, which wasn't the case. This is handled here with the `ApplicationActivate` event.
- Removal of the systray for MacOS as there is already is a default menu on the system with the same functions.
- Removal of the system notification when minimizing the app for MacOS, as this is default on most apps.
The app behaviour when `Minimize in tray` option is unchecked remains unchanged.
Closes #1519
=> MacOS app fixes

newsfragments/1716.bugfix.rst, parsec/core/mountpoint/fuse_runner.py
The problem has been observed on linux, usually when trying to exit the application after the writing of a large file, during the synchronization. It happens sporadically.
=> Fix a fuse issue where the shutdown procedure blocks forever

newsfragments/1713.bugfix.rst, parsec/core/fs/storage/chunk_storage.py, parsec/core/fs/storage/local_database.py, parsec/core/fs/storage/manifest_storage.py, parsec/core/fs/workspacefs/sync_transactions.py, parsec/core/mountpoint/fuse_runner.py, parsec/core/types/manifest.py, tests/conftest.py, tests/core/mountpoint/test_base.py
Also remove thread pool executor from the local database module since trio now caches its threads.
Fix #1698, #1699, #1700 and partially #1701.
=> Fix blocking IO calls to sqlite when uploading large files

newsfragments/1730.bugfix.rst, parsec/core/sync_monitor.py, tests/conftest.py, tests/core/backend_connection/test_authenticated_conn.py, tests/core/gui/test_workspaces_reencrypt.py, tests/core/mountpoint/test_file_failures.py, tests/core/test_sync_monitor.py, tests/test_nursery.py
=> Fix fs bad encryption revision in sync monitor

parsec/backend/client_context.py
without this fix, logs look like this:
```
DEBUG    parsec.api.transport:app.py:405 2021-08-11 08:34:10 [debug    ] Response                       [parsec.api.transport] conn_id=6f223af02d754cf8a2c7a03bdb5de2ef handshake_type=INVITED invitation=DeviceInvitation(greeter_user_id=<UserID 'alice'>, greeter_human_handle=<HumanHandle Alicey McAliceFace <alice@example.com> >, token=UUID('fd52e5c2-2b0a-4f5b-9189-68e14bdb1a0f'), created_on=datetime.datetime(2021, 8, 11, 8, 34, 10, 484840, tzinfo=datetime.timezone.utc), status=<InvitationStatus.READY: 'READY'>) organization_id=CoolOrg rep={'pong': 'foo', 'status': 'ok'}
```
=> Reduce verbosity of backend's InvitedClientContext logger

parsec/core/gui/workspace_button.py, parsec/core/gui/workspaces_widget.py
(by passing a parent to `WorkspaceButton`)
=> Fix the split-second appearing of an empty form when showing the workspace list

parsec/core/gui/main_window.py
This is a temporary fix. See #1860
=> Correctly close app in regards to mountpoints with cmd+Q

newsfragments/1856.bugfix.rst, parsec/core/gui/files_widget.py, parsec/core/gui/trio_jobs.py
It uses the mixing of qt and trio logic within the jobs. This approach is possible now that we migrated to qtrio. 
It also fixes a deadlock issue when a file is imported from another parsec workspace.
=> Refactor FilesWidget import logic

newsfragments/1860.bugfix.rst, parsec/core/gui/main_window.py
Behaviour is now as intended: cmd-Q always displays the confirmation before close widget and closes properly, and the red X either hides the window if `minimize_on_close` is checked, or prompts the same widget.
Closes #1860
=> Fix app closing on MacOS

parsec/core/gui/desktop.py
On MacOS (and supposedly Windows), `QClipboard.Selection` isn't supported as explained [here](https://doc.qt.io/qt-5/qclipboard.html#notes-for-windows-and-macos-users), resulting in the following error : `Data set on unsupported clipboard mode. QMimeData object will be deleted.`
=> Added condition to QClipboard.Selection

packaging/macOS/README.md, packaging/macOS/launch_script.py, packaging/macOS/macos_pyinstaller.sh, packaging/macOS/parsec.spec
When building on MacOS 11 and 12, the `click` error persists even with the current workaround.
The default encoding when launching apps from the Finder/taskbar is `ascii` regardless of which is used in Python, hence the error [here](https://github.com/pallets/click/blob/main/src/click/_unicodefun.py). Setting the correct flags in the `.spec` file solves the issue and allows the previous fix to be removed.
Probably linked to #1703.
=> Fix click errors on MacOS 11 & 12 and update MacOS PyInstaller

newsfragments/1940.feature.rst, parsec/core/cli/__init__.py, parsec/core/cli/human_find.py, parsec/core/cli/share_workspace.py, tests/test_cli.py
share_workspace --recipiant option is used to share a workspace using the human handle of a user (name or email address) instead of the user_id
The human_find command print user_id and human_handle corresponding to the query
=> Added share_workspace --recipiant option and human_find command

.pre-commit-config.yaml
The version in the pre commit config were not fixed previously, which lead to CI errors when trio typing updated to 0.7.0
=> Fixed version in additional_dependencies

parsec/core/backend_connection/authenticated.py, tests/core/gui/conftest.py, tests/core/gui/test_offline.py
This issue has been highlighted by the changes made in #1894 
It fixes some inconsistent failures in the CI, e.g https://github.com/Scille/parsec-cloud/runs/4534230166
=> Check for cancellation before setting status in BackendAuthenticatedConn

parsec/core/gui/navigation_bar_widget.py
Fixes #2025 
With the current code, if a folder has special characters in its name, Qt is unable to parse them during the `setStyleSheet` call resulting in errors and the name not being displayed in the navigation bar.
Proposed solution is to replace said name by the numerical index in the loop, not changing the navigation bar behaviour and correctly setting the colors.
=> Prevent Qt from parsing special characters in navigation bar

tests/backend/invite/test_invite_status_changed_event.py
fix https://dev.azure.com/Scille/parsec/_build/results?buildId=9297&view=logs&j=428b1e07-02b6-507b-4a77-51bcad7c9856&t=ea0bc151-d1c3-5c1f-9830-74ff3d5eadda&l=316
=> Fix test_invite_status_changed_event consistency with lagging PostgreSQL

parsec/core/gui/instance_widget.py
Otherwises raises a ValueError: `binary mode doesn't take an encoding argument`
=> Remove encoding on binary open

parsec/core/gui/create_org_widget.py, parsec/core/gui/main_window.py
Fix a regression found here:
```
/home/max/parsec-cloud/parsec/core/gui/main_window.py:501: RuntimeWarning: coroutine 'InstanceWidget.login_with_smartcard' was never awaited
tab.login_with_smartcard(kf)
```
=> Fix regression with `login_with_smartcard` being async

parsec/core/gui/app.py
move import `QDialogInProcess` in try catch block
to catch `ImportError` when missing QT generated forms
=> move import `QDialogInProcess` in try catch block

parsec/core/gui/enrollment_query_widget.py, parsec/core/gui/instance_widget.py, parsec/core/gui/login_widget.py, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po, parsec/core/local_device.py, parsec/core/pki/accepter.py, parsec/core/pki/exceptions.py, parsec/core/pki/plumbing.py, parsec/core/pki/submitter.py
Backport of https://github.com/Scille/parsec-cloud/pull/2239 for 2.8
=> [GUI] Handle cases where a user does not provide a certificate or a pin - backport 2.8

newsfragments/2211.bugfix.rst, parsec/core/mountpoint/fuse_operations.py, parsec/core/mountpoint/fuse_runner.py, parsec/core/mountpoint/thread_fs_access.py
Tests have been done with TextEdit, the Mac equivalent to NotePad. The issue and solution is shared among all of Mac's native editing softwares.
Upon saving, TextEdit creates a `filename.txt.sb-xxx-xxx` temp folder which seems to handle saves and auto-saves from TextEdit. It is meant to work on HFS drives, which isn’t the format currently used. (It seems auto-saves aren’t attempted, or at least they don’t raise any errors)
Only opening / closing the file with TextEdit is possible and doesn’t raise errors.
Issues come when trying to do a manual save from TextEdit:
If uncaught (current situation), the file `filename.txt` is renamed as `filename.txt.sb-xxx-xxx`, which is a hidden file, and since the extension changed, it becomes unusable for the user. My guess would be that the renaming is …
=> Handle saving from Apple softwares on FUSE drives

newsfragments/2237.bugfix.rst, parsec/core/gui/file_table.py, parsec/core/gui/files_widget.py
Closes #2257 
An error essage about EntryID not being serializable by pickle appeared when dragging a file. It didn't seem to have any incidence as the file could still be dragged and dropped, but it still better to fix it. We do so by ensuring that the EntryID stored in the widget UserData are converted to string. We could instead try to register EntryID to Qt's meta-object system but this would just be annoying and I don't know how to do it with PyQt.
=> [GUI] Fixed an error message appearing when dragging a file

requirement/backend_requirement.txt
Dependabot struggles to update both at the same time (https://github.com/Scille/parsec-cloud/pull/2396 and https://github.com/Scille/parsec-cloud/pull/2399) because of what seems like a circular dependency. So we update them both manually at the same time.
=> Updated boto and botocore requirements

newsfragments/2504.bugfix.rst, parsec/core/gui/files_widget.py, tests/core/gui/test_files.py
Quickfix to avoid overwriting an existing file when importing a new one with the same name: the new file is renamed to something like "file (2).ext".
Closes #2504
=> [GUI] Don't overwrite files when importing a new file with the same name

parsec/core/gui/main_window.py, parsec/core/gui/parsec_application.py, parsec/core/gui/snackbar_widget.py
Better fix for #2530 
Snackbars now have the MainWindow as a parent, meaning they will more closely follow its state instead of appearing above every other windows on Windows.
Also, the snackbars were stored in a global variable. This caused problems, especially while testing, because the C++ Qt object would be deleted when the window was closed at the end of a test while the Python object would stay alive. Snackbars are now stored in an object whose lifetime depends on the main window.
closes #2530
=> [GUI] Fixed snackbar visibility when window is not in focus and how snackbars are handled

parsec/backend/client_context.py
fix log
```log
2022-07-11T09:33:13.064614Z [info     ] Request                        cmd=realm_status conn_id=1937e0ac5b0b425295495ada3ce9948b device_id=<DeviceID 77be7ce907b1428880ff968a09b03b42@5c0b4a5bf59944f68107beea99ef5ed6> organization_id=<OrganizationID foo> status=ok
```
into
```log
2022-07-11T09:33:13.064614Z [info     ] Request                        cmd=realm_status conn_id=1937e0ac5b0b425295495ada3ce9948b device_id=77be7ce907b1428880ff968a09b03b42@5c0b4a5bf59944f68107beea99ef5ed6 organization_id=foo status=ok
```
=> Cleanup display of org/device_id in backend client context logger bind

.github/actions/setup-rust/action.yml, .github/workflows/linux-ci.yml, .github/workflows/quality-assurance.yml
- also remove the step `Run cargo build to prepare rust's cache` since
we'll be using different cache between the qa & test/build job
closes #2634
=> add CI workflow to run rust build & test on linux

.github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml, .github/workflows/package-linux.yml, .github/workflows/windows-ci.yml
Rename Github Action workflow's jobs to be able to select them in the `require status check` in the configuration of this repository before allowing to merge
=> Rename jobs name

.github/workflows/package-linux.yml
We've updated the job's name `package-linux-build-wheel`
but forgot to update to update the job requirement for
`package-linux-build-snap` to reflect to new name for `build-wheel`
=> Correct `needs` for job `package-linux-build-snap`

parsec/sequester_crypto.py, tests/backend/sequester/test_crypto.py
=> Fix oscrypto macos RSA output len in sequester crypto

.azure-pipelines.yml, .github/workflows/package-linux.yml
The azure jobs are kept for tags, while we're validating the new GH action packaging process.
Also add `package-linux-release-pypi` and `package-linux-release-snap` steps in package-linux workflow.
=> Disable azure pipelines for push and PR triggers

.github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml, .github/workflows/quality-assurance.yml, .github/workflows/windows-ci.yml
Add `timeout` to workflow that use `setup-rust`
Example of a workflow that timeout because of a [cache step](https://github.com/Scille/parsec-cloud/runs/7689754508?check_suite_focus=true#step:3:17)
=> Add `timeout` to action `setup-rust`

parsec/backend/asgi/__init__.py, parsec/backend/cli/run.py, tests/backend/test_http.py
Currently, there is two server headers in the parsec server response:
```shell
$ curl --head http://127.0.0.1:6777/foo
HTTP/1.1 404 
content-type: text/html; charset=utf-8
content-length: 823
server: parsec/v2.11.0+dev
date: Tue, 09 Aug 2022 09:19:26 GMT
server: hypercorn-h11
```
=> Improve handling of HTTP `server` header in backend server

.github/workflows/package-ci.yml, build.py, pyproject.toml
A proposal to switch the strategy for building the rust extension in build.py
This approach does not require pip nor a virtualenv, which makes it much more robust.
This is especially useful for fixing the CI in parsec-extensions: https://github.com/Scille/parsec-extensions/commit/1450b88f1587f407c85583e01bbc0c81ae33f38b
=> Switch strategy for building the rust extension in build.py

parsec/backend/blockstore.py, parsec/backend/postgresql/block.py, parsec/backend/postgresql/sequester_export.py, parsec/backend/raid0_blockstore.py, parsec/backend/raid1_blockstore.py, parsec/backend/raid5_blockstore.py, parsec/backend/s3_blockstore.py, parsec/backend/swift_blockstore.py
`MemoryBlockStoreComponent` argument was named `block_id`, but in all other `BlockStoreComponents`, this argument was just named `id`. This caused a problem if you wanted to used named arguments on an abstract `BaseBlockStoreComponent`, ie `blockstore.read(organization_id=org_id, id=block_id)` would fail with `MemoryBlockStoreComponent` but succeed with others.
Since `block_id` is a better name, `id` arguments were renamed to `block_id`.
=> Renamed BlockStoreComponent arguments

.github/scripts/notary/lib.sh, .github/scripts/notary/script.sh
- Don't look for PR to add to the project
- Improve script output
- Inform you when it start looking for issues to add.
- Inform you when it have no issues to add to the project.
=> Remove lonely prs from the script creating tasks in triage

.github/workflows/package-ci.yml
Might detect issue like #2900 earlier.
=> Parametrize snap test job with ubuntu 18, 20 and 22

.github/actions/setup-rust/action.yml
Removing the `restore-keys` entry will force the `actions/cache` to use
a clear cache every-time the `key` change at the cost of longer first
time run (i.e.: the first run when the key have change, the next runs
aren't affected).
=> Remove `restore-keys` in actions `setup-rust`

newsfragments/3056.feature.rst, parsec/core/gui/forms/workspaces_widget.ui, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po, parsec/core/gui/workspace_button.py, parsec/core/gui/workspaces_widget.py, tests/core/gui/conftest.py, tests/core/gui/test_files.py, tests/core/gui/test_workspaces.py
Closes #1744
Closes #3056 (second one was created because 1744 was used incorrectly for another newsfragment).
Add a checkbox to hide unmounted workspaces. The checkbox is checked by default. Ideally it should remember its previous state but it requires a config by device which is quite bothersome. This solution should be good enough for now.
=> Add a way to hide unmounted workspaces

.github/workflows/ci.yml
This will reduce the time taken to execute the jobs, because:
- This will reduce the size of the rust's cache per job, meaning faster download / upload (less data to transfer)
- The cache will be specific for the job so everything is ready (shared cache can be overwritten)
=> Add `github.job` to segregate rust cache per job

oxidation/libparsec/crates/types/src/manifest.rs, oxidation/libparsec/crates/types/tests/test_manifest.rs, parsec/_parsec.pyi, parsec/_parsec_pyi/manifest.pyi, parsec/api/data/manifest.py, src/lib.rs, src/manifest.rs
Rust implementation of what used to be `BaseManifest.unsafe_load()`. It deserializes raw unciphered binary to a manifest.
=> Added `unverified_load()` to load remote manifests

newsfragments/2953.feature.rst, parsec/backend/asgi/__init__.py, parsec/backend/asgi/logger.py, parsec/backend/ping.py, tests/backend/test_logger.py, tests/common/backend.py
As mentioned in [issue 2953](https://github.com/Scille/parsec-cloud/issues/2953) it's better to have device id in logs when users are logged in.
This PR adds a custom implementation over the default Hypercorn `access logger`. A custom logger is required as the device id is base64 encoded in the HTTP author header.
=> Access log enhancement

tests/scripts/run_testenv.py
Since tmp folders created with `tests/scripts/run_testenv.py` cannot be automatically deleted, I added a little prefix to be able to recognize them.
=> Added a prefix to test env name so it can be more easily recognized

oxidation/libparsec/crates/types/src/time.rs, src/time.rs
- Make `LocalDateTime` comparable.
- Allow `LocalDateTime` to be hashed.
- `LocalDateTime` can be represented as an `str`.
=> Add python magic method implementation for `LocalDateTime`

.github/workflows/ci.yml, Cargo.toml, pyproject.toml
Applies the fixes suggested at <https://pyo3.github.io/pyo3/v0.17.0/faq.html#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror>.
This would allow to run `cargo test --workspace` without the `--exclude parsec` part.
=> Allow to run `cargo test` for the root crate

mypy.ini, parsec/_parsec_pyi/local_device.pyi, parsec/core/fs/storage/manifest_storage.py, parsec/core/fs/storage/workspace_storage.py, parsec/core/fs/userfs/userfs.py, parsec/core/fs/workspacefs/workspacefs.py, parsec/core/logged_core.py, parsec/core/mountpoint/manager.py, tests/core/fs/workspacefs/test_confinement.py, tests/core/test_logged_core.py, tests/core/test_sync_monitor.py
Fix #3212 by not compiling the prevent sync pattern from the local database since it's fragile and unnecessary.
=> Do not compile the "prevent sync" pattern from the local database

oxidation/libparsec/crates/client_types/src/local_manifest.rs, oxidation/libparsec/crates/types/src/regex.rs, src/binding_utils.rs, src/regex.rs
When a user has an older cache some regex contains escapes sequences like `\Z` which are not supported by rust `regex` crate. Note that `fancy_regex` has the same issue here.
This is a proposal to fix the issue (#3212) by replacing the unsupported escapes sequences. Although it works, there may be better ways to handle this issue.
=> Add test to check regex compat

newsfragments/3268.feature.rst, parsec/cli_utils.py, parsec/logging.py
> Also resolve some typo in the code.
=> Allow `log-level` & `log-format` CLI option to be case insensitive

.github/workflows/ci.yml, .github/workflows/package-ci.yml
The command `set-output` in **Github Action** has started its process to be fully deprecated. The command was replaced with a special file to set the output accessible via the `GITHUB_OUTPUT` environment var.
see <https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/> for references
=> Correct deprecation of command `set-output`

newsfragments/3300.bugfix.rst, newsfragments/3301.bugfix.rst, parsec/core/gui/forms/workspaces_widget.ui, parsec/core/gui/workspace_button.py, parsec/core/gui/workspaces_widget.py
Closes #3300 : unmounted workspaces did not appear greyed out when logging in
Closes #3301 : scrollbar would scroll to the bottom when unmounting a workspace
Also added a little bit of padding at the botton of the workspace layout so the bottom workspace buttons should no longer appear slightly cut.
=> [GUI] Fixed workspaces display

.github/workflows/ci.yml, build.py
Allow to configure the rust build profile using the environment variable `CARGO_PROFILE`. If the environment is not present we fallback to using the value defined in `DEFAULT_CARGO_PROFILE` which will be the `release` profile.
=> Rework `build.py` on the Rust compile profile selection

.github/workflows/package-ci.yml
Remove `ubuntu-18.04` as it has started it's brownout periods.
> Meaning that jobs using it will fail time to time, see actions/runner-images#6002
This already impact our CI see:
- https://github.com/Scille/parsec-cloud/actions/runs/3250758297
- https://github.com/Scille/parsec-cloud/actions/runs/3250749569
- https://github.com/Scille/parsec-cloud/actions/runs/3250664543
- https://github.com/Scille/parsec-cloud/actions/runs/3250445645
O7 CMDR
=> Remove `ubuntu-18.04` usage in the CI

.github/actions/setup-python-poetry/action.yml
Sometimes installing poetry fail, but we don't have any trace.
Here we will dump the log file generated during the installation,
Thus allowing use to report error if needed.
=> Dump `poetry` install logs on failure

oxidation/libparsec/crates/protocol/schema/authenticated_cmds/device_create.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/events_listen.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/human_find.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/organization_config.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/organization_stats.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_accept.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_info.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_list.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_reject.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_create.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_finish_reencryption_maintenance.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_get_role_certificates.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_start_reencryption_maintenance.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_stats.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_status.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/realm_update_roles.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/user_create.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/user_get.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/user_revoke.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_create.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_list_versions.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_maintenance_get_reencryption_batch.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_maintenance_save_reencryption_batch.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_poll_changes.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_read.json, oxidation/libparsec/crates/protocol/schema/authenticated_cmds/vlob_update.json, oxidation/libparsec/crates/protocol/schema/invited_cmds/invite_info.json, oxidation/libparsec/crates/serialization_format/src/protocol/parser/field.rs, oxidation/libparsec/crates/serialization_format/src/protocol/utils.rs
- The type `RequiredOption` mean for a field that it is always present but its value can be null.
- The type `NonRequiredOption` mean that a field can be absent or its value to be null.
=> Add type `RequiredOption` & `NonRequiredOption` to rust protocol

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/actions/paths-filter/action.yml, .github/actions/paths-filter/filters.yml, .github/workflows/ci.yml
- Disable the check for the news fragment bits.
- Add a pull request template to question the pr's author if the changes need a fragment.
- Update the ci to only check the news fragments if there was an edit on the folder `newsfragments`
=> Disable news fragments check

mypy.ini, parsec/_parsec_pyi/local_manifest.pyi, parsec/core/types/backend_address.py, parsec/core/types/pki.py, parsec/serde/fields.py, parsec/stubs/marshmallow/fields.pyi
This adds mypy types for module `parsec.core.types`. This close #3284.
=> mypy: Added missing types for `parsec.core.types`

mypy.ini, parsec/core/gui/input_widgets.py
This PR adds mypy typing to module `parsec.core.input_widgets`. This closes #3469
=> mypy: Add mypy typing to `input_widgets`

mypy.ini, parsec/core/gui/central_widget.py, parsec/core/gui/menu_widget.py, parsec/core/gui/workspace_button.py
This PR adds mypy typing to `parsec.core.gui.menu_widget`. This closes #3471
=> mypy: Added mypy typing to `menu_widget`

mypy.ini, parsec/logging.py
This PR adds mypy typing to `parsec.core.logging`. This closes #3499
=> mypy: Add mypy typing to `core.logging`

newsfragments/3507.bugfix.rst, src/protocol/invite.rs
Fix the invitation issue when greeter doesn't have HumanHandle
closes #3507
=> Fix invite without human handle

tests/core/gui/users_widget/test_greet.py, tests/core/gui/users_widget/test_invite.py
Added GUI tests for user invitation, making sure that it works when the greeter has no human handle. The test fails without #3509 and succeeds with it, as expected.
Closes #3505
=> Added GUI test to check invitation where the greeter has no human handle

mypy.ini, parsec/core/sync_monitor.py
This PR adds mypy typing to `parsec.core.sync_monitor`. This closes #3508
=> mypy: Add typing for `sync_monitor`

parsec/backend/cli/__init__.py, parsec/backend/cli/__main__.py, parsec/cli.py, parsec/cli_utils.py, parsec/core/cli/__init__.py, parsec/core/cli/__main__.py, parsec/core/cli/run.py
When building a pre-release wheel of `parsec` `cibuildwheel` was failing in the test phase of the wheel.
The cause was a problem with a bad use of the decorator `click.group` alongside `click.command`, both seems to be exclusive.
Alongside the fix, We also choose
- To rename `backend_cmd` => `backend_cmd_group`
- To rename `core_cmd` => `core_cmd_group`
- Correct the definition of the fake cmd `run_gui` in `core.cli.run`
Co-Authored: @vxgmichel
=> Correct fake command group when the module `backend` was missing in the packaging

mypy.ini, parsec/service_nursery.py
This PR adds support to module `add-mypy-service-nursery`. This closes #3530 .
=> mypy: Add mypy typing to `service_nursery`

parsec/core/gui/workspace_button.py
=> [GUI] Fixed user display on workspace button

parsec/core/gui/enrollment_widget.py
Fix pki enrollment typing and removed an incorrect assert.
=> Fixed pki enrollment typing

.github/workflows/package-ci.yml
Basically `actions-rs/toolchain` is not longer being maintained see <https://github.com/actions-rs/toolchain/issues/216>.
=> Use `dtolnay/rust-toolchain` instead of `actions-rs/toolchain`

mypy.ini
This PR adds mypy typing for `crypto` module. This closes #3528
=> mypy: Add mypy typing to `crypto`

parsec/api/protocol/__init__.py, parsec/api/protocol/pki.py
`PkiEnrollmentStatus` is unused
closes #3575
=> Remove pki enrollment status field

mypy.ini
Type checking for `parsec.monitoring` has been accidentally disabled by commit `c404347b94` despite this module has been properly typed by #3515.
=> mypy: Remove unused error ignore for `monitoring`

newsfragments/3534.bugfix.rst, parsec/core/gui/files_widget.py, tests/core/gui/test_files.py
Allows to import (with the button or drag&drop) empty folders.
Empty folders where previously ignored by the GUI.
Closes #3534
=> [GUI] Fixed import of empty folder

mypy.ini, parsec/core/messages_monitor.py
Mypy is now activated on every modules of `parsec.core`. This PR adds mypy typing to `parsec.core.messages_monitor` which is the last module of `core` without proper typing. This closes #3566
=> mypy: Add mypy typing to `messages_monitor`

newsfragments/3595.bugfix.rst, parsec/api/transport.py, parsec/core/backend_connection/transport.py
=> Protect _net_send against LocalProtocolError

.github/actions/setup-rust/action.yml, .github/actions/use-pre-commit/action.yml, .github/workflows/ci.yml, Cargo.toml
the same cache for rust & python jobs
- Build rust code using the same profile for rust & python jobs
- Add job to pre generate rust cache
- Update dependencies on action `actions/cache` to `v3.0.11`
=> Rework rust caching in CI

.github/workflows/package-ci.yml
`node-12` is End of Life since April 2022 and will be no longer supported by Github action next summer.
More info on that: <https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/>
=> Use updated `samuelmeuli/action-snapcraft` to use `node-16`

.github/workflows/ci.yml
The news fragments check is now only run when:
- The folder `newsfragments` or it's content was modified.
- The branch don't start with `yolo`, `revert` and `release`.
Ignoring branch starting with `dependabot` don't make sense here because `dependabot` **MUST NOT** edit that folder or it's content.
=> Remove `dependabot` from ignored branch for the news fragment check

newsfragments/3537.misc.rst, parsec/core/gui/device_recovery_export_widget.py, parsec/core/local_device.py, tests/core/gui/test_recovery.py
=> Add the option to rename recovery device at creation

parsec/backend/cli/sequester.py, parsec/sequester_export_reader.py, tests/backend/sequester/test_export.py
Add sequester timestamp cli parameter when building exported data
=> Sequester export filter date

parsec/core/gui/claim_device_widget.py, parsec/core/gui/claim_user_widget.py, parsec/core/gui/greet_device_widget.py, parsec/core/gui/greet_user_widget.py
Closes #3614 by handling an Optional QtToTrioJob in signal receivers.
=> Set proper typing on pyQtSignal receivers

newsfragments/3749.bugfix.rst, oxidation/libparsec/crates/types/src/id.rs
Fix: Accept parenthesis in HumanHandle's label
closes #3749
=> Fix human handle

parsec/api/protocol/pki.py
Last CI run on master failed because of format error that wasn't caught before merge. This PR remove this problematic line (https://github.com/Scille/parsec-cloud/actions/runs/3658771748/jobs/6183964861).
=> Remove uneccessary line in `protocol/pki`

.github/workflows/ci.yml, newsfragments/3752.bugfix.rst, parsec/backend/invite.py, tests/backend/invite/test_manage_invitations.py
=> Fix special character handling in Reply-To email header

parsec/_parsec_pyi/addrs.pyi, parsec/backend/asgi/rpc.py, parsec/backend/asgi/ws.py, tests/backend/test_rpc_handshake.py, tests/backend/test_ws_handshake.py
This PR allows to show what version a client is using in logs. This closes #3615
=> Add client version in logs

newsfragments/3769.bugfix.rst, parsec/core/gui/custom_widgets.py
Fixed a small bug introduced by typing when mouse hovering the QRCode in a device invitation.
=> UnboundLocalError: local variable `icon_scaled` referenced before assignment

oxidation/client/electron/package-lock.json, oxidation/client/electron/package.json
Override `@electron/universal`'s version to stop using deprecated dependency `asar`
Switch from electron-rebuild to @electron/rebuild (package name change, not breaking).
fixes #3736 
fixes #3733
=> Bump npm packages to remove some deprecated one

.cspell/cspell.config.yml, .github/workflows/ci.yml
Each CI run end up with roughly 6 x 700mo of cache, this is too huge for the 10Go cache :(
A stopgap is to only save the cache of the build on master: PRs cannot share they cache so only master's cache is shared accross PRs
On top of that it brings an incentive to rebase the PRs: you get the cache working if you use a recent enough master base !
Aaaaand last but not least it seems saving cache [takes quiet some time](https://github.com/Scille/parsec-cloud/actions/runs/3735400246/jobs/6338596940): I saw a 2mn30s time to upload 677mo of cache on Windows (~50s on macOS and ~30s on Linux)
=> Tweak CI to save cache only during master build

newsfragments/3846.bugfix.rst, parsec/core/gui/enrollment_widget.py
Hide the spinner during enrollment by PKI.
Closes #3846
=> Fix pki enrollment spinner

parsec/_parsec.pyi, parsec/_parsec_pyi/device.pyi, src/enumerate.rs, src/lib.rs
This PR adds a binding for `DeviceFileType` enum. I didn't removed the python version completely because this will be done in the upcoming PRs to oxidize schemas.
=> Oxidize device file type enum

oxidation/bindings/electron/src/index.d.ts, oxidation/bindings/electron/src/meths.rs, oxidation/bindings/generator/generate.py, oxidation/bindings/generator/templates/binding_electron_index.d.ts.j2, oxidation/bindings/generator/templates/binding_electron_meths.rs.j2, oxidation/bindings/generator/templates/binding_web_meths.rs.j2, oxidation/bindings/generator/templates/client_plugin_definitions.d.ts.j2, oxidation/bindings/web/src/meths.rs, oxidation/client/src/plugins/libparsec/definitions.d.ts
Use camelCase for auto-generated TypeScript bindings. Not sure if I got every cases.
Closes #3886
=> Updated bindings generator to use camelCase for TypeScript

Cargo.lock, oxidation/libparsec/crates/client_types/src/local_device_file.rs, oxidation/libparsec/crates/client_types/src/test/test_local_device.rs, oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs, oxidation/libparsec/crates/platform_device_loader/Cargo.toml, oxidation/libparsec/crates/platform_device_loader/src/native/local_device_file.rs, oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
- Don't serialize anymore legacy device file
- Remove the useless option in `DeviceFilePassword` (we handle `LegacyDeviceFilePassword` somewhere else)
=> Improve DeviceFile & LegacyDeviceFile

.github/actions/paths-filter/filters.yml, .github/workflows/ci.yml, build.py, oxidation/libparsec/crates/core/Cargo.toml, oxidation/libparsec/crates/platform_device_loader/src/web/local_device.rs, oxidation/libparsec/crates/platform_device_loader/src/web/local_device_file.rs, pyproject.toml
The CI packaging is broken, because the `default-feature` isn't disabled for `libparsec_platform_device_loader` which depends on `libparsec_crypto`
=> Fix CI packaging

newsfragments/3855.misc.rst, parsec/core/gui/file_table.py, parsec/core/gui/files_widget.py, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po
This PR adds more distinctions between files and folders in contextual menus and titles.
Closes #3855 
"élément" feels fitting in french, but not quite as much in english. I didn't find another generic term for "file or folder".
=> Better distinction between file and folder in GUI

newsfragments/3946.bugfix.rst, parsec/core/gui/main_window.py
When opening the GUI for the first time, the window should take all the available space.
Closes #3946
=> [GUI] Maximize window by default

src/binding_utils.rs, src/local_device.rs, tests/core/test_local_device.py
This closes #3942 . When we return a `PathBuf` with `pyo3` the default conversion gives a python string. We want this conversion to yield a `pathlib.Path` because it makes path manipulation easier in python.
=> Fix available device key file path type

build.py, poetry.lock, pyproject.toml
- Update `maturin` used in build system to 0.14 (from 0.13)
- Install `patchelf` on Linux platform
- Install extra for `maturin` to use `patchelf`
=> Update maturin & patchelf

packaging/testbed-server/build.sh, packaging/testbed-server/testbed-server.dockerfile
- Rework tagging: provide 2 tag `latest` and one in the format `<date in iso-8601>-<current version>-<short commit sha>`
- Add some documentation output on how to run the builded container + how to push it to GitHub
- Enforce that no command fail with `set -e`
- Add label to the image
=> Improve testbed docker build script

newsfragments/3969.bugfix.rst, parsec/core/config.py, parsec/core/gui/forms/workspaces_widget.ui, parsec/core/gui/workspaces_widget.py, tests/core/gui/conftest.py, tests/core/gui/test_workspaces.py
No longer hides unmounted workspaces by default, and the state of show/hide unmounted workspaces is saved in config.
Closes #3969
=> [GUI] Show unmounted workspace by default and save the state

newsfragments/3967.bugfix.rst, parsec/core/gui/users_widget.py, tests/core/gui/users_widget/test_invite.py
User invitations were ignored by the query string and not displayed even if the email matched what was searched.
Closes #3967
=> [GUI] Include user invitation in the query string

.github/workflows/ci.yml
Sometime the default configured APT proxy in the ubuntu runner image have connection failure. Since this Repo is a cache-proxy meaning it redirect to the official Canonical repo on cache miss, We can have failure if the link between the Cache-proxy and the ubuntu repo fail for whatever reason.
To mitigate that I've applied the suggestion in https://github.com/actions/runner-images/issues/7048#issuecomment-1419426054 We basically make `apt` use a mirror list of APT repos with the Cache-proxy has the top priority one.
=> Configure a mirror list for ubuntu APT repo

src/runtime.rs
=> Fix `FutureIntoCoroutine` runtime binding

parsec/api/protocol/types.py
=> Simplify typing in `parsec.api.protocol.types`

parsec/backend/app.py, parsec/backend/asgi/rpc.py, parsec/backend/ping.py, parsec/backend/utils.py, tests/backend/test_rpc_handshake.py, tests/common/backend.py
460 for organization expired
461 for user revoked
415 for any bad content
=> Replace generic errors in server RPC API by HTTP codes

parsec/core/gui/workspaces_widget.py
Fixed small typing mistake on some callbacks.
Closes 4045
=> Fix callback typing in workspaces_widget

newsfragments/4033.feature.rst, parsec/core/gui/custom_widgets.py, parsec/core/gui/forms/users_widget.ui, parsec/core/gui/tr/parsec_en.po, parsec/core/gui/tr/parsec_fr.po, parsec/core/gui/users_widget.py, tests/core/gui/users_widget/test_list.py
Added a combo box to filter users by their profile (show only administrators for example).
Also fixed a small mistake with input's clear button not showing in some cases.
Closes #4033
=> [GUI] Added user filtering by profile

parsec/core/fs/remote_loader.py, parsec/core/fs/storage/__init__.py, parsec/core/fs/storage/workspace_storage.py, parsec/core/fs/workspacefs/entry_transactions.py, parsec/core/fs/workspacefs/file_operations.py, parsec/core/fs/workspacefs/file_transactions.py, parsec/core/fs/workspacefs/remanence_manager.py, parsec/core/fs/workspacefs/workspacefs.py, parsec/core/gui/create_org_widget.py, parsec/core/sync_monitor.py
- Replace `BaseWorkspaceStorage` with `AnyWorkspaceStorage`
> This change will make more sense when we merge #2903 
- Replace `Tuple` by `tuple`, `Dict` by `dict`, etc
- Move import mostly to `parsec._parsec`
=> [parsec] Improve typing

mypy.ini, tests/common/binder.py, tests/common/freeze_time.py, tests/core/fs/storage/test_user_storage.py, tests/core/fs/test_bootstrap.py, tests/core/fs/test_fs_sync.py, tests/core/fs/test_reencrypt_workspace.py, tests/core/fs/userfs/test_sync.py, tests/core/fs/workspacefs_timestamped/conftest.py, tests/core/test_messages_monitor.py
- Allow to freeze multiple `devices`.
- Use `time_provider` to also freeze time in the rust lib.
- Allow to freeze the global scope alongside some devices.
- Update tests to use the new `freeze_time`
- Also made some change for `test_storage_file_tree`
=> Improve `freeze_time` mock

.github/workflows/ci.yml, oxidation/client/package.json
Currently our unit test started to fail because of a change introduced in node-18.13.0 (nodejs/node#46123).
So using a version before that change would correct the test that fail in #4071.
Changes
-------
- Change node-version in `ci.yml` to `18.12.0`
- Use github action `actions/setup-node` in `Web tests`
=> Prevent using node > 18.13.0

.github/workflows/ci.yml
Sometime the command `npm clean-install` may fail because the network is unstable.
To mitigate that, we wrap the command into a `until loop` that will retry until the command succeeded or we timeout.
=> [ci] Retry install npm package

.github/workflows/package-ci.yml
Macos timeout on that step, see <https://github.com/Scille/parsec-cloud/actions/runs/4254198641/jobs/7400109887>
So i've increase the timeout by 20 minutes.
Closes #4088
=> Correct MacOS timeout on the step `build python wheel`

oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
=> Remove the use uuid in chunk_storage

tests/common/backend.py
=> Improve unused_tcp_port fixture on Windows&MacOS

.github/workflows/ci.yml
This could prevent something like:
<https://github.com/Scille/parsec-cloud/actions/runs/4316921098/jobs/7533327905>
Where the linux runner was stuck for 5h30m (and crash after).
=> Add `timeout` to github action tasks

.github/workflows/package-ci.yml
The PR #3985 have change the name of the app in `package.json::name` to `parsec`. We forgot to update the path in the action `upload-artifact`.
Add check to test if we have the expected generated files.
=> Correct `package-electron-app` not uploading artifact

.github/workflows/package-ci.yml
Settings `if-no-file-found=error` will make the github action `upload-artifact` to fail if it found no file.
depends on #4090
=> Harden `upload-artifact` to fail if no file is found

.github/workflows/package-ci.yml
- Also install the correct python version that is used for internal setup script.
- Install the correct rust version.
- Add timeout to the job & tasks.
- Rewrite the artifact upload to accommodate different path depending on the platform we execute the job on.
=> Add windows to the packaged electron os

.github/workflows/ci.yml
The job <https://github.com/Scille/parsec-cloud/actions/runs/4352606720/jobs/7605596017> timeout-ed because it take more than 1 min to checkout the branch to run the CI on.
So I've increase the timeout to 2min.
=> Increase timeout when checking out the branch to 2min

docs/development/index.rst, docs/development/quickstart.rst, docs/index.rst, docs/userguide/index.rst
`sphinx` during the `make gettext` complain with the following warning:
- Missing document `development`
```txt
/parsec-cloud/docs/index.rst:45: WARNING: toctree contains reference to nonexisting document 'development'
```
Resolved by removing `development` (we don't want those documents on the website).
- Document `functional_architecture` isn't included
```txt
/parsec-cloud/docs/development/functional_architecture.rst: WARNING: document isn't included in any toctree
```
Resolved by including it in the TOC
- Unknown target name in `userguide/index` ```txt /parsec-cloud/docs/userguide/index.rst:20: ERROR: Unknown target name: "parsec user guide [french]<https://parsec.cloud/wp-content/uploads/2022/04/gu-a-jour-android-new-1.pdf>". ```
Resolved by adding a ` ` between `[French]` and …
=> Correct `sphinx` warning

.cspell/cspell.config.yml
`libparsec_python` folder was removed in #2898.
So `cpsell` no longer need to watch (or ignore this path).
=> Remove `libparsec_python` from ignored cpsell ignored paths

.github/workflows/package-ci.yml
Correct a typo on the param `if-no-files-found` used by the github action `upload-artifact`
=> Correct typo on param name for `upload-artifact` GA

.github/filters/ci.yml, .github/workflows/ci.yml
Saving the python lib `libparsec` generated by the binding is useless on the merge queue
Because each branch are one time use so the cache isn't reused.
To correct that, I split the `cache` system into 2 phase `restore` & `save`:
- `restore` will always tries to restore the cache
- `save` will only save the cache when we aren't on Github merge queue and the rust code isn't modified
closes #4153
=> Don't save python lib `libparsec` when on Github merge queue

parsec/backend/asgi/rpc.py
I've replace the custom header value by using an enum to give those values a name.
=> Define constant for custom HTTP code in `backend.rpc`

.github/filters/ci.yml, .github/workflows/ci.yml
Rework the paths filter used in the CI that is used to determined which jobs's tasks (python, rust, web) should be run.
This change is more strict than the previous implementation
I've also simplified the filters, the ci only need to use the `*-jobs` corresponding to `{python,rust,web}-jobs` on its side.
Some paths aren't watched because we don't (currently) have tests for them (except the basic `Q&A`)
=> Rework paths filter used in the CI

oxidation/libparsec/crates/types/src/addr.rs, oxidation/libparsec/crates/types/tests/test_addr.rs, src/addrs.rs, tests/core/test_backend_address.py
Using an enum instead of string errors:
- Reduce the amount of duplicate string found in the codebase.
- Reduce the amount of place where we could have typo.
closes #4230
=> Replace `string error` with an enum in `libparsec_types::addr`

.github/filters/codeql.yml, .github/workflows/codeql.yml
Use `paths filter` in `codeql` to prevent it from running when python code hasn't been modifed
=> Add paths filter to codeql

.cspell/custom-words.txt, .github/filters/ci.yml, oxidation/bindings/generator/generate.py, oxidation/bindings/generator/templates/binding_web_meths.rs.j2, oxidation/bindings/web/src/meths.rs
This was required by the change made in #4233 where we change the error type for AddrError from a string to an enum. But `TypeError` expect a `string` in the `TypeError::new` (would be nice if it allows `impl Display` instead :thinking:)
Other change
------------
Rework generator script to format generated rust code
> Before exiting the script, the generator will call `cargo-fmt` on the modified packages.
=> Update gen web rust template to convert rust error to string

oxidation/libparsec/crates/platform_local_db/src/executor.rs
This timeout would help analyse the flakyness of the test on the CI
see #4176
=> Add timeout to `fail_reopen_database`

tests/scripts/run_testbed_server.py
=> Use port 6770 by default for run_testbed_server.py

.github/filters/codeql.yml, .github/workflows/codeql.yml
I have configured CodeQL to analyse our typescript / javascript codebase that is used to build our new client.
closes #4009
=> Enable CodeQL to scan typescript / javascript code

.github/workflows/codeql.yml, oxidation/bindings/electron/src/meths.rs, oxidation/bindings/generator/api/common.py, oxidation/bindings/generator/templates/binding_electron_index.d.ts.j2, oxidation/bindings/generator/templates/binding_electron_meths.rs.j2, oxidation/bindings/generator/templates/binding_web_meths.rs.j2, oxidation/bindings/generator/templates/client_plugin_definitions.d.ts.j2, oxidation/bindings/web/src/meths.rs
- Use `AsRef<str>` to support more error type for `TypeError` and `ctx.throw_type_error`
- Remove extra space added when generating the typescript definition files from the jinja template
=> Simpler web electron error convertion

.github/workflows/ci.yml, .github/workflows/package-ci.yml, oxidation/bindings/README.md
Configuring cargo to use the sparse checkout will allow for faster updates of the cargo index (The index cache will also be smaller).
For reference: <https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol>
Depends on #4250
=> Configure CI workflows to use cargo sparse checkout when updating its index

parsec/core/fs/workspacefs/workspacefs.py, parsec/core/fs/workspacefs/workspacefs_timestamped.py
=> Remove `remote_devices_manager` field from `WorkspaceFS` & `WorkspaceFSTimestamped`

oxidation/libparsec/crates/crypto/src/rustcrypto/secret.rs
The comment seems to be outdated, because we use `new`
=> Remove outdated comment

Cargo.toml
=> Use 'opt-level = 1' for all non libparsec_* dependencies in dev

.pre-commit-config.yaml
Documentation about [`stages`](https://pre-commit.com/#config-stages)
=> Configure `pre-commit` to run `cspell` hook on manual trigger

Cargo.lock
This will prevent the error tracked in diesel-rs/diesel#3541
=> Bump `diesel_derives` to `2.0.2`

newsfragments/4368.bugfix.rst, parsec/backend/cli/sequester.py
=> Fix `backend sequester list_services` CLI output when error is returned

newsfragments/4367.bugfix.rst, parsec/core/gui/forms/question_widget.ui
Simple fix of a link (`<a href="">`) in a text not being clickable.
Closes #4367
=> [GUI] Fixed user guide link not clickable after creating an organization

README.rst, docs/locale/fr/LC_MESSAGES/userguide.po, docs/userguide/installation.rst
=> move pip installation for parsec on documentation

Cargo.lock, oxidation/libparsec/crates/tests_fixtures/Cargo.toml, oxidation/libparsec/crates/tests_fixtures/src/lib.rs, oxidation/libparsec/crates/types/Cargo.toml, oxidation/libparsec/crates/types/src/error.rs, oxidation/libparsec/crates/types/src/fixtures.rs, oxidation/libparsec/crates/types/src/lib.rs, oxidation/libparsec/crates/types/src/regex.rs, oxidation/libparsec/crates/types/tests/mod.rs, oxidation/libparsec/crates/types/tests/test_addr.rs, oxidation/libparsec/crates/types/tests/test_certif.rs, oxidation/libparsec/crates/types/tests/test_id.rs, oxidation/libparsec/crates/types/tests/test_invite.rs, oxidation/libparsec/crates/types/tests/test_local_device.rs, oxidation/libparsec/crates/types/tests/test_local_device_file.rs, oxidation/libparsec/crates/types/tests/test_local_manifest.rs, oxidation/libparsec/crates/types/tests/test_manifest.rs, oxidation/libparsec/crates/types/tests/test_message.rs, oxidation/libparsec/crates/types/tests/test_pki.rs, oxidation/libparsec/crates/types/tests/test_sas_code.rs, oxidation/libparsec/crates/types/tests/test_time.rs
`libparsec_types` required `libparsec_tests_fixtures` which required `libparsec_types` itself causing an error on rust-analyzer.
To resolve that, I have introduced the module `fixture` that define the fixture that where used during the test of libparsec_types and re-expose them in `libparsec_tests_fixtures`.
rust-analyze fell really more snappy now when working on `libparsec_types`, so I've made some compilation benchmark when building the test for `libparsec_types`
On master: `11.5s`
On this branch: `6.8s`
> Both with `jobs=16 ncpu=16`
This also simplify a lot the dev-dependencies tree.
<details>
<summary>Cargo tree of `libparsec_types` diff between `master` and this branch</summary>
```diff
--- /tmp/libparsec_types_deps_master	2023-04-05 17:43:08.239169906 +0200
+++ …
```
=> Break Cyclic dependencies in `libparsec_types` (fixture mod)

newsfragments/4363.feature.rst, parsec/backend/cli/__init__.py, parsec/cli_utils.py, parsec/core/cli/__init__.py, tests/test_cli.py
Currently, the `--version` is only handled on the root CLI
```
python -m parsec.cli --version
```
But the installed `parsec` app is aliased like that
```
python -m parsec.cli core gui
```
So previously when adding the flag `--version` result in the error described in #4363.
To fix that, I've added `click.version` in the function `debug_config_options` So everywhere this function is used to add the `--debug` flag, we also get the `--version` flag.
I've added more case for the test `test_version` to show it's working with sub-command
Closes #4363
=> Support `--version` flag almost everywhere

Cargo.lock, oxidation/libparsec/Cargo.toml, oxidation/libparsec/crates/client_connection/Cargo.toml, oxidation/libparsec/crates/client_connection/src/anonymous_cmds.rs, oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs, oxidation/libparsec/crates/client_connection/src/error.rs, oxidation/libparsec/crates/client_connection/src/invited_cmds.rs, oxidation/libparsec/crates/miniprotocol/Cargo.toml, oxidation/libparsec/crates/miniprotocol/src/lib.rs, oxidation/libparsec/crates/protocol/Cargo.toml, oxidation/libparsec/crates/protocol/src/error.rs, oxidation/libparsec/crates/protocol/src/lib.rs, oxidation/libparsec/crates/protocol/tests/test_block.rs, oxidation/libparsec/crates/protocol/tests/test_events.rs, oxidation/libparsec/crates/protocol/tests/test_ping.rs, oxidation/libparsec/crates/protocol/tests/test_user.rs, oxidation/libparsec/crates/serialization_format/Cargo.toml, oxidation/libparsec/crates/serialization_format/src/protocol.rs, oxidation/libparsec/crates/serialization_format/src/utils.rs, oxidation/libparsec/crates/serialization_format/tests/test_protocol.rs, oxidation/libparsec/src/lib.rs
The crate `libparsec_protocol` depends on `libparsec_serialization_format` which it self depends on `libparsec_protocol::Request` (in dev-dependencies for testing purpose).
To resolve that, I've create an intermediate crate `libparsec_miniprotocol` that will be used by the crate `protocol` and `serialization_format`.
The Gain
--------
When compiling `libparsec_protocol[test]` the gain is not obvious:
```
master: 11.1s
this branch: 10.4s
```
But when compiling `libparsec_serialization_format[test]` the gain is clear:
```
master: 12.5s
this branch: 2.7s
```
This gain is caused because `libparsec_protocol` take a lot of time in `code-gen` (=> generating code) and `serialization_format` only required `protocol` for `Request`
> Those result is obtain with
>
> ```bash
> cargo clean -p <crate>
> …
```
=> Break cyclic dependencies in `libparsec_protocol`

.github/workflows/ci-python.yml
This would force to re-link the libparsec when updating the python version.
Closes #4413
=> Add python version to libparsec cache key

Cargo.lock, oxidation/libparsec/crates/client_connection/Cargo.toml, oxidation/libparsec/crates/client_connection/src/anonymous_cmds.rs, oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs, oxidation/libparsec/crates/client_connection/src/client.rs, oxidation/libparsec/crates/client_connection/src/invited_cmds.rs, oxidation/libparsec/crates/client_connection/src/lib.rs, oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs, oxidation/libparsec/crates/platform_http_proxy/Cargo.toml, oxidation/libparsec/crates/platform_http_proxy/src/lib.rs, oxidation/libparsec/crates/platform_http_proxy/tests/unit/tests.rs, src/backend_connection/anonymous_cmds.rs, src/backend_connection/authenticated_cmds.rs, src/backend_connection/invited_cmds.rs
I've added a new crate `platform_http_proxy` with the only goal to return the list of proxies to apply to an http client from `reqwest`.
For now it only handle the configuration from the env variables `HTTP_PROXY` & `HTTPS_PROXY` + manual configuration.
Note that proxy configuration isn't possible on `wasm`.
`Reqwest` does not expose `Proxy` when compile on `wasm`
Closes #3873
=> Add a crate to manage http proxy configuration

.github/CODEOWNERS
With the previous definition the main problem was with the `src` folder. The system will look for every `src` folder and will assign the related team.
The is problematic when we modify a file in `oxidation/client/src`, this will assign the python team to it.
Other Changes
-------------
- Correct that some folder is shared between multiple team (e.g. `/src` folder).
- Correct @touilleMan not correctly assign to `.github/CODEOWNERS` (the cause was with the `.github/` match of the ops team).
- Re-order the file this way:
- JS
- JS + Rust
- Rust
- Rust + Python
- Python
- OPS
- CODEOWNERS
=> Correct CODEOWNERS assigned folder

.github/workflows/ci-rust.yml, .github/workflows/ci.yml
This is possible to skipping the `fmt` step that required `rust` (`cargo fmt`). Now the `cargo fmt` step is perform in `ci-rust`.
=> Rework `Q&A` to not require `rust` install.

.github/actions/use-pre-commit/action.yml, .github/filters/ci.yml, .github/workflows/ci-python.yml, .github/workflows/ci.yml
Installing `poetry` & `python` in `Q&A` was only required when we change python code.
It's more efficient to do that in `ci-python` since this workflow should be run when actual python code is changed (note, it is also run when we modify `rust` code).
Other Changes
-------------
- Action `use-pre-commit`:
- Return the install path of `pre-commit` in the outputs variable `install-path`.
- Skip `Run pre-commit` step when `install-only != true`.
=> Don't require to install `poetry` & `python` in Q&A.

.cspell/cspell.config.yml, .github/actions/use-pre-commit/action.yml, .github/filters/ci.yml, .github/workflows/ci-python.yml, .github/workflows/ci-rust.yml, .github/workflows/package-ci.yml, .yamllint.yml
This will ensure a consistent style across our yaml files. 
I choose double-quote since it's the same style enforced in the python files (but remain open to discussion).
=> Change `yamllint` configuration to only allow for double-quote style in yaml files

build.py, pyproject.toml
Since `maturin` isn't stable (version > `1.*`) minor change are allowed to be breaking. This actually bites us because the CI now use the version `0.15.1` that contain breaking change.
To correct that, I've fixed the version (using `==` instead of `~=`) and also display the version of maturin in `build.py`.
=> Fix `maturin` version to `0.14.15`

.pre-commit-config.yaml, .readthedocs.yml
- Validate `Read the doc` configuration file 
- Change `image` to `os` since it's deprecated.
- Fix os version to `ubuntu-22.04`.
- Specify python version `3.9`.
- Config RTD to generate `pdf` alongside the website.
Closes #4517
=> Update `Read the docs` configuration files

.github/workflows/ci-python.yml, .github/workflows/ci-rust.yml, .github/workflows/ci-web.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/cspell.yml, .github/workflows/package-ci.yml
See [`concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency) for more information.
The goal was to limit multiple workflow runs on a given PR. This will cancel previous runs and make the workflows run on the most up-to-date code.
=> Use `concurrency` to prevent multiple workflow runs

.readthedocs.yml
Read the docs doesn't support multiple pdfs generation for the moment. See <https://github.com/readthedocs/readthedocs.org/issues/2045>.
=> Disable pdfs generation on read the docs

.github/scripts/check_newsfragments.py
Correct invalid fragment type `docs` instead of `doc` for fragment `4127.doc.rst`
> Note: Due to renaming the fragment, I need to ignore the github issue check for this specific fragment
=> `check_newsfragment` validate `fragment` type

.github/dependabot.yml
This will increase the update frequency, and reduce the update backlog. I also assign each ecosystem a different weekday to open update PRs.
Closes #4721
=> [Dependabot] Change interval to weekly

parsec/core/cli/run.py, parsec/core/config.py, parsec/core/gui/workspaces_widget.py, parsec/core/logged_core.py, parsec/core/mountpoint/manager.py, parsec/core/mountpoint/winfsp_runner.py, parsec/core/win_registry.py, tests/core/mountpoint/conftest.py, windows-icon-handler/common/include/parsec.h
This PR adds support for single mountpoint mode on Windows: when enabled via the `single_mountpoint_enabled` option, workspaces are mounted into the `base_mountpoint_path` directory instead of using drive letters. 
It is a simpler and safer alternative solution to https://github.com/Scille/parsec-cloud/pull/4538 for #4668.
Closes #4668
=> Add single mountpoint mode for Windows

client/.eslintrc.cjs
By default, switch/case are formatted as
```typescript
switch(v) {
case 0: {
...
}
}
```
which is ugly.
Now they are formatted as
```typescript
switch(v) {
case 0: {
...
}
}
```
which is a bit better.
=> [MS] Fixed eslint for switch-cases

libparsec/crates/types/src/certif.rs, libparsec/crates/types/src/ext_types.rs, libparsec/crates/types/src/id.rs, libparsec/crates/types/src/invite.rs, libparsec/crates/types/src/local_device.rs, libparsec/crates/types/src/local_manifest.rs, libparsec/crates/types/src/manifest.rs, libparsec/crates/types/src/message.rs
This PR replaces all `unwrap_or_else(|_| unreachable!())` with `expect(...)` in the `types` crate.
Error messages use the "error as precondition" style as defined in https://doc.rust-lang.org/std/error/index.html#common-message-styles
Closes #4542 
=> Replace unwrap_or_else(|_| unreachable!()) with expect(...)

.cspell/custom-words.txt, Cargo.toml, bindings/android/libparsec/rust/Cargo.toml, bindings/electron/Cargo.toml, bindings/web/Cargo.toml, libparsec/Cargo.toml, libparsec/crates/client/Cargo.toml, libparsec/crates/client_connection/Cargo.toml, libparsec/crates/client_high_level_api/Cargo.toml, libparsec/crates/crypto/Cargo.toml, libparsec/crates/platform_async/Cargo.toml, libparsec/crates/platform_device_loader/Cargo.toml, libparsec/crates/platform_http_proxy/Cargo.toml, libparsec/crates/platform_storage/Cargo.toml, libparsec/crates/protocol/Cargo.toml, libparsec/crates/serialization_format/Cargo.toml, libparsec/crates/testbed/Cargo.toml, libparsec/crates/tests_fixtures/Cargo.toml, libparsec/crates/tests_macros/Cargo.toml, libparsec/crates/types/Cargo.toml, server/Cargo.toml
Move the multiple (more than 1) definition of a rust dependencies in the root `Cargo.toml`.
Using `workspace.dependencies` provide the following benefit:
- Prevent conflict when 2 actors update one of those dependencies in parallel.
The potential conflict is simpler to resolve, only `/Cargo.toml` is modified.
- Ensure all sub-crates are using the same version.
- Reduce that amount of modified files by `dependabot`.
Here is the list of dependencies that I've moved to `workspace.dependencies`:
- `regex`
- `paste`
- `uuid`
- `tokio`
- `lazy_static`
- `futures`
- `rmp-serde`
- `serde`
- `log`
- `wasm-bindgen`
- `wasm-bindgen-futures`
- `js-sys`
- `console_log`
- `wasm-bindgen-test`
- `reqwest`
- `url`
- `chrono`
- `thiserror`
- `bytes`
- `once_cell`
- `anyhow`
- `pretty_assertions`
- …
=> Specify shared dependencies in `workspace.dependencies`

client/src/components/PasswordInput.vue
Make sure that the ion-input isn't cleared when regaining focus in password mode. It's a bit confusing and doesn't bring much in our case when we can toggle password visibility.
=> [MS] Fixed password input clear on edit

.cspell/custom-words.txt, .github/actions/use-pre-commit/action.yml, Cargo.lock, Cargo.toml, libparsec/crates/crypto/src/rustcrypto/sequester.rs, libparsec/crates/crypto/tests/sequester.rs, libparsec/crates/platform_storage/src/native/db/option.rs, server/src/time.rs
=> Batch rust update

server/poetry.lock, server/pyproject.toml
This PR sets `certifi` version to `^2023.7.22`. Note that this **does not change** the current version, only pins it in `pyproject.toml`.
This should also be backported to the `releases/2.16` branch. See #5027
=> Pin certifi version to 2023.7.22

.cspell/custom-words.txt, .github/workflows/ci-rust.yml
Having a specific steps for each test suite improve the CI because it allow to set tiddier timeout and in case of failure provide a shorter stack trace.
=> Rework libparsec_crates_flags to categorize crates by type

docs/adminguide/index.rst, docs/adminguide/installation.rst, docs/adminguide/stats_organization.rst, docs/adminguide/stats_server.rst, docs/architecture.rst, docs/cryptography.rst, docs/history.rst, docs/index.rst, docs/introduction.rst, docs/roles.rst, docs/userguide/index.rst, docs/userguide/installation.rst, docs/userguide/new_device.rst, docs/userguide/new_organization.rst, docs/userguide/new_user.rst, docs/userguide/revoke_user.rst, docs/userguide/share_data.rst, misc/license_headers.py
The script `license_headers` was using the `HtmlLicenserMixin` for `rst` files instead of `RstLicenserMixin`.
The rst files got their license header updated accordingly.
Closes #5099
=> Fix wrong used license mixin for `rst` file

bindings/generator/templates/binding_electron_meths.rs.j2
This change doesn't currently affect the generated `electron/meth.rs` but will in the future (The PR #5122 contain weird indentation that these changes fix, `cargo fmt` wasn't formatting the code :thinking: )
=> Correct indentation for tuple type

parsec/core/mountpoint/manager.py, parsec/core/mountpoint/winfsp_runner.py, tests/core/mountpoint/test_base.py
The aim of this change is to deliver the personal workspace as quickly as possible, while avoiding the use of the Windows registry.
As the personal workspace is unique per user and per organization, there is no risk of reaching letter saturation on Window.
=> Force personal workspace to mount as letter on windows

bindings/electron/src/index.d.ts, bindings/generator/generate.py
Previously `all` wasn't doing everything now `all` will be handled as if all possible choice listed `TEMPLATE_CHOICES` where passed as arguments to `generate.py`
Other Changes
-------------
- Fix indentation in `electron/index.d.ts` by running `generate.py electron_client`
=> Rework `all` argument passed to `generate.py`

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/generator/api/common.py, bindings/generator/api/invite.py, bindings/generator/api/os.py, bindings/generator/generate.py, bindings/generator/templates/binding_electron_index.d.ts.j2, bindings/generator/templates/binding_electron_meths.rs.j2, bindings/generator/templates/binding_web_meths.rs.j2, bindings/generator/templates/client_plugin_definitions.ts.j2, bindings/web/src/meths.rs, client/src/common/mocks.ts, client/src/common/parsec.ts, client/src/plugins/libparsec/definitions.ts, client/src/views/home/CreateOrganizationModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/tests/component/specs/testInvitationCard.spec.ts, client/tests/component/specs/testInvitationListItem.spec.ts, client/tests/component/specs/testOrganizationCard.spec.ts
The conversion between `typescript enum <-> rust enum` is made using by strings.
The enums needed to be defined in `common.ts` because if it where
defined in `definitions.d.ts` we would not be able to use it as a value.
Other changes
-------------
- Use `type` instead of `str` for `BaseTypeInUse::parse`
=> Provide typescript enum for basic rust enum (flat enum) 

client/src/plugins/libparsec/index.ts, client/src/plugins/libparsec/trampoline-native.ts, client/src/plugins/libparsec/trampoline-web.ts, client/src/plugins/libparsec/trampoline.d.ts, client/src/vite-env.d.ts, client/vite.config.ts
- Use an alias to import the correct `trampoline` file instead of doing a copy each time the platform change.
- Rename the `ts.in` files to `.ts` to make typescript transpile them.
=> Use vue alias configuration for `trampoline` instead of file copy

client/src/plugins/libparsec/trampoline-web.ts
When using libparsec in vitest:
```
FAIL  tests/component/specs/testAvatarGroup.spec.ts > User Avatar > Display avatar for user
Error: libparsec is not available with Vitest, use Cypress instead !
❯ Object.LoadWebLibParsecPlugin [as web] src/plugins/libparsec/trampoline.ts:28:11
26|   // Hence we go with solution 3: prevent use of libparsec from Vitest.
27|   if (import.meta.env.VITEST) {
28|     throw new Error("libparsec is not available with Vitest, use Cypress instead !");
|           ^
29|   }
30| 
❯ loadPluginImplementation node_modules/@capacitor/core/build/runtime.js:53:80
❯ Proxy.getOs node_modules/@capacitor/core/build/runtime.js:92:27
❯ tests/component/specs/testAvatarGroup.spec.ts:14:43
```
=> Vitest fix config

libparsec/Cargo.toml, libparsec/crates/client_connection/Cargo.toml, libparsec/crates/crypto/Cargo.toml, make.py, server/build.py, server/packaging/server/in-docker-build.sh, server/packaging/testbed-server/in-docker-build.sh, server/pyproject.toml
On my machine, clean `cargo build --tests --timings` goes from 2m20 to 1m40
openssl makes ~70s on my machine to build and end up stalling the whole build (at some point, all remaining crates waits on it to finish before being able to start compilation)
We only need to vendor openssl when in `use-sodiumoxide` mode, and only on non-Linux platform (as on Linux we already depends on the openssl shipped by the system anyway)
=> Openssl not vendored

.github/workflows/ci-python.yml, Cargo.lock, libparsec/Cargo.toml, libparsec/crates/serialization_format/src/protocol_python_bindings.rs, libparsec/src/lib.rs, make.py, server/Cargo.toml, server/build.py, server/src/addrs.rs, server/src/api_crypto.rs, server/src/backend_events.rs, server/src/binding_utils.rs, server/src/data/certif.rs, server/src/data/error.rs, server/src/data/manifest.rs, server/src/data/message.rs, server/src/data/organization.rs, server/src/data/pki.rs, server/src/data/user.rs, server/src/enumerate.rs, server/src/ids.rs, server/src/misc.rs, server/src/protocol.rs, server/src/regex.rs, server/src/testbed.rs, server/src/time.rs
On my machine, clean `./make.py r` goes from 2m42 to 1mn40 with this
Python bindings don't need all the client-related stuff from libparsec (which itself has plenty of heavy dependencies such as diesel), so only keeping the crate we actually need seems to really pay off ^^
=> Faster compile python bindings

.github/workflows/ci-python.yml
- Correct `permissions`.
- Skip voiding possible `ls` errors those wouldn't be captured by the `$(..)` since it only capture stdout.
- Rewrite error message to have a title and simplify listing of incriminating file inside `./server/parsec.libs`.
=> Simplify `Restore libparsec ...`

bindings/electron/src/index.d.ts, bindings/generator/templates/binding_electron_index.d.ts.j2, client/src/plugins/libparsec/definitions.ts, make.py
=> Fix `libparsec_bindings_electron` does not have the feature `use-sodiumoxide`

parsec/core/cli/list_workspace.py, parsec/core/fs/userfs/userfs.py, parsec/core/gui/workspaces_widget.py, parsec/core/logged_core.py, parsec/core/mountpoint/manager.py, parsec/core/mountpoint/winfsp_runner.py, parsec/core/remanence_monitor.py, parsec/core/sync_monitor.py, tests/core/fs/workspacefs/test_archiving.py
PR #5061 introduces the following methods to `UserFS`:
- `get_all_workspace_entries()` 
- `get_available_workspace_entries()` 
- `get_unavailable_workspace_entries()` 
Instead it's more convenient to return lists of `WorkspaceFS` objects and rename them to:
- `get_all_workspaces()` 
- `get_available_workspaces()` 
- `get_unavailable_workspaces()`
=> Update get_available_workspaces and similar methods

docs/conf.py, misc/version_updater.py
Since we already manager the `parsec` version with the script `version_updater`, we can use that script to update the version in `docs/conf.py` that simplify the script as it won't rely on a external file of `docs`
=> Manage `parsec` version in `docs/conf.py`

.gitignore, client/.env
.env sets the testbed env variable even if you don't want it, which causes problems when you want to test with a real server. Getting rid of it while adding it to the .gitignore so devs can set it up as they want.
=> [MS] Removed .env

client/src/common/mocks.ts, client/src/components/workspaces/WorkspaceTagRole.vue, client/src/components/workspaces/WorkspaceUserRole.vue, client/src/parsec/types.ts, client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/component/specs/testWorkspaceCard.spec.ts, client/tests/component/specs/testWorkspaceListItem.spec.ts, client/tests/component/specs/testWorkspaceTagRole.spec.ts, client/tests/e2e/specs/test_workspace_sharing_modal.ts
=> [MS] Removed WorkspaceID, WorkspaceRole and WorkspaceName from mocks

client/src/common/mocks.ts, client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/workspaces/WorkspaceSharingModal.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/test_workspace_sharing_modal.ts
If the workspace is not shared, it will display a `Not Shared` label. Also extracted the user's own role from the list of users the workspace is shared with.
=> [MS] Added a "Not Shared" information on workspaces

Cargo.lock, Cargo.toml, libparsec/crates/types/Cargo.toml, libparsec/crates/types/src/id.rs, libparsec/crates/types/tests/id.rs, libparsec/src/validation.rs
Regex compilation is done once but is very costly. When testing this is done for every test (since nextest runs each test in it own process).
Given the regex pattern is simple, we can instead to the check by hand ;-)
Bench:
```
$ cargo nextest run
[...]
Summary [   4.271s] 1380 tests run: 1380 passed, 1 skipped
$ cargo nextest run
[...]
Summary [   3.159s] 1380 tests run: 1380 passed, 1 skipped
```
This is still a WIP though: we use `\w` pattern rule [which corresponds to `word character (\p{Alphabetic} + \p{M} + \d + \p{Pc} + \p{Join_Control})`](https://docs.rs/regex/1.9.5/regex/#perl-character-classes-unicode-friendly)
So we should take extra care that this is correctly handled (and add more tests about that !)
=> Don't use regex for OrganizationID/UserID/DeviceName validation to speedup tests

CONTRIBUTING.md
Rework `Filing Bug` section to include a link that create an issue using the bug report template.
=> Add link that create an issue using the bug report template

.github/CODEOWNERS
The ownership of `/bindings/` folder was overwritten for `*.rs` files that was defined after it.
The change just move the definition of the ownership of `/bindings` after `*.rs` to prevent it being overwritten.
=> Fix code owners of `bindings` folder for rust files

client/src/services/storageManager.ts, client/src/views/settings/SettingsView.vue
For some reason that I can't explain, `StorageManager.DEFAULT_CONFIG` was updated when the config changed (meaning we didn't go into the if, meaning the config was never stored). I have no idea why, as I specifically added a call to `structuredClone` when I wrote this code to prevent this from happening. Anyway, it's fixed using a getter, making sure that the DEFAULT_CONFIG is read only, which is simply better anyway.
=> [MS] Fix config save/load

Cargo.toml
That comment was when we where using the release-candidate of that crate.
That was changed in the commit 2b563996652c6fb49f0693aa675984a6a97d7ae2
=> Remove outdated command for `x25519-dalek`

docs/development/glossary.md
The glossary page is archived here: <https://github.com/Scille/parsec-cloud.old-wiki/blob/master/Glossary.md>
I choose to rely on an html table instead of markdown one because:
- I wanted to not have ultra wide row due to long text that need to fit in a single line. So the long text could be split on multiple line but still being display in the same cell.
- It also allows me to include complex element in a cell. Some cell use html list
Closes #3852, Closes #5509
=> Migrate the Glossary from `wiki` to `docs`

parsec/core/fs/__init__.py, parsec/core/fs/exceptions.py, parsec/core/mountpoint/fuse_operations.py, parsec/core/mountpoint/winfsp_operations.py
Make tests more robusts by not logging local storage errors e.g.:
https://github.com/Scille/parsec-cloud/actions/runs/6535280644/job/17744372411#step:23:355
=> Manage FSLocalStorageError in the mountpoint operation error handlers

client/electron/package-lock.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/user.ts, client/src/views/files/FoldersPage.vue, client/src/views/home/HomePage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/users/RevokedUsersPage.vue, client/tests/e2e/specs/test_folders_page.ts
Closes #5594 
Closes #5595 
Closes #5596 
Didn't want to create multiple PRs for so small changes.
For the revoked user page, I added a function to only retrieve the revoked users. It will make it a bit easier and less confusing if we also want to filter on the revoked users later on.
=> Fixed #5594, #5595 and #5596

Cargo.lock, Cargo.toml
Currently the version `console_error_panic_hook@0.1.7` correspond to any commit in the source repository (cf: rustwasm/console_error_panic_hook#22)
This lock was partially made on dependabot (cf: #4935) but was missing the Rust lock
=> Lock `console_error_panic_hook` to version 0.1.6

HISTORY.rst, misc/releaser.py
When generating a news element for `history.rst` we added the link at then end of the text and then wrap-it. That could result sometime on the link being split.
The link being split don't cause problem once the document is rendered but it's nice to have a functioning link when viewing the raw document.
=> Changelog: linked issue's link is on a new line

CONTRIBUTING.md
Rewrite the contribute code section:
- Change the recommended branch format to have something like the
one that Github create from an issue.
- Indicate to never correct a conflict in a PR using a merge commit.
- Rework link definitions
Update the summary
=> Rewrite the Contribute Code section

client/src/components/core/ms-action-bar/MsActionBar.vue, client/src/views/files/FoldersPage.vue, client/src/views/users/ActiveUsersPage.vue, client/src/views/users/RevokedUsersPage.vue, client/src/views/workspaces/WorkspacesPage.vue
Now the action bar will be always visible.
Cases:
- Workspaces list
- Users list
- Files/folders list
closes #5565
=> [MS] Fixed ActionBar scroll

docs/development/sequester-test-guide.md
The old wiki page can be found here: <https://github.com/Scille/parsec-cloud.old-wiki/blob/master/Sequester-test-guide.md>
Closes #5686
=> Migrate `sequester test guide` wiki page

client/src/components/core/ms-text/MsInformativeText.vue
To avoid any confusion, the caret icon has been changed.
closes #5593
=> [MS] Update caret icon

docs/development/workspace-file-system-architecture.md
Migrate the page `workspace file system architecture`.
The page can be found here: <https://github.com/Scille/parsec-cloud.old-wiki/blob/master/Workspace-file-system-architecture.md>
Closes #5707
=> Migrate `workspace file system architecture` wiki page

libparsec/crates/client/src/certificates_ops/poll.rs, libparsec/crates/client/tests/unit/certificates_ops/mod.rs, libparsec/crates/client/tests/unit/certificates_ops/poll.rs
=> Add tests for `poll_server_for_new_certificates`

libparsec/crates/client/tests/unit/certificates_ops/mod.rs, libparsec/crates/client/tests/unit/certificates_ops/validate_manifest.rs, libparsec/crates/testbed/src/env.rs
closes #5673 
depends on #5711 
depends on #5712
=> Add tests for `CertificatesOps` `validate_manifest`

newsfragments/5759.bugfix.rst, parsec/core/gui/remanence_management_widget.py, tests/core/gui/test_workspace_remanence.py
=> Normalize values to avoid overflow issues with the remanence widget progress bar

.github/workflows/publish.yml
When publishing a release (publish a release that was on draft), that raise 2 events `published` & `edited`.
We configured the workflow to run when one of those is received but since publishing a release raise those 2 events, that make the workflow run 2 time instead of one.
By adding the `concurrent` settings, we prevent the workflow to run on the same `ref`.
=> Prevent concurrent run of `publish` workflow

.github/scripts/check_newsfragments.py, .github/workflows/ci.yml
The script `check_newsfragments` use `origin/master` as the base target (where the pull is targeted) but `origin/master` is not always our target.
For example, if we work on a release branch or on the current `dev/v2` branch, that check don't work if `origin/master` already has the same newsfragment
Other Changes
-------------
- The script no longuer check if it need to check if it's on a branch that should be skipped (e.g.: `master`)
The check is redundant with github actions and require to maintain 2 source of truth.
- Simplify the condition to run the `check_newsfragments`:
- Use `event_name == 'pull_request'` instead of looking for the prefix `ref/pull`.
- Remove the exception for `yolo` prefixed branch as we are no longer required to add a newsfragment.
=> Fix `check_newsfragments` should compare against base

.github/scripts/check_newsfragments.py, .github/workflows/ci.yml
The script `check_newsfragments` use `origin/master` as the base target (where the pull is targeted) but `origin/master` is not always our target.
For example, if we work on a release branch or on the current `dev/v2` branch, that check don't work if `origin/master` already has the same newsfragment
Other Changes
-------------
- The script no longuer check if it need to check if it's on a branch that should be skipped (e.g.: `master`)
The check is redundant with github actions and require to maintain 2 source of truth.
- Simplify the condition to run the `check_newsfragments`:
- Use `event_name == 'pull_request'` instead of looking for the prefix `ref/pull`.
- Remove the exception for `yolo` prefixed branch as we are no longer required to add a newsfragment.
=> [Backport] Fix `check_newsfragments` should compare against base

.github/workflows/docker-server.yml, server/packaging/server/build.sh
The image will be build on tag push or by manual trigger with `workflow_dispatch`.
The image would have the following tags used:
- `VERSION+{{ date 'YYYYMMDD' }}.sha.{{ short-sha }}`
- `MAJOR.minor.patch`
- `MAJOR.minor`
=> Add workflow to build the parsec backend docker image

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/buttons.scss, client/src/theme/components/modals.scss, client/src/views/about/AboutPage.vue, client/src/views/about/AboutView.vue, client/src/views/home/HomePage.vue, client/tests/e2e/specs/test_about_modal.ts, client/tests/e2e/specs/test_about_page.ts, client/tests/e2e/specs/test_changes_modal.ts
- Update links in About View
- Update UI according to mockups (About Page & Version in Homepage)
#5592
=> [MS] Update About View

.github/workflows/docker-server.yml, packaging/server/build.sh
The image will be build on tag push or by manual trigger with `workflow_dispatch`.
The image would have the following tags used:
- `VERSION+{{ date 'YYYYMMDD' }}.sha.{{ short-sha }}`
- `MAJOR.minor.patch`
- `MAJOR.minor`
=> [Backport] Add workflow to build the parsec server's docker image

.github/scripts/check_newsfragments.py, .github/workflows/ci.yml
- Improve logging of newsfragment (display the `git log` command that will be executed).
- Prefix `base` argument with `origin/`.
- Use repeat on base argument to prevent iterating over each char of the string.
- Allow closed issue/PR.
- Fetch `base_ref` before executing the script.
=> Further fix to `check_newsfragments` script

.github/scripts/check_newsfragments.py, .github/workflows/ci.yml
- Improve logging of newsfragment (display the `git log` command that will be executed).
- Prefix `base` argument with `origin/`.
- Use repeat on base argument to prevent iterating over each char of the string.
- Allow closed issue/PR.
- Fetch `base_ref` before executing the script.
=> [Backport] Further fix to `check_newsfragments` script

docs/adminguide/hosting/parsec-server.docker.yaml, misc/version_updater.py
- Use `version_updater` script to do that.
- Change `hide_patch_version` to only use the 1st 2 values of the split (i.e.: the MAJOR and the minor)
=> Use postgres v14.10 in on-premise installation documentation

.github/workflows/ci-python.yml, misc/version_updater.py
Note that the tests that use the database are disabled because that don't work at the moment.
Depends on #5838
=> Change postgres version to v14 in ci-python

.config/nextest.toml, .github/workflows/ci-rust.yml
Add nextest configuration:
- Change the default configuration for `slow-timeout`
The default display a message `SLOW {TEST}` every `60s` without terminating it.
Now the message is displayed every `10s` and stoppind the test at the
3rd warning.
- Add profile `ci` to be used in the CI:
- Laxer `slow-timeout`
Stop the test after 5 slow message (instead of 3).
- Show test failure outputs immediatly and at the end of the run
(default to `immediate` which work well when `fail-fast` is enabled).
- Disable fail fast (enabled in `default` profile).
Full nextest configuration options can be found here: <https://nexte.st/book/configuration.html>
=> Configure nextest timeout for slow tests

server/packaging/server/server.dockerfile, server/packaging/testbed-server/testbed-server.dockerfile
The path `parsec_cli` is required because the root manifest search for
it (The bin crate `parsec_cli`)
=> Link `parsec_cli` in dockerfile

client/src/parsec/device.ts, client/src/parsec/login.ts, client/src/parsec/user.ts, client/src/views/devices/DevicesPage.vue
Not much, just moved functions around.
The only real change is that `hasRecoveryDevice` does not take a parameter anymore.
=> [MS] Moved devices functions to their own file

client/src/components/core/ms-dropdown/MsDropdown.vue, client/src/components/core/ms-dropdown/MsDropdownPopover.vue, client/src/components/core/ms-sorter/MsSorter.vue, client/src/components/core/ms-sorter/MsSorterPopover.vue, client/src/theme/components/popovers.scss, client/src/views/files/FoldersPage.vue, client/src/views/header/ProfileHeader.vue, client/src/views/header/ProfileHeaderPopover.vue, client/src/views/home/HomePage.vue, client/src/views/home/HomePagePopover.vue, client/src/views/users/ActiveUsersPage.vue, client/src/views/users/RevokedUsersPage.vue, client/src/views/workspaces/WorkspacesPage.vue
closes #5890 
@fabienSvtr please take a look at the last commit, we have CSS managing border, border radius and overflow on this class: `popover-side-bottom`. This is causing a lot of problems like you can see, I've used a lot of :not to clean the placement mess due to this global override.
The CSS here is not meant to remain like this, but I would like your opinion on the subject, do we remove this override? Do we prefer case by case? or override on ion-popover maybe?
On another note, I must specify that I like the popovers without the border as much (maybe even more) as they are supposed to be, it is another subject, but maybe we could keep them like they are in the PR.
=> [MS] Fix all existing popover placement

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/devices/ExportRecoveryDevicePage.vue, client/tests/e2e/specs/test_export_recovery_device_page.ts
Closes #5912
1. Keep the download button visible, but adds the label `File downloaded` if the button has been clicked
2. Since there's no way to know when the file has been downloaded, I added a small timeout so that it takes a few ms to display the label
=> [MS] Added the option to redownload recovery files

client/src/components/core/ms-dropdown/MsDropdown.vue, client/src/components/core/ms-types.ts, client/src/components/workspaces/WorkspaceUserRole.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/modals.scss, client/src/views/users/GreetUserModal.vue
closes #5884 
- Add appearance choice for ms-dropdown
- Put Outline as default value
- Update ms-dropdown use cases with appropriate values
- Add a title for Outline appearance
Results:
1. **dropdown clear apperance**
2. **dropdown outline apperance**
3. **dropdown outline apperance with title**
@fabienSvtr as you can see on the last screenshot, the dropdown outline appearance style needs some little adjustments (label and icon placement), I'll leave it up to you to decide whether you want to continue on this branch or open a new issue to do it later.
=> [MS] MsDropdown appearance

.github/scripts/notary/lib.sh, .github/scripts/notary/script.sh
- Set and use `SCRIPTDIR` to be agnostic of the current working directory (i.e.: being able to execute it outside of `parsec-cloud` repo)
- Rework `Debug tool version` block to oneline tools' version instead of relying on debug output (`set -x`).
This allow to run the script with `-x` without it being disable by the `set +x`.
- Allow to provide additional args to `Github-CLI` via the optional var `GH_ADDITIONAL_ARGS` (useful to set `--repo=<Owner>/<Repo>`)
=> Harden notary script

.github/scripts/sink-cache.sh
Also fix how we retrieve the version of the extension `actions/cache`
=> Fix `sink-cache` script where `ENTRIES` wasn't splitted by newline

client/src/components/header/HomePageHeader.vue, client/src/components/header/HomePageSidebar.vue, client/src/services/storageManager.ts, client/src/theme/components/cards.scss, client/src/theme/variables/width.scss, client/src/transitions/SlideHorizontal.vue, client/src/views/home/HomePage.vue, client/src/views/home/LoginPage.vue, client/src/views/home/OrganizationListPage.vue, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/e2e/specs/test_invitations_page.ts
Closes #5957 
Moved the search bar for devices on the login screen (makes it easier to implement, and it's also in line with the new mock-ups, two birds with one stone).
I tried using the routing instead (the actual page being a child of the sidebar and header), but ultimately decided against it as it made everything much more complex than it really needed to be. It makes sense in the logged in UI where a lot of pages use the same template, and the pages are not really linked together. In this case, the pages are more closely related and there's a low and finite number of them.
Animation is disabled, related issue is #6003
=> [MS] Refactoring of HomePage

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/modals.scss, client/src/views/users/ActiveUsersPage.vue, client/src/views/users/RevokedUsersPage.vue, client/src/views/users/UserDetailsModal.vue, client/tests/e2e/specs/test_user_details_modal.ts
=> [MS] User details modal

.github/scripts/notary/lib.sh, .github/scripts/notary/script.sh, .pre-commit-config.yaml, cli/run_testenv.sh, docs/adminguide/hosting/gen-admin-token.sh, docs/adminguide/hosting/ping-mailhog.sh, docs/adminguide/hosting/setup-tls.sh, misc/setup-rust.sh, server/packaging/server/build.sh, server/packaging/testbed-server/build.sh
This PR:
- Adds [shellcheck](https://github.com/koalaman/shellcheck) pre-commit hook to check for warnings and errors in shell scripts
- Fixes existing warnings/errors
=> Add shellckeck pre-commit hook

.github/filters/ci.yml, .github/workflows/ci-rust.yml, .github/workflows/ci.yml
=> Run `cargo-deny` only when rust dependencies are modified

.github/workflows/ci-rust.yml, Cargo.lock, cli/Cargo.toml, cli/src/run_testenv.rs, cli/src/tests.rs
- Split `run_testenv` function into smaller functions.
- Add logic to skip starting the testbed server if the `TESTBED_SERVER` environment variable is set using that URL instead.
- CI: Don't install python dependencies on the rust workflow
Closes #6034
=> Refactor run-testenv

client/src/common/validators.ts, client/src/components/core/ms-input/MsInput.vue, client/src/components/core/ms-modal/MsTextInputModal.vue, client/src/components/organizations/ChooseServer.vue, client/src/components/users/UserInformation.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/translation.ts, client/src/views/devices/ImportRecoveryDevicePage.vue, client/src/views/home/CreateOrganizationModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/HomePage.vue, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/e2e/specs/test_home_page.ts, client/tests/unit/specs/testValidators.spec.ts
Closes #4988 
The idea is to add helper messages to inputs. This is done by:
1. Adding a validator to inputs.
2. Validators return a string giving details on what is invalid
3. Change the input class according to the validity
Since validators are not components but need to get translated strings, I extracted the functions linked to translation to their own file so that it can be used outsider of components. It also cleans the app initialization a bit.
=> [MS] Add validity state to inputs

cli/src/create_workspace.rs, cli/src/list_users.rs, cli/src/main.rs, cli/src/share_workspace.rs, cli/src/tests.rs, cli/src/utils.rs, libparsec/crates/types/src/manifest.rs
closes #6098 
How to solve the error workspace offline ? workspace no access ?
=> Cli share workspace

client/src/services/toastManager.ts, client/src/theme/components/toasts.scss
Closes #6163 
It would probably be easier if toast where our own component, we could probably just bind the duration with Vue. Sadly, they're created by the toastController.
The idea behind this fix is to assigned a unique id to each toast, and dynamically add a `<style>` tag in the `<head>` of the page that contains the CSS with the appropriate duration. The style is removed once the toast is closed.
=> [MS] Fixes animation for toast progress bar

client/src/views/home/HomePageButtons.vue, client/src/views/home/OrganizationListPage.vue
Closes #6170 
This fixes multiple issues on the home page:
1. Create/join buttons when there are no devices work properly
2. Made it possible to create/join an org with only one device
3. Displays the create/join button in all cases
To test, in `OrganizationListPage` in the `refreshDeviceList`, you can add after the `deviceList.value = await listAvailableDevices();`:
`deviceList.value = [];` to check with no devices
`deviceList.value = [deviceList.value[0]];` to check with one device
=> [MS] Fixed homepage with no devices/one device

docs/adminguide/hosting/index.rst, docs/adminguide/hosting/parsec.env, server/parsec/backend/cli/migration.py, server/parsec/backend/cli/run.py, server/parsec/backend/cli/utils.py, server/parsec/cli_utils.py
Also, update Administrator Guide:
- Remove `PARSEC_SPONTANEOUS_ORGANIZATION_BOOTSTRAP` from docs since it has the expected default value (False)
- Add note explaining how to get the full list of available env var
Closes #6173
=> Add `show_envvar` to display env variables in help

client/electron/src/setup.ts
=> [MS] Fix electron tray icon size

Cargo.lock, poetry.lock
Address the following CVE:
```
py:cryptography@39.0.1: 2 CVE
cargo:ghost@0.1.6: 5 CVE
cargo:openssl@0.10.48: 18 CVE
cargo:openssl-sys@0.9.83: 3 CVE
py:pygments@2.14.0: CVE-2022-40896
py:pyinstaller@5.9.0: CVE-2023-49797
py:requests@2.28.1: CVE-2023-32681
cargo:rsa@0.7.2: CVE-2023-49092
py:urllib3@1.26.12: 2 CVE
py:werkzeug@2.2.3: CVE-2023-46136
```
=> Bump v2 dependencies corresponding to specific CVE

client/electron/package-lock.json, client/electron/package.json
`electron-is-dev` version 3.0.X causes bugs when starting electron (see https://github.com/sindresorhus/electron-is-dev/releases/tag/v3.0.0).
=> [MS] Changed `electron-is-dev` back to version 2.0.0

client/src/components/files/FileUploadItem.vue, client/src/services/importManager.ts, client/src/views/files/FileUploadModal.vue
Closes #6192 
Once a file has been imported, can click on it to navigate to its folder.
=> [MS] Navigate to the folder of an imported file

client/src/views/files/FoldersPage.vue
Files currently being imported could be displayed twice, because the import first creates the file, which means that the file appeared with a size of 0, and appeared again as being currently imported.
=> [MS] Exclude files currently being imported from the list

docs/adminguide/hosting/index.rst, docs/adminguide/hosting/parsec.env, packaging/server/template-prod.env.list
Backport https://github.com/Scille/parsec-cloud/pull/6297/commits/405e887e40318da0bec3f463da7ff7f863782a8b from #6297 to `dev/v2`
Related to #6172
=> Backport: Add Sentry as optional component and fix env variable in docs (#6297) to dev/v2

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, misc/version_updater.py
When updating the parsec version, the Cargo.lock file needs to be updated.
This is done by running `cargo generate-lockfile --direct-minimal-versions` (nightly feature for now).
> `cargo generate-lockfile` is the simplest way I've found to update the lockfile without having the compile or check the entire project.
Fix #5971
=> Run post update hook to fix Cargo lock when updating parsec version

docs/Dockerfile, docs/README.md
Dockerfile was broken since the upgrade to Python 3.12.
Also, update README.md to add more details about how to build the docs with Docker.
=> Update docs/Dockerfile to support Python 3.12

client/src/components/files/FileCard.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileImport.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/files/index.ts, client/src/components/files/types.ts, client/src/views/files/FileUploadMenu.vue, client/src/views/files/FileUploadModal.vue, client/src/views/files/FoldersPage.vue, client/tests/component/specs/testFileCard.spec.ts, client/tests/component/specs/testFileListItem.spec.ts, client/tests/e2e/specs/test_folders_page.ts
Refactored folders page.
1. Grid and list are in separated components, which mean they can also be reused (for example for a search feature)
2. FoldersPage has been cleaned quite a bit, a lot less logic to handle
3. The files and folders list are handled by a specific object, which means that they are shared between grid and list view (and thus keeping the selection status)
4. Selection is way clearer (no more refs on list of component)
=> [MS] Refactored folders page

client/.eslintignore, client/src/components/core/ms-action-bar/MsActionBarButton.vue, client/src/components/core/ms-modal/MsTextInputModal.vue, client/src/components/core/ms-toggle/MsGridListToggle.vue, client/src/components/core/ms-tooltip/MsTooltip.vue, client/src/components/organizations/ChooseServer.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/parsec/device.ts, client/src/parsec/file.ts, client/src/parsec/user.ts, client/src/views/devices/GreetDeviceModal.vue, client/src/views/header/NotificationCenterPopover.vue, client/src/views/settings/SettingsView.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/users/MyContactDetailsPage.vue, client/src/views/users/RevokedUsersPage.vue
Clean a bit of code, mostly CSS, to remove eslint's warnings. In the case of unused CSS selectors, I've tried to be as careful as possible and either remove it if the warning was legitimate, or disable the warning if the rule was actually used.
=> [MS] Fixed eslint warnings

.cspell/custom-words.txt, client/src/components/core/ms-input/MsPasswordInput.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/services/hotkeyManager.ts, client/src/views/files/FoldersPage.vue, client/src/views/header/HeaderPage.vue, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/component/specs/testMsChoosePasswordInput.spec.ts, client/tests/component/specs/testPasswordInput.spec.ts, client/tests/component/support/mocks.ts
A piece of #6183 
Search for the device list, settings, go back, display/hide password, new workspace, import files,  switch list/grid for workspaces and files, display notification center, select all files, delete/show info/rename file, ...
A few things to note:
1. I'm not completely satisfied with how shortcuts can be turned off/on
2. For testing purposes, I'm adding the `web` platforms automatically to all shortcuts if `needsMock` returns true
3. Haven't done the user page since it's meant to change
4. It fixes a bug with the files list display checkbox
=> [MS] Added a few application shortcuts

client/scripts/check_unused_translations.py
Definitely not my best work, but it's only meant to be used from time to time to clean the translation files.
```
> python scripts/check_unused_translations.py -t src/locales src
Checking if everything in `en` is in `fr`...
Checking if everything in `fr` is in `en`...
Looking for unused translations...
`app.projectLink` not found in sources
`openFile.failedTitle` not found in sources
`notificationCenter.unread` not found in sources
`notificationCenter.empty` not found in sources
`HomePage.topbar.logoutFailed.title` not found in sources
`HomePage.noExistingOrganization.title` not found in sources
...
```
=> [MS] Added a python script to check if some translations are unused

client/src/services/fileUploadMenu.ts, client/src/views/files/FileUploadMenu.vue
Usage:
```typescript
import useUploadMenu from '@/services/fileUploadMenu';
const uploadMenu = useUploadMenu();
// somewhere in the component 
uploadMenu.show();
uploadMenu.hide();
uploadMenu.isVisible();
uploadMenu.isMinimized();
uploadMenu.minimize();
uploadMenu.expand();
```
=> [MS] Show/hide upload menu from outside

docs/rfcs/1007-frozen-users.md, server/parsec/asgi/administration.py, server/parsec/asgi/rpc.py, server/parsec/client_context.py, server/parsec/components/auth.py, server/parsec/components/events.py, server/parsec/components/memory/auth.py, server/parsec/components/memory/datamodel.py, server/parsec/components/memory/factory.py, server/parsec/components/memory/user.py, server/parsec/components/user.py, server/parsec/events.py, server/tests/administration/test_create_organization.py, server/tests/administration/test_freeze_user.py, server/tests/administration/test_get_organization.py, server/tests/administration/test_list_users.py, server/tests/administration/test_patch_organization.py, server/tests/administration/test_stats.py, server/tests/api_v4/authenticated/test_user_revoke.py, server/tests/common/client.py, server/tests/test_rpc.py, server/tests/test_sse.py
- Implementation only in memory
- [Documentation is missing](https://github.com/Scille/parsec-cloud/pull/5842/files#diff-d4f43e12c074bcf616dead86bed45702a8b68331df85a4dc7804c7e352780833)
- No client support
=> Add user freeze feature

.github/workflows/ci-rust.yml, .github/workflows/ci-web.yml, Cargo.lock, libparsec/crates/client/src/monitors/connection.rs, libparsec/crates/client_connection/Cargo.toml, libparsec/crates/client_connection/src/authenticated_cmds/mod.rs, libparsec/crates/client_connection/src/authenticated_cmds/sse.rs, libparsec/crates/client_connection/src/lib.rs, libparsec/crates/client_connection/tests/unit/authenticated.rs, libparsec/crates/client_connection/tests/unit/disconnect_proxy.rs, libparsec/crates/types/src/addr.rs, server/parsec/asgi/rpc.py, server/parsec/components/events.py, server/parsec/events.py, server/tests/test_sse.py
=> Add SSE client test for `last-event-id` mechanism

misc/releaser.py
The semver specification does not allow the use of a hyphen to separate a prerelease part from another, we should use a dot instead.
=> Fix dev specifier for full version

.github/workflows/publish.yml
I directly push to `stable` for the nightly track because we wont a validation process for those versions.
=> [fix #6589]: Change the default track for the snap to `nightly/stable`

client/src/components/files/FileListDisplay.vue, client/src/parsec/file.ts, client/src/views/files/FileContextMenu.vue, client/src/views/header/HeaderPage.vue, client/tests/e2e/specs/test_folders_page.ts
1. incorrect selection being kept when changing folder
2. missing workspaceId when using the breadcrumb, resulting in incorrect workspace role
3. removed unused file actions
4. lowered the amount of files and folders to avoid overflowing on cy
=> [MS] Fixed bugs for file FileListDisplay

client/electron/electron-builder.config.yml
=> [fix #6623]: Add package `fuse3` to snap

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/generator/api/common.py, bindings/generator/api/events.py, bindings/generator/api/invite.py, bindings/web/src/meths.rs, client/src/parsec/login.ts, client/src/parsec/organization.ts, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/src/config.rs, libparsec/crates/client/src/event_bus.rs, libparsec/crates/client/src/lib.rs, libparsec/crates/client/src/monitors/connection.rs, libparsec/crates/client/src/monitors/mod.rs, libparsec/crates/client/src/monitors/server_config.rs, libparsec/crates/types/src/invite.rs, libparsec/src/client.rs, libparsec/src/config.rs, libparsec/src/events.rs
Bound events:
- `Ping`: for test onyl, just ignore it
- `Offline` & `Online`
- `ServerConfigChanged` always triggered once on first SSE connection with the server (given before the connection, the client starts with a "good enough" default server config)
- `InvitationChanged`
- `TooMuchDriftWithServerClock`
- `IncompatibleServer` 
Main event missing are `ExpiredOrganization` & `RevokedSelfUser` for errors, and `WorkspaceSelfRoleChanged` (on sharing/unsharing) & `WorkspaceEntryChanged` (when data change)
Additional missing events are the ones to inform about the synchronization progress (both for inbound and outbound sync)
=> Event bindings

client/src/components/files/FileCard.vue, client/src/components/files/FileListItem.vue
Small bug that can happen when selecting a file where the checkbox goes into legacy mode because the label was not properly set.
=> [MS] Fix an error that can happen when selecting a file

.cspell/custom-words.txt, client/electron/assets/installer.nsh, client/electron/electron-builder.config.yml, client/electron/package-lock.json, client/electron/package.json, client/electron/scripts/before-pack.js
- Use the electron-builder hook `boforePack` to download the WinFSP.
- Add a custom NSIS script to install WinFSP if it's not already installed.
=> [fix #6535]: Add WinFSP installer to the Electron build

.github/workflows/releaser.yml
The previous condition caused the job to not run event tho all requirement jobs completed successfully (and I don't have a way to debug that). I suspect that the job `schedule-nightly-release` is present in the `needs` object and that's what cause the problem.
=> Flatten condition for the releaser job

client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspacesPage.vue
The new workspace button in the sidebar had two issues:
1. It was visible by outsiders
2. It redirected to the /workspace url and added a `query` string with the workspace name, to let the workspaces page handle the creation. Problem was, this url was not updated after creating the workspace, meaning that you could create a ton of workspace by refreshing the workspace page.
=> [MS] Fixed the new workspace button in the sidebar

client/src/components/core/ms-modal/FolderSelectionModal.vue, client/src/components/core/ms-modal/types.ts, client/src/components/files/FileUploadItem.vue, client/src/components/notifications/MultipleUsersJoinWorkspaceNotification.vue, client/src/components/notifications/UserJoinWorkspaceNotification.vue, client/src/components/notifications/UserSharedDocumentNotification.vue, client/src/components/notifications/WorkspaceAccessNotification.vue, client/src/components/notifications/WorkspaceRoleChangedNotification.vue, client/src/main.ts, client/src/parsec/file.ts, client/src/parsec/login.ts, client/src/parsec/types.ts, client/src/parsec/workspace.ts, client/src/router/checks.ts, client/src/router/index.ts, client/src/router/navigation.ts, client/src/router/params.ts, client/src/router/types.ts, client/src/services/informationManager.ts, client/src/views/files/FileUploadMenu.vue, client/src/views/files/FoldersPage.vue, client/src/views/header/HeaderPage.vue, client/src/views/header/NotificationCenterPopover.vue, client/src/views/home/HomePage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/component/specs/testWorkspaceCard.spec.ts, client/tests/component/specs/testWorkspaceListItem.spec.ts, client/tests/unit/specs/testInformationManager.spec.ts, client/tests/unit/specs/testNotificationManager.spec.ts
Changed how workspaces are being accessed. We use the `workspaceHandle` as our selector to get information on the workspace, and workspaces are now always started and mounted.
=> [MS] Updated how workspace navigation is done

Cargo.lock, libparsec/Cargo.toml, libparsec/crates/crypto/Cargo.toml, libparsec/crates/crypto/src/rustcrypto/secret.rs, libparsec/crates/crypto/src/sodiumoxide/secret.rs, libparsec/crates/crypto/tests/secret.rs, libparsec/crates/tests_fixtures/Cargo.toml, server/Cargo.toml
Test shouldn't be impacted performance-wise given device loader's testbed implementation already [entirely skip the password-to-key generation step \o/](https://github.com/Scille/parsec-cloud/blob/93c4fbb3b39e53f0bb832c91aefac0aca7f7f36d/libparsec/crates/platform_device_loader/src/testbed.rs#L212-L213).
=> Remove test feature `libparsec_crypto/test-unsecure-but-fast-secretkey-from-password`

.github/workflows/releaser.yml
Previously we didn't have that problem since that step was run when we push a tag and the action was able to determine the tag name from the event info.
Additional, the step `Remove previous nightly release` was failing because of the missing env var `GH_TOKEN`.
`permissions.contents: write` was added to be more explicit on the required permissions.
=> Fix releaser schedule cannot create release because of missing tag.

server/tests/api_v4/authenticated/test_invite_1_greeter_wait_peer.py
This PR add test for the command `invite_1_greeter_wait_peer` with the failure response `invitation_not_found` and `invitation_deleted`
=> [fix #6689]: test server auth cmd `invite_1_greeter_wait_peer`

.github/workflows/publish.yml
The permission `id-token: write` is required by the `publish-to-pypi` action to create a new `OpenID Connect`.
=> Add missing permission `id-token: write` to `publish` job

.github/workflows/releaser.yml
Previous the step would fail because the command is not run in a folder with git configured. To circumvent this without cloning the repo, we need to set the `--repo` option like the `publish` workflow.
=> Fix removing previous nightly release

client/src/parsec/workspace.ts, client/src/views/files/FoldersPage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspacesPage.vue
Closes #6800 
Updated how workspace are initialized by splitting the listing from the mounting, and refresh workspaces and files every 10s (temporary solution while we wait for events).
=> [MS] Updated how workspaces are being initialized and refreshed

client/src/components/core/ms-text/MsReportText.vue, client/src/components/devices/KeyringInformation.vue
Style was forgotten on the message provide when the user chose Keyring authentification.
=> [MS] Keyring information missing style

client/electron/package.js
The fuse interface on snap only allow to create a fuse filesystem under `SNAP_USER_{DATA,COMMON}` (`/home/<username>/snap/<snap name/{common,<revision>}`) or `SNAP_{DATA,COMMON}` (`/var/snap/<snap name>/{common,<revision>}`).
=> Set confinement to classic for electron-builder

client/src/components/files/types.ts, client/src/views/files/FoldersPage.vue
Smart update of the files: instead of just clearing the list and replacing it by the new one, we calculate the difference between the old file list and the new one and update only was has to be updated.
Closes #6869
=> [MS] Smart refresh of file list

server/tests/api_v4/authenticated/test_invite_1_greeter_wait_peer.py, server/tests/api_v4/invited/test_invite_1_claimer_wait_peer.py
Only `test_ok` need to be run with different run orders.
Error response don't need to open a conduit, so they can be tested directly.
=> Simplify `test_invite_1_greeter_wait_peer`

.github/workflows/package-client.yml, client/electron/package.js
The more recent version use libssl 3.0 by default instead of 1.1.
=> Use ubuntu 22.04 instead of 20.04 for the client package workflow

client/src/components/files/FileCard.vue, client/src/components/files/FileListItem.vue, client/tests/component/specs/testFileCard.spec.ts, client/tests/component/specs/testFileListItem.spec.ts, client/tests/e2e/specs/test_folders_page.ts
Use dblclick instead of click for interacting with entries (navigating into a folder or opening a file).
`@dblclick` replaces `@click` directly on the `FileListItem` and `FileCard` and emit a `click` event. This is because it's not possible to have both `dblclick` and `click` emitted correctly at the same time (a dblclick will always trigger a click first).
=> Use double click for files

client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/test_workspaces_page.ts
Workspace sharing info were not being refreshed because Vue only watches the array, not the content of the array.
=> [MS] Correctly displays workspace sharing

client/electron/src/index.ts, client/electron/src/setup.ts
`second-instance` is fired for each `requestSingleInstanceLock` and `setupElectronDeepLinking` call.
=> [MS] fixes links opening multiple times of second instances

.github/workflows/releaser.yml
The publish workflow expect the input `release_tag` to be the tag name to use. But that value should not contains the `refs/tags/` prefix, which will cause a failure when used with `gh` commands.
=> Fix wrong value for `release_tag` input provided by the releaser workflow

.cspell/custom-words.txt, .github/workflows/package-client.yml, .gitignore, client/.gitignore, client/.prettierrc.json5, client/electron/package.js, client/electron/snap/snapcraft.yaml, misc/version_updater.py
The custom `snapcraft` as the following benefits:
- `libparsec` is build inside of it, so it will use their the same
environment between build and run.
- We have the `patchelf` hook that is run patching binaries & libraries
to use snap provided libs.
Other changes
-------------
- Add specific job to package the electron app on Linux using `snapcraft`.
- Update `package.js` to take a target argument (e.g.: `dir`, `appimage`,
`nsis`, ...).
=> Provide own custom snapcraft for electron app 

client/src/components/core/ms-dropdown/MsDropdown.vue, client/src/components/core/ms-dropdown/MsDropdownPopover.vue, client/src/components/workspaces/WorkspaceUserRole.vue, client/src/views/settings/SettingsView.vue
Avoid selecting an option by default in dropdown popover (see screenshot). Also renamed `defaultOption` in `defaultKey` since we're not passing a full option with the label but only the key.
=> [MS] Handle no default option in dropdown popover

client/src/common/date.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/greet_device.ts, client/src/views/devices/GreetDeviceModal.vue
Re-enables the ability to send an email when greeting a new device. I added a little bit of magic to discourage spamming.
=> [MS] Re-enable send email for device onboarding

.cspell/custom-words.txt, client/electron/snap/snapcraft.yaml
Previously, we where using the helpers provided by `electron-snap-template`, but those weren't updated since 2019.
The previous helpers also included libs that were outdated.
Other changes
-------------
- Rework listing of staged & primed files
=> Use dekstop helpers provided by ubuntu

.github/workflows/package-client.yml
Forgot to use the same condition has the other jobs
=> Fix electron-snap skipped because `version` is ignored on release

server/tests/api_v4/authenticated/test_realm_create.py, server/tests/api_v4/authenticated/test_realm_rename.py, server/tests/api_v4/authenticated/test_realm_rotate_key.py, server/tests/api_v4/authenticated/test_realm_share.py, server/tests/api_v4/authenticated/test_realm_unshare.py, server/tests/common/__init__.py, server/tests/common/backend.py, server/tests/common/realm.py
This PR adds missing tests for commands:
- `realm_create`
- `realm_rename`
- `realm_rotate_key`
- `realm_unshare`
Also:
- Add some `pytest.fixture` to improve test readability
- Add `common/realm.py` file with functions to patch certificates. IMO this also improves test readability because each test only patches what is needed, instead of creating certificates every time which has a lot of redundancy
- Fix test function names in `realm_share`
Closes #6684 
Closes #6685 
Closes #6686
Closes #6687
=> Add missing tests for API realm_*

client/electron/package.js
I need that option to be able to use `electron-builder` directly
without using the script.
That allow to use the script like so:
```shell
node package.json --export > config.json
```
> For that I needed to change the `console.{debug,log}` to
`console.warn` to make them print to `stderr` instead of `stdout`.
=> Add option `--export` to export the electron buidler config

.github/dependabot.yml
Simplify updating `desktop` dependencies by excluding `electron` from the list.
Also rename `desktop-updates` from `electron-dependencies`
=> Don't include `electron` in the `desktop-updates` group

server/parsec/components/events.py, server/tests/api_v4/authenticated/test_events_listen.py
- Add test with early 404 error.
- Add test where the organization is removing during execution.
=> [fix #6868]: Add test event listen bad outcome close connection

.cspell/custom-words.txt, docs/rfcs/0000-how-to-write-rfcs.md, docs/rfcs/1008-nightly-build.md
Add RFC to discuss then implement nightly build into parsec.
The rendered file can be viewed here: <https://github.com/Scille/parsec-cloud/blob/rfc-nightly-build/docs/rfcs/1008-nightly-build.md>
The way it's written allows to implement it in part independently
Related to #6546
=> Rfc nightly build

client/src/components/notifications/AllImportedElementsNotification.vue, client/src/components/notifications/DefaultNotification.vue, client/src/components/notifications/MultipleUsersJoinWorkspaceNotification.vue, client/src/components/notifications/NewDeviceNotification.vue, client/src/components/notifications/UserJoinWorkspaceNotification.vue, client/src/components/notifications/UserSharedDocumentNotification.vue, client/src/components/notifications/WorkspaceAccessNotification.vue, client/src/components/notifications/WorkspaceRoleChangedNotification.vue, client/src/components/users/InvitationPopoverItem.vue, client/src/views/home/OrganizationListPage.vue
Some calls to `formatTimeSince` weren't translated.
=> [MS] Correctly translate formatTimeSince calls

misc/releaser.py, misc/version_updater.py
The BUSL license file was moved to `LICENSE` in #7059 but the path was not updated in the script.
=> Fix path of the BUSL license in script `releaser.py`

client/src/components/workspaces/utils.ts, client/src/theme/components/popovers.scss, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspaceContextMenu.vue
Closes #7050
From sidebar:
From workspace card
=> [MS] Fine tuned workspace context menu

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/translation.ts, client/src/views/home/CreateOrganizationModal.vue
Translation problems on date where `formatDate()` would return a translatable with key/data in most cases, except when the date was used directly (ie not `03/04/2024`, not `4 days ago`). This caused the already formatted date to go through the translation (`$msTranslate('03/04/2024')`) which caused a warning, because the key does not exist.
=> [MS] Fixed date translations

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/electron/src/setup.ts, client/electron/src/winRegistry.ts, client/src/main.ts, client/src/services/eventDistributor.ts, client/src/services/injectionProvider.ts, client/src/views/header/ProfileHeader.vue, client/src/views/header/ProfileHeaderPopover.vue
Closes #7097 
Exposes
`window.electronAPI.getUpdateAvailability()` that returns an event through the eventDistributor with the update info
`window.electronAPI.updateApp()` to start the update
It also includes a bit of refactoring:
1. uses enums instead of raw strings for the communication channel
2. moved win registry related functions to their own file
=> [MS] App update API

libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/types/src/fs_path.rs, libparsec/crates/types/tests/unit/fs_path.rs
It's way better to factorize this code without using macro, because macro can capture some variables in the current scope, so it is harder to read.
I would like to improve too (remove the loop)
The loop seems not be a performance problem but maybe harder to read ?
=> Factorize `build_next_conflicted_name`

Cargo.lock, Cargo.toml, libparsec/crates/crypto/Cargo.toml, libparsec/crates/crypto/src/rustcrypto/private.rs, libparsec/crates/crypto/src/rustcrypto/secret.rs, libparsec/crates/crypto/src/rustcrypto/sequester.rs, libparsec/crates/crypto/src/rustcrypto/sign.rs, libparsec/crates/crypto/src/rustcrypto/utils.rs
`crypto` was the only crate that depends on `getrandom_01` even tho it didn't use it in the code.
This will allow `dependabot` to update `getrandom`.
Changes
-------
- Remove the dependency `getrandom_01`.
- Rename dependency `getrandom_02` to `getrandom`.
- Rename dependency `rand_08` to `rand`.
- Use `rand_core` provided by `crypto_secretbox`.
=> Use single version of `genrandom`

.github/dependabot.yml, client/electron/package-lock.json, client/electron/package.json
The latest version of electron-is-dev (3.0.1) requires to build ESM module but capacitor don't support that currently.
=> Rollback electron-is-dev to 2.0.0

client/electron/live-runner.js
By setting `ELECTRON_OVERRIDE_DIST_PATH` (the same variable to override the electron used during build) `live-runner.js` will use the provided electron version.
=> Allow live-runner to use custom electron

client/electron/src/setup.ts, client/src/components/notifications/NewVersionAvailableNotification.vue, client/src/components/notifications/index.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/informationManager.ts, client/src/services/injectionProvider.ts, client/src/services/notificationManager.ts, client/src/views/header/NotificationCenterPopover.vue, client/src/views/header/ProfileHeader.vue
Add a notification for when an update is available.
1. The interval to check if a new version is available is now done in Electron. This avoid having 4 queries if 4 orgs are connected, now it's only done once and dispatched to every one. And maybe we won't even need the setInterval in the end.
2. Add a `unique` option on `Information`. This one is a bit tricky because all we want is a notification to inform that a new version is available. We don't care about the message nor the criticity. And it shouldn't be repeated every 10min either. So it's a bit of an outlier and doesn't fit the information system we have now.
closes #7099
=> [MS] Added new version available notification

docs/development/README.md, misc/version_updater.py
The file `docs/development/README.md` was not monitored by the script since it was renamed from `quickstart.md`. The script will now check that the glob pattern produce at least one match and will log an error if it does not.
=> Detect when a glog pattern produce no match

client/electron/src/setup.ts, client/electron/src/updater.ts
If we're in dev mode, we likely don't have the publish configuration file. 
In that case, we should not create the updater and consider no update will be available.
=> Don't create an updater if the configuration isn't available

.github/dependabot.yml
Only for the `github-actions` package ecosystem right, to test how Dependabot will behave with grouping.
=> Use `directories` entry to group all actions in a single entry

.github/workflows/_releaser_nightly_build.yml, .github/workflows/releaser.yml, misc/releaser.py
Update the release script to allow to skip the creation and push of the release tag. 
This allow to configure the releaser workflow to skip the nightly tag creation on schedule runs. 
Then the nightly tag updated upon the creation of the new nightly release.
=> [fix #7296]: Update nightly tag only on releaser workflow success

.github/dependabot.yml
- Some groups were missing some dependencies thus being put in `pydeps` group by default.
- The dependencies listed in group are now ascii sorted (thanks `vscode` :heart:)
- We now share the same entry for `/docs` & `/server` python dependencies.
=> Update python groups

libparsec/crates/client/tests/unit/workspace/file_operations_stateful.rs, libparsec/crates/client/tests/unit/workspace/file_transactions_stateful.rs, libparsec/crates/client/tests/unit/workspace/mod.rs, libparsec/crates/testbed/src/scope.rs
closes #6538 
- `AsyncStateMachineTest` is there to allow `async` in `proptest`, this is not the greatest implementation but good enough for the moment.
- `TestbedScope` couldn't be implemented in the macro, because the `discriminant_dir` of the `env` is needed by `WorkspaceOps`.
Observation:
`ReferenceState` initialize once for each case and use `clone` to save the state and uses it to shrink in order to find the minimal reproductible fail, so it's not viable for `I/O` that's why the `oracle` is implemented in `SUT` (System under test).
Explanation:
The `ReferenceState` is run alone then both `ReferenceState` and `SUT` are run to test the `SUT` behavior,
So if something is written in file, it will be kept in the first run and the state will be different when both are run together.
Ask …
=> Add File transactions stateful test

.github/workflows/package-client.yml, client/electron/snap/snapcraft.yaml
The electron app failed to build the `megashark-lib` dependency during
it's `prepare` step.
The workaround is to pre-package `megashark-lib` using `npm pack` and
patch `client/package.json` with the generated archive.
=> [fix #7210]: Fix snap electron build 

.github/workflows/releaser.yml
Checkout the repository on the last job if we need to update the nightly tag.
=> Fix not a git repo to update nightly tag

.github/workflows/package-client.yml
During the last step of the releaser workflow (releaser.yml), we copy the generated SBOM files with a glob pattern like so:
```shell
cp -v artifacts/**/Parsec-SBOM-*.spdx.json release-files
```
This command fail because we have two file who have the same name: `Parsec-SBOM-Electron-linux-snap.spdx.json`
To fix that, we simply add the extension of the generated application file (`snap`, `AppImage`, `dmg`, `exe`)
=> Fix filename conflict when copying sbom file

libparsec/crates/client/src/workspace/store/sync_updater.rs
Those assertion where using data that was not available in release build (only present in debug build). Thus causing a compilation error on release build.
=> Fix debug assertion on release build

.cspell/names.txt, docs/development/github-action-tips-n-tricks.md
The file is rendered at: <https://github.com/Scille/parsec-cloud/blob/doc-remote-session-github-action/docs/development/github-action-tips-n-tricks.md>
=> Add doc about debugging github action

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/electron/src/setup.ts, client/electron/src/updater.ts, client/src/components/notifications/NewVersionAvailableNotification.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/views/header/ProfileHeader.vue, client/src/views/header/ProfileHeaderPopover.vue
Linked to #5613 
A click on an update button in Parsec will send a `prepareUpdate` event to Electron. Electron will then inform the app to cleanup (logout, cancel the imports, ...) and the app will then tell electron to quit and update. At least, that's the theory.
=> [MS] Add the ability to start an update

.github/workflows/releaser.yml
The param `nightly_build` is expected to be a bool, but it was passed as a string.
=> Fix invalid type for workflow param

client/src/components/users/UserAvatarName.vue, client/src/components/users/UserSelect.vue, client/src/components/users/UserSelectDropdown.vue, client/src/components/users/index.ts, client/src/components/workspaces/utils.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/user.ts, client/src/parsec/workspace.ts, client/src/theme/components/modals.scss, client/src/views/users/BulkRoleAssignmentModal.vue, client/src/views/users/UserContextMenu.vue, client/src/views/users/UsersPage.vue, client/tests/pw/e2e/users_list.spec.ts, client/tests/unit/specs/testWorkspaceRole.spec.ts
closes #7083 
https://www.figma.com/file/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?type=design&node-id=30161-85608&mode=design&t=dt6374A9svgzPN4L-0
Needs a little makeover.
=> [MS] Adds workspace role bulk assignment

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/electron/src/setup.ts, client/electron/src/updater.ts, client/src/main.ts, client/src/parsec/login.ts, client/src/plugins/libparsec/index.ts
Closes #7475 
`console.log` called by the page are not logged anywhere. This exposes an electron API that uses electron-logs to store the logs into a file. It's not done automatically, we have to call `window.electronAPI.log()` to log something. Used it by default on `IncompatibleServerEvents` and for failed calls to the bindings.
Also added a `--log-debug` option to set the log level to debug.
=> [MS] Configure electron-logs and exposes an API for the page to log to electron

.github/filters/ci.yml, .github/workflows/ci.yml
The wasm tests will be run when the toolchain is changed or the dependencies is updated
=> Trigger the wasm tests more frequently

libparsec/crates/client_connection/src/anonymous_cmds.rs, libparsec/crates/client_connection/src/authenticated_cmds/mod.rs, libparsec/crates/client_connection/src/invited_cmds.rs, libparsec/crates/client_connection/tests/unit/anonymous.rs, libparsec/crates/client_connection/tests/unit/authenticated.rs, libparsec/crates/client_connection/tests/unit/invited.rs
=> Connection monitor correctly handles HTTP 504&502 (i.e. bad response due to gateway)

libparsec/crates/platform_storage/src/native/sql/create-certificates-table.sql, libparsec/crates/platform_storage/src/native/sql/create-chunks-table.sql, libparsec/crates/platform_storage/src/native/sql/create-prevent-sync-pattern-table.sql, libparsec/crates/platform_storage/src/native/sql/create-realm-checkpoint-table.sql, libparsec/crates/platform_storage/src/native/sql/create-remanence-table.sql, libparsec/crates/platform_storage/src/native/sql/create-temp-unreferenced-chunks-table.sql, libparsec/crates/platform_storage/src/native/sql/create-vlobs-table.sql
closes #6529
This should be mostly compatible with old way of declaring flexible tables, however it's always better to avoid exotic corner cases so merging it fast (or discarding early !) is advised ;-)
=> Declare local storage's SQLite tables as STRICT (to avoid error in table typing)

client/src/views/files/FoldersPage.vue
Closes #7483 
Re-sort files and folders when a new file is added and when re-listing. Going at it the naive way, would probably be better to insert in the right order directly, but it's more complicated, we'll see how this holds on.
=> [MS] Sort files and folders after imports

libparsec/crates/client/src/certif/add.rs, libparsec/crates/client/src/certif/block_validate.rs, libparsec/crates/client/src/certif/list.rs, libparsec/crates/client/src/certif/manifest_validate.rs, libparsec/crates/client/src/certif/mod.rs, libparsec/crates/client/src/certif/poll.rs, libparsec/crates/client/src/certif/realm_create.rs, libparsec/crates/client/src/certif/realm_decrypt_name.rs, libparsec/crates/client/src/certif/realm_key_rotation.rs, libparsec/crates/client/src/certif/realm_keys_bundle.rs, libparsec/crates/client/src/certif/realm_rename.rs, libparsec/crates/client/src/certif/realm_share.rs, libparsec/crates/client/src/certif/store.rs, libparsec/crates/client/src/certif/user_revoke.rs, libparsec/crates/client/src/certif/workspace_bootstrap.rs, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/src/client/workspace_refresh_list.rs, libparsec/crates/client/src/event_bus.rs, libparsec/crates/client/src/monitors/certif_poll.rs, libparsec/crates/client/src/user/mod.rs, libparsec/crates/client/src/workspace/fetch.rs, libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/tests/unit/certif/utils.rs, libparsec/crates/client/tests/unit/user/utils.rs, libparsec/crates/client/tests/unit/workspace/utils.rs
But why ?
- In the doc sometimes it was CertifOps sometime CertificateOps
- I favored CertificateOps for consistency with other certificate related enums
=> Rename CertifOps to CertificateOps.

server/parsec/stubs/psutil/__init__.pyi
No longer needed since they were added to typeshed library which seems to be bundled with type checkers (such as pyright).
=> Remove psutil stubs

HISTORY.rst
The following versions were missing (see: https://github.com/Scille/parsec-cloud/blob/dev/v2/HISTORY.rst):
- 2.17.0
- 2.16.3
- 2.16.2
- 2.16.1
- 2.16.0
Related #6409
=> Add latest published versions to HISTORY.rst

docs/rfcs/1000-shamir-based-recovery.md, server/parsec/components/memory/datamodel.py, server/parsec/components/memory/shamir.py, server/parsec/components/memory/user.py, server/tests/api_v4/authenticated/test_certificate_get.py, server/tests/common/client.py
Fix #7362 and #7360
In v2, certificates were queried when needed. In v3 all certificates are pulled regularly, so here we don't implement  shared_recovery_device_info and list_shared_recovery_devices routes but we add the shamir certificates to the get_certificates.
=> [Shamir] get_certificates returns shamir certificates.

docs/rfcs/1000-shamir-based-recovery.md
=> Shamir deletion specification - server side

client/electron/src/setup.ts, client/src/common/validators.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/parsec/organization.ts, client/src/router/types.ts, client/src/views/home/CreateOrganizationModal.vue, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/home/SummaryStep.vue, client/tests/pw/e2e/bootstrap_organization.spec.ts, client/tests/pw/e2e/documents_list.spec.ts, client/tests/pw/e2e/home_page.spec.ts
Closes #7639
This updates the `join links` to also handle bootstrap. It's a bit misnamed but it's not a very used case so it's probably alright. Once the link's been parsed, we use the create organization process with some steps disabled.
It should handle all cases:
- passing the link as the argument, both at startup and when clicking on a link with the app already opened
- using the input + join button when the homepage displays the "no devices" page
- using the `Create or join` > `Join organization` button when the homepage has some devices
To get a bootstrap link, with a testbed server running:
`cargo run create-organization --addr parsec3://127.0.0.1:6770?no_ssl=true --token s3cr3t --organization-id MyOrg`
=> [MS] Handle bootstrap links

.cspell/custom-words.txt, .pre-commit-config.yaml, libparsec/crates/platform_storage/src/native/sql/.sqlfluff, libparsec/crates/platform_storage/src/native/sql/create-temp-unreferenced-chunks-table.sql, libparsec/crates/platform_storage/src/native/sql/create-vlobs-table.sql, server/parsec/components/postgresql/migrations/.sqlfluff, server/parsec/components/postgresql/migrations/0001_initial.sql, server/parsec/components/postgresql/migrations/README.md, server/parsec/components/postgresql/migrations/datamodel.sql
Changes in this PR:
- Adds `sqlfluff` linter to `.pre-commit-config.yaml`
- Adds `.sqlfluff` config files for `postgres` and `sqlite` dialects
- Fixes linting issues in existing SQL files
- Adds README about Parsec data model and migrations
More info: https://docs.sqlfluff.com/en/stable/index.html
=> Add SQLFluff linter  

misc/test_expected_payload_cooker.py
This PR adds the script used to re-generate payloads in:
- #7671
- #7682
The script docstring explains how is intended to be used.
=> Add script to cook test payloads

client/src/parsec/file.ts, client/src/parsec/login.ts, client/src/services/eventDistributor.ts, client/src/views/files/FoldersPage.vue
Depends on #7424. Includes the code from that PR so that it's easier to test.
=> [MS] Use `WorkspaceWatchedEntryChanged` to refresh the files list instead of a fixed timer

libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_rotate_key.rs, libparsec/crates/types/tests/unit/certif.rs, libparsec/crates/types/tests/unit/invite.rs, libparsec/crates/types/tests/unit/local_device.rs, libparsec/crates/types/tests/unit/local_device_file.rs, libparsec/crates/types/tests/unit/local_manifest.rs, libparsec/crates/types/tests/unit/manifest.rs, libparsec/crates/types/tests/unit/pki.rs
This PR fixes all impacted payloads in `libparsec_types` unit tests.
Only the following are still to be fixed. They involve _invalid_ payloads that are expected to fail with BadSerialization at some step ("msgpack+validation", "zstd"). But I don't know how to generate these payloads since there is no `expected` value:
- `libparsec/crates/platform_device_loader/tests/list.rs::list_devices`
- `libparsec/crates/types/tests/unit/manifest.rs::dump_load`
- `libparsec/crates/types/tests/unit/manifest.rs::invalid_load`
- `libparsec/crates/types/tests/unit/manifest.rs::serde_file_manifest_invalid_blocksize`
Closes #7669
=> Fix payloads in libparsec types unit tests

.cspell/custom-words.txt, .github/workflows/ci-rust.yml, .github/workflows/ci-web.yml, libparsec/crates/client/src/workspace/store/cache.rs, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/transactions/fd_flush.rs, libparsec/crates/client/src/workspace/transactions/fd_read.rs, libparsec/crates/client/src/workspace/transactions/fd_write.rs, libparsec/crates/client/src/workspace/transactions/file_operations.rs, libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/tests/unit/workspace/file_operations.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_file.rs, libparsec/crates/client/tests/unit/workspace/remove_entry.rs, libparsec/crates/serialization_format/src/protocol_python_bindings.rs, libparsec/crates/serialization_format/src/types.rs, libparsec/crates/testbed/src/template/crc_hash.rs, libparsec/crates/types/schema/local_manifest/local_file_manifest.json5, libparsec/crates/types/src/local_manifest.rs, libparsec/crates/types/tests/unit/local_manifest.rs, server/packaging/testbed-server/README.md
And add an explanation in the docstrings:
```rust
/*
* ChunkView
*/
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
/// Represents the content of a file manifest over a specific range of addresses.
///
/// It is called a `ChunkView` because it is implemented as a view over an
/// underlying chunk of data. Example:
///
/// File addressing:            raw offset            raw offset + raw size
/// Underlying chunk data: |--------|abcdefghijklmnopqrstuvwxyz|-------------|
/// Specific chunk view:   |--------------|ghijklmnopqrstu|------------------|
/// File addressing:                    start           stop
///
```
=> Rename chunk to chunk view when applicable

.github/workflows/publish.yml, .github/workflows/releaser.yml, client/electron/snap/snapcraft.yaml
- Run publish workflow on PR to test it (it will upload the latest nightly release).
- Fix snapcraft publish error where a snap in classic mode cannot use plugs/slots.
- Re-enable publish job in the release workflow
=> Fix snapcraft upload

client/electron/snap/snapcraft.yaml
The stable grade allow the snap to be published to the stable channel.
=> Change snap grade to stable

client/src/locales/en-US.json, client/src/locales/fr-FR.json
Remove space before question mark (EN).
Also remove "Cloud" (both EN and FR) to be consistent with app logo and title: only "Parsec" is displayed.
=> Fix typo in organization create dialog title

Cargo.lock, libparsec/crates/client/Cargo.toml, libparsec/crates/client/README.md, libparsec/crates/client/src/certif/store.rs, libparsec/crates/client/src/lib.rs, libparsec/crates/platform_storage/Cargo.toml, libparsec/crates/platform_storage/src/certificates.rs, libparsec/crates/platform_storage/src/native/certificates.rs, libparsec/crates/platform_storage/src/native/user.rs, libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/user.rs, libparsec/crates/platform_storage/src/web/certificates.rs, libparsec/crates/platform_storage/src/web/model.rs, libparsec/crates/platform_storage/src/web/user.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs
The idea is to hide behind compilation flags the functions that are used only in tests.
=> Use test and testing feature flag instead of unused when needed.

client/src/components/workspaces/utils.ts, client/src/theme/components/popovers.scss, client/src/views/sidebar-menu/SidebarMenuPage.vue
Depending on the side position of the popover when `...` is clicked in a workspace element, we can't tell whether the popover is open from the top or the bottom to customise the position with a class. The quickest solution was therefore to let the global behaviour of ionic. 
closes #7713
=> `SidebarMenu`: Popover side position & elements not clickable behind logo

.github/workflows/publish.yml, .github/workflows/releaser.yml
The releaser workflow should provide the secrets used in the publish workflow, otherwise they will be empty.
=> Fix empty secret when publish workflow is called by releaser

cli/Cargo.toml, cli/src/bootstrap_organization.rs, cli/src/cancel_invitation.rs, cli/src/claim_invitation.rs, cli/src/create_organization.rs, cli/src/create_workspace.rs, cli/src/export_recovery_device.rs, cli/src/greet_invitation.rs, cli/src/import_recovery_device.rs, cli/src/invite_device.rs, cli/src/invite_user.rs, cli/src/list_devices.rs, cli/src/list_invitations.rs, cli/src/list_users.rs, cli/src/list_workspaces.rs, cli/src/remove_device.rs, cli/src/run_testenv.rs, cli/src/share_workspace.rs, cli/src/stats_organization.rs, cli/src/stats_server.rs, cli/src/status_organization.rs, cli/src/tests.rs, cli/src/utils.rs, libparsec/crates/platform_device_loader/src/lib.rs, libparsec/src/config.rs
- Add `env` feature to clap dependency
- Use `env` feature to read some options from env variables:
- `PARSEC_SERVER_ADDR` for server address
- `PARSEC_ADMINISTRATION_TOKEN` for administration token
- `PARSEC_CONFIG_DIR` for Parsec config directory
- `PARSEC_DEVICE_ID` for device ID
=> [parsec-cli] Read some options from env variables

.github/workflows/publish.yml
Fix the following error, by not push package with local version to PyPI:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The use of local versions in <Version('3.0.0b12.dev19927+8a30e48')> is
not allowed. See
https://packaging.python.org/specifications/core-metadata for more
information.
```
<https://github.com/Scille/parsec-cloud/actions/runs/10067328239/job/27831161231>
=> Fix cannot push package with local version to PyPI

.github/workflows/publish.yml, misc/snapcraft_releases.py
Currently only the latest args `--release` is used by snapcraft for upload.
=> Fix uploading snap to multiple channels

.github/workflows/publish.yml, misc/snapcraft_releases.py
The option `--release=` does not take a `s`
=> Fix typo `snapcraft upload` command in `publish.yml`

make.py
`make.py` script is often run while no virtual env is set (this is typically the cas in the CI when packaging the client).
For this reason it is better to stick with Python 3.9 compatibility for now.
=> Remove use of Python>=3.12 feature in `make.py` script

libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs
- Rename `UpdateManifestData` to `ManifestData`
- Add type alias for encrypted manifest
=> Improve typing in platform storage

.github/workflows/package-client.yml
The auth token will be used to upload source maps to sentry during the build process.
=> Add sentry auth token when packaging the client

.github/workflows/package-client.yml
The `sed` command was failing because the secret `SENTRY_AUTH_TOKEN` likely contains a `/` character. I've changed the delimiter to `;` to avoid this issue.
=> Fix patch vite snap

.github/workflows/publish.yml, misc/snapcraft_releases.py
The previous way was not working because snapcraft prevent uploading the same file to multiple channels in multiple steps. The `--release` allows to specify multiple channels with a comma separated list.
Additionally, only the channel `nightly/stable` will be used for the nightly track.
=> Fix upload snapcraft in a single command

.github/workflows/ci-rust.yml
=> Fix `ci-rust` not using the same arguments as `pre-commit` for clippy

client/electron/package-lock.json, client/electron/package.json
That package is used in `src/updater.ts` for generating errors and handling xml files.
=> Add missing dependency `builder-util-runtime` for electron

docs/userguide/installation.rst
- `parsec-v3` --> `parsec_v3` : the syntax for name is `<snap>_<identifier>` (so `parsec_v3`, `parsec_v3beta`... are all accepted).
- No need to specify `--name`, that is for installing a local snap file
- `--channel=v3/stable` --> `--channel=v3` for consistency with previous command
=> Fix snap install command in docs

libparsec/crates/client/src/workspace/merge.rs
With the new pattern application mechanism in #7843, the pattern is always applied.
Closes #7762
=> Remove todo comment about force applying prevent sync pattern in merge local folder manifest

cli/src/cancel_invitation.rs, cli/src/create_organization.rs, cli/src/create_workspace.rs, cli/src/export_recovery_device.rs, cli/src/greet_invitation.rs, cli/src/import_recovery_device.rs, cli/src/invite_device.rs, cli/src/invite_user.rs, cli/src/list_devices.rs, cli/src/list_invitations.rs, cli/src/list_users.rs, cli/src/list_workspaces.rs, cli/src/macro_opts.rs, cli/src/main.rs, cli/src/remove_device.rs, cli/src/shamir_setup.rs, cli/src/share_workspace.rs, cli/src/stats_organization.rs, cli/src/stats_server.rs, cli/src/status_organization.rs, cli/src/utils.rs
Previously we used the structs `*SharedOpts` to share the same configuration for multiple commands. But I don't find that flexible enough, so I created a macro to define the shared options over multiple structs.
The advantage of the struct is already flattened
=> Use macro to define share option over multiple struct

.cspell/custom-words.txt, .github/workflows/ci-rust.yml, cli/src/bootstrap_organization.rs, cli/src/cancel_invitation.rs, cli/src/claim_invitation.rs, cli/src/create_workspace.rs, cli/src/export_recovery_device.rs, cli/src/greet_invitation.rs, cli/src/import_recovery_device.rs, cli/src/invite_device.rs, cli/src/invite_user.rs, cli/src/list_invitations.rs, cli/src/list_users.rs, cli/src/list_workspaces.rs, cli/src/macro_opts.rs, cli/src/main.rs, cli/src/remove_device.rs, cli/src/run_testenv.rs, cli/src/shamir_setup.rs, cli/src/share_workspace.rs, cli/src/tests.rs, cli/src/utils.rs
Simplify testing and working on the CLI as you no longer need to recompile it with `testenv` feature for testing.
- Add option `password-stdin` to allow the user to indicate the password should be read from stdin instead of TTY.
- Pass directly `ConfigWithDeviceSharedOpts` instead of passing each args.
- Update `invite_{user,device}_dance` to use `cargo_bin("parsec_cli")` over raw cargo command.
=> Allow to run CLI tests without testenv feature

cli/src/list_devices.rs, cli/src/remove_device.rs, cli/src/utils.rs
Also improve error message when multiple devices are found for a given short ID by listing the matched devices over the whole list of devices.
=> Remove callback in `load_device_file`

client/electron/snap/snapcraft.yaml
The previous method of using git clone is failable if the commit is not present in the main branch of the repository. Instead, we download the commit archive provided by github.
=> Harden megashark-lib build in snapcraft

.github/workflows/package-client.yml, .github/workflows/releaser.yml, client/electron/package.js
Add this suffix to indicate that the artifacts are not signed.
=> Add suffix `.unsigned` to windows & macos artifacts

deny.toml
- Fix Root configuration being moved to sub field.
- Update advisories configuration to v2.
- Update licenses configuration to v2.
- Add reason to ignoring vuln `RUSTSEC-2023-0071`.
- Allow license `MPL-2.0`.
=> Update cargo deny configuration

docs/rfcs/1011-non-blocking-invite-transport.md, libparsec/crates/protocol/schema/invited_cmds/invite_claimer_start_greeting_attempt.json5, libparsec/crates/protocol/tests/invited_cmds/v4/invite_claimer_start_greeting_attempt.rs, server/parsec/_parsec_pyi/protocol/invited_cmds/v4/invite_claimer_start_greeting_attempt.pyi, server/parsec/components/invite.py, server/tests/api_v4/authenticated/test_invite_greeter_cancel_greeting_attempt.py, server/tests/api_v4/authenticated/test_invite_greeter_step.py, server/tests/api_v4/invited/test_invite_claimer_cancel_greeting_attempt.py, server/tests/api_v4/invited/test_invite_claimer_start_greeting_attempt.py, server/tests/api_v4/invited/test_invite_claimer_step.py, server/tests/common/rpc.py, server/tests/test_greeting_attempt.py
Follow-up https://github.com/Scille/parsec-cloud/pull/7761
Part of #7018
=> [RFC-1011] Fix useless token field in invite_claimer_start_greeting_attempt

.github/workflows/ci-python.yml, .github/workflows/ci-rust.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, misc/lint_sql.py, server/parsec/components/postgresql/utils.py, server/poetry.lock, server/pyproject.toml
EDIT:
:star: :fireworks: New improved version ! :fireworks: :star: 
```
$ python misc/lint_sql.py libparsec
7 linted files, all good ;-)
```
or just \o/
```
$ pre-commit run --all-files sqlfluff
SQLFluff (using `poetry run ./misc/lint_sql.py`).........................Passed
```
Usage:
```
__PARSEC_LINT_SQL=true python -c "import parsec"
```
example:
=> Allow sqlfluff to be used on the SQL embedded in the Python code \o/

.github/workflows/package-client.yml
An extra `--` was added when generating the AppImage for nightly build, causing the flag `--nightly` being parsed as a target alongside `appimage`.
To fix that we factorize adding the `--` part if either _We make a nightly build_ or _Package an AppImage_.
=> Fix AppImage packaging for nightly build

libparsec/crates/testbed/src/scope.rs
The PR #8225 only made a basic search&replace, but we have some logique to remove since the `TESTBED_SERVER` env var was merged with `TESTBED_SERVER_URL`.
That the case when we start the testbed to rust tests where we would fallback to `TESTBED_SERVER_URL` if `TESTBED_SERVER` was not set.
=> Remove fallback to the same env var for setting testbed URL

.pre-commit-config.yaml
because dependabot does not yet support updating pre-commit hooks
=> Update pre-commit hooks via autoupdate

cli/src/commands/run_testenv.rs
This is useful when the default org id was already used and we don't want to restart the testbed.
=> Allow to specify the organization id to use for the test environment

.github/workflows/package-client.yml
When we do not package electron on linux nor we are in a nightly build an extra `false` was added to the command line causing failure on windows & macos jobs.
This commit fix that by handling the `false` case with empty string.
=> Fix extra `false` added to the cmd packaging electron

cli/src/commands/run_testenv.rs
Instead return an error message to the user.
=> Do not panic if testbed url is missing nor main id is not provided

cli/tests/integration/invite_device.rs, cli/tests/integration/invite_user.rs, libparsec/crates/client/src/invite/claimer.rs
Fix the flaky `invite_user_dance` and `invite_device_dance` tests (flakiness introduced in #8066)
This is done by having the claimer not polling the last step of the greeting attempt.
As explained in this comment:
```
// Only perform the acknowledge step once
// This is for two reasons:
// 1. We don't need to wait for the greeter to actually receive it
// 2. The invitation might get marked as completed by the greeter
//    once it has received our acknowledgement. That means that there
//    are no guarantees that will be able to get the 8th greeter step
//    if we poll for it.
```
=> Fix invite dance tests flakiness introduced in #8066

server/parsec/asgi/administration.py, server/parsec/asgi/rpc.py, server/parsec/backend.py, server/parsec/cli/testbed.py, server/parsec/client_context.py, server/parsec/config.py
More specifically:
- consistently log the different outcomes of RPC requests
- reduce the request id size to 4 characters
- log the different steps and outcomes in the SSE context
- bind the command name the the client context logger
- log base exceptions in debug mode, so cancellation or other base exception can appear
~It also adds debug logs to postgre transactions, although these could be dropped when the server crash investigation is over, up to debate.~ removed.
Also add a `--with-postgresql` option to the testbed server
=> Improve logging in the parsec server

libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/src/workspace/transactions/read_folder.rs, libparsec/crates/client/src/workspace/transactions/stat_entry.rs, libparsec/crates/client/tests/unit/workspace/folder_transactions.rs
Partial fix to #8263
Add TODOs for https://github.com/Scille/parsec-cloud/issues/8276
=> Restore local confinement points in outbound sync

bindings/electron/src/lib.rs
Related to #8194 
I was unable to reproduce this bug, so here is a patch to avoid panicking. 
The error is still logged so if we are able to to monitor logs, we'll may gather more information on this.
=> Error management on log initialization

.cspell/custom-words.txt, server/parsec/components/postgresql/handler.py, server/parsec/events.py, server/tests/administration/test_freeze_user.py
... so the payload doesn't exceed 8000 bytes
Also remove the useless b64 conversion in `send/parse_signal`
Fix #8410
=> Lower `EVENT_VLOB_MAX_BLOB_SIZE` 

Cargo.lock, cli/Cargo.toml, cli/src/commands/organization/create.rs, cli/src/commands/organization/stats.rs, cli/src/commands/organization/status.rs, cli/src/commands/server/stats.rs, libparsec/crates/client_connection/src/anonymous_cmds.rs, libparsec/crates/client_connection/src/authenticated_cmds/mod.rs, libparsec/crates/client_connection/src/invited_cmds.rs, libparsec/crates/client_connection/src/lib.rs
Also refactor CLI to use `libparsec_client_connection::build_client` over directly using `reqwest::Client::new()` (That also mean the CLI now support proxy settings ^^)
Closes #8402
=> Refactor client connection to allow loading a custom CA file for TLS

client/src/common/cache.ts, client/src/components/files/FileCopyItem.vue, client/src/components/files/FileMoveItem.vue, client/src/components/files/FileUploadItem.vue, client/src/components/notifications/MultipleUsersJoinWorkspaceNotification.vue, client/src/components/notifications/UserJoinWorkspaceNotification.vue, client/src/parsec/workspace.ts, client/src/views/header/HeaderPage.vue, client/tests/unit/specs/testCache.spec.ts
When displaying imports, a query will be done for workspace info for every file imported. This caches up the workspace name so we can avoid querying the bindings. The cache is invalidated after 5min, so workspace name changes will still be visible.
=> [MS] Added cache for getting workspace name

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/BmsLogin.vue, client/src/views/organizations/creation/CreateOrganizationCustomServer.vue, client/src/views/organizations/creation/CreateOrganizationModal.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/src/views/organizations/creation/CreateOrganizationTrial.vue, client/src/views/organizations/creation/OrganizationNamePage.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/create_organization.spec.ts, client/tests/pw/e2e/create_organization_custom.spec.ts, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/e2e/create_organization_trial.spec.ts, client/tests/pw/helpers/fixtures.ts
Closes https://github.com/Scille/parsec-cloud/issues/8129
=> [MS] Added back buttons after server choice on organization creation

.github/scripts/check_newsfragments.py, .github/workflows/ci.yml, misc/releaser.py, newsfragments/README.rst
Also simplify news fragment check in the CI (https://github.com/Scille/parsec-cloud/pull/8467/commits/48898831914c81f6fb65606f44c266614acbae43): with the previous checks it was impossible to update the README file or update an existing news fragment.
=> Add command to display history for current release

server/parsec/cli/options.py, server/parsec/cli/sequester.py, server/parsec/components/postgresql/events.py, server/parsec/components/postgresql/factory.py
This way, the `PARSEC_DB_MIN_CONNECTIONS/PARSEC_DB_MAX_CONNECTIONS` configuration will correctly reflect the number of connections made to the database.
=> Use asyncpg pool for the notification connection

.github/workflows/releaser.yml
non-nightly releases have their github release created as draft, the publish workflow need the release to be published.
=> Do not run publish workflow on non-nightly release

misc/releaser.py
The current branch check was failing when releasing a nightly build when the patch != 0. This check is here to enforce the use of the release branch for the next patch version. But that doesn't apply to nightly builds.
=> Fix nightly release failure because of invalid current branch

client/electron/scripts/snap_migrate_devices_from_snap_user_data.sh, client/electron/snap/snapcraft.yaml, newsfragments/8464.bugfix.rst
Also migrate previous devices located in snap user data
Closes #8464
=> Make parsec use $HOME/.config as the base configuration directory for the snap package

.github/workflows/_releaser_nightly_build.yml, misc/version_updater.py
The python present by default on the runner don't have the lib `tomllib` which fail the version update steps
=> Fix nightly release failing because of old python version

libparsec/crates/client/src/workspace/transactions/stat_entry.rs, libparsec/crates/client/tests/unit/workspace/read_folder.rs, libparsec/crates/client/tests/unit/workspace/stat_entry.rs, newsfragments/8521.bugfix.rst
=> WorkspaceOps's stat entry & read dir return the current size of opened file instead of the last flushed one (needed by FUSE)

client/src/views/files/FoldersPage.vue, newsfragments/8584.bugfix.rst
When logging out while importing, the import operations are cancelled which triggers a refresh of the file list, but the handle is already invalid due to logging out, which causes a toast to be displayed on the home page.
=> [MS] Hide wrong toast when logging out while importing

client/src/views/files/FileDetailsModal.vue, client/tests/pw/e2e/file_details.spec.ts, newsfragments/8597.bugfix.rst
=> [MS] Fixed sync icon in file details dialog

server/parsec/asgi/administration.py
This seems to be preventing fastapi upgrades: with newer versions, Pydantic was unable to generate pydantic-core schema for these fields even though set `arbitrary_types_allowed=True` in the model_config
See: https://github.com/Scille/parsec-cloud/actions/runs/11101712183/job/30839956516?pr=8544
=> Use Annotated types for Pydantic model fields

cli/src/commands/ls.rs, cli/tests/integration/ls.rs, newsfragments/8629.feature.rst
=> Rename the option `workspace-id` to `workspace` in the CLI command `ls`

cli/src/commands/workspace/import.rs, cli/tests/integration/workspace/import.rs, newsfragments/8622.feature.rst
=> Rename the option `workspace_id` to `workspace` in the CLI command `workspace import`

cli/src/commands/rm.rs, cli/tests/integration/rm.rs, newsfragments/8630.feature.rst
=> Rename the option `workspace-id` to `workspace` in the CLI command `rm`

cli/src/commands/organization/create.rs, cli/tests/integration/organization/create.rs, newsfragments/8620.feature.rst
=> [CLI] Make CLI command `organization create` directly take the organization ID instead of using the option `--organization-id`

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/files/FoldersPage.vue, client/src/views/workspaces/WorkspacesPage.vue
Closes #8616 
You can test with the web version by adding a `await wait(5000)` at the start of `parsec/file.ts:statFolderChildren()` and `parsec/workspace.ts:listWorkspaces()` (import the function from parsec/internals.ts if needed).
=> [MS] Adds spinner when loading workspaces and folders

.github/actions/use-pre-commit/action.yml, .github/workflows/_releaser_nightly_build.yml, .github/workflows/ci-docs.yml, .github/workflows/ci-python.yml, .github/workflows/ci-rust.yml, .github/workflows/ci.yml, .github/workflows/docker-server.yml, .github/workflows/docker-testbed.yml, .github/workflows/package-client.yml, .github/workflows/package-server.yml, .github/workflows/publish.yml, libparsec/crates/platform_device_loader/tests/archive.rs
Summary
-------
- `shell: bash` was added when a run command used pipes (including command that used `set -e -o pipefail`).
For the documentation: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference>
Setting `shell` to that value will automatically add the `-o pipefail` (alongside `-e`)
- `shell: bash ... {0}` was used for run commands that used `set ...`
Fixes
-----
- Fix `yq` syntax (GA use `yq-go` not `yq` (the python wrapper of `jq`))
=> Specify shell in all GitHub Actions workflows when needed

client/src/router/checks.ts, client/src/views/header/HeaderPage.vue, client/src/views/users/UsersPage.vue, newsfragments/8652.bugfix.rst
App could sometimes display the mock values when logging out. This is due to unchecked watchers on the global route. For example:
1. the user pages watches the route for changes
2. the user logs out, which changes the route to /home
3. the watcher gets triggered
4. the page tries to load the data but we have no connection handle, so we load the mock values
The fix is just to make sure the current route is the right one (Routes.Users in this example).
=> [MS] Avoid displaying mock values when logging out

docs/hosting/deployment/gen-admin-token.sh, docs/hosting/deployment/parsec-server.docker.yaml, docs/hosting/deployment/setup-tls.sh
- `setup-tls`: The script now compare the date of the files used to generate the key and certificate to regenerate them if needed.
- `gen-admin-token`: Add `set -euo pipefail` to make the script more robust.
=> Update hosting script to be more robust

server/parsec/templates/index.html
No issue nor newsfragment required, this page isn't really used in practice.
=> Fix start-parsec link in index.html

docs/HOSTING.md, docs/hosting/deployment/parsec.env, newsfragments/8626.feature.rst, server/packaging/server/template-prod.env.list, server/parsec/asgi/__init__.py, server/parsec/cli/run.py, server/parsec/cli/testbed.py, server/parsec/config.py, server/tests/common/backend.py
Add a new option that configure the list of trusted address to parse the proxy headers from.
The parsing is handled by `uvicorn` which currently only support `x-forwarded-{for,proto}` headers.
Closes #8626, closes #8427
=> Add option to enable proxy header

client/src/components/sidebar/SidebarWorkspaceItem.vue, client/src/views/layouts/ConnectedLayout.vue
AcceptTOSEvent are sent twice. The GUI did account for this in two ways:
1. Events while the accept modal itself is opened are ignored
2. It keeps track of the last TOS accepted (using the date) and if the TOS have not changed at the next event, it discards the event
When testing locally, we always ended up in the first case: modal was already opened anyway, so we would just discard the event. But with a distant server and some latency, we can enter the second case, and sadly, the comparaison between the two dates did not work (=== can't be used between two luxon DateTime it seems).
It can be replicated locally by adding some latency:
`tc qdisc add dev lo root handle 1:0 netem delay 400msec`
and
`tc qdisc del dev lo root` to clear it.
Also fixes an error when trying to clear and event …
=> [MS] Fixed tos modal opening twice in some cases

.cspell/custom-words.txt, docs/hosting/deployment/index.rst, server/parsec/asgi/__init__.py, server/parsec/cli/run.py, server/parsec/cli/testbed.py, server/parsec/config.py, server/tests/common/backend.py
Typically, scalingo sets `FORWARDED_ALLOW_IPS` for us.
Fix #8699
=> Keep using FORWARDED_ALLOW_IPS if PARSEC_PROXY_TRUSTED_ADDRESSES is not provided

server/parsec/asgi/administration.py, server/parsec/components/memory/organization.py, server/parsec/components/organization.py, server/parsec/components/postgresql/organization.py, server/parsec/components/postgresql/organization_update.py, server/tests/administration/test_create_organization.py
This was properly done in the memory implementation but not in the postgresql one.
=> Use organization_initial_tos in postgresql create organization method

client/src/components/users/UserSelect.vue, client/src/views/users/BulkRoleAssignmentModal.vue, client/tests/pw/e2e/users_list.spec.ts
Closes #8727 
Caused by the fact that we filter out the current user from the list of users matching the query, but we don't check if the list is empty afterwards.
I also fixed the user tests, we used to create one test per user per list|grid instead of having one test for list and grid that checks all the users.
And I also refactored a bit of code to user an enum instead of raw numbers.
=> [MS] Fix assign workspace role with empty user list

client/src/views/organizations/creation/CreateOrganizationTrial.vue, client/src/views/organizations/creation/OrganizationAuthenticationPage.vue
Since the authentication choice is the last step to the trial organization creation, I replaced the button text from `Next` to `Create organization` to indicate the end of the process.
=> [MS] Set correct button text at the end of trial org creation

cli/src/commands/tos/config.rs, cli/src/commands/tos/mod.rs, cli/src/macro_opts.rs, cli/tests/integration/tos/config.rs, cli/tests/integration/tos/list.rs, cli/tests/integration/tos/mod.rs, newsfragments/8778.feature.rst
=> Add CLI command to configure TOS for an organization

libparsec/crates/platform_mountpoint/src/windows/mount.rs, newsfragments/8818.bugfix.rst
=> Fix file synchro when created from WinFSP mountpoint due to file staying opened indefinitely

client/src/services/environment.ts, client/src/views/about/AboutView.vue
=> [MS] Fixed opening urls

.github/workflows/ci-rust.yml
=> Update macOS runner image to v14 for ci-rust

.github/workflows/package-server.yml
We provide the macos server wheel as best effort.
We don't have a clear understanding of why that step was required and it use deprecated things.
Fix #8845
=> Remove hack step for packaging server wheel for macos

client/electron/assets/installer.nsh, newsfragments/8934.bugfix.rst
Fix #8934
Using `/passive` instead of `/qn` allows for prompting the user for privilege escalation. 
That also means that a progress bar will show up during winfsp installation.
This is what's advertised in electron documentation:
https://www.electron.build/nsis.html#custom-nsis-script
> If you want to include additional resources for use during installation, such as scripts or additional installers, you can place them in the build directory and include them with File. For example, to include and run extramsi.msi during installation, place it in the build directory and use the following:
>  ```
>  !macro customInstall
>    File /oname=$PLUGINSDIR\extramsi.msi "${BUILD_RESOURCES_DIR}\extramsi.msi"
>    ExecWait '"msiexec" /i "$PLUGINSDIR\extramsi.msi" /passive'
>  !macroend
>  ```
Note: …
=> Use passive install for winfsp so the user can be prompted for admin rights

Cross.toml, cli/Cargo.toml, libparsec/Cargo.toml, libparsec/crates/platform_device_loader/Cargo.toml, make.py
Following the peer-review with @touilleMan and @vxgmichel.
- Rename `vendored-keyring` to `vendored-dbus`.
- Use dedicated variable in `make.py` to explicitly state the additional features for vendored libs.
- Add comment in `Cross.toml` for `PKG_CONFIG_ALL_STATIC`.
- Add comment about the meaning of `persistent` in the feature name `linux-native-sync-persistent` of the keyring crate.
=> Further fix for keyring/dbus

server/setup.cfg
Fix warning:
```
/home/emmanuel/.cache/pypoetry/virtualenvs/parsec-cloud-fUS9rJbY-py3.12/lib/python3.12/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
```
=> Configure pytest's asyncio_default_fixture_loop_scope option

client/src/components/workspaces/WorkspaceUserRole.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/inputs.scss, client/src/theme/components/modals.scss, client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/e2e/specs/workspace_sharing.spec.ts, client/tests/e2e/specs/workspaces_actions.spec.ts, newsfragments/8326.feature.rst
Closes #8326 
https://github.com/user-attachments/assets/5b26a93c-0a9b-44ab-8212-a5167fec3b8c
=> [MS] Batch workspace sharing

libparsec/crates/types/src/certif.rs
=> Document why `AnyCertificate::unsecure_load` is incompatible with `SequesterService` & `SequesterRevokedService`

cli/src/commands/invite/claim.rs, cli/src/macro_opts.rs, cli/src/utils.rs, newsfragments/8937.feature.rst
=> Allow overwriting default config & data directory during CLI command `invite claim`

client/src/services/sidebarMenu.ts, client/src/views/client-area/ClientAreaHeader.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/header/HeaderPage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/sidebar-menu/index.ts, client/src/views/sidebar-menu/utils.ts, newsfragments/8851.bugfix.rst
Closes https://github.com/Scille/parsec-cloud/issues/8139, https://github.com/Scille/parsec-cloud/issues/8994
=> [MS] Enhance sidebar behaviour

client/src/components/users/UserFilterPopover.vue, client/src/components/users/types.ts, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/tests/e2e/specs/users_list.spec.ts, newsfragments/8964.feature.rst
=> [MS] UsersPage search input

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/invite.py, bindings/generator/api/workspace.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/event_bus.rs, libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/mod.rs, libparsec/crates/client/src/workspace/transactions/watch_entry.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_file.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_folder.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_root.rs, libparsec/crates/client/tests/unit/workspace/mod.rs, libparsec/crates/client/tests/unit/workspace/watch_entry.rs, libparsec/src/handle.rs, libparsec/src/workspace.rs, newsfragments/9102.bugfix.rst
=> Fix `WorkspaceOps::watch_entry_oneshot` not being triggered when a missing child of the watched folder is finally synchronized

client/src/components/sidebar/SidebarMenuList.vue, client/src/components/sidebar/SidebarRecentFileItem.vue, client/src/components/sidebar/SidebarWorkspaceItem.vue, client/src/components/sidebar/index.ts, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/workspaces_actions.spec.ts, client/tests/e2e/specs/workspaces_list.spec.ts, newsfragments/9088.feature.rst
- Added dropdown feature to toggle visibility
- Rearranged style
- Add animation on click
https://github.com/user-attachments/assets/c73063cd-9255-4a6b-ab71-6ebe0c36f279
closes #8980 
closes #8700
=> [MS] Restyle `SidebarMenuPage`

client/src/parsec/file.ts, client/src/parsec/mock_generator.ts, client/tests/e2e/helpers/assertions.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/file_details.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts
Generates one file of each type for which we have a viewer.
=> [MS] Updated e2e tests to handle file viewers

client/src/components/viewers/FileControlsInput.vue, client/src/components/viewers/index.ts
=> [MS] Implements FileControlsInput

libparsec/crates/platform_mountpoint/src/windows/winify.rs, libparsec/crates/platform_mountpoint/tests/unit/windows_winify.rs, newsfragments/9171.bugfix.rst
=> Fix support for literal tild (i.e. `~`) when converting name in windows mountpoint (unwinify)

cli/src/commands/invite/user.rs, cli/tests/integration/invitations/user.rs, newsfragments/9186.bugfix.rst
=> Fix CLI command `invite user` generating a device invitation link instead of a user invitation link.

libparsec/crates/client/src/workspace/store/cache.rs, libparsec/crates/client/src/workspace/store/file_updater.rs, libparsec/crates/client/src/workspace/store/folder_updater.rs, libparsec/crates/client/src/workspace/store/manifest_access.rs, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/store/reparent_updater.rs, libparsec/crates/client/src/workspace/store/resolve_path.rs, libparsec/crates/client/src/workspace/store/sync_updater.rs, libparsec/crates/platform_async/src/lib.rs, libparsec/crates/platform_async/src/native/mod.rs, libparsec/crates/platform_async/src/web/mod.rs
- Hide `WorkspaceStore`'s cache & storage (i.e. local db) internals
- Access must be done through callback API to limit the scope the lock is taken
- A runtime deadlock detector is present in debug build \o/
=> Workspace store deadlock protection

client/src/components/files/utils.ts
Closes https://github.com/Scille/parsec-cloud/issues/8918
The issue was that `.webloc` files were accounted for twice in the `DragEvent.dataTransfer`, once in `items` and once in `files`, and both showed up when importing such a file (see videos in the issue).
This PR separates the two lists: either `webkitGetAsEntry` works and the import is based on `items`, or it doesn't (`entry` list is empty) and the import is based on `files`.
=> [MS] Separate webkitGetAsEntry and files methods in drag&drop files

libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/transactions/fd_close.rs, libparsec/crates/client/src/workspace/transactions/fd_flush.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/open_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/move_entry.rs, newsfragments/9012.bugfix.rst
Backport for Parsec 3.2 of #9199
=> Backport Parsec 3.2: Quick patch to fix deadlock when reparenting a file from the mountpoint on Windows

client/package-lock.json, client/src/components/client-area/InvoicesContainer.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/translation.ts, client/src/views/client-area/dashboard/DashboardPage.vue, client/tests/e2e/specs/client_area_dashboard.spec.ts, client/tests/e2e/specs/client_area_invoices_page.spec.ts
Translation updated:
- Date
- Status
closes #8731
closes #8732
=> [MS] Update invoice translations

client/src/services/bms/api.ts, client/src/services/bms/mockApi.ts, client/src/services/bms/types.ts, client/tests/e2e/helpers/bms.ts
=> [MS] Adds API and mocks for custom order requests list

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/viewers/SpreadsheetViewer.vue
=> [MS] Properly handle errors in spreadsheet viewer

Cargo.lock, libparsec/Cargo.toml
This dependency was not used and should not be used by this crate directly (to simplify platform specific path/behavior)
=> Remove `dirs` deps from `libparsec` crate

server/parsec/asgi/__init__.py, server/parsec/cli/options.py, server/parsec/logging.py
Improve logging configuration in the server
- Don't generate breadcrumb when logs trigger sentry report
- Add `CONSOLE_NO_TIMESTAMP` format (useful in PAAS when the log collecter already provide a timestamp)
- Support colored output from uvicorn logs
- Avoid useless breadcrumb in structlog sentry handler when the log already cause a report
- Remove no longer needed explicit call to exc_info formatter in structlog processors
- Make consistent the log format between stdlib and structlog
=> Improve server logging

server/parsec/asgi/__init__.py, server/parsec/asgi/rpc.py, server/parsec/components/events.py
you can reproduce the issue with this patch:
```patch
diff --git a/server/parsec/asgi/rpc.py b/server/parsec/asgi/rpc.py
index 9bf016da1..1c9b7c61c 100644
--- a/server/parsec/asgi/rpc.py
+++ b/server/parsec/asgi/rpc.py
@@ -747,6 +747,10 @@ async def authenticated_events_api(raw_organization_id: str, request: Request) -
device_verify_key=auth_info.device_verify_key,
)
+    print("================ GO FOR ^C !!!!")
+    import asyncio
+    await asyncio.sleep(5)
+    print("================ NOW RETURNING STREAMING RESPONSE")
return StreamingResponseMiddleware(
backend,
client_ctx,
```
steps to reproduce:
1. startsthe testbed server with `python -m parsec testbed`
2. start the GUI with `TESTBED_SERVER='parsec3://127.0.0.1:6770?no_ssl=true' npm run electron:open`
3. in the GUI, login as any …
=> Fix handling of SSE connections during gracious teardown of the server

client/package-lock.json, client/package.json, client/src/router/navigation.ts, client/src/views/layouts/LoadingLayout.vue, newsfragments/9287.bugfix.rst
Closes #9287 
Steps to reproduce are given in #9287 
I would also advice testing with the following patch applied to check the behavior in case the base64 encoding still crashes.
```diff
diff --git a/client/src/router/navigation.ts b/client/src/router/navigation.ts
index b1d9e55d5..36c81a7bc 100644
--- a/client/src/router/navigation.ts
+++ b/client/src/router/navigation.ts
@@ -97,6 +97,7 @@ export async function switchOrganization(handle: ConnectionHandle | null, backup
}
const backup = routesBackup[backupIndex];
try {
+      throw new Error('Error');
await navigateTo(Routes.Loading, { skipHandle: true, replace: true, query: { loginInfo: Base64.fromObject(backup) } });
} catch (e: any) {
// We encounter an error, probably the base64 serialization, we remove the backup and log in to the …
```
=> [MS] Fixed switch org bug

.github/workflows/ci-web.yml
Also prune dependencies not listed in `package-lock.json` that could be installed by older cache
=> Check that `package-lock.json` is up-to-date

client/src/components/sidebar/SidebarMenuList.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/sidebar-menu/utils.ts
=> [MS] Remember the state of the sidebar

libparsec/crates/types/src/addr.rs, libparsec/crates/types/tests/unit/addr.rs, newsfragments/9316.bugfix.rst
=> Fix url parsing with splitted scheme

client/src/components/sidebar/SidebarMenuList.vue, client/src/components/sidebar/SidebarWorkspaceItem.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/sidebar-menu/utils.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/sidebar.spec.ts
- Updates the sidebar icons for collapse
- Save the recent documents state
- Fixed recent documents being displaying in org management page
- Show some recent documents by default in dev mode to remember that this feature exists
- Added e2e tests for recents documents
- Added e2e tests for sidebar state
I don't know if a newsfragment is required since the only thing the user will see is the change of icon.
Closes #9306
=> [MS] Updated sidebar menu icons, save recent file menu state

libparsec/crates/client/src/monitors/connection.rs, libparsec/crates/client_connection/src/anonymous_cmds.rs, libparsec/crates/client_connection/src/authenticated_cmds/mod.rs, libparsec/crates/client_connection/src/error.rs, libparsec/crates/client_connection/src/invited_cmds.rs, libparsec/crates/client_connection/src/lib.rs, libparsec/crates/client_connection/src/testbed.rs, libparsec/crates/client_connection/tests/unit/anonymous.rs, libparsec/crates/client_connection/tests/unit/authenticated.rs, libparsec/crates/client_connection/tests/unit/invited.rs
And add client tests for unsupported api version
Part of #9320
I don't think it requires a news fragment.
=> Fix unsupported_api_version_from_headers helper

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/generator/api/common.py, bindings/generator/api/invite.py, bindings/generator/generate.py, bindings/generator/templates/binding_electron_index.d.ts.j2, bindings/generator/templates/binding_electron_meths.rs.j2, bindings/generator/templates/binding_web_meths.rs.j2, bindings/generator/templates/client_plugin_definitions.ts.j2, bindings/web/src/meths.rs, client/src/parsec/claim_device.ts, client/src/parsec/claim_user.ts, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/invite/claimer.rs, libparsec/crates/client/tests/unit/invite/shamir.rs, libparsec/src/client.rs, libparsec/src/handle.rs, libparsec/src/invite.rs
=> Add missing shamir recovery GUI bindings

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/file.ts, client/src/views/viewers/FileViewer.vue
Fixes a few things when opening a file with the viewers
1. Display a generic translated error message if the opening fails
2. If the viewer fails, opens the file with the system if possible
3. Use the correct path in the mocks (previously, opening `/A.pdf` would result in the file path for the viewer to be `/A.pdf/A.pdf`. Not super important since it's all mocks, but still.
4. If the viewer fails to open, the current path was set to the path of the document. Opening `/A.pdf` and failing to do so would result in the app trying to list the content of `/A.pdf`, using it as its current path.
=> [MS] Fixed a few things when opening a file with viewers

client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/e2e/specs/sidebar.spec.ts
=> [MS] Keep the top of the sidebar visible at all times

client/src/components/viewers/controls/FileControlsPagination.vue, client/src/parsec/file.ts
=> [MS] Fix pagination controls

Cargo.lock, cli/Cargo.toml, cli/src/commands/invite/claim.rs, cli/src/commands/invite/greet.rs, cli/src/commands/invite/list.rs, cli/src/utils.rs, cli/tests/integration/invitations/device.rs, cli/tests/integration/invitations/shared_recovery.rs, cli/tests/integration/invitations/user.rs, cli/tests/integration/mod.rs
=> [CLI] Use dialoguer's select in each invitation process.

cli/src/commands/invite/claim.rs, cli/src/commands/shared_recovery/create.rs, cli/src/commands/shared_recovery/info.rs, cli/src/commands/shared_recovery/list.rs, cli/src/utils.rs, cli/tests/integration/mod.rs, cli/tests/integration/shared_recovery/create.rs, cli/tests/integration/shared_recovery/info.rs
=> [CLI] Ask for confirmation before creating shared recovery.

client/src/services/fileOpener.ts, client/src/views/viewers/FileViewer.vue, client/tests/e2e/specs/file_viewers.spec.ts
Correctly switches which file is currently viewed when opening a file through the recent document while a viewer is active. Also fixes reopening the file that is currently viewed.
=> [MS] Correctly opens file from the recent docs

client/src/parsec/login.ts, client/src/services/eventDistributor.ts, client/src/views/files/FoldersPage.vue, newsfragments/9388.bugfix.rst
Closes #9388 
File stat when sync starts and ends. Not ideal, the file size will still not be updated while the copy is progressing, but it will update eventually.
=> [MS] Update file size when sync starts and ends

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/certif/mod.rs, libparsec/crates/client/src/certif/user_update_profile.rs, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/src/client/user_update_profile.rs, libparsec/crates/client/tests/unit/client/mod.rs, libparsec/crates/client/tests/unit/client/update_user_profile.rs, libparsec/src/client.rs
=> Expose user update profile bindings

server/parsec/backend.py, server/parsec/cli/__init__.py, server/parsec/cli/export.py, server/parsec/cli/inspect.py, server/parsec/cli/options.py, server/parsec/cli/run.py, server/parsec/cli/sequester_create.py, server/parsec/cli/sequester_list.py, server/parsec/cli/sequester_revoke.py, server/parsec/cli/testbed.py, server/parsec/cli/utils.py, server/parsec/config.py
=> CLI commands for sequester and realm export

server/parsec/components/memory/organization.py, server/parsec/components/postgresql/organization_stats.py, server/tests/administration/test_stats.py
=> Fix `/administration/stats` endpoint when `at` is provided and before an existing organization

client/src/views/viewers/TextViewer.vue
replace #9379 
related to #9038
=> [MS] Implements Zoom control for TextViewer

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/fileOpener.ts, client/src/views/viewers/FileViewer.vue, client/src/views/workspaces/WorkspaceHistoryPage.vue, newsfragments/9482.feature.rst
=> [MS] Open files in history with viewers

libparsec/crates/client/src/certif/add.rs, libparsec/crates/client/src/certif/realm_create.rs, libparsec/crates/client/src/certif/workspace_bootstrap.rs, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/src/monitors/mod.rs, libparsec/crates/client/src/monitors/user_sync.rs, libparsec/crates/client/src/user/sync.rs, libparsec/crates/client/tests/unit/certif/add_realm_role_certificate.rs, libparsec/crates/protocol/schema/authenticated_cmds/realm_create.json5, libparsec/crates/protocol/tests/authenticated_cmds/v5/realm_create.rs, libparsec/crates/testbed/src/template/events.rs, libparsec/crates/testbed/src/template/utils.rs, server/parsec/_parsec_pyi/protocol/authenticated_cmds/v5/realm_create.pyi, server/parsec/components/memory/realm.py, server/parsec/components/postgresql/realm_create.py, server/parsec/components/realm.py, server/tests/api_v5/authenticated/test_realm_create.py, server/tests/api_v5/authenticated/test_user_revoke.py
close #8226 
New rules are:
- An OUTSIDER cannot create a realm.
- When sharing with an OUTSIDER, the roles MANAGER and OWNER cannot be given.
- A user becoming OUTSIDER retains his existing role in each realm he is part of.
=> Correct Outsider&realm interactions in libparsec&server

.cspell/custom-words.txt, client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/viewers/FileViewer.vue, client/src/views/viewers/SpreadsheetViewer.vue, client/src/views/viewers/workers/spreadsheet_converter.ts, client/src/views/viewers/workers/spreadsheet_document_loader.ts, client/src/views/viewers/workers/spreadsheet_page_loader.ts, client/tests/e2e/specs/file_viewers.spec.ts
Transforming the grid into HTML and then injecting that table to the DOM is incredibly slow and inefficient (a 2MB XLSX is converted to a 80MB HTML string). This uses RevoGrid (https://rv-grid.com/) instead to display the data parsed from SheetJS. It also adds some spinners and texts, a dedicated worker to load the file, and a better workers management.
I've been able to open a 14MB XLSX with this. A bit slow (~20s) but it works and once loaded, the display is smooth.
=> [MS] Updated spreadsheet viewer

Cargo.lock, bindings/electron/Cargo.toml, bindings/electron/src/lib.rs, libparsec/Cargo.toml, libparsec/src/lib.rs
Closes #8518
This PR adds:
- setup logging during libparsec initialization
- add `PARSEC_RUST_LOG_FILE` to set log file path (default `{temp_dir}/libparsec-{date}.log`)
- add `PARSEC_RUST_LOG` to set log level (default `info`)
- note that this is equivalent to `RUST_LOG` (so advanced syntax is supported).
=> Add libparsec logging to file

libparsec/src/lib.rs
=> fix(libparsec): Ignore error to create log dir

docs/hosting/install_cli.rst, misc/version_updater.py
Also fix the name of the downloaded artifact
Fix #9635
=> fix(docs): Fix link to download parsec-cli

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/inputs.scss, client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/e2e/specs/workspace_sharing.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/9690
=> [MS] Update batch sharing in WorkspaceSharingModal

client/src/views/workspaces/WorkspaceHistoryPage.vue
=> [MS] Update workspace history page when route changes

libparsec/src/lib.rs
No longer truncate the file on open, so we won't lose previous session's logs
=> feat(libparsec): Append log to logfile

libparsec/crates/client/src/monitors/workspace_outbound_sync.rs
=> [Fixup PR 9722] Fix event listener panic in workspace outbound sync

libparsec/crates/client/src/monitors/workspace_inbound_sync.rs, libparsec/crates/client/src/monitors/workspace_outbound_sync.rs, libparsec/crates/client/src/workspace/store/resolve_path.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/tests/unit/client/with_monitors.rs, libparsec/crates/client/tests/unit/workspace/folder_transactions.rs, libparsec/crates/client/tests/unit/workspace/retrieve_path_from_id.rs
PR #9741 did not synchronize previously confined entries that are moved outside of their confinement, for instance:
- Consider a confined file: `test.tmp/a/b/file.txt`
- The `b` directory is moved to `/`
- Note that the confinement point `test.tmp` hasn't changed (it sill has one child, `a`)
- Note that the confined entry hasn't changed (only `b` has been reparented)
- That means that nothing will trigger an event to attempt to synchronize `file.txt`
This PR fixes this by using all the entries after the confinement point to detect potential new synchronization.
=> Use all the entries after the confinement point to detect previously confined entries to synchronize

libparsec/crates/client/src/monitors/workspace_inbound_sync.rs, libparsec/crates/client/src/monitors/workspace_outbound_sync.rs, libparsec/crates/platform_async/src/lib.rs, libparsec/crates/platform_async/src/native/mod.rs, libparsec/crates/platform_async/src/web/mod.rs, libparsec/crates/platform_async/tests/unit/mod.rs, libparsec/crates/platform_async/tests/unit/yield_now.rs
backport of https://github.com/Scille/parsec-cloud/pull/9762 on `release/3.3`
=> Backport fix yield in inbound outbound monitors

client/electron/src/setup.ts, newsfragments/9674.bugfix.rst
Closes #9674 
Used 1280x720 as the default as it's a 16/9 resolution (most common ratio and will work with 16/10). It's small enough that the app should fit on most screens that are not 20 years old.
=> [MS] Sets minimal window size for electron

.github/workflows/when-pr-targeting-releases-branch-is-closed.yml
This is a workaround the limitation that github only close linked issues
when the PR target the main branch.
=> Add workflow to close issue linked to PR that target a release branches

.github/workflows/docker-server.yml, .github/workflows/docker-testbed.yml
The action `docker/metadata-action` set some labels by default. But their was some issue:
- Our license (BUSL-1.1) is not correctly detected by the action
internally, it use the GitHub API to retreive that info, and GitHub does not detect the BUSL-1.1 licenses.
- The Title was the repo name (`parsec-cloud`), I've changed that to be more descriptive.
- For the server image, I've added the documentation URL.
- Overwrite the version label with the full version (instead of `{MAJOR}.{minor}.{patch}`)
Closes #9826
=> feat(docker): Set additional labels

client/electron/snap/snapcraft.yaml, docs/development/README.md, misc/version_updater.py, server/packaging/server/in-docker-build.sh, server/packaging/testbed-server/in-docker-build.sh
Installing rustup without a specific toolchain was failing when using `cargo` directly:
```shell
$ cargo --version
error: toolchain '1.81.0-x86_64-unknown-linux-gnu' is not installed
help: run `rustup toolchain install 1.81.0-x86_64-unknown-linux-gnu` to install it
```
This is likely due to `rustup-1.28` that no longer automatically install the active toolchain.
=> fix(build): Install rust with toolchain

misc/releaser.py
=> Fix `misc/releaser.py` handling of `--version` when passing the current version

Cargo.toml
We use `data-encoding` crate instead for this
=> Remove explicit dependency on base64 & base32 crates from `Cargo.toml`

client/src/components/client-area/OrderTrackingProgress.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/types.ts, client/src/services/translation.ts, client/src/views/client-area/ClientAreaPage.vue, newsfragments/9111.feature.rst
Added page for tracking order (Custom order).
closes #7966 
closes #9242
=> [MS] Order tracking client area

libparsec/crates/types/src/id.rs
close #6827
No longer meaningful since Parsec v3
=> Remove mention of legacy id format for OrganizationID

client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/mockApi.ts, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/contracts/ContractsPage.vue, client/src/views/client-area/invoices/CustomOrderInvoicesPage.vue, client/src/views/client-area/payment-methods/PaymentMethodsPage.vue, client/src/views/client-area/statistics/CustomOrderStatisticsPage.vue, client/src/views/client-area/statistics/StatisticsPage.vue, client/tests/e2e/helpers/bms.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/app_update.spec.ts, client/tests/e2e/specs/client_area_custom_order.spec.ts, client/tests/e2e/specs/client_area_custom_order_contract.spec.ts, client/tests/e2e/specs/client_area_custom_order_invoices.spec.ts, client/tests/e2e/specs/client_area_custom_order_statistics.spec.ts
Closes #9859 
Includes a few things: automatically opens the devtools if launching Playwright in debug mode, adds mock in Playwright for invoices, refactored the customer area to avoid multiple requests to listOrganizations, handle custom order with multiple orgs, updated the listCustomOrderInvoices API, added simple tests for custom order invoices.
=> [MS] Custom order multi org

client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/views/files/FoldersPage.vue, newsfragments/8627.feature.rst
=> [MS] Scroll selected element into view

Cargo.lock, Cargo.toml
This fix the warning about `humantime` unmaintained
=> feat(rust-deps): Update env-logger to 0.11.7

Cargo.lock, Cargo.toml, libparsec/crates/platform_storage/src/native/workspace.rs
Bump `sqlx` from `0.7.2` to `0.8.3`
Bump `libsqlite3-sys` from `0.26.0` to `0.30.1`
The `fetch_many` function is deprecated. It was intended for executing a single query string containing multiple SQL statements while still using bind parameters. See: https://github.com/launchbadge/sqlx/issues/3108
Since we were not using it for that, the `fetch_all` function seems to be enough.
Closes #8052
=> Bump sqlx and libsqlite3-sys

client/index.html, client/vite.config.ts
`vite` support relative base
(<https://vite.dev/guide/build#relative-base>).
This is fill our gap where we do not know in advance the how the app will be hosted.
Supersed: https://github.com/Scille/parsec-cloud/pull/9986
=> refactor(webapp): Use relative base href

server/parsec/asgi/__init__.py, server/parsec/cli/run.py
When user wants to create an organization on trial for another domain, OPTIONS request have 405 result status code.
This is because CORS is not explicitly enable.
=> add fastapi CORSMiddleware to allow CORS

libparsec/src/lib.rs
=> Fix log messages not appended in libparsec.log

.github/workflows/releaser.yml
We were using `github.ref` instead of `github.ref_name` to set the value of `tag_name` causing invalid download link when generating the release note.
Both variable hold similar values (`refs/tags/v3.x.x` vs `v3.x.x` respectively) but we want the latter.
=> fix(releaser): Using `github.ref` instead of `github.ref_name`

.github/workflows/package-client.yml, client/src/router/types.ts, client/vite.config.ts
`vue-router` does not support relative `BASE_URL` so we to use an absolute URL.
=> fix(webapp): Configure BASE_URL to `/client`

server/parsec/cli/run.py
Type `list[str]` was not good, type into click is item type not global value type.
=> fix --cors-allow-origins server cli option

client/tests/e2e/helpers/testbed.ts
The message displayed `[Object object]` which is not helpful.
=> test(playwright): Fix error message on testeb init error

.github/workflows/cspell.yml
Removed by mistake in https://github.com/Scille/parsec-cloud/pull/10091/files#diff-b5bea6479fd108441c7fc433db75bdd293b651be540c17849a44ed9d98d1c742
=> Restore cspell-action option removed by mistake

docs/rfcs/1013-parsec-account.md
Parsec Account is a new service that would allow user to store devices on a remote server.
This would be used to simplify enrolling/recovering new end devices (computer, phones, web browsers)
=> docs(rfc): Add RFC about parsec-account

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/common.py, bindings/generator/api/events.py, bindings/web/src/meths.rs, client/src/parsec/login.ts, client/src/parsec/types.ts, client/src/plugins/libparsec/definitions.ts, client/src/services/eventDistributor.ts, libparsec/crates/client/src/event_bus.rs, libparsec/crates/client/src/monitors/connection.rs, libparsec/crates/client_connection/README.md, libparsec/crates/client_connection/src/error.rs, libparsec/crates/client_connection/src/lib.rs, libparsec/crates/client_connection/tests/unit/anonymous.rs, libparsec/crates/client_connection/tests/unit/authenticated.rs, libparsec/crates/client_connection/tests/unit/invited.rs, libparsec/src/events.rs
This PR splits `EventIncompatibleServer` into more specific events depending on the concrete `ConnectionError`.
- Added: 
- `EventOrganizationNotFound`
- `EventInvitationAlreadyUsedOrDeleted`
- `EventFrozenSelfUser`
- `EventClientErrorResponse(error_type)`
- `EventServerInvalidResponseStatus(status_code)`
- `EventServerInvalidResponseContent(decode_error)`
- Changed:
- `EventIncompatibleServer(api_version, supported_api_versions)` now includes version info instead of a `detail` string.
- Removed (see #10092):
- `ConnectionError::WrongApiVersion`
- `ConnectionError::InvalidSSEEventID`
Other changes in this PR:
- Added `README.md` for the `client_connection` crate
- Improve `ConnectionError` messages and comments
- Re-generated bindings
Closes #9996 
Closes #10092
=> Split events related to connection errors

.github/workflows/docker-testbed.yml
The workflow `build-docker-tesbed` is trigger on change on `testbed-server/` folder.
When we update the version of the used testbed accross the repo, we modify a `README.md` file contain in the said folder triggering a new workflow run.
To ignore the `README.md`, we use a negative match pattern
>  The order that you define paths patterns matters:
>
>  - A matching negative pattern (prefixed with !) after a positive match will exclude the path.
>  - A matching positive pattern after a negative match will include the path again.
>
> [`on.<push|pull_request|pull_request_target>.<paths|paths-ignore>`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
=> ci(build-testbed): Ignore `.md` file change

.github/workflows/package-desktop.yml, .github/workflows/package-webapp.yml, .github/workflows/releaser.yml, misc/version_updater.py
Separate the webapp build from desktop one because they do not share the same input and require different trigger on `pull_request`.
=> ci(package): Split `package-client` workflow

docs/rfcs/1013-parsec-account.md, libparsec/crates/client_connection/src/authenticated_account_cmds.rs, libparsec/crates/client_connection/tests/unit/authenticated_account.rs, libparsec/crates/crypto/src/rustcrypto/secret.rs, libparsec/crates/crypto/src/sodiumoxide/secret.rs
Currently the signature is generated with a random key each time until we have access to a stable secret.
It also use an hardcoded email since we do not have an account struct to store the user information.
Related to #10076
=> feat(client_connection): Generate HMAC signature for authentication

libparsec/crates/client_connection/src/authenticated_account_cmds.rs, server/parsec/asgi/rpc.py, server/parsec/components/auth.py, server/parsec/components/memory/auth.py, server/tests/common/client.py
Currently we do not have access to the user hmac key, so we need to send it alongside the request until it can be provided by the internal state.
Close #10171
=> feat(server): Valide account authentication token

docs/development/README.md, server/README.md
- Replace deprecated `poetry shell`
- Complete test section with more examples and options
- Move instructions to server/README.md
=> Fix instructions for server development

.github/filters/ci.yml, deny.toml
A new advisory was created for the now `unmaitained` crate `registry` that
manipulate Windows registry.
We depend on that crate from `winfsp-wrs-sys`, so until
Scille/winfsp_wrs#36 is fixed we have to
ignore it.
=> chore(cargo-deny): Ignore RUSTSEC-2025-0026

.cspell/cspell.config.yml, client/electron/README.md, client/electron/assets/parsec.desktop, client/electron/package.js, client/electron/package.json, client/electron/snap/snapcraft.yaml
Related to #8422
Changes in this PR:
- Added extra info about app in `snapcraft.yaml` and `package.json`.
- Added instructions on how to build snap locally
- Moved desktop entry to a specific file in the `assets` directory. The following keys were changed:
- Added `SingleMainWindow=true` so that the desktop manager does not include a "New Window" action
- Added `StartupNotify=false` to be explicit that this is not managed
- Added `StartupWMClass=parsec` to be explicit about the wmclass
- Fixed `Categories` to use `;` separator
- Added `Keywords` to make it easier to find the application
- Added `GenericName` and improve `Comment`
See: https://specifications.freedesktop.org/desktop-entry-spec/latest/recognized-keys.html
=> Fix minor issues with app desktop entry

.github/workflows/ci-rust.yml, Cargo.lock, Cargo.toml, deny.toml, libparsec/crates/platform_device_loader/Cargo.toml, libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/platform_device_loader/src/web/error.rs, libparsec/crates/platform_device_loader/src/web/internal.rs, libparsec/crates/platform_device_loader/src/web/mod.rs, libparsec/crates/platform_device_loader/src/web/wrapper.rs, libparsec/crates/platform_device_loader/tests/units/archive.rs, libparsec/crates/platform_device_loader/tests/units/list.rs, libparsec/crates/platform_device_loader/tests/units/load.rs, libparsec/crates/platform_device_loader/tests/units/mod.rs, libparsec/crates/platform_device_loader/tests/units/remove.rs, libparsec/crates/platform_device_loader/tests/units/save_list.rs, libparsec/crates/platform_device_loader/tests/units/save_load.rs, libparsec/crates/platform_device_loader/tests/units/update_device_change_authentication.rs, libparsec/crates/platform_device_loader/tests/units/utils.rs, libparsec/crates/tests_fixtures/src/tmp_path.rs
Since `libparsec` is run from a shared worker, we no longer have access to `localStorage` via the `window` property.
This commit refactor the web impl to use `StorageManager` over `LocalStorage` that is available in both browser and shared worker.
Another fix would have been to store the device in IndexedDB.
=> refactor(device-loader): Use `StorageManager` over `LocalStorage` on web

client/tests/e2e/specs/file_viewers.spec.ts
On Chrome137, the `duration` property of the media changes for some reason. This should be a little more flexible.
=> [MS] Fixed audio e2e test following chrome update

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/electron/src/setup.ts, client/src/components/client-area/invoices/InvoicesListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/environment.ts, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/contracts/ContractsPage.vue, client/src/views/client-area/dashboard/DashboardPage.vue, client/src/views/organizations/TOSModal.vue, client/src/views/viewers/DocumentViewer.vue, client/src/views/viewers/FileViewer.vue, newsfragments/10466.feature.rst
When we wanted to open a URL, we has to push the URL inside an array so that electron could check is this URL was authorized or not before opening it. Initially, it was so that only URLs that we know (parsec.cloud, github.com/Scille/parsec-cloud, ...) could be opened.
Since then, some URLs that we can't control have appeared (invoices in customer area, TOS, or links in documents that a user may want to open). This PR removes the whole authorization system, only checking for `http`, `https` and `parsec3` protocol to avoid some potential weird cases with `file://` or `mailto://`.
It's also a bit better at opening links inside a docx (skipping anchors) and ask a question before opening a link in viewers to add a bit of security (at least it's not our fault if the user clicked a dangerous …
=> [MS] Re-factored how url are opened

libparsec/crates/crypto/src/rustcrypto/key_derivation.rs, libparsec/crates/crypto/src/rustcrypto/private.rs, libparsec/crates/crypto/src/rustcrypto/secret.rs, libparsec/crates/crypto/src/rustcrypto/sequester.rs, libparsec/crates/crypto/src/rustcrypto/sign.rs
To not have to think if `thread_rng` can be used as a CSRNG
Closes #10501
=> refactor(crypto): Use `OsRng` over `thread_rng`

Cargo.lock, Cargo.toml, libparsec/crates/client_connection/Cargo.toml
The dependency was not used by the crate
=> chore(lib-client-conn): Remove deps `reqwest-eventsource`

Cargo.lock, bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/__init__.py, bindings/generator/api/account.py, bindings/generator/api/common.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/Cargo.toml, libparsec/crates/account/src/lib.rs, libparsec/crates/client_connection/src/anonymous_account_cmds.rs, libparsec/crates/client_connection/tests/unit/anonymous_account.rs, libparsec/crates/protocol/schema/anonymous_account_cmds/account_create_proceed.json5, libparsec/crates/protocol/schema/anonymous_account_cmds/account_create_send_validation_email.json5, libparsec/crates/protocol/tests/anonymous_account_cmds/v5/account_create_proceed.rs, libparsec/crates/protocol/tests/anonymous_account_cmds/v5/account_create_send_validation_email.rs, libparsec/crates/serialization_format/src/protocol_python_bindings.rs, libparsec/crates/types/src/account.rs, libparsec/src/account.rs, libparsec/src/lib.rs, server/parsec/_parsec_pyi/protocol/anonymous_account_cmds/v5/account_create_proceed.pyi, server/parsec/_parsec_pyi/protocol/anonymous_account_cmds/v5/account_create_send_validation_email.pyi, server/parsec/components/account.py, server/tests/api_v5/anonymous_account/test_account_create_proceed.py, server/tests/common/rpc.py
Fix #10388 
- account_send_email_validation_token
- account_create_with_password_proceed
=> [Account] js bindings for account creation

client/src/parsec/environment.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/home_page.spec.ts
My initial thought was to test
- Warning on Safari
- Warning on small display
- Warning if indexedDB is not available
Sadly, I cannot add a test for the small display because we disable it when using the testbed to not be too annoying when developping, and I don't want to have specific code in the app just for one specific test.
For indexedDB, I haven't found a way to disable it in Playwright: no permissions, and it's used in the web worker so I can't mock `window.indexedDB` or something like that.
We end up we a simple small test to check that the warning is properly displayed on Safari.
=> [MS] Tests warning appearing on Safari

.github/workflows/ci-web.yml, client/playwright.config.ts
More stable CI duration since we just download the container with the required dependendies already installed.
Closes #9063
=> ci(web): Use docker image to run playwright tests

.github/workflows/ci-web.yml
Make the job also depends on `test-web-app` success and run if the workflow is not cancelled.
=> ci(web): Rework run condition on `playwright-reports` job

client/src/common/organization.ts, client/src/components/organizations/OrganizationCard.vue, client/src/parsec/organization.ts, client/src/parsec/types.ts, client/src/services/storageManager.ts, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/menu/MainMenu.vue, client/tests/e2e/helpers/externalWebsites.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/index.ts, client/tests/e2e/specs/about_modal.spec.ts, client/tests/e2e/specs/create_organization_saas.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts, client/tests/e2e/specs/trial_organization.spec.ts
Closes #8405 
The detection of a trial server is done via an environment variable, so if you have devices, it's possible to edit `.env.development.local` to change the trial server (for example, `PARSEC_APP_TRIAL_SERVERS="localhost:6770?no_ssl=true;localhost:6770"` will detect the local server as a trial server).
We can also modify the function that returns the creation date. This bypasses the bindings, so it's not a complete test, but it lets you see how the GUI reacts.
```
diff --git a/client/src/parsec/organization.ts b/client/src/parsec/organization.ts
index ac79f5cf1..0de288128 100644
--- a/client/src/parsec/organization.ts
+++ b/client/src/parsec/organization.ts
@@ -169,7 +169,7 @@ export async function getOrganizationCreationDate(
}
const result = await …
```
=> [MS] Use the bindings to get the org creation date

.github/scripts/check_newsfragments.py, .github/workflows/ci.yml
During certain run of `check_newsfragments` in the CI, we had some `rate limited exceeded`. We get those errors because we make anonymous request, adding `Authorization` header to each HTTP request with a valid token make them authenticated with a much greater rate limit.
I've also added `X-GitHub-Api-Version` header to make the script more robust in case of API version bump on GitHub side.
=> ci(q&a): Chech newsfragment now take GH token

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/account.ts, client/src/parsec/login.ts, client/src/parsec/types.ts, client/src/views/home/HomePage.vue, client/src/views/organizations/creation/CreateOrganizationCustomServer.vue, client/src/views/organizations/creation/CreateOrganizationModal.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/src/views/organizations/creation/OrganizationSummaryPage.vue, client/tests/e2e/specs/account_create_org.spec.ts, client/tests/e2e/specs/account_invitation.spec.ts, client/tests/e2e/specs/account_login.spec.ts, client/tests/e2e/specs/create_organization_custom.spec.ts, client/tests/e2e/specs/create_organization_saas.spec.ts, client/tests/e2e/specs/create_organization_trial.spec.ts
Closes #10851
Quite a nightmare to test. Be mindful of server with `127.0.0.1` and server with `localhost`, those are not considered the same (no DNS resolution or anything). Be also mindful of the port.
- testbed server === account server, log into a device -> should ask if you want to register the device, yes. Logout, log back in, shouldn't need a password.
- testbed server !== account server, log into a device -> nothing
- custom server === account server, without testbed, create an org, then electron, log in to parsec account, the device should be here and accessible.
- create an org with custom server (=== account server), should skip name/email and auth. Should log in automatically while logged into Parsec Account.
Technically the last one is also true with the saas, but it's next …
=> [MS] Implemented logic for device auth/registration for parsec account

server/parsec/components/postgresql/user_update_user.py
The CTE `updated_common_topic` was used twice in the main query
=> Fix wrong SQL query in user_update

server/tests/administration/test_create_organization.py, server/tests/administration/test_create_sequester_service.py, server/tests/administration/test_freeze_user.py, server/tests/administration/test_get_organization.py, server/tests/administration/test_list_sequester_services.py, server/tests/administration/test_list_users.py, server/tests/administration/test_patch_organization.py, server/tests/administration/test_revoke_sequester_service.py, server/tests/administration/test_stats.py, server/tests/administration/test_update_sequester_service_config.py, server/tests/common/__init__.py, server/tests/common/administration.py
- Add fixture to perform unauthenticated tests similar to RPC API tests
- Add fixture to provide an authenticated client for the administration APIs
=> test(server): Add fixture for administration route

client/src/components/files/explorer/FileCard.vue, client/src/components/files/explorer/FileGridDisplay.vue, client/src/components/files/explorer/FileListDisplay.vue, client/src/components/files/explorer/FileListItem.vue, client/src/components/header/SmallDisplayHeaderTitle.vue, client/src/views/files/FoldersPage.vue, client/tests/component/specs/testFileCard.spec.ts, client/tests/component/specs/testFileListItem.spec.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/file_viewers_document.spec.ts
Here's how files and folders behave when clicked:
- Click on the item: Select item (check mark active)
- Click on folder name: Open folder
- Click on file name: Preview (viewer)
I've harmonized the interaction between `FileCard` (and thus `FileGridDisplay`) and `FileListItem` (and thus `FileListDisplay`).
https://github.com/user-attachments/assets/5a9e87f4-0eaf-4f0a-8ba5-599fd1c573e1
closes #10820
=> [MS] Manage click behavior for file and folder items

.github/workflows/ci-python.yml
Note that the `ubuntu-22.04` runner already provides the expected PostgreSQL
version (14).
To bump PostgreSQL version, use `misc/version.toml` & `misc/version_updater.py`
Fix #10973
=> Enable PostgreSQL install in CI

client/src/views/organizations/creation/OrganizationSummaryPage.vue
=> [MS] Fix organization summary label width

client/src/components/settings/SettingsList.vue
- Border radius wasn't apply on setting lists (Electron)
- Missing class on a setting list item (missing padding)
=> [MS] Fix settings list UI bug

client/src/services/cryptpad.ts, client/tests/unit/specs/testCryptpad.spec.ts
While investigated CSV file issue on CryptPad, I found out `.csv` cannot be opened as spreadsheet file but code file only.
⚠️ As editing is not displayed properly, we have decided to suppress editing for CSV files.
closes #10876
=> [MS] Editing `.csv` files as code files

libparsec/crates/protocol/src/version.rs, newsfragments/11017.bugfix.rst, server/parsec/asgi/rpc.py, server/parsec/client_context.py, server/parsec/components/invite.py, server/tests/api_v5/authenticated/test_invite_greeter_step.py, server/tests/api_v5/invited/test_invite_claimer_step.py
=> Prevent client using API < 5.2 from using `invite_(claimer|greeter)_step` commands

.github/filters/ci.yml
- `ci-web` is now only triggered on non platform crates changes or when the web/shared part of a platform crates changes
- Rust wasm test only triggered when web/shared part of platform crates are edited
- `ci-python` only run when non platform crates are edited
=> refactor(CI): Change rust filter

Cargo.lock, Cargo.toml, libparsec/crates/platform_pki/Cargo.toml, libparsec/crates/platform_pki/examples/decrypt_message.rs, libparsec/crates/platform_pki/examples/encrypt_message.rs, libparsec/crates/platform_pki/examples/sign_message.rs, libparsec/crates/platform_pki/examples/utils/mod.rs, libparsec/crates/platform_pki/examples/verify_message.rs, libparsec/crates/platform_pki/examples/windows_encrypt_roundtrip.ps1, libparsec/crates/platform_pki/examples/windows_signature_roundtrip.ps1, libparsec/crates/platform_pki/src/errors.rs, libparsec/crates/platform_pki/src/lib.rs, libparsec/crates/platform_pki/src/shared.rs, libparsec/crates/platform_pki/src/windows/mod.rs
- Use `rustls` crates to provide the parsing of a DER/PEM certificate
- Add example to verify a generated signature (will work on allow platforms, but on unix, we are currently not integrated with a cert store)
=> feat(pki): Allow to verify signature using a certificate

server/poetry.lock, server/pyproject.toml
It seems that optional groups are not yet fully supported for `[dependency-groups]`. They are supported by Poetry but dependabot parser fails (see https://github.com/Scille/parsec-cloud/actions/runs/18305430818)
=> Fix server/pyproject.toml syntax
