Scille/parsec-cloud

libparsec/crates/client/tests/unit/certif/mod.rs, libparsec/crates/client/tests/unit/certif/rename_realm.rs
=> Add tests for CertifOps: rename_realm

client/tests/e2e/specs/test_folders_page.ts
=> [MS] Fixed test folder page

client/src/components/notifications/NotificationItem.vue, client/src/components/notifications/WorkspaceRoleChangedNotification.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/notifications.scss, client/src/theme/global.scss
- Using `i18n` to add specific bold text
- Example created only with `WorkspaceRoleChangedNotification`
- Transfer global notification style on `notifications.scss`
closes #6236
=> [MS] Bold text on notification message

client/src/theme/components/modals.scss
=> [MS] Fixed modal height

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/bootstrap_organization.rs, cli/src/cancel_invitation.rs, cli/src/claim_invitation.rs, cli/src/create_organization.rs, cli/src/create_workspace.rs, cli/src/export_recovery_device.rs, cli/src/greet_invitation.rs, cli/src/import_recovery_device.rs, cli/src/invite_device.rs, cli/src/invite_user.rs, cli/src/list_invitations.rs, cli/src/share_workspace.rs, cli/src/tests.rs, cli/src/utils.rs
=> Change `spinner` dependency

client/src/components/core/ms-toggle/MsGridListToggle.vue
=> [MS] Update `GridListToggle` style

client/src/components/users/InvitationListItem.vue, client/src/components/users/UserListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/users/InvitationsPage.vue, client/tests/e2e/specs/test_invitations_page.ts
New :
- Update table row width
- Add counter 
closes #6302
=> [MS] Update invitation InvitationsPage

.cspell/custom-words.txt, client/src/services/storageManager.ts, client/src/views/files/FoldersPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/test_folders_page.ts, client/tests/e2e/support/index.ts
=> [MS] Saves/loads grid/list mode for folders and workspaces

client/src/components/core/ms-action-bar/MsActionBar.vue, client/src/theme/components/contextual-menu.scss, client/tests/e2e/specs/test_folders_page.ts
=> [MS] Update action bar height

libparsec/crates/client/src/certif/realm_keys_bundle.rs, libparsec/crates/client/tests/unit/certif/rename_realm.rs, libparsec/crates/client/tests/unit/certif/validate_workspace_manifest.rs, libparsec/crates/client/tests/unit/client/ensure_workspaces_bootstrapped.rs, libparsec/crates/client/tests/unit/client/rename_workspace.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_folder.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_root.rs, libparsec/crates/client/tests/unit/workspace/outbound_sync_folder.rs, libparsec/crates/client/tests/unit/workspace/outbound_sync_root.rs, libparsec/crates/protocol/schema/authenticated_cmds/realm_get_keys_bundle.json5, libparsec/crates/protocol/tests/authenticated_cmds/v4/realm_get_keys_bundle.rs
=> Fix: `realm_get_keys_bundle`

libparsec/crates/client/tests/unit/certif/validate_workspace_manifest.rs
=> Add tests certifops validate workspace manifest

libparsec/crates/client/tests/unit/certif/bootstrap_workspace.rs, libparsec/crates/client/tests/unit/certif/mod.rs
=> Add tests for CertifOps: bootstrap_workspace

client/src/components/workspaces/WorkspaceCard.vue
=> [MS] Add style on workspace item

client/src/transitions/SlideHorizontal.vue, client/src/views/home/HomePage.vue
=> fix: add container to avoid overflowing

client/src/common/device.ts, client/src/components/users/UserInformation.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/CreateOrganizationModal.vue, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/e2e/specs/test_user_join_org_modal.ts
=> [MS] Replaced default name for device

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/router/types.ts, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/test_folders_page.ts
=> [MS] Add button to create Workspace on sidebar

client/src/components/core/ms-input/MsInput.vue, client/src/components/core/ms-input/MsPasswordInput.vue, client/src/components/core/ms-modal/MsModal.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/inputs.scss, client/src/theme/components/modals.scss, client/src/views/home/HomePage.vue, client/src/views/home/LoginPage.vue, client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/e2e/specs/test_home_page.ts, client/tests/e2e/specs/test_settings_modal.ts
- Outline is visible without adding padding
- Toast error message changed to input helper text
closes #6149, closes #6460
=> [MS] Update input visual issues (password error and outline on focus)

client/package.json, client/src/parsec/user.ts, client/src/views/home/HomePage.vue, client/src/views/home/LoginPage.vue
#6485 should make this a bit better but in the meantime, this should be enough.
I've also included a commit related to the linter, didn't want to create a new PR.
=> [MS] Get user info

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/platform_device_loader/src/web/mod.rs, libparsec/src/client.rs
=> Binding: Add `change_access`

libparsec/crates/client/src/workspace/store.rs, libparsec/crates/platform_storage/src/native/certificates.rs, libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/testbed.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs, libparsec/crates/platform_storage/tests/unit/workspace.rs
=> Implement cache limit in block storage

client/src/views/files/FoldersPage.vue
Handle giving the FoldersPage a path to a file instead of a folder. It will access the parent folder and select the file.
=> [MS] Handle path to a file in FoldersPage

client/src/components/notifications/AllImportedElementsNotification.vue, client/src/components/notifications/MultipleUsersJoinPopover.vue, client/src/components/notifications/MultipleUsersJoinWorkspaceNotification.vue, client/src/components/notifications/NewDeviceNotification.vue, client/src/components/notifications/UserJoinWorkspaceNotification.vue, client/src/components/notifications/UserSharedDocumentNotification.vue, client/src/components/notifications/WorkspaceAccessNotification.vue, client/src/components/notifications/index.ts, client/src/components/users/UserAvatarName.vue, client/src/components/workspaces/WorkspaceTagRole.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/types.ts, client/src/services/informationManager.ts, client/src/theme/components/notifications.scss, client/src/views/header/NotificationCenterPopover.vue
Adding notification:
- Access to a workspace
- Changing role of user
- A user join a workspace
- Multiple users join a workspace
- Remove organization access
- All file imported
- New device added
This PR doesn't include the notification error.
closes #6464
=> [MS] Basic Notifications

client/src/components/header/InvitationsButton.vue, client/src/components/users/InvitationPopoverItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/list.scss, client/src/theme/components/popovers.scss, client/src/views/header/HeaderPage.vue, client/src/views/users/InvitationsListPopover.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/component/specs/testInvitationCard.spec.ts, client/tests/component/specs/testInvitationListItem.spec.ts, client/tests/e2e/specs/test_greet_user_modal.ts, client/tests/e2e/specs/test_invitations_page.ts
Add a button + popover in the header to manage invitations.
=> [MS] Added invitation management in header

libparsec/crates/client/src/certif/add.rs, libparsec/crates/client/src/certif/realm_share.rs, libparsec/crates/client/tests/unit/certif/add_realm_role_certificate.rs, libparsec/crates/client/tests/unit/certif/bootstrap_workspace.rs, libparsec/crates/client/tests/unit/client/ensure_workspaces_bootstrapped.rs, libparsec/crates/client/tests/unit/user/sync.rs, libparsec/crates/platform_storage/tests/unit/certificates.rs, libparsec/crates/testbed/src/template/events.rs, libparsec/crates/types/schema/certif/realm_role_certificate.json5, libparsec/crates/types/src/certif.rs, libparsec/crates/types/tests/certif.rs, server/parsec/_parsec_pyi/certif.pyi, server/src/data/certif.rs
=> Realm role certif author mandatory

libparsec/crates/client/tests/unit/certif/encrypt_for_realm.rs, libparsec/crates/client/tests/unit/certif/mod.rs
=> Add tests for CertifOps: encrypt_for_realm

server/tests/api_v4/authenticated/test_block_create.py
=> Add missing tests for block_create

.pre-commit-config.yaml, .yamllint.yml, libparsec/crates/client/src/certif/mod.rs, libparsec/crates/client/tests/unit/certif/bootstrap_workspace.rs, libparsec/crates/client/tests/unit/certif/decrypt_current_realm_name.rs, libparsec/crates/client/tests/unit/certif/encrypt_for_realm.rs, libparsec/crates/client/tests/unit/certif/encrypt_for_sequester_services.rs, libparsec/crates/client/tests/unit/certif/ensure_realm_created.rs, libparsec/crates/client/tests/unit/certif/get_current_self_profile.rs, libparsec/crates/client/tests/unit/certif/get_current_self_realm_role.rs, libparsec/crates/client/tests/unit/certif/get_current_self_realms_role.rs, libparsec/crates/client/tests/unit/certif/get_user_device.rs, libparsec/crates/client/tests/unit/certif/list_user_devices.rs, libparsec/crates/client/tests/unit/certif/list_users.rs, libparsec/crates/client/tests/unit/certif/list_workspace_users.rs, libparsec/crates/client/tests/unit/certif/rename_realm.rs, libparsec/crates/client/tests/unit/certif/validate_child_manifest.rs, libparsec/crates/client/tests/unit/certif/validate_workspace_manifest.rs, libparsec/crates/client/tests/unit/client/create_workspace.rs, libparsec/crates/client/tests/unit/workspace/file_operations.rs, libparsec/crates/client/tests/unit/workspace/file_operations_stateful.rs, libparsec/crates/client_connection/src/lib.rs, libparsec/crates/platform_storage/tests/unit/certificates.rs, libparsec/crates/protocol/tests/authenticated_cmds/v4/certificate_get.rs, libparsec/crates/protocol/tests/authenticated_cmds/v4/vlob_read_batch.rs, libparsec/crates/types/tests/unit/fs_path.rs
Also add `clippy-fix` to auto fix
=> [fix #6578]: Re-enable `cargo clippy` in pre-commit

client/src/views/home/OrganizationListPage.vue
=> [MS] Updated font size `OrganizationCard`

client/src/theme/components/popovers.scss, client/src/views/files/FileContextMenu.vue, client/src/views/header/ProfileHeaderPopover.vue, client/src/views/users/UserContextMenu.vue, client/src/views/workspaces/WorkspaceContextMenu.vue, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Updated popover style

libparsec/crates/client/tests/unit/certif/mod.rs, libparsec/crates/client/tests/unit/certif/share_realm.rs
=> Add tests for CertifOps: share_realm

.github/workflows/_parse_version.yml, .github/workflows/package-client.yml, .github/workflows/package-server.yml, .github/workflows/releaser.yml, misc/releaser.py
- Update `action-gh-release`
Require #6600
=> [fix #6597]: Add `package-client` to `releaser` workflow

client/src/components/header/InvitationsButton.vue, client/src/components/users/UserAvatarName.vue, client/src/views/header/HeaderPage.vue, client/src/views/header/ProfileHeader.vue
Small changes in topbar Header.
closes #6308
=> [MS] Update Header

.cspell/custom-ext.txt, .github/workflows/ci-rust.yml, Cargo.lock, Cargo.toml, bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/generator/api/invite.py, bindings/web/src/meths.rs, cli/src/utils.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/invite/claimer.rs, libparsec/crates/client/src/invite/organization.rs, libparsec/crates/platform_device_loader/Cargo.toml, libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/platform_device_loader/src/testbed.rs, libparsec/crates/platform_device_loader/tests/change_auth.rs, libparsec/crates/platform_device_loader/tests/save_load.rs, libparsec/crates/types/schema/local_device/device_file_keyring.json5, libparsec/crates/types/src/local_device.rs, libparsec/crates/types/src/local_device_file.rs, libparsec/crates/types/tests/local_device_file.rs, libparsec/src/client.rs, libparsec/src/invite.rs, server/src/enumerate.rs, server/src/lib.rs
closes #6545
Add keyring
Add serde tests for keyring
Add tests for keyring and password without testbed
Add keyring binding
=> Add `keyring`

client/src/components/users/UserAvatarName.vue, client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/components/users/types.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/list.scss, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/tests/component/specs/testUserCard.spec.ts, client/tests/e2e/specs/test_users_page.ts
=> [MS] Update `UserCard`

server/tests/api_v4/authenticated/test_user_revoke.py
=> Add tests for user_revoke

client/src/views/users/UsersPage.vue
Remember the state of the display in the users paghe (grid/list).
=> [MS] Remember display state of users page

server/tests/api_v4/authenticated/test_user_update.py
=> Add tests for user_update

client/src/theme/global.scss, client/src/views/users/UsersPage.vue
=> [MS] Fixed user grid view

client/src/components/core/ms-input/MsChoosePasswordInput.vue, client/src/components/core/ms-input/MsInput.vue, client/src/components/core/ms-input/MsPasswordInput.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/login.ts, client/src/services/hotkeyManager.ts, client/src/views/users/MyContactDetailsPage.vue, client/src/views/users/UpdatePasswordModal.vue, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/e2e/specs/test_import_recovery_device_page.ts, client/tests/e2e/specs/test_my_contact_details_page.ts
Changed the page view and added a modal with 2 steps instead of single page.
closes #6520
closes #6303
=> [MS] Added `ChangePasswordModal`

Cargo.lock, libparsec/crates/platform_device_loader/Cargo.toml, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/types/schema/local_device/device_file_keyring.json5, libparsec/crates/types/src/local_device.rs, libparsec/crates/types/src/local_device_file.rs, libparsec/crates/types/tests/local_device_file.rs
=> Improve keyring strategy

server/parsec/components/memory/vlob.py, server/parsec/components/vlob.py, server/tests/api_v4/authenticated/test_vlob_create.py, server/tests/api_v4/authenticated/test_vlob_poll_changes.py, server/tests/api_v4/authenticated/test_vlob_read_batch.py, server/tests/api_v4/authenticated/test_vlob_read_versions.py, server/tests/api_v4/authenticated/test_vlob_update.py
Also, fix bug in vlob create/update: the condition for `RequireGreaterTimestamp` did not trigger on equal timestamps (it was reversed).
closes #6629
closes #6630
closes #6631
closes #6632
closes #6633
=> Add tests for vlob_* cmds

.github/dependabot.yml
=> Update pip group patterns to group `pytest` and `pytest-*` together

client/src/components/users/UserFilter.vue, client/src/components/users/UserFilterPopover.vue, client/src/components/users/index.ts, client/src/components/users/types.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/popovers.scss, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/tests/e2e/specs/test_users_page.ts
=> [MS] UsersPage filtering

client/src/theme/components/tags.scss, client/src/views/sidebar-menu/SidebarMenuPage.vue
=> [MS] Update sidebar spaces

client/src/components/devices/DeviceCard.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/devices/GreetDeviceModal.vue, client/tests/e2e/specs/test_greet_device_modal.ts
=> [MS] New device added (update style)

client/src/components/core/ms-input/MsSearchInput.vue, client/src/components/organizations/OrganizationCard.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/OrganizationListPage.vue
=> [MS] Update organization list

client/src/views/about/AboutView.vue
=> [MS] Hide update section

client/src/views/settings/SettingsView.vue, client/tests/e2e/specs/test_settings_modal.ts, client/tests/e2e/specs/test_settings_page.ts
=> [MS] Hide unused settings

client/src/components/core/ms-modal/FolderSelectionModal.vue, client/src/components/files/FileImport.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/file.ts, client/src/parsec/types.ts, client/src/router/navigation.ts, client/src/router/params.ts, client/src/router/types.ts, client/src/services/importManager.ts, client/src/views/files/FileUploadMenu.vue, client/src/views/files/FileUploadModal.vue, client/src/views/files/FoldersPage.vue, client/src/views/header/ProfileHeader.vue, client/tests/e2e/specs/test_file_upload_modal.ts, client/tests/e2e/specs/test_folders_page.ts
Closes #6533 
Fully working file import with bindings.
Had to redo some parts, fixed some bugs, add new things, but I'm satisfied with the result.
=> [MS] Working file import using bindings

client/src/views/header/ProfileHeader.vue
=> [MS] Hide the import menu when logging out

client/src/common/date.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/tests/component/specs/testFileCard.spec.ts, client/tests/component/specs/testFileListItem.spec.ts, client/tests/component/specs/testUserListItem.spec.ts, client/tests/e2e/specs/test_user_details_modal.ts, client/tests/unit/specs/testDate.spec.ts
=> [MS] Update date formatting for small durations

client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/e2e/specs/test_manage_organization.ts
=> [MS] Hide Storage in `SidebarMenu`

client/src/theme/components/popovers.scss, client/src/views/files/FileContextMenu.vue, client/src/views/files/FoldersPage.vue, client/tests/e2e/specs/test_folders_page.ts
Show only options:
- Details
- Copy link
- Delete
- Rename
- Open
closes #6661
=> [MS] Hide options file

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/file.ts, client/src/views/files/FoldersPage.vue, client/tests/e2e/specs/test_invitations_page.ts
=> [MS] Handle renaming a file when another with the same name exists

.github/workflows/publish.yml, .github/workflows/releaser.yml
=> [fix #6717] Publish pypi package on nightly build

client/src/views/users/UsersPage.vue, client/tests/e2e/specs/test_users_page.ts
=> [MS] Correctly display the user count

client/src/components/core/ms-sorter/MsSorter.vue, client/src/components/users/UserFilter.vue, client/src/components/users/UserFilterPopover.vue, client/src/components/users/UserStatusTag.vue, client/src/theme/components/contextual-menu.scss, client/src/theme/components/popovers.scss, client/src/theme/global.scss, client/src/views/users/UserContextMenu.vue
=> [MS] Added filter popover style

server/parsec/asgi/rpc.py, server/parsec/cli/testbed.py, server/parsec/components/invite.py, server/parsec/components/memory/organization.py, server/parsec/components/postgresql/organization.py, server/poetry.lock, server/pyproject.toml, server/tests/api_v4/authenticated/test_vlob_read_batch.py, server/tests/api_v4/authenticated/test_vlob_read_versions.py, server/tests/common/client.py
=> Bump pyright to 1.353

.cspell/custom-words.txt, .cspell/names.txt, client/src/views/home/CreateOrganizationModal.vue
=> [MS] Updated default server addr

client/src/components/core/ms-dropdown/MsDropdown.vue, client/src/components/core/ms-input/MsInput.vue, client/src/theme/components/inputs.scss
Small visual modifications on input and dropdown to harmonise them.
closes #6734
=> [MS] Updated input and dropdown

client/src/services/toastManager.ts, client/src/theme/components/toasts.scss
=> [MS] Add `.body` class to toast

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/organization.ts, client/src/parsec/types.ts, client/src/views/organizations/OrganizationInformationPage.vue, client/tests/e2e/specs/test_manage_organization.ts
=> [MS] Updated organization info page and query

client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/parsec/workspace.ts, client/src/views/workspaces/WorkspacesPage.vue
=> [MS] Updated workspaces info

client/src/theme/components/inputs.scss, client/src/views/home/UserJoinOrganizationModal.vue, client/tests/e2e/specs/test_user_join_org_modal.ts
=> [MS] Removed validation step for the stepper for user claim

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/e2e/specs/test_device_join_org_modal.ts, client/tests/e2e/specs/test_folders_page.ts, client/tests/e2e/specs/test_greet_device_modal.ts, client/tests/e2e/specs/test_greet_user_modal.ts, client/tests/e2e/specs/test_home_page.ts, client/tests/e2e/specs/test_import_recovery_device_page.ts, client/tests/e2e/specs/test_invitations_page.ts, client/tests/e2e/specs/test_manage_organization.ts, client/tests/e2e/specs/test_settings_modal.ts, client/tests/e2e/specs/test_settings_page.ts, client/tests/e2e/specs/test_user_join_org_modal.ts, client/tests/e2e/specs/test_workspaces_page.ts, client/tests/unit/specs/testValidators.spec.ts, client/tests/unit/specs/testWorkspaceRole.spec.ts
=> Update translation files

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/e2e/specs/test_manage_organization.ts, client/tests/e2e/specs/test_users_page.ts
- reorganize the organization management sideBarMenu
- replace addCircle by add icon
=> Improve SideBarMenu UX

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/variables/fonts.scss, client/src/views/files/FileDetailsModal.vue, client/tests/e2e/specs/test_folders_page.ts
=> [MS] Update file details modal

client/src/components/core/ms-input/MsInput.vue, client/src/views/home/CreateOrganizationModal.vue
=> [MS] Fixed organization name already exists

client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/users/UserAvatarName.vue, client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/theme/components/list.scss, client/src/views/home/OrganizationListPage.vue, client/src/views/users/UserListDisplay.vue
Update file list, user list and user grid.
<!-- Give some context about the changes
=> [MS] Update table

client/src/parsec/file.ts, client/tests/e2e/specs/test_folders_page.ts
=> [MS] Fix non-empty folder deletion

client/src/components/users/InvitationPopoverItem.vue
Remove opacity on invitation button and add ellipsis on text overflow.
=> [MS] Fix invitations style

client/src/views/files/FoldersPage.vue
=> [MS] Only display files being imported in the right workspace

client/src/views/home/OrganizationListPage.vue
=> [MS] Added icon on last edit organization

client/src/main.ts, client/src/views/files/FileContextMenu.vue, client/src/views/workspaces/WorkspaceContextMenu.vue, client/tests/e2e/specs/test_folders_page.ts, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Remove file links handling

client/src/common/validators.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json
=> [MS] Fix user info modal text and validators

client/src/components/sas-code/SasCodeChoice.vue, client/src/components/sas-code/SasCodeProvide.vue
- Added focus for keyboard navigation
- Updated global code style
=> [MS] Choose code style

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/users/MyContactDetailsPage.vue, client/tests/e2e/specs/test_create_org_modal.ts
=> [MS] Homogenize password/authentication terms in create organization & contact page

client/electron/src/setup.ts
Fix Links displaying an error if the app is already opened.
close #6823
=> fix links displaying error if app already opened

client/src/views/home/CreateOrganizationModal.vue, client/src/views/home/SummaryStep.vue
=> [MS] SummaryStep resize behaviour

client/src/components/core/ms-sorter/MsSorterPopover.vue, client/src/components/users/TagProfile.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/popovers.scss, client/tests/e2e/specs/test_users_page.ts
=> [MS] Fixed sort by style

client/src/parsec/workspace.ts
=> [MS] Activate mountpoints on Windows

client/src/components/workspaces/WorkspaceListItem.vue, client/src/components/workspaces/WorkspaceTagRole.vue, client/src/theme/components/list.scss
=> [MS] Workspace list style

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue
1. Improved error messages
2. No longer asks for confirmation when the link is invalid at the start
3. No longer displays an error message when the user cancels
4. Prevent the app from opening a link if a modal is opened
=> Multiple fix for claim links

client/electron/src/index.ts
=> [MS] Fix link handling in MacOS

client/src/views/home/HomePage.vue
=> [MS] fix HomePage animation states

client/src/components/core/ms-input/MsPasswordInput.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/components/users/types.ts, client/src/services/hotkeyManager.ts, client/src/views/files/FoldersPage.vue, client/src/views/header/HeaderPage.vue, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/test_users_page.ts
Should be easier and a bit less error prone to add a shortcut.
=> [MS] Ultimate fix for hotkeys

client/src/services/toastManager.ts, client/src/theme/components/toasts.scss, client/tests/e2e/specs/test_create_workspace_modal.ts, client/tests/e2e/specs/test_greet_device_modal.ts, client/tests/e2e/specs/test_greet_user_modal.ts, client/tests/e2e/specs/test_invitations_page.ts, client/tests/e2e/specs/test_my_contact_details_page.ts, client/tests/e2e/specs/test_users_page.ts, client/tests/e2e/specs/test_workspace_sharing_modal.ts, client/tests/e2e/support/index.ts
=> center toast on homepage

libparsec/crates/platform_device_loader/src/native/mod.rs
so it does not prompt the user for their password.
=> Fix is_keyring_available on macos

client/src/components/workspaces/WorkspaceUserRole.vue, client/tests/e2e/specs/test_workspace_sharing_modal.ts
=> [MS] Reordering sharing roles

client/src/components/files/FileCard.vue, client/src/components/users/UserStatusTag.vue, client/src/theme/components/list.scss, client/src/views/sidebar-menu/SidebarMenuPage.vue
**Cursor type** :
- `default`: over the entire app on all elements that are not directly clickable
- `pointer`: on all buttons + clickable elements (i.e. dropdown)
closes #6899
=> [MS] Cursor behaviour

client/src/components/organizations/OrganizationCard.vue, client/src/views/home/OrganizationListPage.vue
=> [MS] Organization `connected` text spacing

client/src/views/home/HomePage.vue
=> [MS] Fixes login error handling in some very specific case that should not happen

client/electron/src/index.ts
=> [MS] "Fixes" links opening multiple times of second instances

client/src/transitions/SlideHorizontal.vue
closes #6784
https://github.com/Scille/parsec-cloud/assets/19772607/8d856563-806e-4f6d-acb0-a8ceb6e15b07
=> [MS] fix SlideHorizontal mode to avoid v-if multiple elements problem

client/src/transitions/SlideHorizontal.vue, client/src/views/home/LoginPage.vue
- remove transition delay since mode is managing the switch for us
- update wrong border radius
=> [MS] Improve Homepage transition

client/src/views/files/FoldersPage.vue
=> [MS] Open files with double click

client/src/App.vue, client/src/components/core/ms-modal/MsAlertModal.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/parsec/login.ts, client/src/services/eventDistributor.ts, client/src/services/toastManager.ts
Also includes a bit of factorisation of the translation files.
=> [MS] Handle incompatible server event

client/src/components/header/InvitationsButton.vue
=> [MS] Fix invitation button wrongly remaining in multi org

client/src/theme/variables/colors.scss
Adding secondary shades
closes #6976
=> [MS] Add secondary color shades

client/src/components/core/ms-input/MsInput.vue, client/src/theme/components/inputs.scss
=> [MS] Improved lisibility on disabled input fields

client/src/App.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/login.ts, client/src/services/eventDistributor.ts
=> [MS] Added revoked and organization expired events

client/electron/src/index.ts
=> [MS] Fix url handling on MacOS from closed app

client/src/views/header/HeaderPage.vue, client/src/views/header/ProfileHeader.vue, client/src/views/header/ProfileHeaderPopover.vue
=> [MS] Add user email and profile in ProfileHeaderPopover

server/parsec/_parsec_pyi/testbed.pyi, server/parsec/components/events.py, server/parsec/events.py, server/tests/api_v4/authenticated/test_events_listen.py
Also fix some typing issue for the testbed and events.
=> [partial #6834]: Add test for each type of events 

.github/workflows/ci-rust.yml, Cargo.lock, Cargo.toml, libparsec/crates/platform_storage/Cargo.toml, libparsec/crates/platform_storage/src/lib.rs, libparsec/crates/platform_storage/src/native/model.rs, libparsec/crates/platform_storage/src/web/certificates.rs, libparsec/crates/platform_storage/src/web/db.rs, libparsec/crates/platform_storage/src/web/mod.rs, libparsec/crates/platform_storage/src/web/model.rs, libparsec/crates/platform_storage/src/web/user.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/tests/unit/certificates.rs, libparsec/crates/platform_storage/tests/unit/user.rs, libparsec/crates/platform_storage/tests/unit/workspace.rs, libparsec/crates/types/Cargo.toml, libparsec/src/lib.rs
Downgrade `uuid` version because of dependencies conflict (`indexed_db_futures`)
closes #4903
=> Add web `storage`

libparsec/crates/platform_storage/src/web/certificates.rs, libparsec/crates/platform_storage/src/web/db.rs, libparsec/crates/platform_storage/src/web/model.rs, libparsec/crates/platform_storage/src/web/user.rs, libparsec/crates/platform_storage/src/web/workspace.rs
Rebased and squashed too fast without fetch
=> Fix web storage

client/src/views/files/FileUploadMenu.vue, client/tests/e2e/specs/test_file_upload_modal.ts
=> [MS] Switch file import tabs if new imports or imports done

client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/components/workspaces/index.ts, client/src/components/workspaces/utils.ts, client/src/views/files/FoldersPage.vue, client/src/views/home/CreateOrganizationModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/component/specs/testWorkspaceCard.spec.ts, client/tests/component/specs/testWorkspaceListItem.spec.ts, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Add workspace contextual menu in sidebar

client/src/parsec/login.ts, client/src/services/informationManager.ts, client/src/services/injectionProvider.ts, client/src/views/home/HomePage.vue, client/src/views/layouts/ConnectedLayout.vue
=> [MS] Isolate information displayed by connected organization

client/src/components/workspaces/utils.ts, client/src/views/workspaces/WorkspaceContextMenu.vue, client/src/views/workspaces/WorkspaceSharingModal.vue
=> [MS] Added workspace name in WorkspaceSharingModal and WorkspaceContextMenu

client/src/views/files/FoldersPage.vue
=> [MS] Disable copy and move until bindings are implemented

client/src/views/workspaces/WorkspaceContextMenu.vue, client/src/views/workspaces/WorkspaceSharingModal.vue
=> [MS] Fixed a small typing mistake for workspace name

client/src/views/users/UserDetailsModal.vue, client/src/views/users/UsersPage.vue
=> [MS] Fixed user details modal injections

client/src/main.ts
More explicit error message when failing to init the testbed
=> [MS] Better error message when failing to init with the testbed

client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/components/workspaces/index.ts, client/src/components/workspaces/utils.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/eventDistributor.ts, client/src/services/storageManager.ts, client/src/views/files/FoldersPage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/WorkspaceContextMenu.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/component/specs/testWorkspaceCard.spec.ts, client/tests/component/specs/testWorkspaceListItem.spec.ts, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Add favorites option to workspaces

client/src/views/home/HomePage.vue, client/src/views/home/LoginPage.vue
=> [MS] Disable the login button while logging in

client/src/components/workspaces/WorkspaceListItem.vue, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Fixed workspace list item not displaying sharing info correctly

client/src/views/workspaces/WorkspaceSharingModal.vue
=> [MS] WorkspaceSharingModal titles style

client/src/views/files/FileUploadMenu.vue
=> [MS] Display in progress files on top of FileUploadMenu instead of at the bottom

client/src/common/validators.ts, client/src/components/core/ms-input/MsInput.vue, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/e2e/specs/test_home_page.ts
=> [MS] Use input validators only on focus lost and enter key pressed

client/src/components/organizations/ChooseServer.vue, client/src/services/informationManager.ts, client/src/views/layouts/ConnectedLayout.vue, client/src/views/workspaces/WorkspaceSharingModal.vue
=> [MS] Fixed a few translations

client/electron/src/setup.ts, client/src/main.ts
=> [MS] Update electron comm to unpack args

client/electron/package-lock.json, client/electron/package.json, client/electron/src/index.ts, client/electron/src/setup.ts, client/electron/src/utils.ts, client/electron/src/winRegistry.ts
=> [MS] Removed electron-is-dev dependency

client/src/main.ts
Error modals and toasts following an event from electron where not displayed because the correct information manager (the one linked with the current org) was not used.
=> [MS] Fixed modal and toast being displayed by the main.ts

client/electron/src/index.ts, client/electron/src/setup.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/storageManager.ts, client/src/views/settings/SettingsModal.vue
=> [MS] Modified app hide & close behavior on MacOS to be more native

client/src/main.ts
=> [MS] Prevent quit dialog overlaps

client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Updated "Not shared" button on workspace card

client/src/parsec/workspace.ts, client/tests/e2e/specs/test_user_details_modal.ts, client/tests/e2e/specs/test_workspace_sharing_modal.ts, client/tests/pw/e2e/workspaces_list.spec.ts, client/tests/pw/helpers/assertions.ts
=> [MS] Added pw tests for workspace list

server/tests/api_v4/anonymous/test_organization_bootstrap.py, server/tests/api_v4/anonymous/test_pki_enrollment_info.py, server/tests/api_v4/authenticated/test_block_create.py, server/tests/api_v4/authenticated/test_events_listen.py, server/tests/api_v4/authenticated/test_invite_1_greeter_wait_peer.py, server/tests/api_v4/authenticated/test_invite_2a_greeter_get_hashed_nonce.py, server/tests/api_v4/authenticated/test_invite_2b_greeter_send_nonce.py, server/tests/api_v4/authenticated/test_invite_3a_greeter_wait_peer_trust.py, server/tests/api_v4/authenticated/test_invite_3b_greeter_signify_trust.py, server/tests/api_v4/authenticated/test_invite_4_greeter_communicate.py, server/tests/api_v4/authenticated/test_invite_cancel.py, server/tests/api_v4/authenticated/test_pki_enrollment_accept.py, server/tests/api_v4/authenticated/test_pki_enrollment_list.py, server/tests/api_v4/authenticated/test_pki_enrollment_reject.py, server/tests/api_v4/authenticated/test_realm_create.py, server/tests/api_v4/authenticated/test_realm_get_keys_bundle.py, server/tests/api_v4/authenticated/test_realm_rename.py, server/tests/api_v4/authenticated/test_realm_share.py, server/tests/api_v4/authenticated/test_realm_unshare.py, server/tests/api_v4/authenticated/test_vlob_read_versions.py, server/tests/api_v4/authenticated/test_vlob_update.py, server/tests/api_v4/invited/test_invite_1_claimer_wait_peer.py, server/tests/api_v4/invited/test_invite_2a_claimer_send_hashed_nonce.py, server/tests/api_v4/invited/test_invite_2b_claimer_send_nonce.py, server/tests/api_v4/invited/test_invite_3a_claimer_signify_trust.py, server/tests/api_v4/invited/test_invite_3b_claimer_wait_peer_trust.py, server/tests/api_v4/invited/test_invite_4_claimer_communicate.py, server/tests/test_api.py
=> Enable test that checks for missing API tests

server/parsec/components/invite.py, server/parsec/components/postgresql/invite.py, server/parsec/components/postgresql/utils.py, server/tests/api_v4/authenticated/test_invite_new_device.py, server/tests/api_v4/authenticated/test_invite_new_user.py
=> Fix send invitation email

client/src/components/workspaces/WorkspaceCard.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspaceContextMenu.vue, client/tests/e2e/specs/test_folders_page.ts, client/tests/e2e/specs/test_workspaces_page.ts
=> [MS] Update sidebar style

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/workspace.ts, client/src/views/files/FileDetailsModal.vue, client/src/views/files/FoldersPage.vue, client/tests/e2e/specs/test_folders_page.ts, client/tests/pw/e2e/file_details.spec.ts, client/tests/pw/helpers/fixtures.ts
Fixed file details modal:
1. created and updated appear correctly
2. the copy path option handles error
3. the copy path option copy the full path on the system
Also added playwright tests for file details modal (and removed the cypress ones)
=> [MS] Updated file details modal + PW tests

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/views/header/ProfileHeader.vue, client/src/views/header/ProfileHeaderPopover.vue
The name and the version will be bigger with `megashark-lib`
closes #7227
=> [MS] Add update message

client/src/components/files/FileCard.vue, client/src/components/workspaces/WorkspaceCard.vue, client/src/views/files/FoldersPage.vue, client/tests/component/specs/testFileCard.spec.ts, client/tests/component/specs/testWorkspaceCard.spec.ts, client/tests/pw/e2e/workspaces_list.spec.ts
=> [MS] Remove "update" text on card item

client/electron/src/preload.ts, client/src/views/header/ProfileHeader.vue
=> [MS] Fixed update info display on electron

client/src/common/validators.ts, client/src/components/organizations/ChooseServer.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/CreateOrganizationModal.vue, client/tests/e2e/specs/test_create_org_modal.ts, client/tests/pw/e2e/create_organization.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/fixtures.ts, client/tests/pw/helpers/testbed.ts, client/tests/pw/helpers/utils.ts
=> [MS] Add error message for invalid server addr and add create org PW tests

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/header/ProfileHeaderPopover.vue
=> [MS] Edit updater bloc

client/src/parsec/login.ts, client/src/services/eventDistributor.ts, client/src/views/files/FoldersPage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/workspaces/WorkspacesPage.vue
Simulate fake Workspace/Entry refreshed events every 10s for electron, and doesn't refresh on web for easier dev.
=> [MS] Only refresh workspaces and entries on electron using an event

client/tests/e2e/specs/test_workspaces_page.ts, client/tests/pw/e2e/workspaces_list.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/utils.ts
Add workspace creation test and some playwright utils.
=> [MS] Added workspace creation test and playwright utils

client/electron/src/setup.ts, client/src/main.ts, client/src/views/header/ProfileHeaderPopover.vue
=> [MS] Update button calls electron update

client/src/components/files/FileListItem.vue
=> [MS] Fix placement sync icon

client/package-lock.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/views/workspaces/WorkspaceSharingModal.vue
=> [MS] Added warning in WorkspaceSharingModal if user is the only workspace owner

client/package-lock.json, client/package.json, client/src/App.vue, client/src/main.ts, client/src/services/storageManager.ts, client/src/views/settings/SettingsModal.vue
1. Properly initialize I18n
2. Use functions to get the default theme and locale
3. Adds theme manager
=> [MS] Updated config for locale and theme

client/src/components/workspaces/WorkspaceListItem.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/e2e/specs/test_workspaces_page.ts, client/tests/pw/e2e/workspaces_actions.spec.ts, client/tests/pw/e2e/workspaces_list.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/utils.ts
=> [MS] Moved most workspace list e2e tests to playwright

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/UserJoinOrganizationModal.vue, client/tests/pw/e2e/user_join.spec.ts, client/tests/pw/helpers/assertions.ts
=> [MS] Added user join e2e pw test

client/tests/e2e/specs/test_home_page.ts, client/tests/pw/e2e/home_page.spec.ts, client/tests/pw/e2e/profile_popover.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Adds homepage pw tests

client/src/components/files/FileListItem.vue, client/tests/e2e/specs/test_folders_page.ts, client/tests/pw/e2e/documents_list.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/fixtures.ts
More of #7245 
Not much for now, but it also fixes a bug \o/
=> [MS] Documents page on playwright

client/src/main.ts
Adds a confirmation popup when the users tries to close the tab in web. It's way more restrictive that I thought: we can't use a custom dialog (would have loved to use the same one as on Electron) and we can't even change the message. It only triggers once the user has interacted with the page in a meaningful way, and it's disabled in dev mode to avoid annoying message on refresh.
I also added a bit of cleaning on unload.
=> [MS] Confirm before closing on web and clean ressources on close

client/tests/pw/e2e/user_details.spec.ts, client/tests/pw/e2e/users_list.spec.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Added pw user details modal tests

server/parsec/components/invite.py, server/parsec/components/memory/invite.py, server/parsec/components/postgresql/invite.py, server/tests/api_v4/test_enrollment.py
=> Fix concurrency issue in InviteComponent._conduit_listen

.cspell/custom-words.txt, .github/workflows/ci.yml, .pre-commit-config.yaml, server/parsec/cli/sequester.py, server/parsec/events.py, server/poetry.lock, server/pyproject.toml, server/tests/test_sse.py
Also fixed following dependency issues:
- Removed unused dependency `pytest-asyncio` (DEP002). It was already listed as dev dependency. 
- Added imported dependencies that were transitive dependencies (DEP003)
- `anyio`
- `pydantic`
- `pydantic_core`
- `starlette`
- `typing-extensions`
- Exclude `parsec/cli/testbed.py` since it imports dev dependency 'psutil' (DEP004)
Closes #7305
=> Add deptry

client/package-lock.json, client/package.json, client/src/components/files/FileCard.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/users/UserCard.vue, client/src/components/users/UserFilterPopover.vue, client/src/components/users/UserListItem.vue, client/src/views/users/UserListDisplay.vue
Depends on https://github.com/Scille/megashark-lib/pull/67
=> [MS] Replace IonCheckbox with MsCheckbox

.cspell/custom-words.txt, .github/dependabot.yml, server/pyproject.toml
Also:
- remove unused ignored dependencies from `dependabot.yml`
- sort dev dependencies in `pyproject.toml`
=> Add deptry to dependabot pytools group

client/electron/src/setup.ts
=> [MS] Fixes error when electron is looking for updates

client/tests/pw/e2e/documents_list.spec.ts, client/tests/pw/e2e/home_page.spec.ts, client/tests/pw/e2e/workspaces_actions.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Added folder navigation tests

.github/workflows/package-client.yml, .github/workflows/releaser.yml, client/electron/assets/publishConfig.d.ts, client/electron/package.js, client/electron/src/updater.ts
Read the commit description for details ;)
=> Support nightly & release candidate

client/src/plugins/libparsec/index.ts
The result of all calls to libparsec gets logged if it fails.
=> [MS] Log libparsec calls on failure

.cspell/custom-words.txt, docs/adminguide/freeze_users.rst, docs/adminguide/index.rst, docs/conf.py, docs/locale/fr/LC_MESSAGES/adminguide/freeze_users.po
Copied from existing docs in v2 + added some examples and clarifications.
Closes #7422
=> Add user freeze documentation

client/electron/src/setup.ts
=> [MS] Force close app on update

client/src/components/files/FileCardImporting.vue, client/src/components/files/FileListItemImporting.vue
=> [MS] Update `FileListImportingItem`

.cspell/names.txt, client/src/views/home/CreateOrganizationModal.vue
=> [MS] Update serveur used by default

client/src/components/users/UserFilter.vue, client/src/components/users/UserFilterPopover.vue
The space of each profile item will be adjusted in megashark-lib.
closes #7437
=> [MS] Update user-filter visual bugs

client/src/common/device.ts, client/src/parsec/greet_user.ts, client/src/views/users/GreetUserModal.vue
Closes #7457
Also fixes a bug where the greeter would get to device the invitee's device name.
=> [MS] Set correct device names

client/package-lock.json, client/package.json, client/src/components/files/FileCopyItem.vue, client/src/components/files/FileMoveItem.vue, client/src/components/files/FileUploadItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/files/FileOperationMenu.vue
=> [MS] Add style on copy/move menu

client/src/views/users/UsersPage.vue
=> [MS] Update users list when invitation is finished

client/src/components/files/FileCard.vue, client/src/components/files/FileListItem.vue
=> [MS] Stop double-clicking on files button/checkbox

client/src/locales/en-US.json, client/src/locales/fr-FR.json
=> [MS] Fix info text with keyring on change password page

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/LoginPage.vue
Closes #7459 
Waiting for #7484
=> [MS] Handle the different login errors

client/electron/src/setup.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json
=> [MS] Updated license link

client/src/views/devices/GreetDeviceModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue
=> [MS] Hide close button on last step of device greet/join

client/electron/src/index.ts
=> [MS] Clean up parsec on sigint

client/src/views/files/FileOperationMenu.vue
Closes #7482 
For operation in progress, the insert order should be enough since it mirrors the order in which the file op manager processes files. For the done/errors, we add a date and sort using it (last finished shows up at the top of the list).
=> [MS] Sort file operations by the time they finish

client/src/components/files/FileCopyItem.vue, client/src/components/files/FileMoveItem.vue, client/src/views/files/FileOperationMenu.vue
=> [MS] Removed click action for finished move and copy

client/src/components/organizations/OrganizationSwitchPopover.vue, client/src/components/sas-code/SasCodeChoice.vue, client/src/components/sas-code/SasCodeProvide.vue, client/src/components/workspaces/WorkspaceCard.vue, client/src/views/files/FileContextMenu.vue, client/src/views/files/FileDetailsModal.vue, client/src/views/home/InformationJoinDeviceStep.vue, client/src/views/users/UserContextMenu.vue, client/src/views/users/UserDetailsModal.vue, client/src/views/workspaces/WorkspaceContextMenu.vue, client/tests/component/specs/testSasCodeProvide.spec.ts, client/tests/e2e/specs/test_greet_device_modal.ts, client/tests/pw/e2e/user_greet.spec.ts
Update old classes (`caption-caption` and `caption-code`).
closes #7473
=> [MS] Update old `caption-...` class

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/users/GreetUserModal.vue
=> [MS] Slight improvement of greet/join errors handling

client/src/plugins/libparsec/index.ts
=> [MS] Fix invalid log call on start

client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/tests/pw/e2e/workspaces_actions.spec.ts, client/tests/pw/e2e/workspaces_list.spec.ts
=> [MS] Update favorite icon (workspace)

client/src/components/users/UserFilterPopover.vue, client/src/theme/components/popovers.scss
https://github.com/Scille/parsec-cloud/assets/81075511/13cf1372-755f-4383-b48e-7bd49d4401d0
closes #7511
=> [MS] Enable global item clickable on filter buttons

client/src/components/users/UserCard.vue, client/src/components/users/UserFilterPopover.vue, client/src/components/users/UserListItem.vue, client/src/components/users/types.ts, client/src/components/workspaces/WorkspaceUserRole.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/home/OrganizationListPage.vue, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/component/specs/testUserCard.spec.ts, client/tests/component/specs/testUserListItem.spec.ts, client/tests/pw/e2e/home_page.spec.ts, client/tests/pw/e2e/users_list.spec.ts, client/tests/pw/e2e/workspace_sharing.spec.ts
Closes #7456 
It was too easy to do it just for the organizations, so I also did it for users and workspace sharing.
=> [MS] Added messages for list where selectors don't match

client/src/components/files/FileInputs.vue
Closes https://github.com/Scille/parsec-cloud/issues/7476 and https://github.com/Scille/parsec-cloud/issues/7479
=> [MS] Fix successive imports of same file or folder

client/src/components/files/FileCard.vue, client/src/components/files/FileListItem.vue, client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/theme/components/list.scss, client/src/views/workspaces/WorkspacesPage.vue
=> [MS] Add hover class to file and user items when menu is opened

client/src/components/devices/ChooseAuthentication.vue, client/src/components/organizations/ChooseServer.vue, client/src/views/home/CreateOrganizationModal.vue
=> [MS] Add logo on organization modal loading

libparsec/crates/client/src/client/mod.rs, libparsec/crates/platform_mountpoint/src/windows/mount.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/mount_unmount.rs
fix https://github.com/Scille/parsec-cloud/issues/7462
=> Fix Windows mountpoint to unmount on drop

client/src/views/home/SummaryStep.vue
=> [MS] Missing style `SummaryStep`

client/src/views/home/OrganizationListPage.vue
=> [MS] Center no-organization section (on Homepage)

client/electron/src/index.ts
=> [MS] Update default config path of electron

client/src/components/files/FileCard.vue, client/src/components/files/FileDropZone.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/files/FoldersPage.vue
=> [MS] Prevent drag&drop when user is reader on the workspace

client/src/components/workspaces/utils.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/pw/e2e/workspace_sharing.spec.ts, client/tests/unit/specs/testWorkspaceRole.spec.ts
=> [MS] Owners can now change the role of other owners

client/src/parsec/login.ts, client/tests/pw/e2e/home_page.spec.ts
Only displays the most recent AvailableDevice per tuple <email, orgId, serverAddr>.
=> [MS] Filter available devices to only display the most recent one

HISTORY.rst
- Added general description for the v3 upcoming release 
- Removed relatively minor changes (a list of major changes should be added instead)
Close #6409
=> Update V3 changelog

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/modals.scss, client/src/views/workspaces/WorkspaceSharingModal.vue
=> [MS] Split sharing modal

client/src/views/home/UserJoinOrganizationModal.vue
=> [MS] Hide cancel button on authentification step

client/src/components/files/FileCard.vue, client/src/components/files/FileListItem.vue, client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/theme/components/list.scss, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue
=> [MS] Add missing separator on first user and fix hover item

client/src/parsec/login.ts
Forgot to also convert the dates when we're not filtering.
=> [MS] Fix date conversion for available device

docs/locale/fr/LC_MESSAGES/userguide/troubleshooting.po, docs/userguide/troubleshooting.rst
Also add missing translations for Troubleshooting section.
Related to #7585
=> Add troubleshooting info for #7585

client/electron/src/index.ts, client/electron/src/setup.ts
=> [MS] More electron logs in dev mode

server/parsec/components/postgresql/block.py, server/parsec/components/postgresql/organization.py, server/parsec/components/postgresql/realm.py, server/parsec/components/postgresql/user.py, server/parsec/components/postgresql/utils.py, server/parsec/components/postgresql/vlob.py, server/tests/api_v4/authenticated/test_realm_create.py
Tasklist:
To be done later in another PR:
- Check that selected columns are actually used by the code
- See if some queries overlap
- Remove duplicated queries
- Extract & store internal ids for organization, user and device during the checks common to all authenticated commands
Related #7122
=> Server SQL queries refactoring

server/parsec/asgi/administration.py, server/tests/administration/test_create_organization.py
=> Return bootstrap url instead of token

docs/rfcs/1000-shamir-based-recovery.md, libparsec/crates/protocol/schema/authenticated_cmds/shamir_recovery_setup.json5, libparsec/crates/protocol/tests/authenticated_cmds/v4/shamir_recovery_setup.rs, libparsec/crates/serialization_format/src/protocol_python_bindings.rs, libparsec/crates/serialization_format/src/types.rs, libparsec/crates/testbed/src/template/crc_hash.rs, libparsec/crates/types/src/token.rs, libparsec/crates/types/tests/unit/token.rs, server/parsec/_parsec_pyi/protocol/authenticated_cmds/v4/shamir_recovery_setup.pyi, server/parsec/components/memory/datamodel.py, server/src/lib.rs, server/src/token.rs, server/tests/api_v4/authenticated/test_shamir_recovery_setup.py, server/tests/common/client.py
=> Replace ShamirRevealToken by a plain InvitationToken.

client/src/views/home/OrganizationListPage.vue
=> Fixed claim links opening the org creation modal

docs/development/how-to-write-sql-queries.md, server/parsec/components/events.py, server/parsec/components/organization.py, server/parsec/components/postgresql/auth.py, server/parsec/components/postgresql/block.py, server/parsec/components/postgresql/events.py, server/parsec/components/postgresql/organization.py, server/parsec/components/postgresql/realm.py, server/parsec/components/postgresql/user.py, server/parsec/components/postgresql/utils.py, server/parsec/components/postgresql/vlob.py
This PR is a sequel to #7620.
- It contains a summary of the discussions with @vxgmichel in #7122 
Closes #7122
=> Refactoring server SQL queries, part 2

.github/actions/system-info/action.yml, .github/actions/system-info/system-info.py, .github/workflows/ci-python.yml, .github/workflows/ci-rust.yml, .github/workflows/ci-web.yml
Add runner version to:
- Rust cache entry
- libparsec cache entry
=> Harden cache entry with runner version

client/electron/macOS/entitlements.plist, client/electron/package.js, client/package-lock.json, client/package.json
Closes https://github.com/Scille/parsec-cloud/issues/7642
=> Fix MacOS app signing & notarization

libparsec/crates/client/tests/unit/workspace/merge_folder.rs
=> Use `rstest` case instead of match kind pattern

.github/workflows/releaser.yml
=> Add python requirement files on release

misc/version_updater.py
=> Manage testbed version using the version updater

libparsec/crates/client/src/workspace/merge.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/tests/unit/workspace/merge_folder.rs
=>  [Confinement point] Apply merge folder logic from v2

Cargo.lock, libparsec/crates/platform_storage/Cargo.toml, libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/web/model.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs, libparsec/crates/platform_storage/tests/unit/workspace.rs
=> Rework debug dump for workspace storage

client/README.md, client/src/router/types.ts, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/index.ts, client/src/services/bms/types.ts, client/src/views/client-area/AuthenticationPage.vue, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaHeader.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/home/HomePageHeader.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/data.ts
Adds a few pages to handle the customer login to the BMS and the customer area.
=> [MS] Added the skeleton of the customer area

client/src/main.ts, client/src/services/bms/access.ts, client/src/services/bms/types.ts, client/src/services/storageManager.ts, client/src/views/client-area/AuthenticationPage.vue, client/src/views/client-area/BillingPage.vue, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/InvoicesPage.vue, client/src/views/client-area/PaymentPage.vue, client/src/views/client-area/StatsPage.vue, client/src/views/client-area/SummaryPage.vue, client/src/views/client-area/types.ts
=> [MS] Adds a few customer area pages

client/src/common/organization.ts, client/src/components/organizations/OrganizationCard.vue, client/src/components/organizations/OrganizationSwitchPopover.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/inputs.scss, client/src/views/devices/ImportRecoveryDevicePage.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/LoginPage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/component/specs/testOrganizationCard.spec.ts, client/tests/pw/e2e/home_page.spec.ts
=> [MS] Add trial section on sidebar

client/package-lock.json, client/package.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue
=> [MS] Adds a dropdown to switch organization in the client area

libparsec/crates/client/src/event_bus.rs, libparsec/crates/client/src/user/store.rs, libparsec/crates/client_connection/src/authenticated_cmds/sse.rs, libparsec/crates/crypto/src/rustcrypto/hash.rs, libparsec/crates/platform_mountpoint/build.rs, libparsec/crates/platform_mountpoint/src/unix/inode.rs, libparsec/crates/platform_storage/src/certificates.rs, libparsec/crates/platform_storage/src/web/certificates.rs, libparsec/crates/serialization_format/tests/common/libparsec_types_mock.rs, libparsec/crates/types/src/addr.rs, libparsec/crates/types/src/id.rs, libparsec/crates/types/src/invite.rs, libparsec/crates/types/src/local_manifest.rs, libparsec/crates/types/src/manifest.rs, server/src/misc.rs
<https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html>
=> Update rust toolchain to 1.80.0

libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/web/model.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs, libparsec/crates/platform_storage/tests/unit/workspace.rs
=> Add `prevent-sync-pattern` route to platform storage

Cargo.lock, Cargo.toml
This update will be required to use the cursor feature
=> Update indexdb to 0.5.0

.cspell/custom-words.txt, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/helpers/bms.ts
Fix the parsing of the results from getInvoices
=> [MS] Fixed bms get invoices request

client/src/components/users/UserAvatarName.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/client-area/BillingDetailsPage.vue, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaHeader.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/ContractsPage.vue, client/src/views/client-area/DashboardPage.vue, client/src/views/client-area/PaymentMethodsPage.vue, client/src/views/client-area/PersonalDataPage.vue, client/src/views/client-area/StatisticsPage.vue, client/src/views/client-area/types.ts, client/tests/pw/e2e/client_area_login.spec.ts
=> [MS] Client header

.cspell/custom-words.txt, client/package-lock.json, client/package.json, client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/types.ts
=> Customize Sidebar

client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/views/client-area/ClientAreaHeader.vue, client/src/views/client-area/ClientAreaPage.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/fixtures.ts
=> Ms client area tests

client/src/views/client-area/ClientAreaPage.vue
=> [MS] Removed incorrect background-color

Cargo.lock, Cargo.toml, bindings/electron/Cargo.toml, bindings/electron/src/lib.rs, bindings/electron/src/meths.rs, bindings/generator/templates/binding_electron_meths.rs.j2, libparsec/crates/platform_storage/tests/unit/workspace.rs
=> Add Sentry support for Rust in electron bindings

client/src/main.ts, client/src/views/settings/SettingsModal.vue, client/tests/pw/e2e/settings_modal.spec.ts
=> [MS] Show enableTelemetry settings option

client/src/services/bms/api.ts, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/client_area_personal_page.spec.ts, client/tests/pw/helpers/bms.ts
=> [MS] Added client area personal page test

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/views/client-area/CreditCardModal.vue, client/src/views/client-area/PaymentMethodsPage.vue, client/tests/pw/e2e/client_area_payment_methods.spec.ts, client/tests/pw/helpers/bms.ts
Closes #7790, progresses #7787
=> [MS] Add card modal and listing

libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs, libparsec/crates/platform_storage/tests/unit/workspace.rs
=> Improve return value of `mark prevent sync pattern as fully applied`

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaHeader.vue, client/tests/pw/e2e/client_area_login.spec.ts
=> [MS] Ask for confirmation before logging out of client area

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaHeader.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/settings_modal.spec.ts
=> [MS] Opens the settings modal from client area

.github/workflows/package-client.yml, client/electron/package-lock.json, client/electron/package.json, client/electron/snap/snapcraft.yaml, client/electron/tsconfig.json
With the help of `@sentry/wizard` that uplift the configuration to upload the client electron source maps to sentry
=> Upload client electron sourcemaps to sentry

libparsec/crates/platform_storage/src/native/workspace.rs, libparsec/crates/platform_storage/src/web/model.rs, libparsec/crates/platform_storage/src/web/workspace.rs, libparsec/crates/platform_storage/src/workspace.rs
=> Add types `RawEncrypted{Block,Chunk,Bytes}`

client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global-client.scss, client/src/theme/global.scss, client/src/views/client-area/ClientAreaHeader.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/DashboardPage.vue, client/src/views/client-area/PaymentMethodsPage.vue, client/tests/pw/e2e/client_area_dashboard.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Add dashboard style

client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts
=> [MS] Added bms route to update authentication

client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/client_area_payment_methods.spec.ts, client/tests/pw/e2e/client_area_stats_page.spec.ts, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Refactored and improved bms mocks in e2e tests

client/tests/pw/helpers/bms.ts
=> Ms mock update client

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/services/translation.ts, client/src/views/client-area/AuthenticationModal.vue, client/src/views/client-area/PersonalDataPage.vue, client/src/views/client-area/PersonalInfoModal.vue, client/src/views/client-area/ProfessionalInfoModal.vue, client/tests/pw/e2e/client_area_personal_page.spec.ts
=> [MS] Client area personal data modals

.github/workflows/package-server.yml
This temporary fix the issue in #7911
But we still need a proper fix for the issue
=> Temporary fix to build macos server wheel

client/src/services/bms/api.ts, client/src/views/client-area/AuthenticationModal.vue, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/PersonalInfoModal.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/client_area_payment_methods.spec.ts, client/tests/pw/e2e/client_area_personal_page.spec.ts, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/data.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Added tests for personal page update

client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/views/client-area/personal-data/PersonalDataPage.vue, client/src/views/client-area/personal-data/SecurityModal.vue
- improve updateAuthentication api
- implements SecurityModal 
depends on #7945
=> [MS] Client area: Implements password update

libparsec/crates/client/src/workspace/merge.rs, libparsec/crates/client/src/workspace/store/cache.rs, libparsec/crates/client/src/workspace/store/prevent_sync_pattern.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/tests/unit/workspace/folder_transactions.rs, libparsec/crates/client/tests/unit/workspace/merge_folder.rs, libparsec/crates/client/tests/unit/workspace/move_entry.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/open_file.rs, libparsec/crates/platform_storage/tests/unit/workspace.rs, libparsec/crates/testbed/src/template/build.rs, libparsec/crates/testbed/src/template/events.rs, libparsec/crates/testbed/src/templates/coolorg.rs, libparsec/crates/testbed/src/templates/minimal_client_ready.rs, libparsec/crates/types/src/local_manifest.rs, libparsec/crates/types/tests/unit/local_manifest.rs
That allow to detected placed where the pattern is not passed when it should be. I've placed TODO comments where the pattern should be passed as it will be fixed in another PR.
=> Change prevent sync pattern type to be mandatory

client/package-lock.json, client/package.json, client/src/views/client-area/personal-data/AuthenticationModal.vue, client/src/views/client-area/personal-data/PersonalInfoModal.vue, client/src/views/client-area/personal-data/ProfessionalInfoModal.vue, client/src/views/client-area/personal-data/SecurityModal.vue
- harmonize error management between modals
- set focus on first input on modals opening
depends on #7946
depends on https://github.com/Scille/megashark-lib/pull/125
=> [MS] Client area: Improve personal data page modals UX

libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/store/file_updater.rs, libparsec/crates/platform_mountpoint/src/unix/filesystem.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/flush_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/mod.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/open_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/read_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/stat_entry.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/utils.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/write_file.rs, libparsec/crates/tests_macros/src/lib.rs
see https://github.com/Scille/parsec-cloud/issues/7881
=> Fuse write then read bug

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/payment-methods/PaymentMethodsPage.vue, client/src/views/client-area/personal-data/AuthenticationModal.vue, client/src/views/client-area/personal-data/PersonalDataPage.vue, client/src/views/client-area/personal-data/PersonalInfoModal.vue, client/src/views/client-area/personal-data/ProfessionalInfoModal.vue, client/src/views/client-area/personal-data/SecurityModal.vue
- inject informationManager in ClientAreaPage and pass it as prop to sub views
- fix: add translationPrefixes to reduce mistakes
- feat: add toast message on modals success
depends on #7947
=> [MS] Client area: Improve user feedback on personal data update

cli/src/export_recovery_device.rs, cli/src/utils.rs
The function was then renamed to `load_and_unlock_device`
=> Remove the callback from `load_device_and_run`

cli/src/cancel_invitation.rs, cli/src/greet_invitation.rs, cli/src/invite_device.rs, cli/src/invite_user.rs, cli/src/list_invitations.rs, cli/src/utils.rs
=> Remove callback in `load_cmds_and_run`

cli/src/create_workspace.rs, cli/src/list_users.rs, cli/src/list_workspaces.rs, cli/src/shamir_setup.rs, cli/src/share_workspace.rs, cli/src/tests.rs, cli/src/utils.rs
Then rename it to `load_client`
=> Remove callback in `load_client_and_run`

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/dashboard/DashboardPage.vue, client/src/views/client-area/invoices/InvoicesPage.vue, client/tests/pw/e2e/client_area_dashboard.spec.ts, client/tests/pw/e2e/client_area_invoices_page.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/fixtures.ts
Adds tests for invoices page. Also handles errors, and fixes dashboard page.
=> [MS] Added invoices page tests

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/statistics/StatisticsPage.vue, client/tests/pw/e2e/client_area_stats_page.spec.ts
=> [MS] Add style on statistics page

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/views/client-area/billing-details/BillingDetailsPage.vue, client/tests/pw/e2e/client_area_billing_details.spec.ts, client/tests/pw/helpers/bms.ts, client/tests/pw/helpers/data.ts, client/tests/pw/helpers/index.ts
=> [MS] Added billing details page & update

client/src/components/client-area/InvoicesContainer.vue
=> [MS] Fixed invoices year container visible/hidden

client/src/components/organizations/CreateOrganizationModalHeader.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaLoginPage.vue, client/src/views/client-area/payment-methods/PaymentMethodsPage.vue, client/src/views/home/HomePage.vue, client/src/views/home/HomePageHeader.vue, client/src/views/home/LoginPage.vue, client/src/views/home/OrganizationListPage.vue, client/tests/e2e/specs/test_about_modal.ts, client/tests/pw/e2e/about_modal.spec.ts, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/client_area_payment_methods.spec.ts, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Enhanced customer area login + modified `update button`

client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/dashboard/DashboardPage.vue, client/src/views/client-area/invoices/InvoicesPage.vue, client/src/views/client-area/statistics/StatisticsPage.vue, client/src/views/client-area/types.ts, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/client_area_personal_page.spec.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Adds all orgs summary

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/router/types.ts, client/src/services/bms/api.ts, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/home/HomePage.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/helpers/bms.ts
https://github.com/user-attachments/assets/c1c1a60b-5b37-4dbd-8e99-b9a810a06c90
=> Add organization state and go home button

client/src/theme/global-client.scss, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/dashboard/DashboardPage.vue, client/src/views/client-area/invoices/InvoicesPage.vue, client/src/views/client-area/statistics/StatisticsPage.vue
=> [MS] Added skeleton stats page

client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts
=> [MS] Added custom order queries

cli/src/ls.rs, cli/src/main.rs, cli/src/tests.rs
=> Add command to list files in a workspace

client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/services/bms/api.ts
=> [MS] Fetch all organizations

bindings/electron/src/meths.rs, bindings/generator/api/common.py, bindings/web/src/meths.rs, libparsec/crates/types/src/id.rs, server/src/ids.rs
=> Add error type for string based id parsing

client/src/services/bms/api.ts, client/src/views/client-area/ClientAreaPage.vue
1. Fixes a bug on manual refresh when the requested org was not the right one
2. Adds a specific timeout for some queries
3. Fixed an exception when stats are empty
=> [MS] Fixed refresh bug on client area

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/contracts/ContractsPage.vue
⚠️ This PR is only a style PR, all data is fake and will have to be replaced when routes will be available.
closes #7984
=> [MS] Added style on contract page

client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/views/client-area/personal-data/PersonalDataPage.vue, client/tests/pw/e2e/client_area_personal_page.spec.ts, client/tests/pw/helpers/bms.ts
=> [MS] Add billing system property on client personal info

client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/theme/global-client.scss, client/src/views/client-area/payment-methods/CreditCardModal.vue, client/src/views/client-area/payment-methods/PaymentMethodsPage.vue, client/src/views/client-area/types.ts, client/tests/pw/e2e/client_area_payment_methods.spec.ts
=> [MS] Delete & set default payment method

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/billing-details/CustomOrderBillingDetailsPage.vue, client/src/views/client-area/contracts/ContractsPage.vue, client/src/views/client-area/invoices/CustomOrderInvoicesPage.vue, client/src/views/client-area/types.ts, client/tests/pw/helpers/bms.ts
=> [MS] Added support for custom order pages and API

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/BmsLogin.vue, client/src/views/organizations/creation/CreateOrganizationModal.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/helpers/assertions.ts, client/tests/pw/helpers/bms.ts
=> [MS] Prevent custom order from creating a Saas org

client/src/services/bms/types.ts
=> [MS] Added missing custom order statuses

libparsec/crates/types/src/sas_code.rs, libparsec/crates/types/tests/unit/sas_code.rs
=> Add error type for SASCode int conversion

libparsec/crates/types/src/id.rs
=> Add error type for parsing `UserProfile`

bindings/electron/src/meths.rs, bindings/generator/api/common.py, bindings/web/src/meths.rs, libparsec/crates/types/src/sas_code.rs, libparsec/crates/types/tests/unit/sas_code.rs
=> Add error type for `SASCode` parsing error

libparsec/crates/types/src/id.rs, server/src/ids.rs
=> Return error type instead of raw string in UUID types parsing

libparsec/crates/types/src/id.rs, server/src/ids.rs
=> Return enum error instead of str for HumanHandle parsing

client/src/services/bms/access.ts
=> [MS] Avoid a network request if token are not fresh

libparsec/crates/types/src/invite.rs
=> Add error type for parsing `InvitationType`

client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/theme/components/popovers.scss
=> [MS] Fixed organization list popover height

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaLoginPage.vue, client/src/views/client-area/forgot-password/BmsForgotPassword.vue, client/src/views/client-area/forgot-password/BmsForgotPasswordEmailSentStep.vue, client/src/views/client-area/forgot-password/BmsForgotPasswordGetEmailStep.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/client_forgotten_password.spec.ts, client/tests/pw/helpers/bms.ts
=> [MS] Client area: implements forgot password

client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/tests/pw/helpers/bms.ts
=> [MS] Adds custom order details info

client/src/components/organizations/CreateOrganizationModalHeader.vue, client/src/theme/components/inputs.scss, client/src/theme/components/modals.scss, client/src/views/client-area/forgot-password/BmsForgotPassword.vue, client/src/views/client-area/forgot-password/BmsForgotPasswordEmailSentStep.vue, client/src/views/client-area/forgot-password/BmsForgotPasswordGetEmailStep.vue, client/tests/pw/e2e/client_forgotten_password.spec.ts, client/tests/pw/e2e/create_organization.spec.ts, client/tests/pw/e2e/create_organization_custom.spec.ts, client/tests/pw/e2e/create_organization_saas.spec.ts, client/tests/pw/e2e/create_organization_trial.spec.ts
=> [MS] Polished forgotten password

client/src/services/bms/api.ts
=> [MS] Fix org user stats

client/src/components/organizations/OrganizationSwitchClientPopover.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue
=> [MS] Updated all orgs switch

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/statistics/CustomOrderStatisticsPage.vue, client/src/views/client-area/types.ts
=> [MS] Custom order Stats

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/api.ts, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/dashboard/CustomOrderProcessingPage.vue, client/src/views/client-area/types.ts
=> [MS] Adds processing page for custom order

client/src/theme/components/popovers.scss, client/src/views/client-area/ClientAreaSidebar.vue
=> [MS] Fixed dropdown popover

client/package-lock.json, client/package.json
=> [MS] Resynced megashark for stripe init

.cspell/cspell.config.yml, client/.env.development, client/electron/src/setup.ts, client/package-lock.json, client/package.json, client/playwright.config.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/bms/api.ts, client/src/services/environment.ts, client/src/views/client-area/BmsLogin.vue, client/src/views/header/ProfileHeader.vue, client/src/views/home/HomePageHeader.vue, client/tests/pw/e2e/create_organization_saas.spec.ts
=> [MS] Updated configuration by env variables

cli/src/commands/run_testenv.rs, cli/src/testenv_utils.rs, cli/tests/integration/cancel_invitation.rs, cli/tests/integration/create_workspace.rs, cli/tests/integration/export_recovery_device.rs, cli/tests/integration/import_recovery_device.rs, cli/tests/integration/invite_device.rs, cli/tests/integration/invite_user.rs, cli/tests/integration/list_invitations.rs, cli/tests/integration/list_users.rs, cli/tests/integration/ls.rs, cli/tests/integration/mod.rs, cli/tests/integration/remove_device.rs, cli/tests/integration/shamir_setup_create.rs, cli/tests/integration/share_workspace.rs
The issue was we where using `other_alice` device instead of `bob` device.
=> Re-enable test `share_workspace`

client/src/main.ts
=> [MS] Log env variables used

client/electron/scripts/sign-windows-package.ps1
... in the `sign-windows-package` script
=> Add `latest-win-x86_64.yml` to the upload directory 

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/router/types.ts, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/home/HomePage.vue, client/src/views/organizations/creation/CreateOrganizationModal.vue
=> [MS] Added a create org button to client area

client/src/components/users/InvitationPopoverItem.vue
=> [MS] Fixed height invitation item

client/src/views/files/FileOperationMenu.vue
=> [MS] Update background color in FileOperationMenu

client/src/views/workspaces/WorkspacesPage.vue, client/tests/pw/e2e/workspaces_list.spec.ts
=> [MS] Removed workspace sorter item `Size`

client/src/components/organizations/OrganizationCard.vue
=> [MS] Fixed organization text length

client/package-lock.json, client/package.json, client/src/views/devices/GreetDeviceModal.vue, client/src/views/files/FoldersPage.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/organizations/creation/CreateOrganizationModal.vue, client/src/views/users/GreetUserModal.vue
=> [MS] Set backdropdismiss to false on relevant AskQuestions

client/src/main.ts
=> [MS] Dismiss popovers on link open

server/parsec/asgi/rpc.py
`block_create` requests and `block_read` replies have by far the largest payloads (up to 512K).
In debug mode, each call to those commands will add up to 1.5MB of content to the logs (due to ASCII representation).
Truncating those payloads allows to reduce the logs to a reasonable size.
=> Truncate block payloads in server logs

libparsec/crates/types/src/addr.rs, libparsec/crates/types/tests/unit/addr.rs
=> Fix addr panic on bad scheme

client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/ClientAreaLoginPage.vue
=> [MS] Updated height BmsLogin

client/package-lock.json, client/package.json, client/src/components/organizations/OrganizationSwitchPopover.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/e2e/specs/test_manage_organization.ts, client/tests/pw/helpers/fixtures.ts
=> [MS] Updated Sidebar style

client/src/common/organization.ts, client/src/services/parsecServers.ts, client/tests/unit/specs/testTrialOrganization.spec.ts
=> [MS] Fix trial organization duration

client/src/views/client-area/forgot-password/BmsForgotPassword.vue, client/src/views/client-area/forgot-password/BmsForgotPasswordGetEmailStep.vue
=> [MS] Valided email with uppercases

server/parsec/asgi/administration.py
Fix #https://github.com/Scille/parsec-cloud/issues/5478
Follow up after #7427
=> Add logging to administration routes

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/personal-data/PersonalDataPage.vue, client/tests/pw/e2e/client_area_personal_page.spec.ts
=> [MS] Added `Not defined` on phone number when empty

libparsec/crates/client/src/workspace/transactions/create_file.rs, libparsec/crates/client/src/workspace/transactions/create_folder.rs, libparsec/crates/client/tests/unit/workspace/folder_transactions.rs, libparsec/crates/client/tests/unit/workspace/utils.rs, libparsec/crates/types/src/local_manifest.rs, libparsec/crates/types/tests/unit/local_folder_manifest.rs
Fix #8068
Many more tests are missing tho.
=> Fix missing prevent sync pattern handling in create file and create folder transaction helpers

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/organizations/creation/OrganizationNameAndServerPage.vue, client/tests/e2e/specs/test_device_join_org_modal.ts, client/tests/pw/e2e/client_area_login.spec.ts, client/tests/pw/e2e/create_organization.spec.ts, client/tests/pw/e2e/create_organization_custom.spec.ts
Fix #8132
Fix #8138
Fix #8140
Fix #8157
=> Improve wording on some dialogs

client/.env.development, client/.env.production, client/.env.release-candidate, client/src/services/environment.ts, client/src/services/parsecServers.ts, client/src/views/organizations/creation/CreateOrganizationModal.vue, client/src/views/organizations/creation/CreateOrganizationTrial.vue, client/tests/unit/specs/testParsecServers.spec.ts, client/tests/unit/specs/testTrialOrganization.spec.ts, client/vite.config.ts
=> [MS] Updated env variables to detect Saas/Trial servers

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue
=> [MS] Added sidebar header no organization style

cli/src/commands/mod.rs, cli/src/commands/workspace_import.rs, cli/src/main.rs, cli/tests/integration/mod.rs, cli/tests/integration/workspace_import.rs, libparsec/crates/client/src/workspace/transactions/open_file.rs
=> Add command to copy a local file to a remote workspace

cli/src/commands/mod.rs, cli/src/commands/rm.rs, cli/src/main.rs, cli/tests/integration/mod.rs, cli/tests/integration/rm.rs
=> Add command to remove files from a workspace

.github/workflows/ci-web.yml, cli/src/testenv_utils.rs, cli/tests/integration/bootstrap_organization.rs, cli/tests/integration/create_organization.rs, cli/tests/integration/mod.rs, client/README.md, client/cypress.config.ts, client/src/main.ts, client/src/views/testing/TestPage.vue, client/tests/e2e/support/index.ts, client/tests/pw/helpers/testbed.ts, client/vite.config.ts, docs/development/README.md, libparsec/crates/testbed/src/scope.rs, server/parsec/cli/testbed.py
Basically just a search&replace
Closes #8219
=> Merge `TESTBED_SERVER_URL` into `TESTBED_SERVER`

.github/workflows/ci-python.yml, misc/releaser.py
Also add alias for `acknowledge` command (`ack`)
=> Simplify callback of sub-commands' main fonction

.github/workflows/ci-rust.yml, .github/workflows/ci-web.yml, bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/invite.py, bindings/web/src/meths.rs, cli/src/commands/claim_invitation.rs, cli/src/testenv_utils.rs, cli/tests/integration/device_option.rs, cli/tests/integration/mod.rs, client/src/parsec/claim_device.ts, client/src/parsec/claim_user.ts, client/src/parsec/greet_device.ts, client/src/parsec/greet_user.ts, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/certif/shamir_recovery_setup.rs, libparsec/crates/client/src/invite/claimer.rs, libparsec/crates/client/src/invite/common.rs, libparsec/crates/client/src/invite/greeter.rs, libparsec/crates/client/src/invite/mod.rs, libparsec/crates/client/src/invite/organization.rs, libparsec/crates/client/tests/unit/invite/claimer.rs, libparsec/crates/client/tests/unit/workspace/file_transactions_stateful.rs, libparsec/crates/platform_device_loader/tests/change_auth.rs, libparsec/crates/platform_device_loader/tests/save_load.rs, libparsec/crates/platform_storage/tests/unit/native_sqlite_db_creation.rs, libparsec/crates/types/src/local_device.rs, libparsec/src/invite.rs, misc/version_updater.py, server/packaging/testbed-server/README.md
Close #8073 
Part of #7018 
Related to #8200
=> [RFC-1011] libparsec_client implementation of the non-blocking invite transport

client/src/parsec/path.ts, client/src/views/files/FoldersPage.vue
=> [MS] Fix subfolder tree on import folder via button

.github/workflows/package-client.yml, .github/workflows/releaser.yml, client/electron/package.js
Closes https://github.com/Scille/parsec-cloud/issues/7547
=> Fix the error message on MacOS about a missing ZIP file

client/src/views/organizations/OrganizationInformationPage.vue
=> [MS] Allowed scroll for server address in organization info

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/claim_device.ts, client/src/parsec/claim_user.ts, client/src/parsec/greet_device.ts, client/src/parsec/greet_user.ts, client/src/parsec/types.ts, client/src/views/devices/GreetDeviceModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/users/GreetUserModal.vue
Closes https://github.com/Scille/parsec-cloud/issues/8233
=> [MS] handle invite reset reasons

server/parsec/components/postgresql/block.py, server/parsec/components/postgresql/block_create.py, server/parsec/components/postgresql/block_read.py
=> Improve `block_create`/`block_read` to release PostgreSQL connection during blockstore access

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/sidebar-menu/SidebarMenuPage.vue
Closes #8300 and better than #8301
=> [MS] Fix opening pricing page outside the app

client/src/components/users/UserFilterPopover.vue, client/src/locales/en-US.json, client/tests/component/specs/testTagProfile.spec.ts, client/tests/e2e/specs/test_manage_organization.ts, client/tests/pw/e2e/user_greet.spec.ts, client/tests/pw/e2e/users_list.spec.ts, client/tests/unit/specs/testWorkspaceRole.spec.ts
Change only locales + tests.
related to #8254
=> [MS] Updated locales (outsider -> external)

server/parsec/backend.py, server/parsec/cli/options.py, server/parsec/cli/run.py, server/parsec/cli/testbed.py, server/parsec/components/postgresql/factory.py, server/parsec/config.py, server/tests/common/backend.py, server/tests/conftest.py
=> Hide postgre password when displaying the database config

client/src/parsec/file.ts, client/src/views/files/FoldersPage.vue
=> [MS] Fixed renaming a file not setting the new path

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/about/AboutView.vue
Closes #8145 
The issue mentions bundling in the license file and displaying it straight in the app, but it's way more complicated that just opening a link (both in code and UI complexity).
Closes #8106
=> [MS] Updated license & changelog links

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/modals.scss, client/src/views/devices/GreetDeviceModal.vue, client/src/views/users/GreetUserModal.vue
Closes #8242 
To make it easier to test, you can change the mocked wait time:
```
diff --git a/client/src/parsec/internals.ts b/client/src/parsec/internals.ts
index 4e5108d21..f1fb7fec0 100644
--- a/client/src/parsec/internals.ts
+++ b/client/src/parsec/internals.ts
@@ -3,7 +3,7 @@
import { ClientConfig } from '@/parsec/types';
import { MountpointMountStrategyTag, WorkspaceStorageCacheSizeTag } from '@/plugins/libparsec';
-export const MOCK_WAITING_TIME = 500;
+export const MOCK_WAITING_TIME = 50000;
export const DEFAULT_HANDLE = 42;
export async function wait(delay: number): Promise<void> {
```
=> [MS] Remove wait indicator when sending claim device link

libparsec/crates/client/tests/unit/workspace/folder_transactions.rs
- Add bootstrap function to prepare test `add_confined_entry`
- Prevent cloning children
=> Rework test `add_confined_entry`

client/src/components/organizations/OrganizationSwitchPopover.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/organization.ts, client/src/parsec/types.ts, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/pw/e2e/invitations_popover.spec.ts
related to #8124 
closes #8221 
closes #8124
=> [MS] frozen organization

client/src/components/files/FileDropZone.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/theme/global.scss
=> [MS] Fixed drag and drop

client/electron/package.js
=> [MS] Rename app from `parsec` to `Parsec`

libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/store/resolve_path.rs, libparsec/crates/client/src/workspace/transactions/read_folder.rs, libparsec/crates/client/src/workspace/transactions/stat_entry.rs, libparsec/crates/client/tests/unit/workspace/folder_transactions.rs, libparsec/crates/client/tests/unit/workspace/mod.rs, libparsec/crates/client/tests/unit/workspace/read_folder.rs, libparsec/crates/client/tests/unit/workspace/resolve_path.rs, libparsec/crates/client/tests/unit/workspace/retrieve_path_from_id.rs, libparsec/crates/client/tests/unit/workspace/stat_entry.rs, libparsec/crates/platform_mountpoint/src/unix/filesystem.rs, libparsec/crates/platform_mountpoint/src/windows/filesystem.rs
=> Add `retrieve_path_from_id` and fix missing confinement points

client/src/components/organizations/OrganizationSwitchPopover.vue, client/src/parsec/login.ts, client/src/parsec/organization.ts, client/src/parsec/types.ts, client/src/views/header/ProfileHeader.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue
Closes #8223 
Stores the state sent by events and use them to display the org current status (connected/disconnected and expired/active).
=> [MS] Handle org expired

.github/workflows/releaser.yml
=> Add macOS zip to release asset

server/parsec/cli/options.py
Fix regression introduced in #8303
=> Accept both postgres:// and postresql:// url

client/src/views/home/OrganizationListPage.vue
=> [MS] Keep logged in device first in devices list

client/src/services/environment.ts, client/src/views/about/AboutView.vue, client/src/views/header/ProfileHeader.vue, client/src/views/home/HomePageHeader.vue
=> [MS] Updated how external links are opened + fixed changelog link

client/package-lock.json, client/package.json, client/src/views/home/OrganizationListPage.vue
=> [MS] Remember sort order on login page

client/src/views/workspaces/WorkspacesPage.vue
=> [MS] Prevent from creating a workspace twice using the back button

client/src/components/files/FolderSelectionModal.vue
=> [MS] Filter out confined entries from folder selection modal

libparsec/crates/types/tests/unit/local_folder_manifest.rs
=> Fix prevent sync pattern in tests

client/src/views/organizations/OrganizationInformationPage.vue
=> [MS] Fix server addr vertical scroll bar

client/src/components/workspaces/WorkspaceCard.vue, client/tests/component/specs/testFileCard.spec.ts
=> [MS] Hide `lastUpdated` in workspace

client/src/views/workspaces/WorkspacesPage.vue, client/tests/pw/e2e/workspaces_list.spec.ts
=> [MS] Remove Last Update from workspace sorting

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/home/OrganizationListPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/pw/e2e/client_area_personal_page.spec.ts, client/tests/pw/e2e/file_details.spec.ts, client/tests/pw/e2e/home_page.spec.ts, client/tests/pw/e2e/my_profile_page.spec.ts, client/tests/pw/e2e/workspaces_list.spec.ts
=> [MS] Adds workspace name filter

.github/workflows/ci-rust.yml, .github/workflows/ci-web.yml, libparsec/crates/client/src/invite/mod.rs, libparsec/crates/client/tests/unit/invite/bootstrap_organization.rs, libparsec/crates/client/tests/unit/invite/claimer.rs, misc/version_updater.py, server/packaging/testbed-server/README.md, server/parsec/backend.py
=> Reenable invitation tests

client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/header/ProfileHeader.vue
=> [MS] Updated logout to add a spinner and not fail on clientStop error

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/workspaces/WorkspacesPage.vue, client/tests/pw/e2e/workspaces_list.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/8461
=> [MS] Add specific text if no workspace match the search filter

Cargo.lock, Cargo.toml, bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/web/src/meths.rs, cli/Cargo.toml, cli/src/utils.rs, cli/tests/integration/ls.rs, cli/tests/integration/rm.rs, cli/tests/integration/workspace/import.rs, cli/tests/integration/workspace/share.rs, cli/tests/integration/workspace/sync.rs, client/src/plugins/libparsec/definitions.ts, libparsec/Cargo.toml, libparsec/crates/platform_ipc/Cargo.toml, libparsec/crates/platform_ipc/src/lib.rs, libparsec/crates/platform_ipc/src/testbed.rs, libparsec/crates/platform_ipc/src/unix/mod.rs, libparsec/crates/platform_ipc/src/windows/mod.rs, libparsec/crates/platform_ipc/tests/unit/base.rs, libparsec/crates/tests_fixtures/Cargo.toml, libparsec/src/client.rs, libparsec/src/handle.rs, libparsec/src/lib.rs
=> Add libparsec_platform_ipc crate

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/parsec/environment.ts, client/src/views/settings/SettingsModal.vue, newsfragments/8455.feature.rst
=> [MS] Adds a button to open config dir in explorer

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/LoginPage.vue
=> [MS] Handle device already in use error

client/src/components/devices/ChooseAuthentication.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/login.ts, client/src/theme/components/modals.scss, client/src/views/users/MyProfilePage.vue, client/src/views/users/UpdateAuthenticationModal.vue, client/tests/pw/e2e/my_profile_page.spec.ts
=> [MS] Change authentication

server/parsec/logging.py
This PR 
- adds `AsyncioIntegration` because it is _not_ automatically added by Sentry
- removes `LoggingIntegration` because it is automatically added by Sentry
- also, the configuration we used (`level = logging.INFO`, `event_level=logging.ERROR`) corresponds to the default
=> Add Sentry's AsyncioIntegration

libparsec/crates/client/src/certif/mod.rs, libparsec/crates/client/src/certif/realm_create.rs, libparsec/crates/client/src/certif/realm_key_rotation.rs, libparsec/crates/client/src/certif/realm_rename.rs, libparsec/crates/client/src/certif/realm_share.rs, libparsec/crates/client/src/certif/shamir_recovery_setup.rs, libparsec/crates/client/src/certif/user_revoke.rs, libparsec/crates/client/src/invite/greeter.rs, libparsec/crates/client/src/user/sync.rs, libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/tests/unit/client/revoke_user.rs, libparsec/crates/types/src/time.rs, newsfragments/8270.bugfix.rst
Fix #8270 and adds a regression test.
=> Manage RequireGreaterTimestamp errors

client/package-lock.json, client/package.json, client/src/components/files/FileCopyItem.vue, client/src/components/files/FileMoveItem.vue, client/src/components/files/FileUploadItem.vue, newsfragments/8468.bugfix.rst
=> [MS] Use progress bars from lib in FileOperationMenu

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaHeader.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/tests/pw/e2e/client_area_login.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/8437
=> [MS] Made 'Go to home' button in client area accessible when an org is chosen

server/parsec/asgi/rpc.py, server/parsec/components/events.py
=> Better internal SSE disconnection when a client gets revoked or frozen

libparsec/crates/client/tests/unit/workspace/mod.rs, libparsec/crates/platform_mountpoint/src/windows/mount.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/windows_winfsp_tests.rs, newsfragments/8362.bugfix.rst
=> Properly manage mountpoint artifacts on windows

libparsec/crates/platform_storage/src/native/workspace.rs, newsfragments/8517.bugfix.rst
=> Fix #8517: Missing block cleanup when promoted from chunk

client/src/components/files/FileQueuedItem.vue, client/src/components/files/index.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/fileOperationManager.ts, client/src/views/files/FileOperationMenu.vue
Closes https://github.com/Scille/parsec-cloud/issues/8445
=> [MS] Aggregate file operations

client/electron/src/index.ts, client/electron/src/setup.ts, client/electron/src/updater.ts, client/electron/src/winRegistry.ts
=> [MS] Added some try/catch on electron side

client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/types.ts, client/src/theme/components/modals.scss, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/forgot-password/BmsForgotPasswordGetEmailStep.vue, client/src/views/client-area/personal-data/AuthenticationModal.vue, client/tests/pw/e2e/client_area_personal_page.spec.ts, client/tests/pw/helpers/bms.ts
=> [MS] Use code to validation new email

libparsec/crates/client/src/invite/greeter.rs, server/parsec/components/postgresql/invite.py, server/tests/api_v4/authenticated/test_invite_complete.py
=> Remove incorrect admin check in invite_complete

Cargo.lock, libparsec/Cargo.toml, libparsec/src/invite.rs
=> Add log for bootstrap org

client/src/router/navigation.ts, client/src/views/workspaces/WorkspacesPage.vue, newsfragments/8571.bugfix.rst
=> [MS] Fixed navigation loop after opening a workspace link

libparsec/crates/client/src/workspace/store/per_manifest_update_lock.rs, libparsec/crates/client/src/workspace/transactions/open_file.rs
close https://github.com/Scille/parsec-cloud/issues/8579
=> Reenable manifest update lock guard release check

client/src/router/types.ts, client/src/views/client-area/ClientAreaLayout.vue, client/src/views/client-area/ClientAreaLoginPage.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue, newsfragments/8578.bugfix.rst
Closes #8578 
Bug was caused by the router not remounting the client area page.
=> [MS] Fixed the reloading of the client area

client/src/services/bms/api.ts, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/tests/pw/e2e/create_organization_saas.spec.ts, newsfragments/8588.bugfix.rst
=> [MS] Fixed global timeouts and error handling on org creation

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/device.ts, client/src/parsec/types.ts, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, newsfragments/8593.feature.rst
=> [MS] Ask to archive an expired trial device

newsfragments/8367.misc.rst, server/parsec/templates/invitation_mail.html, server/parsec/templates/invitation_mail.txt
Workaround for [#8329](https://github.com/Scille/parsec-cloud/issues/8329)
=> Add raw invitation URL in invitation email

cli/src/commands/device/import_recovery_device.rs, cli/tests/integration/device/import_recovery_device.rs, newsfragments/8567.feature.rst
=> Treat passphrase like password in `import-recovery-device`

client/src/views/workspaces/WorkspaceSharingModal.vue, newsfragments/8538.misc.rst
=> [MS] Hide suggested users for readers and contributors

client/electron/scripts/sign-latest-release.py
A python script to help automate the signing of the windows release using the latest pre-built artefact.
=> Add sign-latest-release.py to the electron scripts

client/src/components/files/FileCard.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/sidebar/SidebarWorkspaceItem.vue, client/src/components/sidebar/index.ts, client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceListItem.vue, client/src/components/workspaces/utils.ts, client/src/main.ts, client/src/views/files/FileContextMenu.vue, client/src/views/files/FolderGlobalContextMenu.vue, client/src/views/files/FoldersPage.vue, client/src/views/files/index.ts, client/src/views/files/types.ts, client/src/views/sidebar-menu/SidebarMenuPage.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/pw/e2e/document_context_menu.spec.ts, client/tests/pw/e2e/users_list.spec.ts, client/tests/pw/e2e/workspaces_actions.spec.ts, newsfragments/8645.feature.rst
=> [MS] Added right click on users, files and workspaces

server/parsec/asgi/__init__.py, server/parsec/cli/run.py, server/parsec/cli/utils.py, server/parsec/components/postgresql/events.py, server/tests/common/postgresql.py
Fix #8658 
Related to #8656 
This PR has minimal changes to make the mechanism to retry after a postgresql connection loss work as expected.
There might be better ways to address the issue though.
=> Fix parsec server retry loop on postgresql connection loss

libparsec/crates/client/src/workspace/merge.rs, libparsec/crates/client/tests/unit/workspace/merge_folder.rs, libparsec/crates/types/src/local_manifest/folder.rs, libparsec/crates/types/tests/unit/local_folder_manifest.rs
=> Improve confinement logic by adding the UnconfinedLocalFolderManifest type

client/package-lock.json, client/package.json, client/src/components/files/FileAggregateDoneItem.vue, client/src/components/files/FileAggregateQueuedItem.vue, client/src/components/files/FileCopyItem.vue, client/src/components/files/FileMoveItem.vue, client/src/components/files/FileUploadItem.vue, client/src/components/files/index.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/files/FileOperationMenu.vue, newsfragments/8557.misc.rst
Closes https://github.com/Scille/parsec-cloud/issues/8557
=> [MS] Aggregate Done & Error items in FileOperationMenu.vue

client/src/views/files/FileContextMenu.vue, client/src/views/files/FoldersPage.vue, client/tests/pw/e2e/document_context_menu.spec.ts
=> [MS] Enable right click for multiple files

client/package-lock.json, client/package.json
=> [MS] Resync megashark-lib to fix global file checkbox

client/src/views/layouts/ConnectedLayout.vue
=> [MS] Fix notifications error

client/src/views/client-area/ClientAreaSidebar.vue, newsfragments/8733.bugfix.rst
=> [MS] Fixed logout and home buttons in customer area

client/electron/src/communicationChannels.ts, client/electron/src/setup.ts, client/src/main.ts, client/src/parsec/login.ts, client/src/plugins/libparsec/index.ts, client/src/views/layouts/ConnectedLayout.vue, client/src/views/organizations/TOSModal.vue, client/src/views/organizations/creation/CreateOrganizationSaas.vue
=> [MS] Serialize objects when logging them

client/electron/scripts/sign-latest-release.py
This way, the full windows signing process is now a single command on a machine with:
- GitHub CLI authenticated
- SimplySign authenticated
=> Upload release assets automatically using the gh command in sign-latest-release.py

client/src/views/sidebar-menu/SidebarMenuPage.vue, client/tests/pw/e2e/workspaces_list.spec.ts
=> [MS] Made the workspace title in the sidebar link to the workspaces page

client/package-lock.json, client/package.json
=> [MS] Resync megashark-lib properly

client/src/parsec/file.ts, client/src/parsec/mock_generator.ts
Some simple refactoring of mock values generation for files
=> [MS] Updated generation of mock values for files and folders

client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/parsec/types.ts, client/src/parsec/user.ts, client/tests/component/specs/testUserCard.spec.ts, client/tests/component/specs/testUserListItem.spec.ts
=> [MS] Displays frozen users

libparsec/crates/client/src/certif/mod.rs, libparsec/crates/client/src/certif/shamir_recovery_setup.rs, libparsec/crates/client/src/client/shamir_setup_create.rs, libparsec/crates/client/tests/unit/client/shamir_setup_create.rs
=> Split shamir setup into two retry loops

cli/src/commands/mod.rs, cli/src/commands/tos/list.rs, cli/src/commands/tos/mod.rs, cli/src/main.rs, cli/tests/integration/mod.rs, cli/tests/integration/tos/list.rs, cli/tests/integration/tos/mod.rs, newsfragments/8773.feature.rst
=> Add CLI command to list the TOS of an organization

client/src/router/navigation.ts, client/src/views/devices/DevicesPage.vue, client/src/views/header/HeaderPage.vue, client/src/views/home/HomePage.vue, client/src/views/layouts/ConnectedLayout.vue, client/src/views/layouts/LoadingLayout.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue
Adds logs to the log file for a few cases of weird behaviors.
=> [MS] Adds a few logs on weird behavior

client/src/views/users/GreetUserModal.vue
Closes https://github.com/Scille/parsec-cloud/issues/8726
=> [MS] Fix disabled email field display in UserInformation.vue

cli/src/commands/tos/accept.rs, cli/src/commands/tos/list.rs, cli/src/commands/tos/mod.rs, cli/tests/integration/tos/accept.rs, cli/tests/integration/tos/mod.rs, newsfragments/8782.feature.rst
=> Add CLI command to accept TOS of an organization

libparsec/crates/client/src/invite/claimer.rs, libparsec/crates/client/src/monitors/connection.rs, libparsec/crates/client_connection/src/error.rs, libparsec/crates/client_connection/src/invited_cmds.rs, libparsec/crates/client_connection/tests/unit/anonymous.rs, libparsec/crates/client_connection/tests/unit/authenticated.rs, libparsec/crates/client_connection/tests/unit/invited.rs
=> Improve libparsec client connection tests

client/electron/snap/local/desktop-launch.sh, client/electron/snap/local/xdg-open.sh, client/electron/snap/snapcraft.yaml, newsfragments/8737.bugfix.rst
=> Add xdg-open script to parsec snap bin directory

client/src/components/sas-code/SasCodeChoice.vue, client/src/parsec/greet_user.ts, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/users/GreetUserModal.vue, newsfragments/8817.misc.rst
=> [MS] Slight improvement of disconnect handling during the invitation process

libparsec/crates/platform_mountpoint/src/unix/filesystem.rs
=> Fix Macos Fuse mountpoint initialization

client/src/components/workspaces/WorkspaceUserRole.vue, client/src/locales/fr-FR.json, client/tests/pw/e2e/workspace_sharing.spec.ts, newsfragments/8245.feature.rst
Closes #8245 
Closes #8569 (didn't want to open another PR for so small a change)
=> [MS] Add external profile tag in workspace sharing

client/src/components/users/UserCard.vue, client/src/components/users/UserListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/tests/pw/e2e/users_list.spec.ts, newsfragments/5941.feature.rst
=> [MS] Show user joined date

cli/src/commands/device/export_recovery_device.rs, cli/src/commands/device/import_recovery_device.rs, cli/tests/integration/device/export_recovery_device.rs, cli/tests/integration/device/import_recovery_device.rs, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/tests/unit/client/recovery.rs, libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/platform_device_loader/src/web/mod.rs, libparsec/src/lib.rs, libparsec/src/recovery.rs
=> Fix CLI recovery device feature

Cargo.lock, Cargo.toml, libparsec/crates/platform_mountpoint/src/unix/filesystem.rs
=> Update to fuser 0.15.0

client/src/parsec/device.ts, client/src/views/devices/ExportRecoveryDevicePage.vue
=> [MS] Disable export recovery device button while processing

client/src/services/fileOperationManager.ts, client/src/views/files/FoldersPage.vue
Fixes two problems:
1. Lessens the blinking in file operation menu by making each operation take at least 500ms
2. Smoothes the refresh of the files by not transitioning between the list and the spinner constantly when importing a large number of files
=> [MS] Smoothes file operations

client/src/views/workspaces/WorkspaceHistoryPage.vue
=> [MS] Display names in calendar using appropriate locale

.cspell/custom-words.txt, libparsec/crates/platform_mountpoint/src/unix/mount.rs
=> Set `volname` option in MacOS to set the volume name

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/device.ts, client/src/views/devices/DevicesPage.vue, client/src/views/devices/ExportRecoveryDevicePage.vue, client/tests/e2e/specs/export_recovery_device.spec.ts, client/tests/e2e/specs/import_recovery_device.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts
=> [MS] Updated export recovery device

client/src/components/files/types.ts, client/src/parsec/file.ts, client/src/views/files/FoldersPage.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/documents_list.spec.ts
=> [MS] Fixed file selection

client/src/parsec/login.ts, client/src/services/eventDistributor.ts, client/src/views/files/FoldersPage.vue
=> [MS] Refresh the file list when a file is synchronized

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts
=> [MS] Handle libparsec load error at startup

docs/development/guide-release-parsec.md
- Update the versions used as example to be more recent.
- Fix the link to translation files.
- Specify that the list of version's files is non-exhaustive.
- Update the command to be correct against the current CLI.
- Specify how patches should be included in the release branch by using either a PR or cherry-pick.
- Specify that at the end of a patch release train, that the release should be acknowledged.
- A steps to continue stabilizing the release and once the release is considered stable.
=> Update release guide

client/src/views/layouts/ConnectedLayout.vue
=> [MS] Fix Firefox scroll problems

client/package-lock.json, client/package.json, client/src/theme/global.scss, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/home/SummaryStep.vue, client/src/views/organizations/creation/OrganizationSummaryPage.vue, client/src/views/workspaces/WorkspaceHistoryPage.vue
=> [MS] Update fill-available to fix cross browser compatibility

client/src/components/files/FileDropZone.vue, client/src/components/files/FileInputs.vue, client/src/main.ts
=> [MS] Swapped calls to document.` for window.document.`

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/statistics/StatisticsPage.vue
=> [MS] Updated the message for stats page when all orgs selected

client/src/components/users/UserFilter.vue, client/src/components/users/types.ts, client/src/views/users/UsersPage.vue, newsfragments/8969.feature.rst
=> [MS] Remember user filtering and sorting option

client/src/views/files/FoldersPage.vue, newsfragments/8970.bugfix.rst
=> [MS] Refresh the folder when a copy ended

docs/rfcs/1000-shamir-based-recovery.md, libparsec/crates/client/src/invite/claimer.rs, libparsec/crates/client/tests/unit/invite/claimer.rs, libparsec/crates/protocol/schema/invited_cmds/invite_info.json5, libparsec/crates/protocol/tests/invited_cmds/v4/invite_info.rs, server/parsec/_parsec_pyi/protocol/invited_cmds/v4/invite_info.pyi, server/parsec/components/invite.py, server/tests/api_v4/invited/test_invite_info.py
Single PR to make sure this change doesn't break compatibility
=> Replace UserOrDevice with InvitationType

server/parsec/asgi/__init__.py, server/parsec/asgi/rpc.py
Also add a timeout of 10 seconds for graceful shutdown
Also close #9091
=> Close the registered client connections when should_exit is registered

client/src/parsec/internals.ts, client/tests/e2e/helpers/fixtures.ts
=> [MS] Should solve flaky playwright tests

client/.env.development, client/README.md, client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/mockApi.ts, client/src/services/bms/types.ts
Defines three env variables that can be used to toggle whether a function from the BMS API should be mocked or not.
=> [MS] Mock BMS API

client/src/theme/components/contextual-menu.scss, client/src/theme/global.scss, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/workspaces_list.spec.ts
https://github.com/user-attachments/assets/08f81690-2435-4437-b637-46270701c4e5
closes #9090
=> [MS] Added style for searchbar

cli/src/commands/workspace/import.rs, cli/src/utils.rs, cli/tests/integration/workspace/import.rs, libparsec/crates/client/src/workspace/transactions/stat_entry.rs, newsfragments/8941.bugfix.rst
=> Fix infinite loop during synchronization of a workspace when importing a file using the CLI command `workspace import`

client/src/services/injectionProvider.ts, client/src/views/header/NotificationCenterPopover.vue
Closes #9084 
I haven't been able to reproduce, I just guessed as to what may have caused the error.
=> [MS] Fixed small bug on notifications

client/src/components/files/FileCardProcessing.vue, client/src/views/devices/ExportRecoveryDevicePage.vue, client/tests/e2e/specs/file_viewers.spec.ts
=> [MS] Added e2e tests for file viewers

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/src/components/files/FileDropZone.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/fileOpener.ts, client/src/views/files/FileContextMenu.vue, client/src/views/files/FolderGlobalContextMenu.vue, client/src/views/files/FoldersPage.vue, client/src/views/files/types.ts, newsfragments/8961.feature.rst
Closes #8961 
Also add the context menu when right clicking in an empty folder.
=> [MS] Added see in explorer action for files and folders

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/mockApi.ts, client/src/views/client-area/contracts/ContractsPage.vue
=> [MS] Custom order contract page

libparsec/crates/client/src/workspace/store/folder_updater.rs, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/store/resolve_path.rs, libparsec/crates/client/src/workspace/store/sync_updater.rs, libparsec/crates/client/src/workspace/transactions/read_folder.rs, libparsec/crates/client/src/workspace/transactions/stat_entry.rs, libparsec/crates/client/tests/unit/workspace/retrieve_path_from_id.rs
=> Introduce `WorkspaceStore::for_update_sync`

cli/src/commands/user/mod.rs, cli/src/commands/user/revoke.rs, cli/tests/integration/user/mod.rs, cli/tests/integration/user/revoke.rs, newsfragments/9143.feature.rst
=> [CLI] Add user revoke command.

cli/src/commands/invite/list.rs, cli/tests/integration/invitations/list.rs, newsfragments/9176.bugfix.rst
This is a parcially cherry-pick of commit 100152ac72a262790468ceac444256ac25399c93
Closes https://github.com/Scille/parsec-cloud/issues/9176
=> Fix `invite list` command crashing when having more than one entry

client/package.json, client/playwright.config.ts, client/src/theme/components/modals.scss, client/src/views/home/UserJoinOrganizationModal.vue, client/tests/e2e/helpers/index.ts, client/tests/e2e/helpers/mediaAssertions.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/create_organization_custom.spec.ts, client/tests/e2e/specs/create_organization_saas.spec.ts, client/tests/e2e/specs/create_organization_trial.spec.ts, client/tests/e2e/specs/device_join_organization.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts, client/tests/e2e/specs/import_recovery_device.spec.ts, client/tests/e2e/specs/user_join.spec.ts
=> [MS] Test file viewers in more details

client/src/main.ts, client/src/services/bms/access.ts
=> [MS] Fix not logged in

client/src/services/storageManager.ts
Viewers could be used if you deleted your config or if you're launching the app for the first time.
=> [MS] Make sure that viewers are skipped by default

libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/transactions/fd_close.rs, libparsec/crates/client/src/workspace/transactions/fd_flush.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/open_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/move_entry.rs, newsfragments/9012.bugfix.rst
=> Quick patch to fix deadlock when reparenting a file from the mountpoint on Windows

client/tests/e2e/specs/client_area_custom_order_statistics.spec.ts
=> [MS] Added e2e tests for custom order stats page

client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/mockApi.ts, client/src/services/bms/types.ts, client/tests/e2e/helpers/bms.ts, client/tests/e2e/helpers/fixtures.ts
=> [MS] Adds BMS API for calls to create custom orders

client/src/components/files/HistoryFileListItem.vue
=> [MS] Removed history workspace list item offset

client/src/views/layouts/ConnectedLayout.vue
=> [MS] Update last login on log out

client/.gitignore, client/src/components/viewers/controls/FileControlsInput.vue, client/src/components/viewers/controls/FileControlsPagination.vue, client/src/components/viewers/index.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/viewers/PdfViewer.vue, client/tests/e2e/specs/file_viewers.spec.ts
closes #9024
related to #9039 
https://github.com/user-attachments/assets/6def052f-34a1-4182-9760-c90f034e68b9
=> [MS] Implements FileControlsPagination component

client/src/views/layouts/LoadingLayout.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/file_viewers.spec.ts
=> [MS] Updated e2e tests to better handle loadings

libparsec/crates/platform_mountpoint/src/unix/filesystem.rs, libparsec/crates/platform_mountpoint/src/unix/mount.rs, libparsec/crates/platform_mountpoint/src/windows/mount.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/create_folder.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/list_directory.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/open_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/remove_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/remove_folder.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/rename_entry.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/stat_entry.rs, newsfragments/9197.bugfix.rst
close #9197
close #9229
alternative version of #9239 ^^
=> Improve mountpoint behavior when the workspace is read only

client/src/common/device.ts, client/src/main.ts, client/src/services/bms/mockApi.ts, client/src/views/client-area/ClientAreaPage.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue
=> [MS] Match available devices using the server addr

server/parsec/__main__.py, server/parsec/cli/__init__.py
Already done in `server/parsec/cli/__init__.py`
=> Remove useless monkeypatch in `server/parsec/__main__.py`

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/services/bms/types.ts, client/src/theme/components/modals.scss, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/ClientAreaSidebar.vue, client/src/views/client-area/orders/NewOrderModal.vue, client/src/views/client-area/orders/OrdersPage.vue, client/src/views/client-area/types.ts, client/tests/e2e/specs/client_area_custom_order.spec.ts
=> [MS] New custom order modal

client/package-lock.json, client/package.json, client/src/components/viewers/controls/FileControlsVolume.vue, client/src/components/viewers/index.ts, client/src/views/viewers/AudioViewer.vue, client/src/views/viewers/VideoViewer.vue, client/tests/e2e/specs/client_area_custom_order_contract.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/9021 and https://github.com/Scille/parsec-cloud/issues/9036
=> [MS] FileControlsVolume component

client/src/components/viewers/controls/FileControlsFlux.vue, client/src/components/viewers/index.ts, client/src/views/viewers/AudioViewer.vue, client/src/views/viewers/VideoViewer.vue, client/tests/e2e/specs/file_viewers.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/9022 and https://github.com/Scille/parsec-cloud/issues/9035
=> [MS] FileControlsFlux component

client/src/components/viewers/controls/FileControlsPlayback.vue, client/src/components/viewers/controls/FileControlsVolume.vue, client/src/components/viewers/index.ts, client/src/views/viewers/AudioViewer.vue, client/src/views/viewers/VideoViewer.vue
Closes https://github.com/Scille/parsec-cloud/issues/9212
=> [MS] FileControlsPlayback component

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/viewers/PdfViewer.vue
=> [MS] Handle errors for PDF viewer

libparsec/crates/platform_mountpoint/src/unix/filesystem.rs, libparsec/crates/platform_mountpoint/src/unix/mount.rs, libparsec/crates/platform_mountpoint/src/windows/mount.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/create_folder.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/list_directory.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/open_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/remove_file.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/remove_folder.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/rename_entry.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/stat_entry.rs, newsfragments/9197.bugfix.rst
=> Backport read only mountpoint

client/package-lock.json, client/package.json, client/src/components/client-area/InvoicesContainer.vue, client/src/components/workspaces/AvatarGroup.vue, client/src/theme/components/tags.scss, client/src/views/client-area/dashboard/DashboardPage.vue
Updated tags colors to WCAG accessibilty AA
=> [MS] Updated tags colors to WCAG accessibilty AA

client/src/components/workspaces/WorkspaceCard.vue, client/src/components/workspaces/WorkspaceTagRole.vue, client/src/components/workspaces/index.ts, client/src/parsec/workspace.ts, client/src/views/files/FoldersPage.vue, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/users_list.spec.ts, client/tests/e2e/specs/workspaces_list.spec.ts, newsfragments/9174.feature.rst
Closes #9174 
Missing the icons to describe each role but it's beyond my CSS skills and I'm not sure where to find the icons anyway.
=> [MS] Add user role to files page and workspace card

.github/workflows/releaser.yml
Also bump softprops/action-gh-release to v2.2.1
=> Add workflow dispatch for nightly releaser workflow

.cspell/custom-words.txt, Cargo.lock, Cargo.toml, libparsec/crates/client/Cargo.toml, libparsec/crates/types/Cargo.toml, libparsec/crates/types/src/shamir.rs
=> Migrate from sharks to blahaj

client/package-lock.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/viewers/FileViewer.vue
Closes https://github.com/Scille/parsec-cloud/issues/9029
=> [MS] File viewer topbar details

server/parsec/components/memory/invite.py, server/parsec/components/postgresql/invite.py, server/parsec/components/postgresql/migrations/datamodel.sql, server/tests/api_v4/authenticated/test_invite_complete.py
=> Fix missing claimer_email in shamir recovery invitations in PostgreSQL

client/src/components/devices/DeviceCard.vue, client/src/components/misc/TechnicalId.vue, client/src/components/misc/index.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/types.ts, client/src/parsec/user.ts, client/src/parsec/workspace.ts, client/src/theme/components/modals.scss, client/src/views/devices/DevicesPage.vue, client/src/views/devices/GreetDeviceModal.vue, client/src/views/files/FileDetailsModal.vue, client/src/views/users/UserDetailsModal.vue, client/tests/component/specs/testDeviceCard.spec.ts, client/tests/e2e/specs/file_details.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts, client/tests/e2e/specs/user_details.spec.ts, newsfragments/9299.feature.rst
=> [MS] Displays technical id of users, devices and files

client/src/views/viewers/ImageViewer.vue, client/src/views/viewers/PdfViewer.vue, client/src/views/viewers/SpreadsheetViewer.vue, client/src/views/viewers/VideoViewer.vue, client/tests/e2e/specs/file_viewers.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/9213
=> [MS] FileControlsFullscreen component

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/organizations/creation/OrganizationUserInformationPage.vue
=> [MS] Added hover over TOS links

libparsec/crates/client/src/monitors/connection.rs, libparsec/crates/client_connection/src/anonymous_cmds.rs, libparsec/crates/client_connection/src/authenticated_cmds/mod.rs, libparsec/crates/client_connection/src/error.rs, libparsec/crates/client_connection/src/invited_cmds.rs, libparsec/crates/client_connection/src/lib.rs, libparsec/crates/client_connection/src/testbed.rs, libparsec/crates/client_connection/tests/unit/anonymous.rs, libparsec/crates/client_connection/tests/unit/authenticated.rs, libparsec/crates/client_connection/tests/unit/invited.rs
=> [Backport PR #9337] Fix unsupported_api_version_from_headers helper

cli/src/commands/invite/claim.rs, cli/src/commands/invite/greet.rs, cli/src/commands/shared_recovery/create.rs, cli/src/utils.rs, newsfragments/9109.bugfix.rst
=> [CLI] Close handles with symbol instead of newline.

cli/src/commands/invite/shared_recovery.rs, cli/src/commands/shared_recovery/create.rs, cli/src/commands/shared_recovery/delete.rs, cli/src/commands/shared_recovery/info.rs, cli/src/commands/shared_recovery/list.rs, cli/src/commands/user/list.rs, cli/src/commands/user/revoke.rs, cli/src/commands/workspace/list.rs, cli/src/utils.rs
For consistency in spinners and ease of use.
=> [CLI] Add helper to poll for new certificates.

cli/src/commands/user/list.rs, cli/src/commands/workspace/list.rs
=> [CLI] Remove redundant client stop.

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/workspace.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/transactions/create_file.rs, libparsec/crates/client/src/workspace/transactions/create_folder.rs, libparsec/crates/client/src/workspace/transactions/move_entry.rs, libparsec/crates/client/src/workspace/transactions/read_folder.rs, libparsec/crates/client/src/workspace/transactions/remove_entry.rs, libparsec/crates/client/tests/unit/workspace/move_entry.rs, libparsec/crates/platform_mountpoint/src/windows/filesystem.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/create_folder.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/move_entry.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/rename_entry.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/utils.rs, newsfragments/9226.bugfix.rst
=> Backport 3.2: winfsp fix rename name collision

.cspell/custom-words.txt, libparsec/crates/platform_mountpoint/src/windows/filesystem.rs, libparsec/crates/platform_mountpoint/src/windows/mount.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/create_folder.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/open_file.rs, newsfragments/9382.bugfix.rst
=> Backport  Winfsp fix write operations on read only workspace

client/src/assets/images/background/background-fileviewer.svg, client/src/components/viewers/FileViewerBackground.vue, client/src/components/viewers/controls/FileControlsFlux.vue, client/src/components/viewers/index.ts, client/src/views/viewers/AudioViewer.vue, client/tests/e2e/specs/file_viewers.spec.ts
=> [MS] AudioViewer UI/UX improvements

docs/locale/fr/LC_MESSAGES/userguide/installation.po, docs/userguide/installation.rst
=> Removed warning macOS

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Github introduced [issue types]
[issue types]: https://github.blog/changelog/2025-01-13-evolving-github-issues-public-preview/#organize-your-work-with-issue-types
=> Update issue template to set issue type

client/electron/package-lock.json, client/electron/package.json
=> [MS] Update electron to latest

client/package-lock.json, client/package.json, client/src/parsec/file.ts, client/src/services/fileOperationManager.ts, client/src/views/files/FileContextMenu.vue, client/src/views/files/FoldersPage.vue, client/src/views/viewers/FileViewer.vue, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/file_details.spec.ts
=> [MS] Adds download file feature in web mode

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/access.ts, client/src/views/organizations/creation/CreateOrganizationSaas.vue, client/tests/e2e/specs/create_organization_saas.spec.ts
=> [MS] Use BmsAccess when creating an organization

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/devices/ImportRecoveryDevicePage.vue, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, client/tests/e2e/specs/import_recovery_device.spec.ts
=> [MS] Added an option to import recovery devices on the home page

client/src/components/users/TagProfile.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/tags.scss, client/src/views/client-area/contracts/ContractsPage.vue, client/tests/e2e/specs/client_area_custom_order_contract.spec.ts, client/tests/e2e/specs/client_area_custom_order_statistics.spec.ts, client/tests/e2e/specs/home_page.spec.ts, client/tests/e2e/specs/invitations_popover.spec.ts, client/tests/e2e/specs/organization_information.spec.ts, client/tests/e2e/specs/user_greet.spec.ts, client/tests/e2e/specs/users_list.spec.ts, client/tests/unit/specs/testInformationManager.spec.ts, docs/development/glossary-EN.md, docs/locale/fr/LC_MESSAGES/userguide/manage_organization.po, docs/rfcs/old/0035-create-a-glossary-to-improve-consistency-in-translations.md, docs/userguide/manage_organization.rst
Changed the profile name `Standard` to `Member`.
closes #9095
=> Change `standard` profile to `member`

client/src/views/workspaces/WorkspaceSharingModal.vue, client/tests/e2e/specs/workspace_sharing.spec.ts
=> [MS] Hide batch role reassign when not enough permissions

newsfragments/9428.bugfix.rst, server/parsec/components/postgresql/queries/q_auth_lock_realm.py, server/parsec/components/postgresql/realm_create.py, server/tests/api_v5/authenticated/test_realm_create.py, server/tests/api_v5/authenticated/test_realm_rotate_key.py, server/tests/conftest.py
Also protect against concurrent key rotation
Fix #9428
=> Protect against concurrent realm creation

client/src/views/viewers/SpreadsheetViewer.vue
=> [MS] Implements Spreadsheet Zoom control; improve UI/UX

client/electron/src/index.ts, client/electron/src/setup.ts
=> [MS] Disable electron updates by setting `GUI_DISABLE_UPDATES=true`

client/package-lock.json, client/package.json
=> [MS] Fixes BMS login caused by bad b64 decoding

client/src/views/header/HeaderPage.vue
=> [MS] Updated Sidebar toggle icon

libparsec/crates/client/src/invite/claimer.rs, libparsec/crates/client/src/invite/greeter.rs
A commit addressing @touilleMan's comments I forgot to push on #9462.
=> Add comments and renaming about inital ctx cancellation

client/src/views/viewers/FileViewer.vue
=> [MS] Hides "Open with system" if viewing a file from history

client/src/components/viewers/controls/FileControlsVolume.vue, client/src/views/viewers/AudioViewer.vue, client/src/views/viewers/VideoViewer.vue
- UI/UX improvements for video viewer
- Rework FileControlsVolume to fix multiple problems
- minor code improvements on both viewers
closes #9054
=> [MS] Multiple fixes for media-based viewers

client/src/services/bms/access.ts, client/src/services/bms/api.ts, client/src/services/bms/mockApi.ts, client/src/services/bms/types.ts, client/src/services/bms/utils.ts
=> [MS] API for custom order invoices

client/src/components/organizations/OrganizationCard.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/home/HomePage.vue, client/src/views/home/HomePageHeader.vue, client/src/views/home/HomePageSidebar.vue, client/src/views/home/OrganizationListPage.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/client_area_login.spec.ts, client/tests/e2e/specs/client_forgotten_password.spec.ts, client/tests/e2e/specs/home_page.spec.ts, client/tests/e2e/specs/settings_modal.spec.ts
=> [MS] Polish details homepage

client/src/components/viewers/controls/FileControlsDropdown.vue, client/src/components/viewers/controls/FileControlsDropdownItem.vue, client/src/components/viewers/controls/FileControlsDropdownPopover.vue, client/src/components/viewers/index.ts, client/src/components/viewers/types.ts, client/src/views/viewers/SpreadsheetViewer.vue, client/src/views/viewers/VideoViewer.vue, client/tests/e2e/specs/file_viewers.spec.ts
=> [MS] FileControlsDropdown & FileControlsDropdownItem

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/fileOpener.ts, client/src/services/viewers.ts, client/src/theme/global.scss, client/src/views/viewers/TextViewer.vue
closes #9057 
closes #9031
- add fullscreen control
- configure editor style to harmonize with the rest of the app
- improve loading & error handling
=> [MS] Improve TextViewer UI/UX

.github/workflows/releaser.yml
Correcting a mistake I made in #9308
=> Fix releaser CI configuration

libparsec/crates/client/src/workspace/transactions/fd_flush.rs, libparsec/crates/client/tests/unit/workspace/fd_flush.rs, libparsec/crates/client/tests/unit/workspace/outbound_sync_file.rs
=> Check `new_chunks` in `fd_flush` to properly reshape when flushing a file 

client/tests/e2e/helpers/assertions.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/create_organization.spec.ts, client/tests/e2e/specs/create_organization_custom.spec.ts, client/tests/e2e/specs/create_organization_saas.spec.ts, client/tests/e2e/specs/create_organization_trial.spec.ts, client/tests/e2e/specs/device_greet.spec.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/home_page.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts, client/tests/e2e/specs/user_greet.spec.ts, client/tests/e2e/specs/user_join.spec.ts, client/tests/e2e/specs/users_list.spec.ts
=> [MS] Fixed e2e tests

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/invite.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/invite/claimer.rs, libparsec/src/invite.rs
=> Remove unused function claimerUserGetCreatedByUserInitialInfo

client/src/views/viewers/SpreadsheetViewer.vue, client/src/views/viewers/workers/spreadsheet_page_loader.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/file_viewers.spec.ts, client/tests/e2e/specs/file_viewers_image.spec.ts, client/tests/e2e/specs/file_viewers_spreadsheet.spec.ts
=> [MS] Updated e2e tests for spreadsheet

libparsec/crates/platform_mountpoint/src/unix/filesystem.rs, libparsec/crates/platform_mountpoint/src/unix/mount.rs, libparsec/crates/platform_mountpoint/src/windows/filesystem.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/mod.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/unix_permissions.rs, newsfragments/9389.bugfix.rst, server/tests/sequester_export/test_export.py
=> Set file permissions to 0o500 when the workspace is read-only on linux

.github/workflows/package-client.yml
=> [MS] Fixes electron build

client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue
=> [MS] Fixed empty home page when no devices

client/src/common/fileTypes.ts
=> [MS] Adds webm file format

client/src/common/fileTypes.ts
=> [MS] Fixed XLSX detected as zips

client/package-lock.json, client/package.json, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/fileOpener.ts
=> [MS] Resync megashark and fixes opening files in workspace history

client/src/components/viewers/controls/FileControlsInput.vue, client/src/locales/fr-FR.json, client/src/theme/components/action-bar.scss, client/src/views/home/HomePageSidebar.vue, client/src/views/sidebar-menu/SidebarMenuPage.vue
=> [MS] Missing visual changes

client/src/locales/en-US.json, client/src/views/organizations/creation/CreateOrganizationCustomServer.vue, client/src/views/organizations/creation/CreateOrganizationTrial.vue
=> [MS] Displays a better error message when creating an org with incompatible APIs

client/src/components/users/UserCard.vue, client/src/theme/components/grid.scss
=> [MS] Removed duplicate user profile in grid mode

server/parsec/templates/invitation_mail.html
Closes https://github.com/Scille/parsec-cloud/issues/9613
=> [MS] Fixed obsolete or invalid invitation email links

client/src/views/home/HomePage.vue
=> [MS] Fixed refresh device list when archiving a device

client/src/views/devices/ExportRecoveryDevicePage.vue, client/src/views/organizations/TOSModal.vue
=> [MS] Fixed missing org name in recovery file names

client/package-lock.json, client/package.json, client/src/theme/components/modals.scss, client/src/views/organizations/creation/OrganizationAuthenticationPage.vue
=> [MS] Scroll authentification modal

server/parsec/components/events.py, server/parsec/components/invite.py, server/parsec/components/memory/events.py, server/parsec/components/memory/invite.py, server/parsec/components/postgresql/events.py, server/parsec/components/postgresql/factory.py, server/parsec/components/postgresql/invite.py, server/parsec/components/postgresql/organization.py, server/parsec/components/postgresql/organization_update.py, server/parsec/components/postgresql/realm.py, server/parsec/components/postgresql/realm_create.py, server/parsec/components/postgresql/realm_rename.py, server/parsec/components/postgresql/realm_rotate_key.py, server/parsec/components/postgresql/realm_share.py, server/parsec/components/postgresql/realm_unshare.py, server/parsec/components/postgresql/sequester.py, server/parsec/components/postgresql/sequester_create_service.py, server/parsec/components/postgresql/sequester_revoke_service.py, server/parsec/components/postgresql/user.py, server/parsec/components/postgresql/user_create_device.py, server/parsec/components/postgresql/user_create_user.py, server/parsec/components/postgresql/user_freeze_user.py, server/parsec/components/postgresql/user_revoke_user.py, server/parsec/components/postgresql/user_update_user.py, server/parsec/components/postgresql/vlob.py, server/parsec/components/postgresql/vlob_create.py, server/parsec/components/postgresql/vlob_update.py, server/tests/api_v5/authenticated/test_events_listen.py, server/tests/test_cross_server_event.py, server/tests/test_sse.py
=> [Backport] Use send_signal to send events in postgresql server implementation

client/src/common/fileTypes.ts
=> [MS] Handle yaml file type

client/electron/src/index.ts
=> [MS] Updated how files are opened

client/src/views/users/BulkRoleAssignmentModal.vue
=> [MS] hide last step cancel button

client/package-lock.json, client/package.json
=> [MS] Resync megashark lib

client/src/views/viewers/FileViewer.vue
=> [MS] Hide download button on electron

server/parsec/cli/run.py
Fixup for #9722 
Already backported in `releases/3.3` for `v3.3.0-rc.10`
=> Fixup for handling the sse-keepalive option in the CLI 

client/src/parsec/organization.ts, client/tests/e2e/specs/organization_information.spec.ts, newsfragments/9723.bugfix.rst
=> [MS] Only count active users

client/src/components/files/types.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/fileOpener.ts, client/src/views/viewers/FileViewer.vue
=> [MS] Correctly update file on move

client/electron/src/index.ts, client/electron/src/setup.ts, client/src/main.ts
Closes #9736
The app initialization has two major problems.
- in the page itself, the init specific to Electron was not done sequentially, which could lead to that init being done before the page was fully initialized.
- on the Electron side, we would send the link without knowing if the page was fully initialized. It was especially visible on MacOS where we naively added a timeout.
Now the electron stuff is initialized sequentially, and we wait for the page to be fully initialized before sending the link.
=> [MS] Fixed app initialization

libparsec/crates/client/src/monitors/workspace_inbound_sync.rs, libparsec/crates/client/src/monitors/workspace_outbound_sync.rs, libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/src/workspace/transactions/outbound_sync.rs, libparsec/crates/client/tests/unit/client/with_monitors.rs, libparsec/crates/client/tests/unit/workspace/folder_transactions.rs, libparsec/crates/client/tests/unit/workspace_inbound_sync_monitor.rs
=> Manage confined entries in synchronization monitor

client/tests/e2e/specs/file_viewers_pdf.spec.ts
Not exactly proud of this fix but it does work.
=> [MS] Fixed flaky pdf viewer test

client/src/parsec/greet_user.ts, client/src/views/users/GreetUserModal.vue
=> [MS] Hide next button while user is created

client/src/services/bms/mockApi.ts, client/tests/e2e/helpers/bms.ts
=> [MS] Mock get invoices for custom order in playwright

libparsec/crates/client/src/monitors/workspace_inbound_sync.rs, libparsec/crates/client/src/monitors/workspace_outbound_sync.rs, libparsec/crates/platform_async/src/lib.rs, libparsec/crates/platform_async/src/native/mod.rs, libparsec/crates/platform_async/src/web/mod.rs, libparsec/crates/platform_async/tests/unit/mod.rs, libparsec/crates/platform_async/tests/unit/yield_now.rs
=> Fix yield in inbound outbound monitors

libparsec/crates/client/src/workspace/store/mod.rs, libparsec/crates/client/src/workspace/store/per_manifest_update_lock.rs, libparsec/crates/client/src/workspace/store/sync_updater.rs, libparsec/crates/client/src/workspace/transactions/inbound_sync.rs, libparsec/crates/client/tests/unit/workspace/inbound_sync_file.rs, libparsec/crates/tests_fixtures/src/moment_hook.rs
backport of #9756 on `release/3.3`
=> Backport simplify manifest update lock guard

client/src/components/files/FileDownloadItem.vue, client/src/components/files/index.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/fileOperationManager.ts, client/src/views/files/FileContextMenu.vue, client/src/views/files/FileOperationMenu.vue, client/src/views/files/FoldersPage.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/download_file.spec.ts, client/tests/e2e/specs/export_recovery_device.spec.ts
=> [MS] Includes downloads in the file operation menu

Cargo.lock, Cargo.toml, libparsec/crates/types/src/lib.rs
=> Bump rstest v0.24.0 & rstest_reuse v0.7.0

cli/src/commands/invite/device.rs, cli/src/commands/invite/shared_recovery.rs, cli/src/commands/invite/user.rs, cli/tests/integration/invitations/device.rs, cli/tests/integration/invitations/shared_recovery.rs, cli/tests/integration/invitations/user.rs
=> [CLI] Display invitation token on invitation creation.

cli/src/commands/organization/bootstrap.rs, cli/src/testenv_utils.rs, cli/tests/integration/device_option.rs, cli/tests/integration/organization/bootstrap.rs
=> [CLI] Support sequester in organization bootstrap.

cli/src/commands/organization/bootstrap.rs, cli/src/testenv_utils.rs, cli/tests/integration/device_option.rs, cli/tests/integration/organization/bootstrap.rs
Backport for 21011b8f201641d9d5228d50b4792f12d1a8d919 #9765 
Fix #9773
=> [Backport][CLI] Support sequester in organization bootstrap.

.github/workflows/package-cli.yml, misc/version_updater.py, newsfragments/9771.feature.rst
=> feat(CLI): Package CLI for windows

server/parsec/cli/inspect.py, server/parsec/cli/sequester_create.py, server/parsec/cli/sequester_list.py, server/parsec/cli/sequester_revoke.py, server/parsec/cli/utils.py, server/parsec/components/blockstore.py, server/parsec/components/memory/user.py, server/parsec/components/postgresql/realm_dump_realms_granted_roles.py, server/parsec/components/postgresql/user_test_dump_current_users.py, server/parsec/components/user.py, server/parsec/config.py, server/tests/api_v5/authenticated/test_user_create.py, server/tests/api_v5/authenticated/test_user_update.py
Backport of https://github.com/Scille/parsec-cloud/pull/9644 for `releases/3.3`
=> Backport fix server cli inspect

client/src/components/settings/SettingsList.vue, client/src/views/users/MyProfilePage.vue, client/tests/e2e/specs/settings_modal.spec.ts
=> [MS] Fix bug url profile feedback

.cspell/custom-words.txt, client/src/components/viewers/controls/FileControlsDropdownItem.vue, client/src/components/viewers/controls/FileControlsDropdownPopover.vue, client/src/components/viewers/controls/FileControlsFlux.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/viewers/AudioViewer.vue, client/src/views/viewers/VideoViewer.vue, client/src/views/viewers/utils.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/file_viewers.spec.ts, newsfragments/9750.feature.rst
Closes https://github.com/Scille/parsec-cloud/issues/9042 and https://github.com/Scille/parsec-cloud/issues/9045 (no issue on `loop`)
=> [MS] Add loop + picture in picture + playback speed in audio & video viewers

client/src/services/bms/access.ts, client/src/views/client-area/BmsLogin.vue, newsfragments/9616.bugfix.rst
Closes #9616 
Fixed the "remember me" checkbox, added a skeleton text for the checkbox on the BMS login page, made a few adjustements to reduce blinking, replaced v-if by v-show to avoid mounting all the elements once the page is loaded.
=> [MS] Fixed "remember me" for custom area and made a few adjustements

server/tests/common/client.py
=> Remove duplicated docstring from `server/tests/common/client.py`.

libparsec/crates/types/tests/unit/id.rs
=> Re-enable tests for OrganizationID/HumanHandle/DeviceLabel

client/src/views/organizations/OrganizationInformationPage.vue
Closes https://github.com/Scille/parsec-cloud/issues/9626
=> [MS] Add margin for chips in organization user info

libparsec/src/client.rs
=> Improve `libparsec` concurrent handling of start and stop on the same device

client/electron/src/index.ts
=> [MS] Fixed file opening

client/electron/src/index.ts, newsfragments/9849.bugfix.rst
=> [MS] Fixed error message when opening a file

client/src/components/users/types.ts, client/src/views/users/UsersPage.vue, newsfragments/9621.misc.rst
=> [MS] Hide Status sort options for users if all are active

client/src/router/types.ts, client/src/views/layouts/ConnectedLayout.vue, client/tests/e2e/specs/redirect.spec.ts
Closes #8776 
Difficult to fully test it with the mocks, but it should do the job.
=> [MS] Properly handle invalid URL

libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/tests/load.rs
=> Small cleanups in `platform_device_loader`

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/client-area/billing-details/BillingDetailsPage.vue, client/tests/e2e/specs/client_area_billing_details.spec.ts, newsfragments/9607.misc.rst
Closes https://github.com/Scille/parsec-cloud/issues/9607
=> [MS] Fix billing page issues

client/src/main.ts, client/src/parsec/history.ts, client/tests/e2e/specs/workspace_history.spec.ts
=> [MS] Added workspace history tests

.github/workflows/package-client.yml, .github/workflows/releaser.yml
=> feat(client): Package the macos client for arm64 architecture

client/src/locales/fr-FR.json, client/tests/e2e/specs/my_profile_page.spec.ts
=> [MS] Add tests profile page

client/src/components/organizations/OrganizationCard.vue
=> [MS] Use short date formatting for org card

client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/client_area_custom_order_contract.spec.ts, client/tests/e2e/specs/client_area_custom_order_statistics.spec.ts
=> [MS] Added tests for custom area multi org

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global-client.scss, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/dashboard/CustomOrderProcessingPage.vue
=> [MS] CustomOrder Processing Page

client/package-lock.json, client/package.json, client/src/components/organizations/OrganizationCard.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/inputs.scss, client/src/views/home/HomePage.vue, client/src/views/home/HomePageHeader.vue, client/src/views/home/OrganizationListPage.vue, client/tests/e2e/specs/home_page.spec.ts, newsfragments/9878.feature.rst
https://github.com/user-attachments/assets/817d9493-79cb-45d8-995e-1dd546282a92
closes #9523, closes #9515
=> [MS] Organization page responsive

libparsec/crates/platform_mountpoint/tests/unit/operations/mod.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/unix/mod.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/unix/setattr.rs
=> feat(mountpoint): Add test for setattr

client/src/components/files/FileCard.vue, client/src/components/files/FileDropZone.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/workspaces/WorkspaceCard.vue, client/src/theme/components/list.scss, client/src/theme/global.scss, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/workspace_history.spec.ts, client/tests/e2e/specs/workspace_sharing.spec.ts, client/tests/e2e/specs/workspaces_actions.spec.ts, newsfragments/9902.feature.rst
https://github.com/user-attachments/assets/55a65964-e97f-40e9-90ba-53f81d5981cd
closes #9511, closes #9531
=> [MS] File list responsive

client/src/services/bms/mockApi.ts, client/src/views/client-area/BmsLogin.vue, client/tests/e2e/helpers/bms.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/client_area_custom_order_contract.spec.ts, client/tests/e2e/specs/client_area_custom_order_invoices.spec.ts
=> [MS] Added e2e tests for custom order invoices

client/electron/package-lock.json, client/electron/package.json
=> [MS] Really use our repo of capacitor-electron

client/capacitor.config.ts, client/electron/package-lock.json, client/electron/package.json, client/package-lock.json, client/package.json
Added back capacitor-electron to client to get the commands.
Copied from https://github.com/Scille/parsec-cloud/pull/9896 without `electron-unhandled` because it breaks everything.
=> [MS] Update packages in electron/

libparsec/crates/platform_mountpoint/src/unix/mount.rs, libparsec/crates/platform_mountpoint/src/windows/mount.rs, libparsec/crates/platform_mountpoint/tests/unit/operations/mount_unmount.rs, newsfragments/9925.bugfix.rst
=> Backport sanitize mountpoint path name

client/src/common/fileTypes.ts, client/src/services/fileOpener.ts, client/src/views/layouts/ConnectedLayout.vue, client/src/views/viewers/AudioViewer.vue, client/src/views/viewers/FileViewer.vue, client/src/views/viewers/ImageViewer.vue, client/src/views/viewers/VideoViewer.vue, client/src/views/viewers/utils.ts, client/tests/unit/specs/testFileTypes.spec.ts
=> [MS] Updated how file detection is done

client/electron/package-lock.json, client/electron/package.json
=> [MS] Fixed app build

client/electron/src/index.ts, client/electron/src/setup.ts, newsfragments/9950.bugfix.rst
=> [MS] Fixed clicking on dock when app is opening on osx

client/capacitor.config.ts, client/electron/capacitor.config.ts, client/electron/src/index.ts, client/electron/src/setup.ts, client/electron/src/splashscreen.ts
Closes #9954 
Better to implement it ourselves rather than use capacitor-electron, it gives us more control.
=> [MS] Adds a splashscreen to electron

client/src/views/menu/DesktopMenu.vue
=> [MS] Hide upload menu when switch orgs

libparsec/crates/client_connection/src/error.rs
=> Improve AuthenticationTokenExpired error message

server/parsec/asgi/__init__.py
Base url of SPA into Parsec server is `/client`. So when user go to `/`, server redirect to `/client`. Then SPA homepage is `/home`. And final url is `/client/home`.
But if user refresh page, `/client/home` do not exist (404). So we must deal with this case by adding a fastapi middleware to response `index.html` file on 404 response.
=> add fastapi middleware to process SPA router

newsfragments/10011.bugfix.rst
Adding missing newsfragment for #10011
=> Add missing newsfragment for libparsec.log append message bugfix

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/config.py, bindings/web/src/meths.rs, client/src/parsec/internals.ts, client/src/parsec/organization.ts, client/src/plugins/libparsec/definitions.ts, client/src/views/testing/TestPage.vue, libparsec/src/config.rs, libparsec/src/lib.rs
=> feat(libparsec): Add log level in client config

client/src/components/workspaces/utils.ts, client/src/theme/components/_popovers.scss, client/src/views/files/FoldersPage.vue, client/src/views/files/SmallDisplayFileContextMenu.vue, client/src/views/files/index.ts, client/src/views/files/utils.ts, client/src/views/users/SmallDisplayUserContextMenu.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/SmallDisplayWorkspaceContextMenu.vue, client/src/views/workspaces/WorkspacesPage.vue
Closes https://github.com/Scille/parsec-cloud/issues/9502
=> [MS] Add small display versions of users/files/workspaces contextual menus

client/src/views/home/HomePageHeader.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/organizations/creation/OrganizationSummaryPage.vue
- On Safari, the SummarizePage when we create an organization, is oversize.
- On mobile, when no organization has been created, the organization creation isn't displayed correctly.
=> [MS] Fixed height SummarizePage +  No organization HomePage responsive

server/parsec/asgi/__init__.py
=> add user-agent to allow fastapi header

client/playwright.config.ts, client/src/views/files/FileDetailsModal.vue, client/tests/e2e/specs/file_details.spec.ts
- fix e2e tests
- remove clipboard copy/paste on web
=> [MS] FileDetailsModal web fixes

client/playwright.config.ts, client/src/views/workspaces/WorkspaceHistoryPage.vue, client/tests/e2e/specs/workspace_history.spec.ts
=> [MS] Updated workspace history e2e tests

libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/platform_device_loader/src/testbed.rs, libparsec/crates/platform_device_loader/src/web/error.rs, libparsec/crates/platform_device_loader/src/web/mod.rs, libparsec/src/client.rs
This PR renames `ChangeAuthentificationError` into `ChangeAuthenticationError` (_authentification_ is French)
=> Fix typo in ChangeAuthenticationError name

client/playwright.config.ts, client/tests/e2e/helpers/assertions.ts, client/tests/e2e/helpers/bms.ts, client/tests/e2e/helpers/data.ts, client/tests/e2e/specs/create_organization_custom.spec.ts, client/tests/e2e/specs/create_organization_saas.spec.ts
=> [MS] Reactivates client area e2e tests

client/playwright.config.ts, client/src/parsec/login.ts, client/src/views/layouts/DevLayout.vue, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/home_page.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts
=> [MS] Reactivated & updated profile tests

client/playwright.config.ts, client/tests/e2e/specs/device_greet.spec.ts
=> [MS] Reenabled greet/join devices e2e tests

.cspell/custom-words.txt, client/src/components/files/FileCard.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/header/SmallDisplayHeaderTitle.vue, client/src/components/small-display/SmallDisplayCategoryFileContextMenu.vue, client/src/components/small-display/SmallDisplayCategoryUserContextMenu.vue, client/src/components/small-display/SmallDisplayContextMenuButtons.vue, client/src/components/small-display/SmallDisplayFileContextMenu.vue, client/src/components/small-display/SmallDisplayUserContextMenu.vue, client/src/components/small-display/index.ts, client/src/components/users/types.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_popovers.scss, client/src/views/files/FoldersPage.vue, client/src/views/files/index.ts, client/src/views/files/types.ts, client/src/views/files/utils.ts, client/src/views/users/UserContextMenu.vue, client/src/views/users/UserGridDisplay.vue, client/src/views/users/UserListDisplay.vue, client/src/views/users/UsersPage.vue, client/src/views/users/utils.ts, client/src/views/workspaces/SmallDisplayWorkspaceContextMenu.vue, newsfragments/9505.feature.rst
Closes https://github.com/Scille/parsec-cloud/issues/9505
Goes along with https://github.com/Scille/parsec-cloud/pull/9964
=> [MS] Small display category context menus

client/package-lock.json, client/package.json, client/src/components/organizations/CreateOrganizationModalHeader.vue, client/src/theme/components/_modals.scss, client/src/views/client-area/BmsLogin.vue, client/src/views/client-area/forgot-password/BmsForgotPassword.vue, client/src/views/devices/GreetDeviceModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/users/BulkRoleAssignmentModal.vue, client/src/views/users/GreetUserModal.vue, client/src/views/users/UpdateAuthenticationModal.vue
As the title says, the aim is to remove all container from the close button modal.
Should be done when https://github.com/Scille/megashark-lib/pull/207 will be merged.
=> [MS] Removed `closeBtn-container`

client/src/components/devices/ChooseAuthentication.vue, client/src/components/organizations/ChooseServer.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_modals.scss, client/src/views/devices/ImportRecoveryDevicePage.vue, client/tests/e2e/specs/device_greet.spec.ts, client/tests/e2e/specs/user_greet.spec.ts
=> [MS] Avoid to scroll when choosing password authentification

client/playwright.config.ts, client/src/views/layouts/LoadingLayout.vue, client/tests/e2e/specs/organization_switch_popover.spec.ts
=> [MS] Organization switch popover web tests

libparsec/crates/client_connection/src/error.rs, libparsec/crates/serialization_format/src/protocol.rs, libparsec/crates/types/src/addr.rs, misc/gen_protocol_typings.py, server/tests/common/backend.py
So it can account for two words families
=> Fix protocol generation

client/src/theme/components/_modals.scss, client/src/views/users/BulkRoleAssignmentModal.vue
=> [MS] Added scroll to copy workspace role modal

.github/workflows/ci-docs.yml, .pre-commit-config.yaml, docs/locale/fr/LC_MESSAGES/userguide/installation.po, docs/locale/fr/LC_MESSAGES/userguide/troubleshooting.po, docs/poetry.lock, docs/pyproject.toml, docs/userguide/installation.rst, docs/userguide/troubleshooting.rst
=> Add a troubleshoot section about file operation issues with Finder on MacOS

client/electron/src/preload.ts, client/src/main.ts, client/src/plugins/libparsec/index.ts, client/src/services/bms/api.ts, client/src/services/bms/mockApi.ts, client/src/services/bms/types.ts, client/src/services/environment.ts, client/src/services/webLogger.ts
```typescript
// Example
async function sendBugReport(): Promise<void> {
const mockFiles = await import('@/parsec/mock_files');
// Query to BMS /feedback (fails currently because invalid data)
await BmsApi.reportBug(
{ name: 'Max', email: 'maxime.grandcolas@scille.fr', description: 'THIS IS A TEST' },
{ includeLogs: true, files: [{ name: 'hell_yeah.png', mimeType: 'image/png', data: await mockFiles.getMockFileContent(mockFiles.MockFileType.PNG) }]},
);
// Open logs in a new tab
await Env.Links.openLogs();
}
```
=> [MS] Added log API for web

client/src/main.ts, client/src/views/layouts/DevLayout.vue, client/tests/e2e/helpers/assertions.ts, client/tests/e2e/helpers/bms.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/greet.ts, client/tests/e2e/helpers/index.ts, client/tests/e2e/helpers/testbed.ts, client/tests/e2e/helpers/types.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/app_update.spec.ts, client/tests/e2e/specs/device_greet.spec.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts, client/tests/e2e/specs/invitations_popover.spec.ts, client/tests/e2e/specs/organization_information.spec.ts, client/tests/e2e/specs/user_details.spec.ts, client/tests/e2e/specs/user_greet.spec.ts, client/tests/e2e/specs/users_list.spec.ts, client/tests/e2e/specs/workspace_history.spec.ts, client/tests/e2e/specs/workspace_sharing.spec.ts
=> [MS] Reactivated some skipped e2e tests

.github/workflows/ci-docs.yml, docs/hosting/maintenance/backup_restore.rst, docs/hosting/maintenance/index.rst, docs/hosting/maintenance/upgrade_downgrade.rst, docs/locale/fr/LC_MESSAGES/hosting/maintenance/backup_restore.po, docs/locale/fr/LC_MESSAGES/hosting/maintenance/upgrade_downgrade.po, newsfragments/6174.doc.rst
The Server Maintenance section has been split into:
- Backup and Restore (new section, added in this PR)
- Upgrade and Downgrade (existing, was only moved) 
Closes #6174
=> Add docs for database and S3 backup

client/src/components/organizations/CreateOrganizationModalHeader.vue, client/src/theme/components/_modals.scss, client/src/views/client-area/BmsLogin.vue, client/src/views/home/HomePage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/organizations/creation/OrganizationNameAndServerPage.vue, client/src/views/organizations/creation/OrganizationNamePage.vue, client/src/views/organizations/creation/OrganizationSummaryPage.vue, client/src/views/organizations/creation/OrganizationUserInformationPage.vue, client/src/views/organizations/creation/ServerTypeChoice.vue
https://github.com/user-attachments/assets/29883539-ae56-429f-b782-5b3050f162d3
closes #10150
=> [MS] Create organization responsive

client/src/components/files/FileCard.vue, client/src/components/files/FileGridDisplay.vue, client/src/components/files/FileUploadItem.vue, client/src/components/files/FolderSelectionModal.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_grid.scss, client/src/theme/components/_modals.scss, client/src/views/files/FileOperationMenu.vue, client/src/views/files/FoldersPage.vue, client/src/views/header/HeaderPage.vue, client/src/views/users/UsersPage.vue
The user can select an item by clicking on it on small display while clicking on any point on the file card.
https://github.com/user-attachments/assets/a0307750-9b89-4d55-8966-e4577ab7efbb
- [ x] Keep changes in the pull request as small as possible
closes #9512
=> [MS] Responsive file grid

client/src/theme/components/_popovers.scss, client/src/views/client-area/statistics/CustomOrderStatisticsPage.vue, client/tests/e2e/specs/client_area_custom_order_statistics.spec.ts
=> [MS] Updated custom order stats appearance

client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/users_list.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/10088
=> [MS] Added e2e tests for small display contextual menus

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/electron/src/setup.ts, client/src/main.ts
=> [MS] Fix electron opening with testbed server offline

client/package-lock.json, client/package.json, client/src/components/header/InvitationsButton.vue, client/src/components/header/SmallDisplayStepModalHeader.vue, client/src/components/sas-code/SasCodeChoice.vue, client/src/components/users/InvitationPopoverItem.vue, client/src/components/users/InvitationsListModal.vue, client/src/components/users/InvitationsListPopover.vue, client/src/components/workspaces/utils.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_modals.scss, client/src/views/files/FoldersPage.vue, client/src/views/home/HomePage.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/users/GreetUserModal.vue, client/src/views/users/UsersPage.vue, client/src/views/workspaces/WorkspaceSharingModal.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/device_greet.spec.ts, client/tests/e2e/specs/invitations_popover.spec.ts, client/tests/e2e/specs/user_greet.spec.ts
This PR includes the responsive of:
- The InvitationListModal when the invitation button is clicked
- The greeting process
- The joining process
- Cancelled modals
https://github.com/user-attachments/assets/bcf3f65a-5668-4330-a994-8fbac3766ae6
closes #10151, closes #10152
=> [MS] Join organization modal responsive

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/mockApi.ts, client/src/views/client-area/statistics/CustomOrderStatisticsPage.vue, client/tests/e2e/specs/client_area_custom_order_statistics.spec.ts
=> [MS] Show CustomOrderStats if org is bootstrapped

client/package-lock.json, client/package.json, client/src/components/workspaces/WorkspaceUserRole.vue, client/src/components/workspaces/utils.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_list.scss, client/src/theme/components/_modals.scss, client/src/views/workspaces/WorkspaceSharingModal.vue, client/src/views/workspaces/WorkspacesPage.vue, client/tests/e2e/specs/workspace_sharing.spec.ts
=> [MS] Responsive - Workspace share Modal

README.rst
Some links were broken and some descriptions outdated.
=> Minor fixes and improvements to main README

client/package-lock.json, client/package.json, client/src/components/workspaces/WorkspaceCard.vue
=> [MS] Update workspace favorite icon position

client/src/views/client-area/forgot-password/BmsForgotPasswordGetEmailStep.vue
=> [MS] Trim email in forgotten password

client/src/views/header/HeaderPage.vue, client/tests/e2e/specs/my_profile_page.spec.ts
=> [MS] Show back button when on profile page

client/.gitignore, client/src/views/client-area/ClientAreaPage.vue, client/src/views/client-area/orders/NewOrderModal.vue, client/src/views/client-area/orders/OrdersPage.vue, client/tests/e2e/specs/client_area_custom_order_orders.spec.ts
Adds e2e tests for requesting a new org with custom order, adds a confirmation when requesting a new org, disable the send request button while a request is being made.
=> [MS] Adds confirmation when ordering new org and adds e2e tests

.cspell/custom-words.txt, client/package-lock.json, client/package.json, client/src/parsec/environment.ts
=> [MS] Added a function to check if incognito mode

client/src/views/users/UsersPage.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/users_list.spec.ts
Closes #10289 
Also adds a fixture to test pages with a standard user.
=> [MS] Don't show user context menu if empty

client/src/views/client-area/personal-data/PersonalInfoModal.vue, client/src/views/client-area/personal-data/ProfessionalInfoModal.vue, client/src/views/client-area/personal-data/SecurityModal.vue
=> [MS] Disable buttons in custom area modals while query is being perfomed

client/src/locales/en-US.json
=> [MS] Fixed parsec-cloud link in English

.github/workflows/ci-rust.yml, Cargo.lock, Cargo.toml, deny.toml, libparsec/crates/platform_device_loader/Cargo.toml, libparsec/crates/platform_device_loader/src/lib.rs, libparsec/crates/platform_device_loader/src/native/mod.rs, libparsec/crates/platform_device_loader/src/web/error.rs, libparsec/crates/platform_device_loader/src/web/internal.rs, libparsec/crates/platform_device_loader/src/web/mod.rs, libparsec/crates/platform_device_loader/src/web/wrapper.rs, libparsec/crates/platform_device_loader/tests/units/archive.rs, libparsec/crates/platform_device_loader/tests/units/list.rs, libparsec/crates/platform_device_loader/tests/units/load.rs, libparsec/crates/platform_device_loader/tests/units/mod.rs, libparsec/crates/platform_device_loader/tests/units/remove.rs, libparsec/crates/platform_device_loader/tests/units/save_list.rs, libparsec/crates/platform_device_loader/tests/units/save_load.rs, libparsec/crates/platform_device_loader/tests/units/update_device_change_authentication.rs, libparsec/crates/platform_device_loader/tests/units/utils.rs, libparsec/crates/tests_fixtures/src/tmp_path.rs
=> Backport of #10259

client/src/components/header/SmallDisplayModalHeader.vue, client/src/components/header/SmallDisplayStepModalHeader.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_modals.scss, client/src/views/devices/DevicesPage.vue, client/src/views/devices/GreetDeviceModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/profile/OrganizationRecoveryPage.vue, client/src/views/users/GreetUserModal.vue, client/src/views/users/UpdateAuthenticationModal.vue, client/tests/e2e/helpers/greet.ts, client/tests/e2e/specs/device_greet.spec.ts, client/tests/e2e/specs/user_greet.spec.ts
https://github.com/user-attachments/assets/ccdb3e8d-2c12-43a3-96a3-59a6aebe81bd
https://github.com/user-attachments/assets/1cbfd951-6d57-4bdd-926d-2aa0b3de8490
closes #9545, closes #9548
=> [MS] Responsive profile modal update

server/poetry.lock, server/pyproject.toml
=> Downgrade cryptography to v43.0.3

client/src/router/types.ts, client/src/services/bms/access.ts, client/src/services/storageManager.ts, client/src/views/client-area/ClientAreaLoginPage.vue, client/src/views/client-area/ClientAreaPage.vue, client/src/views/home/HomePage.vue, client/tests/e2e/helpers/assertions.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/client_area_login.spec.ts, client/tests/e2e/specs/redirect.spec.ts
=> [MS] Fixed client area login when refreshing the page

client/src/plugins/libparsec/trampoline-web.ts
- Add log to indicate the mode `libparsec` is run
- Add event watcher for worker error
- Add event watcher for worker port error
=> refactor(libparsec-web): Add log on trampoline-web

client/package-lock.json, client/package.json, client/src/views/client-area/personal-data/PersonalDataPage.vue
Closes #10356 
- [X Keep changes in the pull request as small as possible
=> [MS] Disable updating the email when not using Stripe

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/smallDisplayWarning.ts, client/src/views/client-area/ClientAreaPage.vue, client/src/views/home/HomePage.vue, client/src/views/layouts/ConnectedLayout.vue
=> [MS] Shows a warning dialog on small displays

client/src/components/small-display/SmallDisplayCreateJoinModal.vue, client/src/theme/components/_modals.scss, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/LoginPage.vue, client/src/views/home/OrganizationListPage.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/organizations/creation/CreateOrganizationModal.vue, client/src/views/organizations/creation/OrganizationAuthenticationPage.vue, client/src/views/organizations/creation/OrganizationSummaryPage.vue, client/src/views/organizations/creation/ServerTypeChoice.vue, client/src/views/users/GreetUserModal.vue
=> [MS] Added scroll on OrganizationSummaryPage + miscellaneous

client/src/components/users/InvitationPopoverItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/users/UsersPage.vue, client/tests/e2e/helpers/greet.ts, client/tests/e2e/specs/invitations_popover.spec.ts
=> [MS] Adds a "send email" button to invitations

libparsec/crates/types/src/id.rs
Initially proposed by @mmmarcos with https://github.com/Scille/parsec-cloud/pull/10352#discussion_r2109269819
=> chore(types): Update comment about unicode for email

server/parsec/components/memory/account.py, server/parsec/components/memory/auth.py, server/parsec/components/memory/datamodel.py, server/tests/api_v5/authenticated_account/test_vault_key_rotation.py, server/tests/common/account.py
Closes https://github.com/Scille/parsec-cloud/issues/10451
=> feat(server): Add deleted_on on Account model

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/src/client/organization_info.rs, libparsec/src/client.rs
=> feat(bindings): Add organization_info

client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/components/files/types.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_list.scss, client/src/views/files/FoldersPage.vue, client/tests/e2e/specs/documents_list.spec.ts, newsfragments/10454.feature.rst
=> [MS] Creation date on file list

client/electron/package-lock.json, client/electron/package.json, client/electron/src/communicationChannels.ts, client/electron/src/setup.ts, client/electron/src/winRegistry.ts, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/storageManager.ts, client/src/views/about/LongPathsSupportModal.vue, newsfragments/10131.misc.rst
=> [MS] Detects disabled long paths support and displays a message

client/src/components/files/FileUploadItem.vue, client/src/theme/global.scss, client/src/views/viewers/FileViewer.vue, client/src/views/viewers/VideoViewer.vue
=> [MS] Fix video viewer on Firefox

client/src/components/account/AccountUserInformation.vue, client/src/components/devices/ChooseAuthentication.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/account.ts, client/src/parsec/types.ts, client/src/router/types.ts, client/src/router/watchers.ts, client/src/theme/components/_inputs.scss, client/src/theme/global.scss, client/src/views/account/AccountLoginPage.vue, client/src/views/account/CreateAccountPage.vue, client/src/views/home/AccountHomePage.vue, client/src/views/home/HomePageHeader.vue, client/src/views/home/LoginPage.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/specs/account_login.spec.ts, client/tests/e2e/specs/client_area_login.spec.ts, client/tests/e2e/specs/client_forgotten_password.spec.ts, client/tests/e2e/specs/home_page.spec.ts
=> [MS] Parsec Account creation page

client/package-lock.json, client/package.json, client/src/components/client-area/TimeFilterPopover.vue, client/src/components/client-area/invoices/InvoicesListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/bms/types.ts, client/src/services/translation.ts, client/src/theme/components/_popovers.scss, client/src/views/client-area/dashboard/DashboardPage.vue, client/src/views/client-area/invoices/CustomOrderInvoicesPage.vue, client/src/views/client-area/personal-data/PersonalInfoModal.vue, client/tests/e2e/specs/client_area_custom_order_invoices.spec.ts, client/tests/e2e/specs/client_area_invoices_page.spec.ts
=> [MS] Update invoice status for Custom Order

client/package-lock.json, client/package.json, client/src/views/client-area/payment-methods/CreditCardModal.vue
=> [MS] Fix CreditCardModal spinner position

server/parsec/templates/account_email_deletion.html, server/parsec/templates/account_email_validation.html, server/parsec/templates/email/base.css, server/parsec/templates/email/macros.html.j2, server/parsec/templates/invitation_mail.html
Closes #10589
<details>
<summary>Diff between 4d1e99306c and 46c40663b9:</summary>
```diff
diff --color -u --recursive 4d1e99306c/account_deletion_email.html 46c40663b9/account_deletion_email.html
--- 4d1e99306c/account_deletion_email.html	2025-06-19 15:51:36.000000000 +0200
+++ 46c40663b9/account_deletion_email.html	2025-06-20 10:30:50.697278639 +0200
@@ -72,13 +72,6 @@
/* content */
.content-wrapper .content-section {
display: block;
-}
-
-.content-wrapper .content-section.first-section {
-  margin-bottom: 24px;
-}
-
-.content-wrapper .content-section.second-section {
margin-bottom: 24px;
}
@@ -386,162 +379,168 @@
<td class="content-wrapper">
<table cellspacing="0" cellpadding="0" align="center" width="100%"
style="border-collapse: collapse;">
-                      <tr …
```
=> refactor(email-templates): Use macros to generate main content

server/parsec/templates/account_email_deletion.html, server/parsec/templates/account_email_validation.html, server/parsec/templates/email/base.html.j2, server/parsec/templates/invitation_mail.html
Closes #10591, closes #10594, closes #10595
<details>
<summary>Diff between 46c40663b9 and e99608ef8e:</summary>
```diff
diff --color -u --recursive 46c40663b9/account_deletion_email.html e99608ef8e/account_deletion_email.html
--- 46c40663b9/account_deletion_email.html	2025-06-20 10:30:50.697278639 +0200
+++ e99608ef8e/account_deletion_email.html	2025-06-20 11:22:47.087888547 +0200
@@ -336,13 +336,9 @@
<body>
-  <span class="preheader"
-    style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; mso-hide: all; visibility: hidden; width: 0;">
-    You have requested to delete your Parsec Account.
-  </span>
+  <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; mso-hide: all; visibility: hidden; width: 0;">You …
```
=> refactor(email-templates): Provide a base template for email

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/files/FoldersPage.vue, client/src/views/menu/MainMenu.vue, client/src/views/menu/TabBarOptions.vue, client/src/views/menu/TabBarOptionsModal.vue, client/src/views/menu/index.ts, client/src/views/menu/types.ts, client/src/views/menu/utils.ts, client/src/views/users/UsersPage.vue, client/tests/e2e/specs/options_tab_menu.spec.ts
Closes https://github.com/Scille/parsec-cloud/issues/9871
=> [MS] Tabbar contextual menu

client/src/components/header/HeaderBreadcrumbs.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/router/navigation.ts, client/src/services/eventDistributor.ts, client/src/views/home/HomePage.vue, client/tests/e2e/specs/workspace_history.spec.ts
=> [MS] Added error for a few missing events

client/src/services/bms/access.ts, client/src/services/bms/types.ts, client/src/views/client-area/personal-data/PersonalDataPage.vue, client/src/views/client-area/personal-data/PersonalInfoModal.vue
=> [MS] Fix client area personal info change with empty phone number

client/src/components/files/FileListDisplay.vue, client/src/components/files/FileListItem.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/file.ts, client/src/parsec/history.ts, client/src/parsec/types.ts, client/src/parsec/user.ts, client/src/views/files/FileDetailsModal.vue, client/tests/component/specs/testFileCard.spec.ts, client/tests/component/specs/testFileListItem.spec.ts, client/tests/e2e/specs/file_details.spec.ts
Depends on #10633 
Closes #10616
=> [MS] Display last updater

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/global.scss, client/src/views/devices/ImportRecoveryDevicePage.vue, client/src/views/home/HomePage.vue, client/src/views/home/HomePageHeader.vue, client/src/views/home/LoginPage.vue, client/src/views/home/OrganizationListPage.vue
https://github.com/user-attachments/assets/3fca1df7-6a58-4bd5-86d4-8d9e86b97bd2
closes #9522, closes #9524
=> [MS] Responsive recover password

client/src/components/account/AccountUserInformation.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/parsec/account.ts, client/src/parsec/types.ts, client/src/services/environment.ts, client/src/views/account/AccountLoginPage.vue, client/src/views/account/CreateAccountPage.vue, client/src/views/home/HomePageHeader.vue, client/tests/e2e/specs/account_create.spec.ts
Closes #10498
Waiting for #10431
=> [MS] Create account using bindings

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/client.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/certif/store.rs, libparsec/crates/client/src/client/mod.rs, libparsec/crates/client/src/client/organization_info.rs, libparsec/crates/client/tests/unit/client/organization_info.rs, libparsec/src/client.rs
=> Expose `get_bootstrap_date`.

client/src/components/header/SmallDisplayModalHeader.vue, client/src/components/header/SmallDisplayStepModalHeader.vue, client/src/components/organizations/CreateOrganizationModalHeader.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_modals.scss, client/src/views/devices/GreetDeviceModal.vue, client/src/views/home/DeviceJoinOrganizationModal.vue, client/src/views/home/UserJoinOrganizationModal.vue, client/src/views/users/BulkRoleAssignmentModal.vue, client/src/views/users/GreetUserModal.vue, client/src/views/users/UpdateAuthenticationModal.vue, client/tests/e2e/specs/options_tab_menu.spec.ts
=> [MS] Responsive copy workspace role

client/electron/src/communicationChannels.ts, client/electron/src/index.ts, client/electron/src/preload.ts, client/electron/src/setup.ts, client/src/components/files/FileInputList.vue, client/src/components/files/index.ts, client/src/components/misc/BugReportModal.vue, client/src/components/misc/LogDisplay.vue, client/src/components/misc/LogDisplayModal.vue, client/src/components/misc/index.ts, client/src/components/misc/utils.ts, client/src/components/settings/SettingsList.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/main.ts, client/src/services/bms/api.ts, client/src/services/environment.ts, client/src/services/webLogger.ts, client/src/theme/components/_modals.scss, client/src/views/header/ProfileHeaderOrganization.vue, client/src/views/header/ProfileHeaderOrganizationPopover.vue, client/tests/e2e/helpers/bms.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/bug_report.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts, client/tests/e2e/specs/profile_popover.spec.ts, client/tests/e2e/specs/settings_modal.spec.ts
Closes #10134
No newsfragment because it's hidden for now until the API is implemented on the server side.
=> [MS] Adds report bug modal and logs

newsfragments/5903.feature.rst
=> Add news fragment for custom branding

libparsec/crates/client/tests/unit/client/list_frozen_users.rs
=> Add test case for list frozen user.

client/tests/e2e/specs/organization_switch_popover.spec.ts
=> [MS] Unskip org switch test

bindings/electron/src/index.d.ts, bindings/electron/src/meths.rs, bindings/generator/api/workspace.py, bindings/web/src/meths.rs, client/src/plugins/libparsec/definitions.ts, libparsec/crates/client/src/workspace/mod.rs, libparsec/crates/client/src/workspace/transactions/open_file.rs, libparsec/crates/client/tests/unit/workspace/open_file.rs, libparsec/src/workspace.rs
=> Add is_file_content_local api.

client/src/plugins/libparsec/trampoline-web.ts, client/src/plugins/libparsec/web_shared_worker.ts
=> Fix error handling in web bindings when calling a non-existing function or providing the wrong param types

client/src/components/header/InvitationsButton.vue, client/src/components/workspaces/utils.ts, client/src/views/files/utils.ts, client/src/views/header/HeaderPage.vue, client/src/views/home/HomePage.vue, client/src/views/menu/TabBarMenu.vue, client/src/views/menu/TabBarOptions.vue, client/src/views/users/utils.ts
Closes https://github.com/Scille/parsec-cloud/issues/10023
=> [MS] Disabled expandToScroll on sheet modals

client/src/components/files/HistoryFileListItem.vue, client/src/components/header/HeaderBreadcrumbs.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_popovers.scss, client/src/views/header/HeaderPage.vue, client/src/views/menu/MainMenu.vue, client/src/views/workspaces/WorkspaceHistoryPage.vue, client/tests/e2e/helpers/assertions.ts, client/tests/e2e/specs/home_page.spec.ts, client/tests/e2e/specs/options_tab_menu.spec.ts, client/tests/e2e/specs/profile_popover.spec.ts, client/tests/e2e/specs/workspace_history.spec.ts
=> [MS] Responsive workspace history

client/src/router/types.ts, client/src/views/files/FoldersPage.vue, client/src/views/files/utils.ts, client/src/views/viewers/FileViewer.vue, client/tests/e2e/helpers/data.ts, client/tests/e2e/specs/file_viewers.spec.ts, client/tests/e2e/specs/home_page.spec.ts
- Update the download feature from the file viewers to use the fileOperationManager, so that downloads get added to the file operations menu
- Added the file operation menu to the viewers, so that the download is showing
- Fixed playwright with SSL
- Little bit of factorization for download
- Added a test for download from the file viewers
=> [MS] Updated download from file viewers

.pre-commit-config.yaml, server/parsec/components/postgresql/sequester_create_service.py, server/parsec/components/postgresql/sequester_get_service.py, server/parsec/components/postgresql/sequester_revoke_service.py, server/parsec/components/postgresql/sequester_update_config_for_service.py
=> Fix sqlfluff linter errors in sequester component

.pre-commit-config.yaml, server/parsec/components/postgresql/events.py, server/parsec/components/postgresql/sequester_create_service.py, server/parsec/components/postgresql/sequester_get_service.py, server/parsec/components/postgresql/sequester_revoke_service.py, server/parsec/components/postgresql/sequester_update_config_for_service.py
=> Fix sqlfluff linter errors in events component

client/tests/e2e/specs/account_manage.spec.ts
=> [MS] Fix: Update password test (1-digit day of the month)

.pre-commit-config.yaml, server/parsec/components/postgresql/pki.py
=> Fix sqlfluff linter errors in pki

.pre-commit-config.yaml, server/parsec/components/postgresql/queries/q_auth_lock_common_only.py, server/parsec/components/postgresql/queries/q_auth_no_lock.py, server/parsec/components/postgresql/queries/q_lock_realm.py, server/parsec/components/postgresql/queries/q_lock_shamir.py
=> Fix sqlfluff linter errors in common queries

.pre-commit-config.yaml, server/parsec/components/postgresql/realm_create.py, server/parsec/components/postgresql/realm_dump_realms_granted_roles.py, server/parsec/components/postgresql/realm_export_do_base_info.py, server/parsec/components/postgresql/realm_export_do_blocks_metadata_batch.py, server/parsec/components/postgresql/realm_export_do_certificates.py, server/parsec/components/postgresql/realm_export_do_vlobs_batch.py, server/parsec/components/postgresql/realm_get_current_realms_for_user.py, server/parsec/components/postgresql/realm_get_keys_bundle.py, server/parsec/components/postgresql/realm_rename.py, server/parsec/components/postgresql/realm_rotate_key.py, server/parsec/components/postgresql/realm_share.py, server/parsec/components/postgresql/realm_unshare.py, server/parsec/components/postgresql/user_get_certificates.py
=> Fix sqlfluff linter errors in realm

.pre-commit-config.yaml, server/parsec/components/postgresql/shamir_delete.py, server/parsec/components/postgresql/shamir_setup.py
=> Fix sqlfluff linter errors in shamir

.pre-commit-config.yaml, server/parsec/components/postgresql/user.py, server/parsec/components/postgresql/user_create_user.py, server/parsec/components/postgresql/user_freeze_user.py, server/parsec/components/postgresql/user_get_certificates.py, server/parsec/components/postgresql/user_get_user_info.py, server/parsec/components/postgresql/user_list_active_users.py, server/parsec/components/postgresql/user_list_frozen_users.py, server/parsec/components/postgresql/user_revoke_user.py, server/parsec/components/postgresql/user_test_dump_current_users.py, server/parsec/components/postgresql/user_update_user.py
=> Fix sqlfluff linter errors in user

.pre-commit-config.yaml, server/parsec/components/postgresql/test_queries.py
=> Fix sqlfluff linter errors in test queries

client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/utils.ts, client/tests/e2e/specs/account_invitation.spec.ts, client/tests/e2e/specs/download_file.spec.ts, client/tests/e2e/specs/workspace_history.spec.ts, client/tests/e2e/specs/workspace_sharing.spec.ts
=> [MS] Adds e2e tests for archive download

docs/development/README.md, docs/development/how-to-debug-github-actions.md, docs/development/how-to-log-with-sentry.md, docs/hosting/deployment/index.rst, docs/rfcs/1000-shamir-based-recovery.md, docs/rfcs/1008-nightly-build.md, docs/rfcs/1009-hexstring-format.md, docs/rfcs/1012-workspace-mountpoint-integration.md
I did not correct typos under `rfcs/old`.
=> Fix typos found by codespell

client/src/components/small-display/SmallDisplayFileContextMenu.vue, client/src/services/environment.ts, client/src/views/files/FileContextMenu.vue, client/src/views/files/handler/FileHandler.vue, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/types.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/editics_enable.spec.ts, client/tests/e2e/specs/file_details.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts
Update in:
- Contextual menu popover (large & small display)
- Directly in the viewer
closes #10895
=> [MS] Hide Editics button not enabled

client/src/components/workspaces/utils.ts, client/src/services/recentDocuments.ts, client/src/views/menu/MainMenu.vue, client/tests/e2e/specs/documents_list.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts, client/tests/e2e/specs/sidebar.spec.ts
=> [MS] Update recent workspace on rename and added tests

server/parsec/templates/email/footer.html.j2, server/parsec/templates/email/invitation.html.j2
=> Upate social icons with server URL and invitation mail content

server/parsec/templates/email/account_create.html.j2, server/parsec/templates/email/account_delete.html.j2, server/parsec/templates/email/account_recover.html.j2, server/parsec/templates/email/base.css
=> [MS] Improve UI for account creation and deletion emails

client/src/components/settings/SettingsList.vue, client/src/components/settings/SettingsOption.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_modals.scss, client/src/views/account/AccountSettingsPage.vue, client/src/views/home/HomePage.vue, client/src/views/home/HomePageHeader.vue, client/src/views/users/MyProfilePage.vue, client/tests/e2e/specs/account_login.spec.ts, client/tests/e2e/specs/my_profile_page.spec.ts, client/tests/e2e/specs/profile_popover.spec.ts
https://github.com/user-attachments/assets/a160821f-1f35-4878-b621-6a8538e05f26
https://github.com/user-attachments/assets/3ab54925-f0b7-4450-8926-40444155a21c
closes #10954,
closes #10952,
closes #10912
=> [MS] Improve settings list and some design tweaks

client/src/components/account/AccountUserInformation.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/views/account/CreateAccountPage.vue, client/src/views/account/RecoverAccountPage.vue, client/tests/e2e/specs/account_create.spec.ts
https://github.com/user-attachments/assets/0136713a-8873-4121-8dda-156bcf339d9d
closes #10983
=> [MS] Improve UI and add back button (Create account)

client/src/main.ts, client/src/views/layouts/ConnectedLayout.vue
=> [MS] Adds warning when refreshing the page when logged in

client/src/components/account/AccountUserInformation.vue, client/src/services/environment.ts, client/src/views/account/AccountLoginPage.vue, client/src/views/account/RecoverAccountPage.vue
=> [MS] Fixed account server scheme, validation and focus

client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/services/cryptpad.ts, client/src/views/files/handler/FileHandler.vue, client/src/views/files/handler/editor/FileEditor.vue, client/src/views/files/handler/viewer/FileViewer.vue, client/tests/unit/specs/testCryptpad.spec.ts
https://github.com/user-attachments/assets/570f9fc4-0947-45a7-9a7e-f12c620d00a3
closes #10896,
closes #10760
=> [MS] Error management file editor loading

client/playwright.config.ts, client/src/views/files/handler/FileHandler.vue, client/src/views/files/handler/editor/FileEditor.vue, client/tests/e2e/helpers/cryptpad.ts, client/tests/e2e/helpers/fixtures.ts, client/tests/e2e/helpers/types.ts, client/tests/e2e/specs/document_context_menu.spec.ts, client/tests/e2e/specs/file_editor.spec.ts, client/tests/e2e/specs/file_viewers.spec.ts, client/tests/e2e/specs/libparsec_without_shared_worker.spec.ts, client/tests/e2e/specs/options_tab_menu.spec.ts, client/vite.config.ts
Closes https://github.com/Scille/parsec-cloud/issues/10893
=> [MS] Tests for edition and read-only contextual menus

client/src/parsec/workspace.ts, client/src/services/recentDocuments.ts, client/src/views/header/HeaderPage.vue, client/src/views/menu/MainMenu.vue, client/tests/e2e/specs/sidebar.spec.ts, client/tests/e2e/specs/workspaces_actions.spec.ts, newsfragments/11056.bugfix.rst
Closes https://github.com/Scille/parsec-cloud/issues/11056
=> [MS] Fix workspace name update sync issue on header and sidebar

client/src/services/resourcesManager.ts, server/parsec/asgi/__init__.py, server/pyproject.toml
- Make client check more robust on `content-type` value
- Add redirection exclusion for server
Fix #11029
=> fix(custom): Fix custom branding detection

client/src/views/account/CreateAccountPage.vue, client/src/views/account/RecoverAccountPage.vue, client/src/views/home/AccountHomePage.vue
=> [MS] Slight improvement of account pages init

client/src/components/header/SmallDisplayStepModalHeader.vue, client/src/components/organizations/CreateOrganizationModalHeader.vue, client/src/components/organizations/SequesterKeyInput.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/theme/components/_modals.scss, client/src/views/client-area/BmsLogin.vue, client/src/views/organizations/creation/OrganizationCreatedPage.vue, client/src/views/organizations/creation/OrganizationNameAndServerPage.vue, client/src/views/organizations/creation/OrganizationNamePage.vue, client/src/views/organizations/creation/OrganizationSummaryPage.vue, client/tests/e2e/specs/create_organization.spec.ts, client/tests/e2e/specs/create_organization_custom.spec.ts, client/tests/e2e/specs/create_organization_saas.spec.ts
Update the create organization responsive (with sequester).
It fixed the multiple responsive and scroll issues on the creation process.
https://github.com/user-attachments/assets/8ec28424-83f2-405d-b34d-59a74dad53ca
closes #11085
=> [MS] Create organization responsive with sequester

client/src/views/files/handler/editor/FileEditor.vue, client/tests/e2e/specs/file_editor.spec.ts
=> [MS] feat: Replace fileId with a random UUID to limit edition to private sessions

client/src/parsec/file.ts, client/src/services/fileOperationManager.ts, client/src/views/files/FileOperationMenu.vue, client/src/views/files/FoldersPage.vue
Closes https://github.com/Scille/parsec-cloud/issues/11107
Closes https://github.com/Scille/parsec-cloud/issues/10054
=> [MS] Fix import cancel & import replace issues

Cargo.lock, libparsec/crates/platform_pki/Cargo.toml, libparsec/crates/platform_pki/examples/get_certificate_der.rs, libparsec/crates/platform_pki/examples/list_certificate.rs, libparsec/crates/platform_pki/examples/sign_message.rs, libparsec/crates/platform_pki/examples/utils/mod.rs, libparsec/crates/platform_pki/src/lib.rs, libparsec/crates/platform_pki/src/windows/mod.rs
(Windows only for now)
- Add an example that sign a provided message by using a referenced certificate.
=> feat(pki): Sign message using cert store

client/src/components/organizations/OrganizationUserInformation.vue, client/src/locales/en-US.json, client/src/locales/fr-FR.json, client/src/router/types.ts, client/src/views/invitations/InvitationSwitchModal.vue, client/src/views/invitations/InvitationsPage.vue, client/src/views/invitations/types.ts, client/tests/e2e/specs/organization_information.spec.ts
=> Access invitations page from organization page responsive

client/src/views/client-area/ClientAreaPage.vue, client/src/views/home/HomePage.vue, client/src/views/layouts/ConnectedLayout.vue, newsfragments/11190.misc.rst
=> [MS] Removed small displays warning

libparsec/crates/platform_mountpoint/src/unix/filesystem.rs
=> feat(mountpoint): Add info log when destroying a mountpoint

libparsec/crates/platform_pki/examples/decrypt_message.rs, libparsec/crates/platform_pki/examples/encrypt_message.rs, libparsec/crates/platform_pki/examples/sign_message.rs, libparsec/crates/platform_pki/src/lib.rs, libparsec/crates/platform_pki/src/windows/mod.rs
Used to identify which algorithm was used and which to use even tho we only support RSA for now
=> feat(pki): Add algorithm ID

client/src/components/files/explorer/FileCard.vue, client/src/components/files/explorer/FileListItem.vue, client/src/components/files/types.ts, client/src/main.ts, client/src/services/eventDistributor.ts, client/src/views/files/FoldersPage.vue, newsfragments/11057.feature.rst
=> [MS] Specific icon for a file being uploaded

.github/workflows/publish.yml
=> ci(publish): Missing handling `schedule` event for nightly build

.cspell/names.txt, docs/rfcs/1020-pki-support.md
=> docs(pki): Add RFC to document how an external PKI work with Parsec
