Scille/parsec-cloud

- parsec/core/fs/file_syncer.py
> Add concurrent upload to file sync

- parsec/core/cli/__init__.py
- parsec/core/cli/share_workspace.py
- tests/test_cli.py
Usage:
```console
parsec core share_workspace -D billy@laptop hello alice
```
To merge after #103.
>  Add share_workspace command to parsec core cli group 

- setup.py
> Import setuptools before cx_Freeze

- .travis.yml
- misc/run_test_environment.sh
- parsec/api/transport.py
- parsec/backend/app.py
- parsec/backend/cli.py
- parsec/backend/drivers/postgresql/user.py
- parsec/backend/user.py
- parsec/backend/vlob.py
- parsec/core/devices_manager/cipher.py
- parsec/core/devices_manager/manager.py
- parsec/core/devices_manager/pkcs11_cipher.py
- parsec/core/encryption_manager.py
- parsec/core/fs/local_folder_fs.py
- parsec/core/gui/main_window.py
- parsec/core/gui/register_device_dialog.py
- parsec/core/gui/register_user_dialog.py
- parsec/core/mountpoint/operations.py
- parsec/core/types/local_device.py
- parsec/core/types/local_manifests.py
- setup.cfg
- tests/common.py
- tests/core/mountpoint/test_fuse_file_operations.py
- tests/event_bus_spy.py
- tests/monitor.py
- tests/oracles.py
- tests/test_cli.py
In particular, it is quite useful to have F821 and F841 enabled:
- F821: undefined name
- F841:  local variable name is assigned to but never used
@Max-7 you might want to have a look at 2d0e8cf and 06b5b33 since those might be related to some bugs in the GUI.
>  Remove F841, E501 and F821 from the flake8 ignore list 

- parsec/serde/schema.py
> Improve serde perf

- parsec/backend/app.py
- parsec/backend/events.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/core/fs/test_local_file_fs.py
- tests/core/mountpoint/test_fuse_mount.py
- tests/core/test_messages_monitor.py
- tests/event_bus_spy.py
- tests/open_tcp_stream_mock_wrapper.py
Also update to pytest 4.2.0, update warning policy and fix a few of them.
>  Update to trio 0.11.0 and hypothesis-trio 0.3.0

- parsec/api/protocole/base.py
- parsec/serde/porcelaine.py
- tests/test_serde.py
> Fix repr for Serializer and CmdSerializer

- parsec/backend/drivers/postgresql/handler.py
- parsec/backend/drivers/postgresql/user.py
- tests/backend/user/test_device_invite.py
- tests/backend/user/test_user_invite.py
- tests/conftest.py
Allow to invite an user or a device with the same name across multiple organizations
> Fix invitations

- parsec/core/mountpoint/thread.py
> Use auto unmount for fuse mountpoint

- parsec/backend/user.py
> Fix possible event miss in backend claim APIs

- parsec/event_bus.py
Introduced in 2a4f90dec04791f6c4d161e0d1ee7f21fb942909
> Remove a debug warning in event_bus

- parsec/core/gui/lang.py
> Silence "no language in settings" warning to avoid spam in sentry

- tests/backend/test_vlob_group.py
closes #226
Ça pose la question du bien fondé de `backend.event_bus.spy`:
L'idée à la base est de remplacer `EventBus` dans les tests par `SpiedEventBus` qui fournit des outils en plus pour les tests (genre `listen` permettant de créer un objet `EventBusSpy` pour enregistrer tous les events envoyés).
Le truc c'est que pour obtenir l'historique complet des events (c'est à dire y compris les choses s'étant passé dans l'init des fixtures), le `SpiedEventBus` a été doté d'un `EventBusSpy` par défaut (le fameux `event_bus.spy`).
Et c'est là le soucis: bien souvent dans les tests on n'est pas intéressé par l'historiques des events (on veut plutôt écouter les event à partir du moment où on déclenche le truc qu'on teste), dans le cas actuelle on attendait 3 events `vlob_group.updated` sauf que …
> Fix flaky error in test_vlob_group_updated_event

- parsec/core/encryption_manager.py
- parsec/core/fs/file_syncer.py
- parsec/core/fs/folder_syncer.py
- parsec/core/fs/local_file_fs.py
- parsec/core/fs/local_folder_fs.py
- parsec/core/fs/remote_loader.py
- parsec/core/fs/sharing.py
- parsec/core/local_db.py
- parsec/core/logged_core.py
- tests/common.py
- tests/core/conftest.py
- tests/core/fs/test_local_file_fs.py
- tests/core/fs/test_local_folder_fs.py
- tests/core/test_local_db.py
> Rework local db

- parsec/api/protocole/vlob.py
- parsec/backend/drivers/memory/vlob.py
- parsec/backend/drivers/postgresql/block.py
- parsec/backend/drivers/postgresql/block_init.sql
- parsec/backend/drivers/postgresql/vlob.py
- parsec/backend/drivers/postgresql/vlob_init.sql
- parsec/backend/organization.py
- parsec/backend/vlob.py
- parsec/crypto.py
- tests/backend/test_vlob.py
> Remove generate token

- .appveyor.yml
- .travis.yml
- README.rst
Too many issues with coveralls :'(
> Replace coveralls by codecov

- .codecov.yml
- parsec/core/fs/file_syncer.py
- parsec/core/fs/local_folder_fs.py
>  Make sure the file still exists on the fs while syncing 

- parsec/core/gui/app.py
- parsec/core/gui/bootstrap_organization_widget.py
- parsec/core/gui/claim_user_widget.py
- parsec/core/gui/login_widget.py
- parsec/core/gui/main_window.py
- parsec/core/gui/trio_thread.py
- tests/gui/conftest.py
- tests/gui/test_bootstrap_organization.py
- tests/gui/test_claim_user.py
> [WIP] Improve GUI testability

- parsec/core/gui/file_items.py
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
> [GUI] Avoid filtering parent workspace or parent folder

- parsec/core/gui/file_items.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/workspaces_widget.py
> [GUI] Handle file synchronization

- parsec/backend/blockstore.py
- parsec/backend/config.py
- parsec/backend/raid5_blockstore.py
- tests/backend/test_block.py
- tests/conftest.py
Only the raid5_blockstore.py file and config changes for now, unit tests still not implemented
> First version of the raid5_blockstore

- parsec/__init__.py
- parsec/_version.py
- parsec/api/protocole/__init__.py
- parsec/api/protocole/handshake.py
- parsec/serde/fields.py
- tests/test_handshake.py
Added api_version field to handshake request and check for the client, raises HandshakeAPIVersionError if mismatch
> Added API versioning

- parsec/core/fs/entry_transactions.py
- parsec/core/fs/file_transactions.py
- parsec/core/fs/fs.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/fs/workspacefs.py
- parsec/core/gui/files_widget.py
- parsec/core/local_storage.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/thread_fs_access.py
- parsec/core/mountpoint/winfsp_operations.py
- tests/core/fs/conftest.py
- tests/core/fs/test_entry_transactions.py
- tests/core/fs/test_file_transactions.py
- tests/core/fs/test_fs_idempotent_sync.py
- tests/core/fs/test_fs_offline_restart_and_rwfile.py
- tests/core/fs/test_fs_offline_restart_and_tree.py
- tests/core/fs/test_fs_online_concurrent_tree_and_sync.py
- tests/core/fs/test_fs_online_rwfile_and_sync.py
- tests/core/fs/test_fs_online_tree_and_sync.py
- tests/core/fs/test_fs_sync.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/mountpoint/test_fuse.py
- tests/core/mountpoint/test_winfsp.py
- tests/core/test_cross_cores_sync.py
- tests/core/test_vlob_group_monitor.py
- tests/fuzzing/test_fuzz_core.py
- tests/oracles.py
Continue the work started with #370.
> Implement atomic transactions for entry operations

- parsec/core/gui/central_widget.py
- parsec/core/gui/custom_widgets.py
- parsec/core/gui/file_table.py
- parsec/core/gui/loading_dialog.py
- parsec/core/gui/menu_widget.py
- tests/gui/test_babel_extractor.py
- tests/gui/test_custom_widgets.py
- tests/gui/test_file_table.py
- tests/gui/test_input_dialogs.py
- tests/gui/test_loading_dialog.py
- tests/gui/test_menu.py
- tests/gui/test_workspace_button.py
Also includes some refactoring and a potential bug fix.
> [GUI] Added tests for simple widgets

- parsec/core/fs/userfs/userfs.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/fuse_runner.py
- parsec/core/mountpoint/manager.py
- parsec/core/mountpoint/thread_fs_access.py
- parsec/core/mountpoint/winfsp_operations.py
- parsec/core/mountpoint/winfsp_runner.py
- tests/core/mountpoint/conftest.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_fuse.py
> Update mountpoint module to the new workspace FS API

- parsec/core/config.py
- parsec/core/gui/color.py
- parsec/core/gui/forms/global_settings_widget.ui
- parsec/core/gui/forms/workspace_button.ui
- parsec/core/gui/global_settings_widget.py
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
Issue #219. Can be enabled in settings.
> [GUI] Added colors to workspaces

- parsec/core/fs/file_transactions.py
- parsec/core/fs/fs.py
- parsec/core/fs/workspacefs.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/workspaces_widget.py
- parsec/core/mountpoint/thread_fs_access.py
- parsec/core/types/base.py
- tests/common.py
- tests/core/fs/test_fs_sync.py
- tests/core/fs/test_workspace_fs.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/test_sync_monitor.py
- tests/core/test_vlob_group_monitor.py
- tests/fuzzing/test_fuzz_core.py
This should help with the removal of the FS class.
>  Add the pathlib/shutil-inspired interface to workspace fs 

- parsec/core/mountpoint/fuse_runner.py
- parsec/core/mountpoint/manager.py
- parsec/core/mountpoint/winfsp_runner.py
- tests/core/mountpoint/conftest.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/mountpoint/test_fuse.py
> Implement (almost) collision-safe mountpoint

- .appveyor.yml
- parsec/core/mountpoint/winfsp_operations.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/test_vlob_group_monitor.py
>  Fix type mismatch in readdir winfsp callback 

- parsec/core/backend_connection/__init__.py
- parsec/core/backend_connection/event_listener.py
- parsec/core/backend_connection/exceptions.py
- parsec/core/backend_connection/monitor.py
- parsec/core/backend_connection/transport.py
- parsec/core/gui/bootstrap_organization_widget.py
- parsec/core/gui/central_widget.py
- parsec/core/gui/main_window.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/logged_core.py
- parsec/core/vlob_groups_monitor.py
Integrating API versioning check between front and back to the GUI
> WIP: [GUI] API versioning

- .pre-commit-config.yaml
- setup.py
missing setup.py : updated black, added flake8
> Flake8 in pre commit

- parsec/core/fs/local_folder_fs.py
should fix https://ci.appveyor.com/project/touilleMan/parsec-cloud/builds/25043489
> Fix FSManifestLocalMiss legacy raise access

- parsec/core/gui/workspaces_widget.py
Quick fix, ça manque d'un test (et j'imagine que ce truc est en cours de rework de toute façon)
> Fix gui workspaces display with backend offline

- parsec/core/fs/workspacefs/sync_transactions.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/sync_monitor.py
Several hot fixes for issue #501, #502 and #503.
> Fix several synchronization issues

- parsec/core/persistent_storage.py
> Use synchronous=OFF for sqlite3 connection

- parsec/core/fs/workspacefs/entry_transactions.py
- parsec/core/fs/workspacefs/sync_transactions.py
- parsec/core/fs/workspacefs/workspacefs.py
- tests/core/fs/workspacefs/test_workspace_fs.py
> Cleaning up the fs module

- .appveyor.yml
- .travis.yml
> Fix coverage by using --cov-append

- parsec/core/fs/workspacefs/entry_transactions.py
- parsec/core/local_storage.py
- tests/core/fs/workspacefs/test_entry_transactions.py
> Do not remove the manifests from the local storage

- parsec/core/fs/workspacefs/workspacefs.py
Fixes: https://ci.appveyor.com/project/touilleMan/parsec-cloud/builds/26098902
> Protect _sync_by_id against race conditions on the entry 

- parsec/core/cli/utils.py
- parsec/core/fs/__init__.py
- parsec/core/fs/exceptions.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/forms/ts_ws_dialog.ui
- parsec/core/gui/forms/workspace_button.ui
- parsec/core/gui/parsec-gui.pro
- parsec/core/gui/ts_ws_dialog.py
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- parsec/core/mountpoint/exceptions.py
- parsec/core/mountpoint/manager.py
- tests/core/fs/workspacefs_timestamped/conftest.py
- tests/core/fs/workspacefs_timestamped/test_entry_transactions_timestamped.py
Add a timestamped WorkspaceFS from an already mounted workspace through the GUI
> [GUI] timestamped WS

- parsec/core/fs/userfs/userfs.py
- parsec/core/fs/workspacefs/entry_transactions.py
- parsec/core/fs/workspacefs/sync_transactions.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/local_storage.py
- parsec/core/persistent_storage.py
- parsec/core/types/local_manifests.py
- parsec/core/types/remote_manifests.py
- tests/core/fs/conftest.py
- tests/core/fs/userfs/test_sync.py
- tests/core/fs/workspacefs/test_file_transactions.py
- tests/core/fs/workspacefs/test_sync_transactions.py
- tests/core/fs/workspacefs_timestamped/conftest.py
- tests/core/fs/workspacefs_timestamped/test_entry_transactions_timestamped.py
- tests/core/fs/workspacefs_timestamped/test_workspacefs_timestamped.py
- tests/core/test_local_storage.py
- tests/core/test_persistent_storage.py
> Provide local manifests with a base manifest attribute 

- parsec/core/gui/custom_widgets.py
- parsec/core/gui/forms/message_dialog.ui
- parsec/core/gui/main_window.py
> [GUI] Added details to message dialog

- parsec/core/local_device/__init__.py
- parsec/core/local_device/utils.py
- tests/core/test_local_device.py
> Add local device's change_device_password

- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/forms/files_widget.ui
> [GUI] Added drag&drop from file explorer

- parsec/core/fs/userfs/userfs.py
- tests/core/fs/userfs/test_sharing.py
> Core shared event guaranteed

- parsec/core/backend_connection/event_listener.py
- parsec/core/backend_connection/monitor.py
- tests/common.py
- tests/conftest.py
- tests/core/backend_connection/test_anonymous_cmds.py
- tests/core/backend_connection/test_cmds.py
- tests/core/backend_connection/test_event_listener.py
- tests/core/backend_connection/test_porcelain.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/fs/userfs/test_sync.py
- tests/event_bus_spy.py
- tests/fixtures.py
- tests/open_tcp_stream_mock_wrapper.py
> Mutiple cleanups

- parsec/core/fs/workspacefs/entry_transactions.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/mountpoint/thread_fs_access.py
- tests/common.py
- tests/core/backend_connection/test_event_listener.py
- tests/core/fs/test_fs_idempotent_sync.py
- tests/core/fs/test_fs_online_concurrent_tree_and_sync.py
- tests/core/fs/test_fs_online_concurrent_user.py
- tests/core/fs/test_fs_online_rwfile_and_sync.py
- tests/core/fs/test_fs_online_tree_and_sync.py
- tests/core/fs/test_fs_online_user.py
- tests/core/fs/test_fs_realm_access_lost.py
- tests/core/fs/test_fs_sync.py
- tests/core/fs/test_reencrypt_workspace.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/fs/workspacefs/test_entry_transactions.py
- tests/core/fs/workspacefs/test_workspace_fs.py
- tests/core/fs/workspacefs_timestamped/conftest.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/test_cross_cores_sync.py
- tests/core/test_messages_monitor.py
- tests/core/test_sync_monitor.py
- tests/core/test_sync_monitor_stateful.py
- tests/fuzzing/test_fuzz_core.py
- tests/oracles.py
> Remove path argument from workspace.sync method

- parsec/api/data/__init__.py
- parsec/api/data/base.py
- parsec/api/data/manifest.py
- parsec/core/fs/local_storage.py
- parsec/core/fs/realm_storage.py
- parsec/core/fs/userfs/merging.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/types/__init__.py
- parsec/core/types/local_manifests.py
- parsec/core/types/manifest.py
- tests/core/conftest.py
- tests/core/fs/conftest.py
- tests/core/fs/test_local_storage.py
- tests/core/fs/userfs/test_merging.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/fs/userfs/test_sync.py
- tests/core/fs/workspacefs/test_entry_transactions.py
- tests/core/fs/workspacefs/test_file_transactions.py
- tests/fixtures.py
> UserManifest in api.data

- parsec/backend/app.py
- parsec/backend/cli.py
- parsec/backend/config.py
- parsec/backend/postgresql/handler.py
Added options for backend to set the min and max numbers of connections to Postgres
> Added options for the minimum and maximum number of backend connections 

- parsec/api/transport.py
> Specify `/ws` resource endpoint for backend connection

- parsec/core/gui/main_window.py
- parsec/core/gui/trio_thread.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/conftest.py
- tests/core/gui/test_color.py
- tests/core/gui/test_files.py
- tests/core/gui/test_trio_thread.py
> Make GUI tests more robust

- setup.py
```sh
$ pip install PyQt5==5.11.2
[...]
$ du -sh venv/lib/python3.7/site-packages/PyQt5
317M	venv/lib/python3.7/site-packages/PyQt5
$ pip install PyQt5==5.13.1
[...]
$ du -sh venv/lib/python3.7/site-packages/PyQt5
181M	venv/lib/python3.7/site-packages/PyQt5
```
> Upgrade PyQt5 dependency

- parsec/core/fs/exceptions.py
- parsec/core/fs/utils.py
- parsec/core/fs/workspacefs/entry_transactions.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/gui/trio_thread.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/fuse_runner.py
- parsec/core/mountpoint/manager.py
- parsec/core/mountpoint/thread_fs_access.py
- parsec/core/mountpoint/winfsp_operations.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/mountpoint/test_base.py
Fix #721 and some exception handling logic.
> Better handling of revoked workspace

- parsec/core/gui/app.py
fixed fonts scaling on wayland
> [GUI] Fix wayland scaling

- newsfragments/734.bugfix.rst
- parsec/core/fs/remote_loader.py
- parsec/core/fs/workspacefs/workspacefs.py
- tests/core/fs/test_fs_sync.py
- tests/core/fs/userfs/test_invalid_data.py
- tests/core/fs/workspacefs/test_invalid_data.py
> Add role certificate validity check when loading manifest in core

- .travis.yml
> Force `git fetch --tags` on travis to have consistent behavior from releaser.py

- parsec/core/gui/app.py
Fix scaling of QIcons on high DPI screens, which doesn't seem blurry as before (QImages were fine)
> [GUI] Fix high DPI pixmap scaling

- newsfragments/770.bugfix.rst
- parsec/core/mountpoint/thread_fs_access.py
- tests/core/mountpoint/test_base.py
> Fix rights checking in winfsp operations

- tests/core/gui/conftest.py
- tests/core/gui/test_files.py
- tests/core/gui/test_workspaces.py
> Fix inconsistent GUI tests

- parsec/backend/app.py
- parsec/backend/postgresql/user_queries/revoke.py
- tests/backend/user/test_user_revoke.py
- tests/conftest.py
https://github.com/Scille/parsec-cloud/projects/3#card-28814502
> [BACKEND] Close backend connection on user revokation 

- parsec/core/gui/about_widget.py
- parsec/core/gui/rc/misc/history.html
- parsec/core/gui/rc/resources.qrc
- setup.py
> [GUI] Generate the changelog from HISTORY.rst

- tests/backend/user/test_user_revoke.py
When the backend receive a `user_revoke` it 1) stores the revocation information in dabase and then 2) sends a `user.revoked` event that is processed to determine which connection to close.
The trick is there is a causality between 1) and 2) when running the tests with the mocked backend (given calling `event_bus.send(...)` dispatch to the callback directly).
On the other hand using PostgreSQL there is no guarantee a event will be processed by every consumer before the backend replied to the client.
The funny thing is this is hidden most of the time on linux given postgresql is really fast on it, but on appveyor the postgresql is really slow so we end up with this kind of flaky error that looks windows only (but is not ! ^^).
> Fix test_backend_close_on_user_revoke flaky error with postgresql

- newsfragments/819.misc.rst
- parsec/core/invite_claim.py
> Use an invitation token of 6 digits

- newsfragments/774.feature.rst
- newsfragments/777.feature.rst
- parsec/core/gui/app.py
- parsec/core/gui/forms/main_window.ui
- parsec/core/gui/main_window.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_en.ts
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/tr/parsec_fr.ts
#777 and #774 
Since the "Add New Instance" button is contained within the tabbar, it can  no longer be automatically hidden if there's only one tab (so tabs are always visible now).
The button only appears when there's no "Log-In" tab.
> [GUI] Reworked the tab system

- newsfragments/821.feature.rst
- parsec/core/gui/central_widget.py
- parsec/core/gui/forms/main_window.ui
- parsec/core/gui/instance_widget.py
- parsec/core/gui/main_window.py
> Tab changes color when an instance receives a notification

- parsec/core/fs/userfs/userfs.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspaces_widget.py
- tests/core/fs/userfs/test_invalid_data.py
- tests/core/gui/test_workspaces.py
- tests/core/mountpoint/test_base.py
> Prevent workspace create/rename with invalid name 

- newsfragments/838.bugfix.rst
- parsec/core/mountpoint/winfsp_operations.py
- parsec/core/mountpoint/winfsp_runner.py
- setup.py
- tests/core/mountpoint/test_winfsp.py
> Fix mountpoint label too long for WinFSP

- newsfragments/855.feature.rst
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/forms/files_widget.ui
- parsec/core/gui/forms/main_window.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_files.py
> [GUI] Added copy/cut/paste to file explorer

- newsfragments/884.bugfix.rst
- parsec/core/types/backend_address.py
- tests/core/test_backend_address.py
> Fix missing percent-encode of unicode organization_id in backend address

- newsfragments/885.bugfix.rst
- parsec/backend/memory/organization.py
- parsec/backend/postgresql/organization.py
- tests/backend/test_organization.py
> Allow recreation of a not yet bootstrapped organization

- newsfragments/881.bugfix.rst
- parsec/core/mountpoint/winfsp_runner.py
> Deal with broken links in base mountpoint directory on windows

- newsfragments/905.bugfix.rst
- parsec/core/mountpoint/winfsp_runner.py
> Safer fs.start for winfsp

- tests/test_scripts.py
~Let's give it another try :crossed_fingers:~
Didn't work out, but I'm still committing those changes.
> Fix test_run_testenv on windows

- tests/core/mountpoint/conftest.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_file_failures.py
- tests/core/mountpoint/test_file_operations.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/mountpoint/test_fuse.py
- tests/core/mountpoint/test_winfsp.py
> Improve mountpoint service fixture

- newsfragments/916.bugfix.rst
- parsec/core/gui/workspace_sharing_dialog.py
> [GUI] Prevent managers from inviting other users as managers

- newsfragments/920.bugfix.rst
- parsec/core/gui/files_widget.py
> [GUI] Clear display files on stat error

- setup.py
> Update to winfspy 0.7.0

- parsec/core/fs/workspacefs/workspacefs.py
- tests/core/fs/test_fs_offline_restart_and_rwfile.py
- tests/core/fs/test_fs_online_rwfile_and_sync.py
- tests/core/fs/workspacefs/test_workspace_fs.py
> Fix the write_bytes method

- newsfragments/927.bugfix.rst
- newsfragments/932.bugfix.rst
- parsec/core/gui/custom_widgets.py
- parsec/core/gui/devices_widget.py
- parsec/core/gui/forms/central_widget.ui
- parsec/core/gui/forms/devices_widget.ui
- parsec/core/gui/forms/main_window.ui
- parsec/core/gui/forms/menu_widget.ui
- parsec/core/gui/forms/users_widget.ui
- parsec/core/gui/forms/workspaces_widget.ui
- parsec/core/gui/main_window.py
- parsec/core/gui/users_widget.py
- parsec/core/gui/workspaces_widget.py
> [GUI] Fixes on low resolution (users/devices, menu bar)

- newsfragments/934.bugfix.rst
- newsfragments/935.bugfix.rst
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_en.ts
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/tr/parsec_fr.ts
> [GUI] Disable Paste button and display error when paste failed

- newsfragments/942.feature.rst
- newsfragments/944.feature.rst
- parsec/core/gui/forms/main_window.ui
- parsec/core/gui/main_window.py
> Fixed tab display

- .appveyor.yml
- parsec/core/fs/__init__.py
- parsec/core/fs/exceptions.py
- parsec/core/fs/workspacefs/file_transactions.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/thread_fs_access.py
- parsec/core/mountpoint/winfsp_operations.py
- parsec/core/mountpoint/winfsp_runner.py
- setup.py
- tests/core/mountpoint/test_winfsp.py
- tests/core/mountpoint/test_winfsp_tests.py
- tests/core/mountpoint/test_winfstest.py
... and add winfstest+winfsp-tests to the test suites
> Winfsp operations update

- newsfragments/981.bugfix.rst
- parsec/core/gui/file_table.py
> [GUI] Disable file operations for a reader

- newsfragments/980.bugfix.rst
- parsec/core/gui/files_widget.py
- parsec/core/gui/instance_widget.py
- parsec/core/gui/workspaces_widget.py
> [GUI] Fix files refresh when widget is hidden

- tests/scripts/run_testenv.py
> Set default gui variables for easier debugging

- parsec/core/gui/files_widget.py
- parsec/event_bus.py
Fix issue #971.
Also catch and log exceptions in event bus callbacks (eeb37f9)
> Fix sharing_updated_qt optional argument

- newsfragments/1001.bugfix.rst
- parsec/core/gui/files_widget.py
> [GUI] Fix invalid access to workspace_fs on event

- newsfragments/963.feature.rst
- parsec/core/gui/main_window.py
> [GUI] Only allows one login tab at all times

- newsfragments/1018.bugfix.rst
- parsec/core/mountpoint/fuse_runner.py
> Make _wait_for_fuse_ready more resilient

- newsfragments/1016.bugfix.rst
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/gui/workspaces_widget.py
- parsec/core/remote_devices_manager.py
> Fix gui reencryption need offline handling

- parsec/backend/memory/factory.py
- parsec/backend/postgresql/factory.py
- parsec/backend/utils.py
- parsec/core/backend_connection/authenticated.py
- parsec/service_nursery.py
- parsec/test_utils/organization.py
- tests/core/mountpoint/conftest.py
- tests/test_nursery.py
>  Add MultiError collapsing to open_service_nursery

- newsfragments/1039.bugfix.rst
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/mountpoint/winfsp_operations.py
- tests/core/mountpoint/test_base.py
> Fix marker issue in winfsp read_directory operation

- misc/releaser.py
> Fix releaser to allow comparaisons of 2 digits version numbers

- .azure-pipelines.yml
- misc/releaser.py
- newsfragments/1060.empty.rst
- newsfragments/README.rst
> Check newsfragment on PR

- parsec/core/cli/create_organization.py
> Fix missing fstring in create_organization cli

- newsfragments/1075.bugfix.rst
- parsec/core/types/backend_address.py
> Cli improvement

- newsfragments/1112.misc.rst
- packaging/win32/freeze_parsec.py
- packaging/win32/installer.nsi
> Update nsis installer for windows builds

- newsfragments/1085.feature.rst
- parsec/core/gui/forms/workspace_button.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspace_button.py
> [GUI] Added a contextual menu on workspace buttons

- newsfragments/1123.bugfix.rst
- parsec/utils.py
- tests/test_nursery.py
>  Decouple Cancelled() exceptions from MultiErrors

- newsfragments/1128.bugfix.rst
- parsec/core/mountpoint/winfsp_operations.py
- tests/core/mountpoint/test_winfsp.py
> Support replace_if_exists flag in the rename winfsp operation

- newsfragments/1139.feature.rst
- parsec/core/gui/app.py
- parsec/core/gui/forms/login_widget.ui
- parsec/core/gui/instance_widget.py
- parsec/core/gui/login_widget.py
- parsec/core/gui/main_window.py
- parsec/core/gui/parsec_application.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_en.ts
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/tr/parsec_fr.ts
> [GUI] Hide device from available devices

- newsfragments/1151.feature.rst
- newsfragments/1156.bugfix.rst
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/main_window.py
- parsec/core/gui/parsec_application.py
> [GUI] Added keyboard shortcuts and bugfix

- newsfragments/1210.bugfix.rst
- parsec/core/mountpoint/winfsp_runner.py
fix #1207 the proper way (not like #1208 :trollface: )
> Disable reject_irp_prior_to_transact0 option for WinFSP

- newsfragments/940.misc.rst
- parsec/core/config.py
- parsec/core/fs/storage/local_database.py
- parsec/core/ipcinterface.py
- parsec/core/local_device.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/fuse_runner.py
> Restrict read access for parsec directories to the current user

- parsec/core/mountpoint/winfsp_operations.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/mountpoint/test_winfsp_tests.py
- tests/core/mountpoint/test_winfstest.py
~Might fix #1232~
Does fix #1232 \o/
>  Immediate deletion in winfsp cleanup operation 

- newsfragments/1243.bugfix.rst
- parsec/core/gui/file_history_widget.py
> Fix FileHistoryButton typing error for setText on source

- newsfragments/1245.bugfix.rst
- parsec/core/gui/app.py
- setup.py
> Set the high DPI scale factor rounding policy to passthrough for Qt

- newsfragments/1184.bugfix.rst
- parsec/backend/memory/vlob.py
- parsec/backend/postgresql/block.py
- parsec/backend/postgresql/invite.py
- parsec/backend/postgresql/message.py
- parsec/backend/postgresql/organization.py
- parsec/backend/postgresql/queries.py
- parsec/backend/postgresql/realm_queries/create.py
- parsec/backend/postgresql/realm_queries/get.py
- parsec/backend/postgresql/realm_queries/maintenance.py
- parsec/backend/postgresql/realm_queries/update_roles.py
- parsec/backend/postgresql/user_queries/create.py
- parsec/backend/postgresql/user_queries/device_invitation.py
- parsec/backend/postgresql/user_queries/find.py
- parsec/backend/postgresql/user_queries/get.py
- parsec/backend/postgresql/user_queries/revoke.py
- parsec/backend/postgresql/user_queries/user_invitation.py
- parsec/backend/postgresql/vlob.py
- parsec/backend/vlob.py
- tests/backend/realm/test_block.py
- tests/backend/realm/test_reencryption_maintenance.py
- tests/backend/realm/test_roles.py
- tests/backend/realm/test_vlob_access.py
> Simplify SQL queries for block

- newsfragments/1239.bugfix.rst
- parsec/core/gui/file_history_widget.py
> [GUI] Fixed missing reject method on file history

- MANIFEST.in
- docs/hosting_server.rst
- newsfragments/1177.feature.rst
- parsec/backend/cli/run.py
- parsec/backend/client_context.py
- parsec/backend/config.py
- parsec/backend/invite.py
- parsec/backend/mail/__init__.py
- parsec/backend/mail/invite_mail.tmpl.html
- parsec/backend/memory/factory.py
- parsec/backend/postgresql/factory.py
- setup.py
- tests/conftest.py
I've written quite a lot of comments to highlight the issues I'm facing, mostly :
- I'm unsure about the place I've put the modifications in, if it should be inside the class or outside
- The email HTML text is huge and I'm not sure where it should be, clearly it's not ideal right now
- I don't know what email address will be used to send it, and I don't know how to secure its password while keeping the process automated
> WIP: Invitation email

- parsec/core/logged_core.py
- tests/core/gui/users_widget/test_invite.py
> Fix cancel user invitation

- parsec/core/gui/devices_widget.py
- tests/core/gui/test_password_change.py
> Fix device password change

- tests/core/gui/test_revoked_user.py
fix issue #1267
I ran it 50 times in the pipeline [there](https://dev.azure.com/Scille/parsec/_build/results?buildId=2001&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=1b8d0bba-f11a-562f-077c-1aaa5fdf35ee)
> Gui flaky test revoked user

- newsfragments/1295.bugfix.rst
- parsec/core/gui/main_window.py
> Gui close dialog force show top

- setup.py
Fix https://github.com/Scille/parsec-cloud/issues/1307
> Rollback to PyQt 5.14.2

- .azure-pipelines.yml
- newsfragments/1296.misc.rst
- packaging/snap/snap/snapcraft.yaml
> Add fuse package (required by libfuse2) to snapcraft

- tests/postgresql.py
> Make sure the asyncio event loops are closed in postgresql testbed

- parsec/core/gui/app.py
- parsec/core/gui/main_window.py
> No welcome screen if the invite link is clicked

- newsfragments/1321.bugfix.rst
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspace_button.py
> Fixed workspace title using UserId

- newsfragments/1335.bugfix.rst
- parsec/core/fs/__init__.py
- parsec/core/fs/exceptions.py
- parsec/core/fs/remote_loader.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/fs/workspacefs/workspacefs_timestamped.py
- parsec/core/remote_devices_manager.py
- tests/core/fs/userfs/test_sharing.py
- tests/core/fs/workspacefs/test_workspace_fs.py
- tests/core/gui/test_workspaces.py
> Translate remote devices manager exceptions to the fs module

- newsfragments/1330.feature.rst
- parsec/core/gui/central_widget.py
- parsec/core/gui/instance_widget.py
- parsec/core/gui/main_window.py
- parsec/core/gui/systray.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_offline.py
Display systray notification to make offline mode more obvious to the users
#1330
> Display systray notification on backend disconnected event

- newsfragments/1353.bugfix.rst
- parsec/core/gui/central_widget.py
> Do not display disconnected notification when login in

- newsfragments/1352.feature.rst
- parsec/core/gui/forms/greet_user_check_info_widget.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_en.ts
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/tr/parsec_fr.ts
- tests/core/gui/users_widget/test_greet.py
> [GUI] Added a warning when selecting the user role

- parsec/api/data/base.py
- parsec/api/data/certif.py
- parsec/api/data/manifest.py
- parsec/api/data/message.py
- parsec/api/protocol/types.py
- parsec/core/fs/storage/user_storage.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/fs/workspacefs/entry_transactions.py
- parsec/core/fs/workspacefs/sync_transactions.py
- parsec/core/types/manifest.py
- parsec/serde/__init__.py
- tests/core/fs/conftest.py
- tests/core/fs/storage/test_user_storage.py
- tests/core/fs/storage/test_workspace_storage.py
- tests/core/fs/userfs/test_merging.py
- tests/core/fs/userfs/test_sync.py
- tests/core/fs/workspacefs/test_file_operations.py
- tests/core/fs/workspacefs/test_file_transactions.py
- tests/core/fs/workspacefs/test_sync_transactions.py
- tests/schemas/api_data.json
- tests/schemas/builder.py
- tests/schemas/core_data.json
... except for `UserCertificateContent` and `DeviceCertificateContent`
To merge after #1248
> Make author field mandatory for all data classes

- .azure-pipelines.yml
Ubuntu system package needs to be updated, else there can be some broken downloaded package links. e.g. postgresql `Failed to fetch http://...postgresql amd64.deb  404  Not Found [IP: xxxx 80]`
> Fix broken Ubuntu Azure pipelines

- newsfragments/1385.bugfix.rst
- parsec/core/gui/files_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_workspace_sharing.py
> [GUI] Fixed error message when workspace is unshared and added tests

- parsec/core/gui/workspace_button.py
- tests/core/gui/test_workspace_sharing.py
> [GUI] Display workspace as private if all users it's shared with are revoked

- newsfragments/1398.bugfix.rst
- parsec/core/gui/main_window.py
- tests/core/gui/test_main_window.py
> Gui file link on opened organization

- newsfragments/1390.feature.rst
- parsec/core/gui/create_org_widget.py
- parsec/core/gui/forms/create_org_user_info_widget.ui
- parsec/core/gui/forms/create_org_widget.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/validators.py
- tests/common.py
- tests/conftest.py
- tests/core/gui/test_create_organization.py
> [GUI] Allows creation of an org on a custom backend

- newsfragments/1414.bugfix.rst
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspaces.py
> Fix gui open mountpoint when not mounted

- newsfragments/1412.bugfix.rst
- parsec/core/gui/workspaces_widget.py
> Fix uncatched BackendNotAvailable in GUI on offline list workspace

- docker-compose.yml
Added spontaneous bootstrap
Added binding for /tmp to /tmp (not ideal)
Configure PARSEC_BACKEND_ADDR from env
> Added spontaneous bootstrap and binding to docker-compose

- newsfragments/1391.bugfix.rst
- parsec/core/fs/storage/manifest_storage.py
- parsec/core/fs/workspacefs/workspacefile.py
- tests/core/fs/workspacefs/test_workspacefile.py
- tests/core/test_sync_monitor.py
> Fix issue with workspace files not being closed properly 

- newsfragments/1340.bugfix.rst
- parsec/core/backend_connection/authenticated.py
> Fix the reporting of exceptions with very long traces from the backend connection module

- newsfragments/1418.feature.rst
- parsec/core/gui/forms/sharing_widget.ui
- parsec/core/gui/workspace_sharing_widget.py
- tests/core/gui/test_workspace_sharing.py
> [GUI] Better display user role changes

- newsfragments/1423.feature.rst
- parsec/core/gui/forms/workspace_button.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspace_button.py
- tests/core/gui/test_workspace_button.py
> [GUI] Display workspace reencryption

- newsfragments/1345.bugfix.rst
- parsec/core/gui/create_org_widget.py
- tests/core/gui/test_create_organization.py
> [GUI] Fixed error message when org name already exists

- newsfragments/1405.feature.rst
- parsec/core/gui/central_widget.py
- parsec/core/gui/instance_widget.py
- parsec/core/gui/login_widget.py
- parsec/core/gui/main_window.py
- tests/core/gui/test_main_window.py
> GUI: Force login on file link click with not connected organization

- newsfragments/1473.feature.rst
- parsec/core/cli/create_organization.py
- parsec/core/cli/stats_organization.py
- parsec/core/cli/status_organization.py
- parsec/core/cli/utils.py
> Add parsec core cli envvar support

- tests/core/gui/test_workspaces.py
> Fix wrong unmounted assumption in gui test_workspaces

- newsfragments/1481.misc.rst
- parsec/core/gui/trio_thread.py
> Fix job result error repr

- newsfragments/1459.bugfix.rst
- parsec/core/gui/claim_device_widget.py
- parsec/core/gui/claim_user_widget.py
- tests/core/gui/devices_widget/test_claim.py
- tests/core/gui/users_widget/test_claim.py
> Disable validate button by default when chosing a password

- newsfragments/1456.feature.rst
- parsec/core/gui/login_widget.py
- tests/core/gui/conftest.py
- tests/core/gui/test_expired_organization.py
- tests/core/gui/test_login.py
- tests/core/gui/test_main_window.py
> [GUI] Ask password immediatly if only once device

- newsfragments/1453.bugfix.rst
- parsec/core/gui/main_window.py
- tests/core/gui/test_login.py
- tests/core/gui/test_main_window.py
> [GUI] Refresh devices list when logging out

- newsfragments/1455.bugfix.rst
- parsec/core/gui/main_window.py
- tests/core/gui/conftest.py
- tests/core/gui/test_login.py
- tests/core/gui/test_main_window.py
> [GUI] Fixed opening the GUI with a file link containing an unknown org

- newsfragments/1486.feature.rst
- parsec/core/config.py
- parsec/core/gui/app.py
- parsec/core/gui/main_window.py
- tests/core/gui/conftest.py
> [GUI] Remember the previous position and size of the window

- newsfragments/1454.feature.rst
- parsec/core/gui/central_widget.py
- parsec/core/gui/forms/workspaces_widget.ui
- parsec/core/gui/mount_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/users_widget.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspaces.py
> Display shared workspaces between two users

- newsfragments/1485.bugfix.rst
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
> [GUI] Fixed blinking reencrypt button

- newsfragments/1449.bugfix.rst
- parsec/core/gui/forms/devices_widget.ui
- parsec/core/gui/forms/users_widget.ui
> [GUI] Prevent unecessary scrolling for users and devices

- newsfragments/1497.empty.rst
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- setup.py
Closes #1497 
Lots of diffs in the translations files. It will be a problem for the current pull requests.
> [GUI] Fixed the order in which translations are extracted

- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspaces.py
Remove filter user when adding a new workspace
> Remove filter user when adding a workspace

- newsfragments/1495.bugfix.rst
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/workspace_sharing_widget.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspace_sharing.py
> [GUI] Refresh workspace list when closing the sharing dialog

- newsfragments/1447.bugfix.rst
- parsec/core/gui/forms/changelog_widget.ui
- parsec/core/gui/forms/devices_widget.ui
- parsec/core/gui/forms/license_widget.ui
- parsec/core/gui/forms/login_accounts_widget.ui
- parsec/core/gui/forms/settings_widget.ui
- parsec/core/gui/forms/users_widget.ui
- parsec/core/gui/forms/workspaces_widget.ui
- parsec/core/gui/main_window.py
- parsec/core/gui/parsec_application.py
- parsec/core/gui/rc/styles/main.css
- tests/core/gui/test_login.py
- tests/core/gui/test_main_window.py
- tests/core/gui/test_workspace_sharing.py
> [GUI] Fixed GUI style on MacOS

- newsfragments/1505.bugfix.rst
- parsec/core/gui/login_widget.py
- tests/core/gui/test_login.py
> [GUI] Hide return button on login screen when only one device

- newsfragments/1491.bugfix.rst
- parsec/core/gui/files_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_files.py
Closes #1491 
- displays a specific error message for PermissionDenied errors
- displays different messages depending on the number of files imported
> [GUI] Improved import files error messages

- newsfragments/1442.feature.rst
- parsec/core/gui/custom_widgets.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/forms/files_widget.ui
> Add table files spinner

- newsfragments/1525.bugfix.rst
- parsec/core/gui/desktop.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_files.py
> [GUI] Fix file open failure

- newsfragments/1515.bugfix.rst
- parsec/core/gui/workspaces_widget.py
> Clear workspace list when spinner is displayed

- newsfragments/1520.misc.rst
- parsec/core/gui/app.py
> [GUI] Log exceptions occuring in Qt slots

- newsfragments/1514.feature.rst
- parsec/core/gui/forms/sharing_widget.ui
- parsec/core/gui/forms/workspace_sharing_widget.ui
- parsec/core/gui/workspace_sharing_widget.py
- tests/core/gui/test_workspace_sharing.py
> [GUI] Added email in workspace sharing dialog

- newsfragments/1531.bugfix.rst
- parsec/core/gui/central_widget.py
- parsec/core/gui/mount_widget.py
- tests/core/gui/test_main_window.py
> GUI: mount workspace with link pointing to an unmounted workspace

- newsfragments/1544.bugfix.rst
- parsec/core/gui/claim_user_widget.py
- parsec/core/gui/create_org_widget.py
- parsec/core/gui/greet_user_widget.py
- parsec/core/gui/validators.py
- tests/core/gui/test_create_organization.py
> Trim user name

- mypy.ini
- parsec/api/__init__.py
- parsec/api/data/base.py
- parsec/api/data/certif.py
- parsec/api/data/entry.py
- parsec/api/data/invite.py
- parsec/api/data/invite_claim.py
- parsec/api/data/manifest.py
- parsec/api/data/message.py
- parsec/api/protocol/base.py
- parsec/api/protocol/events.py
- parsec/api/protocol/handshake.py
- parsec/api/protocol/invite.py
- parsec/api/protocol/types.py
- parsec/api/transport.py
- parsec/api/version.py
- parsec/serde/exceptions.py
- parsec/serde/schema.py
> Mypy on parsec.api

- parsec/logging.py
> Enable local timezone in logging messages

- newsfragments/1543.bugfix.rst
- parsec/core/gui/loading_widget.py
- tests/core/gui/test_loading_dialog.py
> [GUI] Fixed overflow in loading dialog

- newsfragments/1541.bugfix.rst
- parsec/core/gui/workspaces_widget.py
> [GUI] Fixed UnboundLocalError when opening a workspace in the file explorer

- misc/gui_widgets_debug.py
- newsfragments/1512.feature.rst
- parsec/core/gui/calendar_widget.py
- parsec/core/gui/forms/timestamped_workspace_widget.ui
- parsec/core/gui/rc/styles/main.css
- parsec/core/gui/timestamped_workspace_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
> [GUI] Reworked calendar widget

- newsfragments/1542.bugfix.rst
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspaces_widget.py
> [GUI] Added an error message when there are no drives available to mount a workspace

- newsfragments/1593.bugfix.rst
- parsec/backend/organization.py
- parsec/core/gui/create_org_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_create_organization.py
> Fix uncatched InviteNotFoundError during core bootstrap in GUI

- newsfragments/621.misc.rst
- parsec/core/gui/central_widget.py
- parsec/core/gui/devices_widget.py
- tests/core/gui/conftest.py
- tests/core/gui/test_password_change.py
> [GUI] Moved password change to a different location

- newsfragments/1619.bugfix.rst
- parsec/core/gui/workspaces_widget.py
> [GUI] Improved workspace loading (less reencryption queries)

- newsfragments/1611.misc.rst
- parsec/backend/app.py
- tests/backend/http/test_http.py
> Add early&cheap check in backend on incoming client request validity

- newsfragments/1638.misc.rst
- packaging/macOS/launch_script.py
- packaging/snap/bin/parsec
- packaging/win32/parsec-bootstrap.c
> Disable core file logging in packaging

- newsfragments/1646.bugfix.rst
- parsec/core/gui/forms/devices_widget.ui
- parsec/core/gui/forms/keys_widget.ui
- parsec/core/gui/rc/styles/main.css
> [GUI] Fixed style on MacOS with dark mode

- newsfragments/1634.bugfix.rst
- parsec/backend/cli/migration.py
- parsec/backend/cli/run.py
- parsec/backend/config.py
- parsec/backend/postgresql/factory.py
- parsec/backend/postgresql/handler.py
- setup.py
- tests/backend/test_postgres_db.py
- tests/conftest.py
> Postgres improved connection

- newsfragments/1658.bugfix.rst
- parsec/core/gui/workspaces_widget.py
> Fix WorkspacesWidget._on_fs_entry_updated_trio method

- .azure-pipelines.yml
- packaging/win32/installer.nsi
- setup.py
And winfsp version to 1.8.20304.
> Bump winfspy version to 0.8.2

- newsfragments/1665.bugfix.rst
- parsec/core/gui/flow_layout.py
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_files.py
- tests/core/gui/test_workspaces.py
> Fix blinking buttons by not re-instanciating the workspace buttons when refreshing the GUI

- parsec/core/config.py
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/file_table.py
- parsec/core/gui/main_window.py
- parsec/core/gui/new_version.py
- parsec/core/gui/settings_widget.py
- parsec/core/gui/workspace_button.py
- parsec/core/ipcinterface.py
- parsec/core/mountpoint/manager.py
- parsec/core/win_registry.py
- tests/backend/test_postgres_db.py
- tests/core/fs/test_fs_offline_restart_and_tree.py
- tests/core/fs/test_fs_online_tree_and_sync.py
- tests/core/fs/test_fs_online_user.py
- tests/core/fs/workspacefs/test_entry_transactions.py
- tests/core/fs/workspacefs/test_file_transactions.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/mountpoint/test_inconsistent_folder.py
- tests/core/mountpoint/test_winfsp_tests.py
- tests/core/mountpoint/test_winfstest.py
- tests/core/test_ipc.py
- tests/core/test_local_device.py
- tests/oracles.py
- tests/scripts/run_testenv.py
- tests/test_cli.py
- tests/test_scripts.py
> Standardise the way to identify platforms

- parsec/core/win_registry.py
> Make explicit psutil&winreg imports in parsec.core.win_registry

- parsec/core/mountpoint/fuse_runner.py
- tests/core/mountpoint/test_base.py
PR #1716 introduced some freezing in the CI.
This PR implements another approach to fix the issue.
> Fix a fuse issue where the shutdown procedure blocks forever, second edition

- parsec/core/cli/share_workspace.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/logged_core.py
- tests/test_cli.py
> Fix cli share_workspace

- newsfragments/1732.bugfix.rst
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
> Fix error handling for drag&drop in gui

- newsfragments/1758.misc.rst
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/users_widget.py
- tests/core/gui/users_widget/test_invite.py
> Add red color to remove widget dialogue confirmation button in GUI

- newsfragments/1761.bugfix.rst
- parsec/core/gui/flow_layout.py
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspace_button.py
> Add a mapping to workpaces widget in order to manage the workspace buttons

- parsec/core/gui/new_version.py
> Fix urlopen exception catching in gui new version check

- parsec/core/gui/app.py
- parsec/core/gui/central_widget.py
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/switch_button.py
- parsec/core/gui/trio_thread.py
- parsec/core/gui/workspaces_widget.py
- tests/conftest.py
- tests/core/gui/conftest.py
- tests/core/gui/test_file_history.py
- tests/core/gui/test_files.py
- tests/core/gui/test_main_window.py
- tests/core/gui/test_workspace_sharing.py
The non-hacky brother of #1739
fix #1740
> Replace QTimer in GUI by QtToTrioJobScheduler.submit_delayed_job

- newsfragments/1780.misc.rst
- parsec/backend/invite.py
- parsec/backend/templates/invitation_mail.html
- parsec/core/types/backend_address.py
- tests/backend/invite/test_base.py
> Host email images in backend and add tests on urls in emails

- parsec/core/fs/remote_loader.py
- parsec/core/gui/central_widget.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/fuse_runner.py
- parsec/core/mountpoint/winfsp_operations.py
- parsec/core/mountpoint/winfsp_runner.py
- parsec/core/types/base.py
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_folder_operations.py
- tests/core/mountpoint/test_inconsistent_folder.py
- tests/core/mountpoint/test_winfsp.py
> Add absolute path in mountpoint error events

- parsec/core/mountpoint/winfsp_runner.py
Fix https://dev.azure.com/Scille/parsec/_build/results?buildId=6843&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=0efb1b0d-5afc-53c9-1ac1-4093fcfe20f6&l=465
> Ignore FileSystemNotStarted exceptions in winfsp_mountpoint_runner teardown

- parsec/_subprocess_dialog.py
- parsec/core/gui/app.py
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/device_recovery_export_widget.py
- tests/core/gui/test_dialog.py
> Implement a much better way to deal with printer dialogs

- tests/core/mountpoint/test_base.py
Closes #1818, #1898, and #1911.
Issue #1935 has been created instead.
> Skip inconsistent Catalina mountpoint tests

- parsec/core/gui/instance_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
> Added detection for deprecated versions of macfuse

- tests/core/gui/test_expired_organization.py
Thanks @alexandrediasldev for the report
> Fix regression in test_expired_organization introduced in #1894

- parsec/api/data/certif.py
- parsec/api/data/invite.py
- parsec/api/protocol/__init__.py
- parsec/api/protocol/organization.py
- parsec/api/protocol/types.py
- parsec/api/rest.py
- parsec/backend/client_context.py
- parsec/backend/user.py
- parsec/backend/webhooks.py
- parsec/core/cli/recovery.py
- parsec/core/invite/claimer.py
- parsec/core/invite/greeter.py
- parsec/core/invite/organization.py
- parsec/core/local_device.py
- parsec/core/recovery.py
- parsec/core/types/local_device.py
- parsec/test_utils/organization.py
- tests/core/test_local_device.py
- tests/schemas/api_data.json
- tests/schemas/core_data.json
https://github.com/Scille/parsec-cloud/issues/1937
> Fix device_label size

- newsfragments/1983.feature.rst
- parsec/core/config.py
- parsec/core/fs/storage/chunk_storage.py
- parsec/core/fs/storage/workspace_storage.py
- parsec/core/fs/userfs/userfs.py
- parsec/core/logged_core.py
- tests/core/fs/storage/test_workspace_storage.py
> Expose the workspace cache size in the configuration file

- parsec/core/gui/navigation_bar_widget.py
> Specify navigation widget background color

- setup.py
Current solution found [here](https://github.com/pypa/pip/issues/6658).
> Fix libparsec file scheme in setup.py

- newsfragments/2037.misc.rst
- parsec/core/gui/authentication_change_widget.py
- parsec/core/gui/authentication_choice_widget.py
- parsec/core/gui/forms/password_authentication_widget.ui
> Specify background color in AuthenticationChangeWidget

- parsec/core/gui/workspace_sharing_widget.py
> Specify color in share workspace widget

- parsec/core/gui/validators.py
- parsec/core/gui/workspaces_widget.py
> [GUI] Fix workspace creation and renaming

- parsec/core/gui/device_recovery_import_widget.py
- parsec/core/gui/forms/authentication_choice_widget.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
> Fix title & color on device_recovery_import widget

- parsec/core/gui/devices_widget.py
> [GUI] Fixed device name display in devices list

- parsec/core/gui/files_widget.py
> [GUI] Fixed file drag&drop

- parsec/core/gui/workspaces_widget.py
> [GUI] Fix workspaces filtering

- parsec/api/protocol/handshake.py
https://github.com/Scille/parsec-cloud/issues/2118
> remove challenge size

- packaging/win32/pyinstaller.spec
> Fix a typo in pyinstaller.spec

- tests/core/gui/conftest.py
- tests/core/gui/devices_widget/test_claim.py
- tests/core/gui/test_authentication_change.py
- tests/core/gui/test_create_organization.py
- tests/core/gui/test_expired_organization.py
- tests/core/gui/test_file_history.py
- tests/core/gui/test_input_dialogs.py
- tests/core/gui/test_login.py
- tests/core/gui/test_recovery.py
- tests/core/gui/test_validators.py
- tests/core/gui/test_workspace_sharing.py
- tests/core/gui/users_widget/test_claim.py
- tests/core/gui/users_widget/test_list.py
.. as it started to behave weirdly on some systems (i.e. mine).
It is now an async method and waits for the keys to actually be taken into account by the corresponding text widget.
> Fix aqtbot.key_clicks in gui tests

- parsec/backend/postgresql/pki.py
- tests/backend/test_pki.py
Simplify submit command to look only at the latest entry for a certificate
> Only look at the latest entry for a certificate in a submit command

- newsfragments/2161.bugfix.rst
- packaging/snap/snap/snapcraft.yaml
- parsec/core/gui/custom_dialogs.py
> Fix the print dialog pop-up in snap builds (backport 2.7)

- parsec/api/data/manifest.py
- parsec/core/types/manifest.py
> Enforce BlockAccess.size to be strictly positive

- newsfragments/2178.bugfix.rst
- parsec/core/gui/login_widget.py
> [GUI] Fixed key event in login widget

- parsec/core/cli/pki.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/login_widget.py
- parsec/core/gui/main_window.py
- parsec/core/pki/submitter.py
- tests/core/gui/test_files.py
- tests/core/gui/test_main_window.py
> Fixed using a file link when disconnected

- newsfragments/2184.feature.rst
- parsec/core/gui/forms/login_no_devices_widget.ui
- parsec/core/gui/instance_widget.py
- parsec/core/gui/login_widget.py
- parsec/core/gui/main_window.py
- tests/core/gui/test_login.py
> [GUI] Added a recover device button when the list of devices is empty

- .azure-pipelines.yml
- oxidation/crates/parsec_api_types/src/addr.rs
- oxidation/libparsec_python/src/addrs.rs
- parsec/api/protocol/__init__.py
- parsec/api/protocol/cmds.py
- parsec/api/protocol/organization.py
- parsec/api/version.py
- parsec/backend/http.py
- parsec/backend/organization.py
- parsec/core/backend_connection/__init__.py
- parsec/core/backend_connection/anonymous.py
- parsec/core/cli/bootstrap_organization.py
- parsec/core/gui/create_org_widget.py
- parsec/core/invite/organization.py
- parsec/test_utils/organization.py
- setup.py
- tests/core/gui/test_create_organization.py
- tests/core/gui/test_validators.py
- tests/core/test_bootstrap_organization.py
- tests/open_tcp_stream_mock_wrapper.py
- tests/schemas/api_protocol.json
> Migrate organization_bootstrap command to ANONYMOUS_CMDS

- parsec/api/protocol/handshake.py
- parsec/api/version.py
- tests/api/test_handshake.py
- tests/backend/test_handshake.py
so we can later break the compatibility with version 2.4 and lower
> Bump api version to 3.0 

- newsfragments/2223.bugfix.rst
- parsec/core/gui/app.py
- parsec/core/gui/central_widget.py
- parsec/core/gui/main_window.py
- tests/core/gui/test_main_window.py
> [GUI] Fixed file link in some instances

- .azure-pipelines.yml
> Fix ci snapcraft login - backport 2.8

- newsfragments/2255.misc.rst
- parsec/api/protocol/pki.py
- parsec/backend/memory/pki.py
- parsec/backend/memory/user.py
- parsec/backend/pki.py
- parsec/backend/postgresql/pki.py
- parsec/core/backend_connection/anonymous.py
- parsec/core/backend_connection/cmds.py
- parsec/core/gui/enrollment_query_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/pki/exceptions.py
- parsec/core/pki/submitter.py
- tests/backend/common.py
- tests/backend/test_pki.py
- tests/backend/test_postgres_concurrency.py
- tests/schemas/api_protocol.json
> Pki submit email check

- .github/ISSUE_TEMPLATE/config.yml
> allow to create blank issues

- Cargo.lock
- oxidation/crates/parsec_api_crypto/Cargo.toml
- oxidation/libparsec_python/src/local_manifest.rs
In my machine:
model name: AMD Ryzen 7 3800X 8-Core Processor
cache size: 512 KB
cpu MHz: 3515.208 (min) - 4397.87 (max)
Data Size: 524 KB
Before: ~ 10 ms
Now: ~ 0.27 ms
> Improve evolve_as_block speed

- newsfragments/2339.misc.rst
- parsec/backend/http.py
- tests/backend/http/test_http.py
> Fix handling of non-ascii location in redirection

- newsfragments/2331.misc.rst
- parsec/core/gui/files_widget.py
- parsec/core/gui/validators.py
- tests/core/gui/test_validators.py
> [GUI] Added validators when entering file names

- parsec/core/gui/settings_widget.py
> Disabled minimize in tray checkbox on MacOS

- .azure-pipelines.yml
- tests/core/mountpoint/test_base.py
- tests/core/mountpoint/test_file_failures.py
- tests/core/mountpoint/test_file_operations.py
- tests/test_scripts.py
> Add MacOS 12 to CI

- newsfragments/2426.bugfix.rst
- parsec/core/gui/files_widget.py
> [GUI] Clear file table when entering a new workspace

- newsfragments/2411.bugfix.rst
- parsec/core/gui/files_widget.py
- parsec/core/gui/forms/files_widget.ui
- parsec/core/gui/forms/spinner_widget.ui
> [GUI] Fixed performance issues when loading a folder

- oxidation/crates/parsec_client_types/src/local_device.rs
- oxidation/libparsec_python/libparsec/types.py
- oxidation/libparsec_python/src/addrs.rs
- oxidation/libparsec_python/src/crypto.rs
- oxidation/libparsec_python/src/lib.rs
- oxidation/libparsec_python/src/local_device.rs
- parsec/core/types/local_device.py
- tests/rust/test_local_device.py
> Add LocalDevice binding

- docs/development/release.rst
- correct `complex`
- correct `being`
- correct `information`, it's a uncountable noun.
- correct `Alternatively`
> Correct typo on doc `Release Cheat-Sheet`

- newsfragments/2406.empty.rst
- parsec/core/config.py
- parsec/core/gui/forms/settings_widget.ui
> [GUI] Removed workspace_color option in settings

- parsec/core/mountpoint/fuse_runner.py
Also fix the random SIGPIPE crashes in the GUI tests.
> Make the workaround to fuse signal handling more robust

- oxidation/crates/parsec_api_crypto/src/sodiumoxide/hash.rs
- oxidation/crates/parsec_api_crypto/src/sodiumoxide/private.rs
- oxidation/crates/parsec_api_crypto/src/sodiumoxide/secret.rs
- oxidation/crates/parsec_api_crypto/src/sodiumoxide/sign.rs
- oxidation/crates/parsec_api_crypto/tests/hash.rs
- oxidation/crates/parsec_api_crypto/tests/private.rs
- oxidation/crates/parsec_api_crypto/tests/secret.rs
- oxidation/crates/parsec_api_crypto/tests/sign.rs
> Oxidation update libsodium

- newsfragments/2416.feature.rst
- parsec/core/gui/files_widget.py
- parsec/core/gui/forms/files_widget.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
> [GUI] Display the number of files in the current folder

- newsfragments/2512.bugfix.rst
- parsec/core/gui/files_widget.py
- parsec/core/mountpoint/fuse_runner.py
- tests/scripts/run_testenv.py
> More robust file listing when importing from the GUI

- newsfragments/2505.bugfix.rst
- parsec/api/version.py
- parsec/backend/memory/realm.py
- parsec/backend/postgresql/realm_queries/update_roles.py
- parsec/backend/realm.py
- parsec/backend/user_type.py
- parsec/core/fs/userfs/userfs.py
- tests/backend/realm/test_roles.py
- tests/core/fs/userfs/test_sharing.py
> Fix the propagation of the revoked status to other users

- packaging/snap/bin/parsec
- tests/scripts/run_testenv.py
> Do not create parsec directories in scripts

- newsfragments/2534.feature.rst
- parsec/core/gui/users_widget.py
- tests/core/gui/users_widget/test_list.py
> [GUI] Added an option to copy a user's email

- newsfragments/2531.feature.rst
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/files_widget.py
- tests/core/gui/test_input_dialogs.py
> [GUI] Select the file name when renaming a file

- oxidation/libparsec_python/Cargo.toml
- oxidation/libparsec_python/pyproject.toml
> rename generated artifact by libparsec python

- .github/workflows/linux-ci.yml
depends on #2639 
closes #2640
> add CI workflow to test python codebase on linux

- .github/workflows/windows-ci.yml
> Migrate Windows ci to Github action for python-only

- .github/workflows/windows-ci.yml
- tests/core/gui/conftest.py
- tests/test_cli.py
> Fix subprocess run on Windows for test_cli that could lead not to use the correct virtualenv

- .github/workflows/macos-ci.yml
> Migration MacOS CI to Github Action python-only part

- Cargo.lock
- oxidation/libparsec/crates/types/Cargo.toml
- oxidation/libparsec/crates/types/src/id.rs
- tests/api/test_types.py
> Add HumanHandle validation to rust implementation

- .github/workflows/linux-ci.yml
make env var `PYTEST_BASE_ARGS` to expand directly, this will log the value
of `PYTEST_BASE_ARGS` in the log of github action
> improve debugging

- .github/workflows/package-linux.yml
- The value version was not quoted, now sed will quote it.
- Added a line to debug the sed'ed file
- Trigger the workflow when it's edited
> Correct `Set snap build version`

- newsfragments/2694.bugfix.rst
- parsec/core/cli/share_workspace.py
- parsec/core/logged_core.py
> Fixed share_workspace CLI

- parsec/core/backend_connection/authenticated.py
> Gui sequester diplay

- .github/workflows/package-linux.yml
- parsec/backend/cli/sequester.py
- tests/test_cli.py
> Sequester export cli

- newsfragments/2708.feature.rst
- parsec/core/cli/__init__.py
- parsec/core/cli/reencrypt_workspace.py
- tests/test_cli.py
> Added reencrypt_workspace CLI

- parsec/core/gui/files_widget.py
- tests/core/gui/test_files.py
> [GUI] Fixed an import error with files without extensions

- packaging/macOS/create_dmg.sh
> Add a script for .dmg generation for MacOS packaging

- .github/workflows/linux-ci.yml
- .github/workflows/macos-ci.yml
- .github/workflows/windows-ci.yml
remove the step that was generating `pyqt` data since we run the command
in the `build.py` script
> Remove step `Generate PyQT GUI data`

- .github/workflows/test-python-ci.yml
- build.py
- oxidation/libparsec/crates/platform_async/src/native/timer.rs
- src/ids.rs
Maybe release mode can improve CI
> Make CI build in release mode

- newsfragments/2699.bugfix.rst
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspaces_reencrypt.py
> [GUI] Hide reencryption button when role is changed

- parsec/backend/asgi/administration.py
> Remove patch method on organisation stats

- oxidation/client/src/components/AlertConfirmation.ts
- oxidation/client/src/components/CreateOrganisationModal.vue
- oxidation/client/src/components/CreateOrganizationModal.vue
- oxidation/client/src/components/JoinByLinkModal.vue
- oxidation/client/src/components/SettingsOption.vue
- oxidation/client/src/views/HeaderPage.vue
- oxidation/client/src/views/MenuPage.vue
- oxidation/client/src/views/SettingsPage.vue
Add license headers to make `QA` happy on the main branch
> Add license headers

- .github/workflows/ci.yml
> Trigger `test-python-matrix` & `test-rust-matrix` on main branch

- .github/workflows/ci.yml
> Use official `PostgreSQL` APT repository to install `postgresql-12`

- .github/actions/paths-filter/action.yml
- .github/actions/paths-filter/filters.yml
- .github/workflows/ci.yml
- Add job to build the Vue webapp in the CI
> Build web app in CI

- oxidation/libparsec/crates/types/src/error.rs
- oxidation/libparsec/crates/types/src/manifest.rs
- oxidation/libparsec/crates/types/tests/test_manifest.rs
- oxidation/libparsec_python/src/manifest.rs
- parsec/_parsec.pyi
- parsec/_parsec_pyi/manifest.pyi
- parsec/api/data/__init__.py
- parsec/api/data/manifest.py
- parsec/core/fs/remote_loader.py
- parsec/core/fs/workspacefs/sync_transactions.py
- parsec/core/fs/workspacefs/workspacefs.py
- parsec/core/types/manifest.py
- parsec/sequester_export_reader.py
- src/lib.rs
- src/manifest.rs
- tests/api/test_types.py
- tests/core/fs/workspacefs/test_workspace_fs.py
- tests/schemas/builder.py
> Remove `_Py` classes in `manifest` python module

- .github/workflows/package-ci.yml
- packaging/snap/bin/parsec
- packaging/snap/bin/parsec-cli
- parsec/__init__.py
> Configure oscrypto with correct libraries when running with snap

- newsfragments/2839.bugfix.rst
- parsec/core/gui/claim_device_widget.py
- parsec/core/gui/claim_user_widget.py
- parsec/core/gui/create_org_widget.py
- parsec/core/gui/device_recovery_export_widget.py
- parsec/core/gui/device_recovery_import_widget.py
- parsec/core/gui/devices_widget.py
- parsec/core/gui/enrollment_widget.py
- parsec/core/gui/file_history_widget.py
- parsec/core/gui/file_status_widget.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/greet_device_widget.py
- parsec/core/gui/greet_user_widget.py
- parsec/core/gui/instance_widget.py
- parsec/core/gui/new_version.py
- parsec/core/gui/timestamped_workspace_widget.py
- parsec/core/gui/trio_jobs.py
- parsec/core/gui/users_widget.py
- parsec/core/gui/workspace_sharing_widget.py
- parsec/core/gui/workspaces_widget.py
> Trio job system relies on (qobject, signal name) instead of pyqtBoundSignal

- .github/workflows/package-ci.yml
- pyproject.toml
> Bump macos version in packaging CI

- .github/workflows/ci.yml
- .github/workflows/package-ci.yml
- docs/development/quickstart.rst
- Update the version used in the CI workflows.
- Update the documentation to reflect the actual version of `poetry` used.
> Migrate to `poetry-1.2.0`

- newsfragments/3022.bugfix.rst
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
> [GUI] Update cut status when overriden by a copy

- oxidation/client/README.md
- Use code-block for code snipet.
- Use quote-block for notes.
> Rewrite dev documentation for the Ionic client.

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- build.py
- oxidation/libparsec/crates/types/src/manifest.rs
- src/addrs.rs
- src/binding_utils.rs
- src/ids.rs
- src/invite.rs
- src/manifest.rs
- src/time.rs
See https://github.com/Scille/parsec-cloud/issues/3077 and https://github.com/Scille/parsec-cloud/issues/3078 for more information
> Chore clean binding_utils & use on manifest

- parsec/core/cli/run.py
- src/time.rs
This expose a method `from_rfc3339` for rust's DateTime type. close #3135
> Datetime rfc3339

- parsec/core/gui/workspace_button.py
- tests/core/gui/test_workspaces.py
> [GUI] Fixed workspace buttons displaying the wrong number of people

- .github/workflows/ci.yml
- oxidation/libparsec/crates/platform_async/src/lib.rs
- oxidation/libparsec/crates/platform_async/src/wasm32/sync/mod.rs
- oxidation/libparsec/crates/platform_async/src/wasm32/sync/watch.rs
- oxidation/libparsec/crates/types/src/time.rs
- parsec/core/backend_connection/authenticated.py
- parsec/core/logged_core.py
- parsec/core/sync_monitor.py
- parsec/utils.py
- src/lib.rs
- src/local_device.rs
- src/runtime.rs
- src/time.rs
- tests/common/freeze_time.py
- tests/core/backend_connection/test_authenticated_conn.py
- tests/core/fs/workspacefs/test_workspace_reencryption_need.py
- tests/core/gui/test_offline.py
- tests/core/test_messages_monitor.py
- tests/core/test_sync_monitor_stateful.py
- tests/test_time_provider.py
and use it to fix `test_process_while_offline`
> Add speed_factor feature to mock_time

- parsec/backend/postgresql/sequester_export.py
- parsec/sequester_export_reader.py
- tests/backend/sequester/test_export.py
> Change sequester sqlite timestamp to us

- parsec/_parsec_pyi/protocol.pyi
- parsec/api/protocol/invite.py
- parsec/backend/invite.py
- parsec/core/gui/greet_device_widget.py
- parsec/core/gui/users_widget.py
- parsec/core/logged_core.py
- src/protocol/invite.rs
- tests/backend/invite/test_manage_invitations.py
- tests/core/gui/devices_widget/test_greet.py
> Fully oxidize `InvitationEmailSentStatus`

- newsfragments/3198.feature.rst
- parsec/backend/cli/__init__.py
- parsec/backend/cli/migration.py
- parsec/backend/cli/sequester.py
- tests/backend/sequester/test_service.py
- tests/backend/test_administration_rest_api.py
- tests/test_cli.py
backport of #3231 for Parsec 2.13
> Backport 2.13 sequester cli offline splitup

- oxidation/libparsec/crates/protocol/schema/authenticated_cmds/invite_new.json
- oxidation/libparsec/crates/protocol/tests/test_invite.rs
- oxidation/libparsec/crates/types/src/ext_types.rs
- parsec/backend/invite.py
- parsec/core/cli/invitation.py
- src/protocol/invite.rs
- tests/core/gui/test_workspaces_reencrypt.py
> Fix type of `email_sent` field in `invite_new` command

- .github/scripts/check_newsfragments.py
When we've multiple newsfragment and only one is valid, the check may failed. Because it check the one that aren't valid and raise an exception before checking the valid one.
This rework the function that does the check in a manner that don't raise exception on validation error but will return `False` instead.
On top of that the function will return `None` for older news fragment, thus allowing to filter-out None element to see if the user have added a new newsfragment(s).
> Improve `check_newsfragment` check.

- docs/locale/fr/LC_MESSAGES/userguide.po
- docs/userguide/installation.rst
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
> Updated macFUSE installation doc

- HISTORY.rst
> Correct history formatting

- newsfragments/3302.bugfix.rst
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspaces_widget.py
- tests/core/gui/test_workspace_sharing.py
> [GUI] Updated how workspace are displayed when offline

- .github/workflows/ci.yml
- Cargo.toml
Add a custom profile for testing purpose that optimize the code, but keep the
debug assertions.
depends on #3309
> Create a custom profile for rust test

- parsec/backend/cli/sequester.py
- parsec/backend/http_utils.py
- parsec/backend/vlob.py
- tests/backend/sequester/test_vlob.py
> Update webhook to add service_id

- oxidation/libparsec/crates/platform_async/tests/eyeballs.rs
On the test `test_eyeballs` we check if it don't take too much time to execute. The minimal possible value for the test is `800ms` (`TIMEOUT * 2 + 300`). Previously we were adding 100ms for the overhead of async code but time to time the test will fail. Here we're adding another 100ms for the overhead and should drastically reduce the number of false positive
> Relax `test_eyeballs` expected delay timeout to 1s

- oxidation/libparsec/crates/serialization_format/src/protocol/intermediate/cmd.rs
Let's say we have introduced some fields in the version `2.3`. We can add new fields in a major release but those would be unstable since we can't unsure that all client/server use a version that include those fields, so they're wrapped in `Maybe`.
But when we release a new major version (the version `3.0` from the version `2.3`), those fields can now be considered stable and don't need the `Maybe` wrapping.
> Stabilize introduced field in previous version

- newsfragments/3269.bugfix.rst
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspace_sharing_widget.py
- parsec/test_utils/organization.py
- tests/core/gui/test_workspace_sharing.py
> Managers can not longer promote users to manager

- mypy.ini
- parsec/core/pki/accepter.py
- parsec/core/pki/plumbing.py
- parsec/core/pki/submitter.py
> Add mypy typing to `parsec.core.pki.*`

- mypy.ini
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/fuse_runner.py
- parsec/core/mountpoint/manager.py
- parsec/core/mountpoint/thread_fs_access.py
- parsec/core/mountpoint/winfsp_operations.py
- parsec/core/mountpoint/winfsp_runner.py
- parsec/core/mountpoint/winify.py
> Add mypy support `parsec.core.mountpoint.*`

- newsfragments/3109.misc.rst
- parsec/api/rest.py
- parsec/backend/asgi/administration.py
- parsec/backend/memory/block.py
- parsec/backend/memory/organization.py
- parsec/backend/memory/realm.py
- parsec/backend/organization.py
- parsec/backend/postgresql/organization.py
- parsec/cli_utils.py
- parsec/core/cli/__init__.py
- parsec/core/cli/stats_organization.py
- tests/backend/test_administration_rest_api.py
- tests/backend/test_server_stats.py
- tests/common/binder.py
- tests/test_cli.py
This PR adds support to exports server stats from the CLI as described in #3109. This close #3109
> Per organization stats cli

- newsfragments/3345.misc.rst
- parsec/core/cli/run.py
> Remove noop --timestamp param from `parsec core run` CLI command

- .github/workflows/ci.yml
- .github/workflows/package-ci.yml
- parsec/api/transport.py
- parsec/backend/asgi/administration.py
- parsec/backend/asgi/rpc.py
- parsec/backend/asgi/ws.py
- parsec/backend/vlob.py
- poetry.lock
- pyproject.toml
- tests/backend/sequester/test_vlob.py
- tests/conftest.py
requires https://github.com/pgjones/quart-trio/issues/3 to be fixed
> Upgrade to quart 0.18.0

- mypy.ini
- parsec/core/gui/color.py
> Add mypy typing for `core.gui.color`

- mypy.ini
- parsec/core/backend_connection/apiv1_anonymous.py
- parsec/core/backend_connection/cmds.py
- parsec/core/backend_connection/expose_cmds.py
- parsec/core/backend_connection/invited.py
- parsec/core/invite/organization.py
- parsec/core/pki/accepter.py
This PR enable mypy for `parsec.protocol.invite.*`
> Add mypy for `protocol.invite`

- mypy.ini
- parsec/core/gui/license_widget.py
- parsec/core/gui/loading_widget.py
- parsec/core/gui/login_widget.py
- parsec/core/gui/trio_jobs.py
> Add mypy core gui licence loading login widget

- mypy.ini
- parsec/core/gui/lang.py
This PR adds mypy typing to `core.gui.lang` module and closes #3432
> mypy: Added mypy typing to `core.gui.lang`

- mypy.ini
- parsec/core/gui/mount_widget.py
This PR adds mypy typing to module `parsec.core.gui.mount_widget`. This closes #3475
> mypy: Add mypy typing to `mount_widget`

- mypy.ini
- parsec/core/gui/organization_info_widget.py
> Mypy gui organization info widget

- mypy.ini
- parsec/core/gui/parsec_application.py
> Mypy gui parsec application

- mypy.ini
- parsec/core/gui/app.py
> Mypy gui app

- mypy.ini
- parsec/core/gui/instance_widget.py
- parsec/core/gui/main_window.py
This PR adds mypy typing for `parsec.core.gui.instance_widget`. This closes #3437
> mypy: Added mypy typing for `instance_widget`

- mypy.ini
- parsec/core/gui/file_history_widget.py
- parsec/core/gui/file_items.py
- parsec/core/gui/file_size.py
- parsec/core/gui/file_status_widget.py
- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
This PR adds mypy typing for modules `parsec.core.gui.file[s]*`. This closes #3440.
> Add mypy typing to `core.gui.file[s]*`

- mypy.ini
- parsec/core/local_device.py
> Add mypy core local device

- mypy.ini
- parsec/core/config.py
- parsec/core/gui/app.py
- parsec/core/gui/main_window.py
> mypy: Add mypy typing to `core.config`

- mypy.ini
- parsec/core/gui/greet_device_widget.py
- parsec/core/gui/greet_user_widget.py
> mypy: Added mypy typing for`greet_device_widget` and `greet_user_widget`

- mypy.ini
- parsec/_subprocess_dialog.py
- parsec/core/gui/custom_dialogs.py
- parsec/core/gui/custom_widgets.py
- parsec/core/gui/main_window.py
> Type `core.gui.custom_{widgets,dialogs}`

- mypy.ini
- parsec/core/gui/claim_user_widget.py
- parsec/core/gui/device_recovery_export_widget.py
- parsec/core/gui/device_recovery_import_widget.py
- parsec/core/gui/devices_widget.py
- parsec/core/gui/main_window.py
Adds mypy typing to 
- parsec/core/gui/device_recovery_export_widget.py
- parsec/core/gui/device_recovery_import_widget.py
- parsec/core/gui/devices_widget.py
closes #3426
> Add mypy typing `parse.core.gui.device[s]*`

- mypy.ini
- parsec/core/gui/notification_center_widget.py
- parsec/core/gui/notification_widget.py
> Mypy gui notification

- mypy.ini
- parsec/core/fs/remote_loader.py
- parsec/core/remote_devices_manager.py
This PR adds mypy typing to module `parsec.core.remote_devices_manager`. This closes #3484
> mypy: Added mypy typing for `remote_devices_manager`

- .github/workflows/ci.yml
- .github/workflows/package-ci.yml
- docs/development/quickstart.rst
- misc/setup-rust.sh
- oxidation/bindings/electron/src/meths.rs
- oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
- oxidation/libparsec/crates/client_connection/tests/utils/server.rs
- oxidation/libparsec/crates/client_types/src/local_device_file.rs
- rust-toolchain.toml
- src/certif.rs
- src/protocol/invite.rs
> Bump rust to version 1.65.0

- mypy.ini
- parsec/core/gui/__init__.py
- parsec/core/gui/timestamped_workspace_widget.py
This closes #3353. This also adds typing to `timestamped_workspace_widget`.
> Add mypy typing `core.gui.*`

- oxidation/generate_test_data/protocol/realm.py
- oxidation/generate_test_data/protocol/vlob.py
- oxidation/libparsec/crates/protocol/src/handshake.rs
- parsec/utils.py
- tests/backend/sequester/test_bootstrap_organization.py
> Increase ballpark window

- misc/generate_pyqt.py
- newsfragments/3335.bugfix.rst
- parsec/core/fs/exceptions.py
- parsec/core/fs/storage/local_database.py
- parsec/core/gui/files_widget.py
- parsec/core/gui/instance_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- tests/core/gui/test_files.py
> Log off the logged core when an operational error happens in the local storage

- parsec/core/gui/claim_user_widget.py
> Fix import

- HISTORY.rst
Correct `HISTORY.rst` formatting to correct a wrong formatted bullet point list.
> Correct `HISTORY.rst` formatting

- mypy.ini
- parsec/monitoring.py
This PR adds mypy typing to module `parsec.core.monitoring`. This closes #3511
> mypy: Add mypy typing for `monitoring`

- mypy.ini
- parsec/sequester_export_reader.py
> Mypy sequester export reader

- parsec/core/gui/workspace_button.py
- parsec/core/gui/workspace_roles.py
- parsec/core/gui/workspace_sharing_widget.py
- parsec/test_utils/organization.py
Workspace unsharing has been broken since 2.13, this is the fix for 2.14. It also includes some typing fixes and general improvements for workspace sharing.
Closes #3536
> [GUI] Fixed unsharing a workspace with someone

- newsfragments/3538.bugfix.rst
- parsec/backend/memory/user.py
- parsec/backend/postgresql/user_queries/find.py
- tests/backend/user/test_human_find.py
- tests/core/test_logged_core.py
> Update user search to include legacy users

- parsec/core/gui/validators.py
- tests/core/gui/test_validators.py
> Use HumanHandle to validate emails in the application

- mypy.ini
- parsec/backend/postgresql/handler.py
- parsec/core/mountpoint/manager.py
- parsec/stubs/trio_asyncio/__init__.pyi
- parsec/utils.py
> mypy: Added mypy typing for `core.utils`

- parsec/api/protocol/base.py
> Remove require_greeter_timestamp_rep_dump

- oxidation/generate_test_data/protocol/invite.py
- parsec/_parsec.pyi
- parsec/_parsec_pyi/enumerate.pyi
- parsec/_parsec_pyi/protocol.pyi
- parsec/api/protocol/invite.py
- parsec/backend/postgresql/invite.py
- parsec/core/cli/invitation.py
- parsec/core/invite/greeter.py
- parsec/core/logged_core.py
- src/enumerate.rs
- src/lib.rs
- src/protocol/events.rs
- src/protocol/invite.rs
- tests/backend/invite/test_manage_invitations.py
#3237 is blocked and outdated
closes #3232
> Oxidation update invite enum

- oxidation/libparsec/crates/client_types/src/lib.rs
- parsec/_parsec.pyi
- parsec/_parsec_pyi/enumerate.pyi
- parsec/api/protocol/base.py
- parsec/backend/app.py
- parsec/backend/asgi/rpc.py
- parsec/backend/client_context.py
- parsec/backend/invite.py
- parsec/backend/organization.py
- parsec/backend/ping.py
- parsec/backend/pki.py
- parsec/backend/utils.py
- src/enumerate.rs
- src/lib.rs
- tests/core/backend_connection/test_authenticated_cmds.py
- tests/core/backend_connection/test_authenticated_conn.py
> Oxidation client type

- mypy.ini
- parsec/core/mountpoint/fuse_runner.py
- parsec/win32.py
This PR adds mypy typing for `win32` module. This closes #3547
> mypy: Added mypy typing for `win32`

- mypy.ini
- parsec/types.py
> mypy: Add mypy typing to `types`

- oxidation/generate_test_data/protocol/pki.py
- parsec/api/data/__init__.py
- parsec/api/protocol/__init__.py
- parsec/api/protocol/pki.py
- parsec/backend/memory/pki.py
- parsec/backend/pki.py
- parsec/backend/postgresql/pki.py
- parsec/core/backend_connection/anonymous.py
- parsec/core/backend_connection/cmds.py
- parsec/core/cli/pki.py
- parsec/core/pki/accepter.py
- parsec/core/pki/plumbing.py
- parsec/core/pki/submitter.py
- parsec/core/types/__init__.py
- parsec/core/types/pki.py
- src/lib.rs
- tests/backend/test_pki.py
- tests/backend/test_postgres_concurrency.py
- tests/common/smartcard.py
- tests/fixtures.py
- tests/schemas/api_protocol.json
- tests/schemas/core_data.json
> Add EnrollmentID

- parsec/api/transport.py
- parsec/core/gui/files_widget.py
> Make Transport.recv more robust

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
> Update `flake8` & correct `pre-commit` hook

- parsec/_subprocess_dialog.py
- parsec/backend/postgresql/user_queries/find.py
- parsec/serde/packing.py
- tests/fuzzing/test_fuzz_core.py
- tests/monitor.py
Keep fixing issues flagged by [pyupgrade](https://github.com/asottile/pyupgrade).
* Use f-strings or format() instead of printf-style formatting.
* Avoid parentheses after decorator without arguments (default arguments).
> Fix more issues flagged by pyupgrade

- oxidation/bindings/android/libparsec/build.gradle
> Downgrade appcompat should fix CI

- misc/license_headers.py
- parsec/core/ipcinterface.py
- parsec/win32.py
Start fixing issues flagged by [pyupgrade](https://github.com/asottile/pyupgrade).
I have left out:
* suggestions related to type checking, as they are pervasive, and I am not sure if you would be willing to consider them,
* suggestions to change immutable lists such `[gen_date() for _ in range(4)]` into tuples such as `(gen_date() for _ in range(4))`, as you might find the result less readable.
> Fix a few issues flagged by pyupgrade

- parsec/core/mountpoint/fuse_operations.py
> Handle trio.RunFinishedError in fuse_operations

- oxidation/libparsec/crates/protocol/tests/test_block.rs
- oxidation/libparsec/crates/protocol/tests/test_common.rs
- oxidation/libparsec/crates/protocol/tests/test_events.rs
- oxidation/libparsec/crates/protocol/tests/test_invite.rs
- oxidation/libparsec/crates/protocol/tests/test_organization.rs
- oxidation/libparsec/crates/protocol/tests/test_realm.rs
- oxidation/libparsec/crates/protocol/tests/test_user.rs
- oxidation/libparsec/crates/protocol/tests/test_vlob.rs
> Chore protocol test

- oxidation/libparsec/crates/serialization_format/src/protocol/intermediate/cmd.rs
- oxidation/libparsec/crates/serialization_format/src/protocol/intermediate/collection.rs
> Speedup liparsec_protocol compilation

- oxidation/libparsec/crates/core_fs/Cargo.toml
Diesel crate compilation on my machine: 19s before vs 8s wit this fix
> Tweak Diesel features to speedup it compilation

- parsec/api/protocol/__init__.py
- parsec/api/protocol/types.py
- parsec/core/config.py
- parsec/core/local_device.py
- parsec/core/mountpoint/winfsp_operations.py
- parsec/test_utils/organization.py
- parsec/win32.py
- tests/backend/common.py
- tests/backend/test_postgres_db.py
This PR delete an unsed code in the codebase.
To identify dead code I did the following steps:
- Use [vulture](https://github.com/jendrikseipp/vulture) to list unused functions and their result's confidence
- Check if there's any reference using my lsp
- Look for any references in the whole codebase using `grep`
> Remove dead code in `parsec` and `tests`

- oxidation/libparsec/crates/serialization_format/Cargo.toml
- oxidation/libparsec/crates/types/Cargo.toml
> Remove uneeded features for syn and chrono deps

- parsec/core/local_device.py
> Fix parsec-extensions

- parsec/api/protocol/__init__.py
- parsec/api/protocol/sequester.py
- parsec/backend/postgresql/vlob.py
- parsec/backend/postgresql/vlob_queries/write.py
> Remove SequesterServiceIDField

- parsec/serde/fields.py
depends on #3636 
closes #3643 #3644
> Remove sequester key field

- parsec/api/data/__init__.py
- parsec/api/data/base.py
- tests/schemas/builder.py
> Remove base data

- .github/scripts/notary/script.sh
Rework the script to also add orphan PR to the board.
closes #3782
> Add pull-request to board using script

- parsec/api/protocol/handshake.py
- parsec/backend/asgi/rpc.py
- parsec/backend/asgi/ws.py
- parsec/backend/client_context.py
- parsec/backend/handshake.py
- tests/backend/test_rpc_handshake.py
- tests/backend/test_ws_handshake.py
- tests/common/rpc_api.py
> Fix client API version reporting in the server logs

- parsec/_parsec_pyi/events.pyi
- parsec/_parsec_pyi/protocol/realm.pyi
- parsec/backend/postgresql/realm_queries/get.py
- parsec/backend/postgresql/realm_queries/maintenance.py
- src/binding_utils.rs
- src/enumerate.rs
- src/protocol/realm.rs
This PR improves and generalize the usage of the `impl_enum_field` macro.
> Improve const enum macro

- .github/actions/use-pre-commit/action.yml
> Bump pre-commit to 2.21.0

- oxidation/libparsec/crates/client_types/src/local_device.rs
- oxidation/libparsec/crates/client_types/src/local_device_file.rs
- oxidation/libparsec/crates/client_types/tests/test_local_device_file.rs
- parsec/_parsec.pyi
- parsec/_parsec_pyi/local_device.pyi
- parsec/core/cli/list_devices.py
- parsec/core/cli/utils.py
- parsec/core/gui/authentication_change_widget.py
- parsec/core/gui/claim_device_widget.py
- parsec/core/gui/claim_user_widget.py
- parsec/core/gui/create_org_widget.py
- parsec/core/gui/device_recovery_import_widget.py
- parsec/core/local_device.py
- parsec/test_utils/organization.py
- src/lib.rs
- src/local_device.rs
- tests/core/gui/conftest.py
- tests/core/gui/test_enrollment.py
- tests/core/gui/test_expired_organization.py
- tests/core/gui/test_login.py
- tests/core/gui/test_main_window.py
- tests/core/gui/test_recovery.py
- tests/core/gui/test_workspace_sharing.py
- tests/core/test_local_device.py
- tests/test_cli.py
This PR adds rust implementations and binding for:
- `save_device_with_password_in_config`
- `save_device_with_password`
- `change_device_password`
This closes #3865
> Oxidize device save

- Cargo.lock
- oxidation/bindings/electron/src/index.d.ts
- oxidation/bindings/electron/src/meths.rs
- oxidation/bindings/generator/api.py
- oxidation/bindings/generator/generate.py
- oxidation/bindings/generator/templates/binding_electron_index.d.ts.j2
- oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
- oxidation/bindings/generator/templates/binding_web_meths.rs.j2
- oxidation/bindings/generator/templates/client_plugin_definitions.d.ts.j2
- oxidation/bindings/web/src/meths.rs
- oxidation/client/src/plugins/libparsec/definitions.d.ts
- oxidation/client/src/views/TestPage.vue
- oxidation/libparsec/Cargo.toml
- oxidation/libparsec/crates/client_types/Cargo.toml
- oxidation/libparsec/crates/core/Cargo.toml
- oxidation/libparsec/crates/core/src/error.rs
- oxidation/libparsec/crates/core/src/lib.rs
- oxidation/libparsec/crates/core/src/logged_core.rs
- oxidation/libparsec/crates/platform_async/src/lib.rs
- oxidation/libparsec/src/lib.rs
- Implement a way to login and keep all rust stuff in memory
closes #3843
> Oxidation login

- oxidation/libparsec/crates/client_types/src/local_device.rs
- parsec/_parsec_pyi/local_device.pyi
- parsec/core/invite/claimer.py
- parsec/core/invite/organization.py
- parsec/core/local_device.py
- parsec/core/pki/submitter.py
- parsec/test_utils/organization.py
- src/local_device.rs
- tests/common/population.py
This closes #3863. `load_device_with_password` is exposed in #3896 so this PR depends on #3896.
> Oxidize generate new device

- Cargo.lock
- oxidation/libparsec/crates/client_connection/Cargo.toml
- oxidation/libparsec/crates/core/Cargo.toml
- oxidation/libparsec/crates/core/tests/test_trustchain.rs
- oxidation/libparsec/crates/tests_fixtures/Cargo.toml
- oxidation/libparsec/crates/tests_fixtures/src/trustchain.rs
- oxidation/libparsec/crates/types/Cargo.toml
- oxidation/libparsec/crates/types/src/time.rs
- src/time.rs
> Bump chrono

- Cargo.lock
- oxidation/bindings/electron/src/index.d.ts
- oxidation/bindings/electron/src/meths.rs
- oxidation/bindings/generator/api.py
- oxidation/bindings/generator/templates/binding_electron_meths.rs.j2
- oxidation/bindings/web/src/meths.rs
- oxidation/client/src/plugins/libparsec/definitions.d.ts
- oxidation/client/src/views/TestPage.vue
- oxidation/libparsec/crates/client_types/src/error.rs
- oxidation/libparsec/crates/client_types/src/local_device.rs
- oxidation/libparsec/crates/client_types/src/local_device_file.rs
- oxidation/libparsec/crates/core/Cargo.toml
- oxidation/libparsec/crates/core/src/error.rs
- oxidation/libparsec/crates/core/src/logged_core.rs
- oxidation/libparsec/crates/platform_device_loader/Cargo.toml
- oxidation/libparsec/crates/platform_device_loader/src/lib.rs
- oxidation/libparsec/crates/platform_device_loader/src/native/local_device.rs
- oxidation/libparsec/crates/platform_device_loader/src/native/local_device_file.rs
- oxidation/libparsec/crates/platform_device_loader/src/web/local_device.rs
- oxidation/libparsec/crates/platform_device_loader/src/web/local_device_file.rs
- oxidation/libparsec/crates/platform_device_loader/src/web/mod.rs
- oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
- oxidation/libparsec/src/lib.rs
- src/local_device.rs
- Remove `test_gen_default_devices`
- Deserialize `devices` in `LocalStorage` with `json`
- Add `LocalDevice` in `LoggedCore`
- Fix `login` args with `path | slug` and `password`
depends on #3842 
need for #3843
> Oxidation load device password web

- newsfragments/3925.misc.rst
- src/addrs.rs
- src/binding_utils.rs
- src/data/organization.rs
- src/data/pki.rs
- src/protocol/block.rs
- src/protocol/invite.rs
- src/protocol/message.rs
- src/protocol/mod.rs
- src/protocol/organization.rs
- src/protocol/pki.rs
- src/protocol/realm.rs
- src/protocol/user.rs
- src/protocol/vlob.rs
- src/trustchain.rs
> Do not use Vec<u8> as argument type in the binding

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- build.py
- make.py
- oxidation/bindings/electron/Cargo.toml
- oxidation/bindings/electron/package-lock.json
- oxidation/bindings/electron/package.json
- oxidation/bindings/electron/scripts/build.js
- oxidation/client/electron/package.json
- oxidation/libparsec/Cargo.toml
- oxidation/libparsec/crates/client_connection/Cargo.toml
- oxidation/libparsec/crates/client_types/Cargo.toml
- oxidation/libparsec/crates/core/Cargo.toml
- oxidation/libparsec/crates/core_fs/Cargo.toml
- oxidation/libparsec/crates/crypto/Cargo.toml
- oxidation/libparsec/crates/crypto/src/lib.rs
- oxidation/libparsec/crates/platform_device_loader/Cargo.toml
- oxidation/libparsec/crates/protocol/Cargo.toml
- oxidation/libparsec/crates/tests_fixtures/Cargo.toml
- oxidation/libparsec/crates/types/Cargo.toml
- oxidation/libparsec/crates/types/src/time.rs
- pyproject.toml
- src/time.rs
you want nicer python dev? https://asciinema.org/a/KQjcrhjhBDNHHZc4NUnm92TsR
you want nicer rust dev ? https://asciinema.org/a/GfqislRXGXQTai8XFPPFaOEz4
> Introduce make.py build command and import cargo features & defaults

- make.py
> Fix make.py when not running from the root folder

- oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs
- oxidation/libparsec/crates/platform_local_db/src/executor.rs
- oxidation/libparsec/crates/types/src/id.rs
- src/runtime.rs
- src/storage/workspace_storage.rs
- tests/scripts/run_testenv.py
- tests/scripts/run_testenv.sh
- Improve test env script => add cleanup function
- Improve `Vec<u8>` conversion in `set_chunk`
- Improve `set_manifest` => allow to do operation in cache
- Improve `get_manifest` => allow to do operation in cache
- Improve `load_file_descriptor` => allow to do operation in cache
> Storage module impro perf

- Cargo.lock
- oxidation/libparsec/crates/client_connection/Cargo.toml
- oxidation/libparsec/crates/core/Cargo.toml
- oxidation/libparsec/crates/core/src/error.rs
- oxidation/libparsec/crates/core/src/remote_devices_manager.rs
- oxidation/libparsec/crates/core/src/trustchain.rs
- oxidation/libparsec/crates/core/tests/test_trustchain.rs
- src/trustchain.rs
Fill RemoteDevicesManager in the rust implementation
> Add RemoteDevicesManager

- Cargo.lock
- oxidation/libparsec/Cargo.toml
- oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
- oxidation/libparsec/crates/client_connection/src/client.rs
- oxidation/libparsec/crates/client_connection/src/lib.rs
- oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
- oxidation/libparsec/crates/client_connection/tests/utils/server.rs
- oxidation/libparsec/src/lib.rs
- parsec/_parsec.pyi
- parsec/_parsec_pyi/backend_connection.pyi
- src/backend_connection/authenticated_cmds.rs
- src/backend_connection/error.rs
- src/backend_connection/mod.rs
- src/binding_utils.rs
- src/data/message.rs
- src/lib.rs
- src/protocol/mod.rs
- tests/core/backend_connection/test_authenticated_cmds.py
- tests/test_cli.py
> Authenticated cmds binding

- oxidation/client/vue.config.js
> feat: add source map for easier typescript debugging

- make.py
> Fix make.py running echo command on Windows

- parsec/core/gui/file_table.py
- parsec/core/gui/files_widget.py
> Fix fstring usage for tr files

- oxidation/client/src/components/MsSelect.vue
- oxidation/client/src/components/MsSelectPopover.vue
- oxidation/client/src/components/OrganizationCard.vue
- oxidation/client/src/theme/variables.css
- oxidation/client/src/views/HomePage.vue
> Ms global parsec colors

- oxidation/client/src/transitions/SlideHorizontal.vue
- oxidation/client/src/views/HomePage.vue
> make slide horizontal a reusable transition

- oxidation/client/.eslintrc.js
- oxidation/client/src/components/WorkspaceShareModal.vue
- oxidation/client/src/views/HomePage.vue
- oxidation/client/src/views/OrganizationPageUsers.vue
- oxidation/client/src/views/SettingsPage.vue
- oxidation/client/src/views/WorkspacesPage.vue
> fix: replace PascalCase comps by kebab-case

- oxidation/client/src/components/SearchInput.vue
- oxidation/client/src/views/HomePage.vue
- oxidation/client/tests/unit/HomePage.spec.ts
- oxidation/client/tests/unit/SearchInput.spec.ts
> feat: search input is a reusable component

- oxidation/client/src/common/mocks.ts
- oxidation/client/src/views/HomePage.vue
- oxidation/client/tests/e2e/specs/test_home_page.ts
- oxidation/client/tests/unit/HomePage.spec.ts
> [MS] Moved mocks to  their own file

- oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
- tests/conftest.py
- tests/core/fs/test_bootstrap.py
The come back of `retrieve` :stuck_out_tongue:
> Correct some typo

- oxidation/client/package-lock.json
- oxidation/client/package.json
- oxidation/client/src/common/date.ts
- oxidation/client/src/common/mocks.ts
- oxidation/client/src/main.ts
- oxidation/client/src/services/storageManager.ts
- oxidation/client/src/views/HomePage.vue
- oxidation/client/tests/unit/HeaderPage.spec.ts
- oxidation/client/tests/unit/HomePage.spec.ts
- oxidation/client/tests/unit/common/date.spec.ts
- oxidation/client/tests/unit/common/storage.spec.ts
> Use luxon to manage dates

- tests/scripts/run_testenv.py
- tests/scripts/run_testenv.sh
Previous to cleanup our testenv we would have to close the shell that started the env. But in my case I would get zombie process that run instance of parsec-backend.
I rework the script to have a `cleanup` function that the user can call to kill the backend + remove file + clean env var.
> [testenv] Rework script to allow cleanup

- tests/common/backend.py
- tests/core/test_sync_monitor.py
- tests/test_cli.py
> Fix flaky tests and improve speed in tests/core/test_sync_monitor.py

- oxidation/libparsec/crates/protocol/build.rs
> Fix rebuild-on-json-schema-modified detection in protocol crate

- .cspell/custom-words.txt
- oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
- oxidation/libparsec/crates/client_connection/src/client.rs
- oxidation/libparsec/crates/client_connection/src/error.rs
- oxidation/libparsec/crates/client_connection/src/invited_cmds.rs
- oxidation/libparsec/crates/client_connection/src/lib.rs
- parsec/_parsec.pyi
- parsec/_parsec_pyi/backend_connection.pyi
- parsec/backend/asgi/rpc.py
- parsec/backend/memory/invite.py
- parsec/core/backend_connection/invited.py
- parsec/core/invite/claimer.py
- src/addrs.rs
- src/backend_connection/error.rs
- src/backend_connection/invited_cmds.rs
- src/backend_connection/mod.rs
- tests/core/backend_connection/test_invited_cmds.py
depends on #3959 
closes #3876 
closes #3879
> Oxidation invited cmds

- .github/workflows/ci.yml
- oxidation/bindings/generator/generate.py
- oxidation/libparsec/crates/client_high_level_api/src/fs.rs
- parsec/backend/postgresql/sequester_export.py
- tests/backend/sequester/test_service.py
- tests/core/fs/test_sequester.py
> Fix typo retrieve

- poetry.lock
> Set werkzeug dependency as optional

- src/runtime.rs
> Simplify future_id in runtime.rs

- .cspell/custom-words.txt
- .github/workflows/ci.yml
- oxidation/libparsec/crates/client_connection/src/authenticated_cmds.rs
- oxidation/libparsec/crates/client_connection/src/invited_cmds.rs
- parsec/__init__.py
- parsec/backend/asgi/rpc.py
- parsec/core/backend_connection/authenticated.py
- parsec/core/backend_connection/invited.py
- src/backend_connection/invited_cmds.rs
- tests/backend/test_rpc_handshake.py
- tests/common/backend.py
- tests/common/rpc_api.py
- tests/conftest.py
- tests/core/backend_connection/test_authenticated_cmds.py
- tests/core/backend_connection/test_authenticated_conn.py
- tests/core/backend_connection/test_invited_cmds.py
- tests/core/backend_connection/test_keepalive.py
- tests/core/gui/devices_widget/test_claim.py
- tests/core/gui/test_expired_organization.py
- tests/core/gui/test_main_window.py
- tests/core/gui/test_offline.py
- tests/core/gui/users_widget/test_claim.py
- tests/core/test_invite.py
> Complete the invited_cmds PR

- src/runtime.rs
- src/storage/user_storage.rs
- src/storage/workspace_storage.rs
- src/storage/workspace_storage_snapshot.rs
- src/testbed.rs
> Remove `PyResult` around `FutureIntoCoroutine`

- tests/scripts/run_testbed_server.py
> Add CORS to testbed server

- src/backend_connection/invited_cmds.rs
> Simplify InvitedCmds binding

- .github/workflows/package-ci.yml
> Add MacOS to packaged electron app target

- make.py
- poetry.lock
- pyproject.toml
Update `docutils` to `0.18.1` the last version supported by `sphinx-rtd-theme`.
> Add a docs dependencies group to pyprojecttoml

- docs/rfcs/1001-update-user-profile.md
> Add RFC-1001 Update user profile

- parsec/_parsec_pyi/storage/__init__.pyi
> Add `__init__.pyi` for storage

- docs/development/release.rst
> Add `Release Checklist` in `release.rst`

- parsec/core/fs/remote_loader.py
- parsec/core/fs/userfs/userfs.py
> Simplify UserRemoteLoader

- .cspell/custom-words.txt
- .github/workflows/ci.yml
- Cargo.lock
- oxidation/libparsec/crates/client_connection/Cargo.toml
- oxidation/libparsec/crates/client_connection/tests/auth_cmds.rs
- oxidation/libparsec/crates/core_fs/Cargo.toml
- oxidation/libparsec/crates/core_fs/src/file_operations.rs
- oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs
- oxidation/libparsec/crates/platform_async/Cargo.toml
- oxidation/libparsec/crates/platform_async/src/native/sync/notify.rs
- oxidation/libparsec/crates/platform_async/tests/eyeballs.rs
- oxidation/libparsec/crates/platform_device_loader/Cargo.toml
- oxidation/libparsec/crates/platform_device_loader/tests/test_local_device_file.rs
- oxidation/libparsec/crates/platform_local_db/Cargo.toml
- oxidation/libparsec/crates/platform_local_db/src/executor.rs
- oxidation/libparsec/crates/platform_local_db/src/lib.rs
- oxidation/libparsec/crates/platform_local_db/tests/simple.rs
- oxidation/libparsec/crates/testbed/Cargo.toml
- oxidation/libparsec/crates/testbed/src/lib.rs
- oxidation/libparsec/crates/tests_fixtures/Cargo.toml
- oxidation/libparsec/crates/tests_fixtures/src/testbed.rs
> Oxidation log

- .github/workflows/codeql.yml
- oxidation/bindings/android/libparsec/build.gradle
Skip building rust code when checking the java code with codeql
closes #4211
> Skip rust build for android on codeql

- .github/actions/use-pre-commit/action.yml
- .github/workflows/ci.yml
This will save sometime on the CI by only running `pre-commit` and the modified files in a PR
From `~5m` to `~1m`
> Run `pre-commit` on all files on master & merge queue

- oxidation/libparsec/crates/core/src/invite/claimer.rs
- oxidation/libparsec/crates/core/src/invite/greeter.rs
- src/data/local_device_file.rs
> Use `Ok?` instead of multiple `return`

- Cargo.lock
- oxidation/libparsec/crates/client_connection/Cargo.toml
- oxidation/libparsec/crates/crypto/tests/secret.rs
- oxidation/libparsec/crates/platform_async/Cargo.toml
> Fix crypto tests with all features

- docs/development/simple_benchmark.md
The will provide the steps to benchmark the parsec application
> Add documentation to make a basic benchmark

- oxidation/libparsec/crates/types/src/invite.rs
> Improve SASCode

- .github/workflows/ci.yml
- oxidation/libparsec/crates/crypto/src/sodiumoxide/secret.rs
> Fix rust test sodiumoxide

- oxidation/libparsec/crates/types/src/time.rs
- parsec/core/sync_monitor.py
- src/time.rs
> Fix sync monitor awake consistency after a short sleep

- docs/development/simple_benchmark.md
- oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/mod.rs
- oxidation/libparsec/crates/core_fs/src/storage/user_storage.rs
- oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs
- parsec/_parsec_pyi/storage/workspace_storage.pyi
- src/core_fs/storage/user_storage.rs
- src/core_fs/storage/workspace_storage.rs
- tests/core/gui/test_files.py
- Simplify the storage
- Fix the doc for the benchmark
> Simplify storage

- parsec/core/fs/storage/user_storage.py
- parsec/core/mountpoint/manager.py
> Fix mountpoint access after core teardown 

- tests/core/test_sync_monitor.py
> Fix flaky test_sync_with_concurrent_reencryption

- Cargo.lock
- oxidation/libparsec/crates/crypto/Cargo.toml
- oxidation/libparsec/crates/crypto/src/sodiumoxide/sequester.rs
- oxidation/libparsec/crates/crypto/tests/sequester.rs
> Fix sodiumoxide SequesterCrypto

- oxidation/bindings/generator/generate.py
- oxidation/libparsec/crates/serialization_format/src/lib.rs
- oxidation/libparsec/crates/serialization_format/src/protocol.rs
- oxidation/libparsec/crates/serialization_format/tests/test_protocol.rs
- tests/test_logging.py
> Fix typo familly -> family

- Cargo.lock
- oxidation/libparsec/crates/serialization_format/Cargo.toml
- oxidation/libparsec/crates/tests_macros/Cargo.toml
- oxidation/libparsec/crates/tests_macros/src/lib.rs
`syn` crate has some breaking changes
> Bump parsec macros dependencies

- .github/CODEOWNERS
This configuration is not complete, it's more a POC to see how the code owner system work.
Closes #4412
> Add code owners configuration files

- .github/workflows/ci-web.yml
- .github/workflows/ci.yml
- oxidation/client/package-lock.json
- oxidation/client/src/App.vue
- oxidation/client/src/main.ts
- oxidation/client/src/views/HomePage.vue
- oxidation/client/src/views/SettingsPage.vue
- oxidation/client/src/views/TestPage.vue
- oxidation/client/src/vite-env.d.ts
- oxidation/client/tsconfig.json
Other Changes
-------------
- Add steps to verify code style
- Add a disabled step build web binding.
Currently disabled because it won't be used until we re-enable the tests steps.
> Re-enable `ci-web` by desactivating `e2e tests` & `unit tests` steps

- .github/workflows/ci.yml
Remove the variables defined in `env` since they're now unused.
> Remove `env` variables in `ci.yml`

- .github/custom-problem-matchers/version-updater.json
- .github/workflows/ci-python.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/package-ci.yml
- .pre-commit-config.yaml
- docs/development/quickstart.md
- misc/version_updater.py
- mypy.ini
- pyproject.toml
This script is configurable to add new file to watch for a specific version used by a tool.
> Add script to udpate the version of an used tool across the entire repository

- docs/rfcs/1000-shamir-based-recovery.md
> Fix typo concent -> consent

- docs/rfcs/1000-shamir-based-recovery.md
`self` is a rust keyword which isn't allowed as raw identifier, see: https://github.com/rust-lang/rust/blob/1.31.1/src/libsyntax_pos/symbol.rs#L455-L463
> Fix shamir RFC

- oxidation/client/src/App.vue
- oxidation/client/src/common/injectionKeys.ts
- oxidation/client/src/main.ts
- oxidation/client/src/views/HomePage.vue
- oxidation/client/src/views/SettingsPage.vue
> [MS] Moved injection keys to a separate file

- .github/workflows/package-ci.yml
- .github/workflows/package-webapp.yml
- misc/version_updater.py
- oxidation/client/package-lock.json
- oxidation/client/package.json
- oxidation/client/src/views/SidebarMenuPage.vue
Other Changes
-------------
- Correct `run: command not found`
I discover that the script `web:release` was executing `run lint` after `vite build`.
I suppose the command here was meant to be `npm run lint` but running the lint at that moment seems odd.
Depends on #4444
Closes #4419
> Add updated workflow to build webapp 

- .github/workflows/package-ci.yml
- .github/workflows/package-webapp.yml
- oxidation/bindings/electron/scripts/build.js
> Update package electron job

- oxidation/client/src/components/ProfileHeader.vue
- oxidation/client/src/components/ProfileHeaderPopover.vue
Just making the log out take you back to the list of devices.
> [MS] Implemented log out button

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/release-starter.yml
- docs/development/release.md
- misc/releaser.py
- misc/version_updater.py
- mypy.ini
That new workflow will help creating new release.
To use it, you need to go at <https://github.com/Scille/parsec-cloud/actions/release-starter.yml>.
You will than have a button `Run workflow` (more info here <https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow>)
Other Changes
-------------
- `misc/version_updater.py` can update parsec version.
- Can update parsec version in `parsec/_version.py`, `pyproject.toml` & `licenses/BUSL-Scille.txt`
- Fix `args` is not defined instead of using `not update` in `check_tool(..)`
- Rework `releaser.py`
- Rework sub commands.
- Allow for more customization of arguments required by each commands.
- Add sub command `parse-version` to parse a provided version.
- Refactor python code: add typing, split functions.
- Use …
> Create release starter workflow 

- .github/workflows/release-starter.yml
- docs/development/release.md
- Fix syntax error in step `Create git branch for new version` where a `then` was missing after `elif <cond>;```.
- Add the workflow link in `release.md`.
> Fix release-starter workflow syntax error

- .cspell/custom-words.txt
- .github/workflows/release-starter.yml
> Add git configuration to workflow `release-starter`

- .github/workflows/publish-testbed.yml
- packaging/testbed-server/build-testbed.sh
- packaging/testbed-server/build.sh
Rework tag used for the docker testbed image the format is `vMAJOR.MINOR.PATCH+dev.YYYY-MM-DD-sha.<commit-sha>`
> Add workflow to publish `testbed` docker image

- oxidation/client/.eslintrc.cjs
- oxidation/client/scripts/vite_plugin_wasm_pack.ts
- oxidation/client/src/services/storageManager.ts
- oxidation/client/tests/component/specs/testMsSelectPopover.ts
Closes #4596 
Update the linter configuration to not comment on unused variable for variables prefixed with "_".
> [MS] Mark variables prefixed by "_" as unused for eslint

- oxidation/client/src/common/date.ts
- oxidation/client/src/common/filesize.ts
- oxidation/client/src/common/injectionKeys.ts
- oxidation/client/src/common/mocks.ts
- oxidation/client/src/components/AvatarGroup.vue
- oxidation/client/src/components/ButtonOption.vue
- oxidation/client/src/components/MsSelect.vue
- oxidation/client/src/components/MsSelectPopover.vue
- oxidation/client/src/components/WorkspaceCard.vue
- oxidation/client/src/components/WorkspaceContextMenu.vue
- oxidation/client/src/components/WorkspaceListItem.vue
- oxidation/client/src/components/listGridToggle.vue
- oxidation/client/src/components/tagRole.vue
- oxidation/client/src/locales/en-US.json
- oxidation/client/src/locales/fr-FR.json
- oxidation/client/src/main.ts
- oxidation/client/src/router/index.ts
- oxidation/client/src/theme/variables.css
- oxidation/client/src/views/HomePage.vue
- oxidation/client/src/views/WorkspacesPage.vue
- oxidation/client/tests/component/specs/testWorkspaceCard.ts
- oxidation/client/tests/e2e/specs/test_home_page.ts
- oxidation/client/tests/e2e/support/index.ts
> [MS] Updated workspaces page

- oxidation/client/src/components/HeaderBackButton.vue
- oxidation/client/src/components/HeaderBreadcrumbs.vue
- oxidation/client/src/components/ProfileHeader.vue
- oxidation/client/src/components/SettingsView.vue
- oxidation/client/src/locales/en-US.json
- oxidation/client/src/locales/fr-FR.json
- oxidation/client/src/router/index.ts
- oxidation/client/src/views/HeaderPage.vue
- oxidation/client/src/views/SettingsPage.vue
Closes #4500 
Does not include the title, as it will be handled by the breadcrumbs (see #4575)
> [MS] Updated the settings page

- oxidation/client/src/main.ts
- oxidation/client/tests/e2e/support/index.ts
> [MS] Force e2e tests to en-EN

- packaging/server/build.sh
- packaging/testbed-server/README.md
- packaging/testbed-server/build.sh
Add instructions to:
- Setup docker with the github container registry.
- Build the testbed docker image.
- Test the image.
- Publish the image.
Other Changes
-------------
- Remove `latest` docker tag from the script
We don't want to use the latest tag for our image because it will be too simple to break something that rely on it.
Closes #4609
> Add documentation for building testbed server

- .github/filters/ci.yml
- .github/workflows/ci-python.yml
Also display the information about the current virtualenv configuration of poetry using `poetry env info`.
> Rename workflow `ci-python` to `CI Python` (previously called `ci-rust` caused by a wrong copy/paste)

- oxidation/client/src/locales/en-US.json
- oxidation/client/src/locales/fr-FR.json
- oxidation/client/src/views/SidebarMenuPage.vue
> [MS] Fixed localization of side menu bar

- tests/scripts/run_testenv.py
This allow the mocked backend to accept connection for a different ip than `localhost`.
I use this to accept connection from one of my VM
> Allow to customize the backend host for the testenv

- oxidation/client/tests/component/specs/testSettingsOption.spec.ts
- oxidation/client/tests/e2e/specs/test_settings_modal.ts
- oxidation/client/tests/e2e/specs/test_settings_page.ts
> [MS] Added settings tests

- oxidation/client/src/common/path.ts
- oxidation/client/tests/unit/specs/testPath.spec.ts
> [MS] Added unit test for path

- oxidation/client/src/common/filesize.ts
- oxidation/client/tests/unit/specs/testFileSize.spec.ts
> [MS] Added tests for filesize formatting

- docs/development/release.md
> Update release documentation

- client/src/views/SidebarMenuPage.vue
- client/tests/e2e/specs/test_workspaces_page.ts
> [MS] Fixed side bar workspaces

- client/package-lock.json
- client/package.json
- client/src/common/injectionKeys.ts
- client/src/main.ts
- client/src/services/notificationCenter.ts
- client/tests/unit/specs/testNotificationCenter.spec.ts
Closes #4674
Simple service to handle anything related to how to provide the user with an information: centralizing modals, snackbars and notification.
> [MS] Added notification center

- client/electron/src/setup.ts
- client/src/common/mocks.ts
- client/src/components/ProfileHeader.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/router/index.ts
- client/src/views/DevicesPage.vue
- client/src/views/HeaderPage.vue
- client/tests/e2e/specs/test_profile_menu.ts
Closes #4498 
Added a mock devices page.
External link for `Help & feedback` points to `https://my.parsec.cloud/help`. Link can be open both in web and electron (uses the system browser).
> Added profile actions

- parsec/core/fs/remote_loader.py
Simplify the python typing in `remote_loader.py`
> Simplify typing

- docs/development/quickstart.md
> Update quickstart documentation

- client/src/common/validators.ts
- client/tests/unit/specs/testValidators.spec.ts
Working on #4759, splitting it into multiple PRs. This one includes the validator for claim_user links and some associated unit tests.
> [MS] Added tests for validators and claim_user link validator

- parsec/core/config.py
- parsec/core/logged_core.py
- parsec/core/mountpoint/manager.py
- tests/core/mountpoint/test_base.py
This PR adds support for personal workspaces (see #4768). 
Closes #4768
> Add personal workspace support

- docs/development/snapcraft-101.md
- docs/userguide/installation.rst
- misc/version_updater.py
- newsfragments/4760.bugfix.rst
- packaging/snap/snap/snapcraft.yaml
- Update version updater to update snapcraft version file
- Add a document to list important command to build a snap
- Update the userguide installation about installing fuse2 on their side.
> Missing fusermount in snap

- client/scripts/vite_plugin_wasm_pack.ts
- client/src/components/CustomInput.vue
- client/src/components/ItemGrid.vue
- client/src/components/MobileItemList.vue
- client/src/components/UserInformationPage.vue
- client/src/views/CreateOrganizationModal.vue
- Moved the UserInfoPage so that it can be reused.
- Added props to set default values for email and name.
- Added props to disable inputs.
> [MS] Update user info page, add the ability to disable inputs

- client/src/components/SasCodeChoice.vue
- client/tests/component/specs/testSasCodeChoice.spec.ts
Linked to #4759, trying to avoid one enormous PR.
This creates the component for the Sas code choice for the enrolment process.
> [MS] Added a component to chose the Sas Code

- .github/CODEOWNERS
> Update `packaging` path in `CODEOWNERS` file

- .github/workflows/ci-python.yml
- .github/workflows/codeql.yml
- .github/workflows/package-server.yml
- docs/development/quickstart.md
- misc/version_updater.py
- server/packaging/server/in-docker-build.sh
- server/packaging/testbed-server/in-docker-build.sh
The previous version was `1.3.2`.
Closes #4808
> Update minimal used poetry version to `1.5.1`

- .cspell/custom-words.txt
- .github/workflows/package-python.yml
- .github/workflows/package-webapp.yml
- .github/workflows/releaser.yml
- .syft.yaml
- newsfragments/4770.doc.rst
Generate SBOM file for python wheels, python apps, electron apps and web app.
Other Changes
-------------
- Add `concurrency` to `package-webapp` workflow.
> Generate SBOM for generated Package [2.16]

- .cspell/custom-words.txt
- .github/workflows/package-server.yml
- .github/workflows/package-webapp.yml
- .syft.yaml
- newsfragments/4770.doc.rst
> Generate SBOM for generated Package

- .cspell/custom-words.txt
- client/src/common/constants.ts
- client/src/common/passwordValidation.ts
- client/src/common/validators.ts
- client/src/components/AlertConfirmation.ts
- client/src/components/ChoosePassword.vue
- client/src/components/CreateWorkspaceModal.vue
- client/src/components/HomePagePopover.vue
- client/src/components/JoinByLinkModal.vue
- client/src/components/JoinOrganization/FinishProcess.vue
- client/src/components/JoinOrganization/WaitForHostPage.vue
- client/src/components/PasswordInput.vue
- client/src/components/SasCodeProvide.vue
- client/src/components/UserInformationPage.vue
- client/src/components/WizardStepper.vue
- client/src/components/WorkspaceShareModal.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/CreateOrganizationModal.vue
- client/src/views/HomePage.vue
- client/src/views/JoinOrganizationModal.vue
- client/src/views/SettingsModal.vue
- client/tests/component/specs/testPasswordInput.spec.ts
- client/tests/component/specs/testWizardStepper.spec.ts
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_join_org_modal.ts
Closes #4759
Added the pages, the logic and the tests for the join org modal (claim user).
It looks ugly but that's the point of #4748.
A lot of the logic depends upon the invitation process which is not yet available. I've done my best to mock it so that all we will have to do is replace a few function calls.
> [MS] Added pages and tests for join org modal

- libparsec/crates/client/src/certificates_ops/add.rs
Remove `if` statement in `match`
> Simplify add_certificates_batch

- libparsec/crates/client/src/invite/claimer.rs
Some `clone` are useless, so it has been removed.
> Remove useless clone in claimer ctx

- libparsec/crates/types/tests/manifest.rs
Add attention to the error returned
> Check that is the right error in `serde_file_manifest_invalid_blocksize`

- libparsec/crates/platform_storage/src/native/certificates.rs
- libparsec/crates/platform_storage/src/native/user.rs
- libparsec/crates/platform_storage/src/native/workspace.rs
Format correctly the platform storage.
> Format platform storage correctly

- client/src/common/mocks.ts
- client/src/components/FileCard.vue
- client/src/views/FoldersPage.vue
- client/tests/component/specs/testFileCard.spec.ts
- client/tests/component/specs/testFileListItem.spec.ts
- client/tests/e2e/specs/test_folders_page.ts
Juste some additional tests for the folders page, file card and file list item.
> [MS] Added tests for folders page

- client/src/components/ChoosePassword.vue
- client/src/components/CustomInput.vue
- client/src/components/HomePagePopover.vue
- client/src/components/InformativeText.vue
- client/src/components/JoinOrganization/FinishProcess.vue
- client/src/components/JoinOrganization/OrganizationLinkPage.vue
- client/src/components/JoinOrganization/WaitForHostPage.vue
- client/src/components/PasswordInput.vue
- client/src/components/SasCodeChoice.vue
- client/src/components/SasCodeProvide.vue
- client/src/components/WizardStepper.vue
- client/src/components/WizardStepperStep.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/variables.css
- client/src/views/JoinOrganizationModal.vue
- client/tests/component/specs/testPasswordInput.spec.ts
- client/tests/component/specs/testWizardStepper.spec.ts
- client/tests/e2e/specs/test_join_org_modal.ts
- Adapt UI depending on mockups
- Create a stepper component for following modal
- Fixed of join organization tests with the new UI
closes #4784
> Ms join org style

- client/src/common/permissions.ts
- client/src/components/ButtonOption.vue
- client/src/components/ListGridToggle.vue
- client/src/components/Users/UserCard.vue
- client/src/components/Users/UserListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/router/conditions.ts
- client/src/router/index.ts
- client/src/views/ActiveUsersPage.vue
- client/src/views/FoldersPage.vue
- client/src/views/HeaderPage.vue
- client/src/views/InvitationsPage.vue
- client/src/views/OrganizationInformationPage.vue
- client/src/views/RevokedUsersPage.vue
- client/src/views/SidebarMenuPage.vue
- client/src/views/StoragePage.vue
- client/src/views/WorkspacesPage.vue
- client/tests/e2e/specs/test_manage_organization.ts
Closes #4854
Changes the side menu, adds permissions (differenciates between admin, standard and outsider), adds pages for users, org info and org storage.
Adds related tests.
> [MS] Manage organization pages & routing

- .github/actions/setup-python-poetry/action.yml
- .github/workflows/ci-python.yml
- .github/workflows/ci-rust.yml
- .github/workflows/codeql.yml
- .github/workflows/package-server.yml
- misc/version_updater.py
> Use `python-version-file` to load the python version in `pyproject.toml`

- client/src/common/mocks.ts
- client/src/components/ButtonOption.vue
- client/src/components/FileListItem.vue
- client/src/components/UserTag.vue
- client/src/components/WizardStepper.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/variables.css
- client/src/views/FoldersPage.vue
- client/tests/component/specs/testFileListItem.spec.ts
- client/tests/e2e/specs/test_folders_page.ts
Depends on #4827 
Adds file selection to FoldersPage
- adds a checkbox to the title bar to select all files
- adds checkboxes to each file
- switches the action buttons depending on how many files are selected
- adds tests
1.  [X] Keep changes in the pull request as small as possible
2.  [X] Ensure the commit history is sanitized
3.  [X] Give a meaningful title to your PR
4.  [X] Describe your changes
> [MS] Added file selection

- client/src/components/ButtonOption.vue
- client/src/theme/variables.css
- client/src/views/FoldersPage.vue
- client/src/views/WorkspacesPage.vue
- visual UI changes
closes #4894
> Update contextual menu buttons

- client/src/main.ts
- client/src/theme/components/buttons.scss
- client/src/theme/components/cards.scss
- client/src/theme/components/contextual-menu.scss
- client/src/theme/components/inputs.scss
- client/src/theme/components/modals.scss
- client/src/theme/components/popovers.scss
- client/src/theme/components/scrollbars.scss
- client/src/theme/global.scss
- client/src/theme/variables/colors.scss
- client/src/theme/variables/colorsIonic.scss
- client/src/theme/variables/fonts.scss
- client/src/theme/variables/radius.scss
- client/src/theme/variables/shadows.scss
- client/src/theme/variables/spacing.scss
- client/src/theme/variables/width.scss
• 2 new folders (components and variables)
• Split existing styles (variables.css) to specific files
Closes #3841
> [MS] Create specific files for variables and components

- Cargo.lock
- Cargo.toml
- libparsec/crates/client_connection/Cargo.toml
Remove `url` dependency and remove useless `features` (for the moment ?) 
> Clean `client_connection` dependencies

- libparsec/crates/platform_storage/Cargo.toml
Remove an useless line because it is already specified in the main `Cargo.toml`
> Remove useless `diesel` specification

- .github/filters/ci.yml
> Correct filter path for python code

- client/src/components/ActionBar.vue
- client/src/views/ActiveUsersPage.vue
- client/src/views/FoldersPage.vue
- client/src/views/WorkspacesPage.vue
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/specs/test_manage_organization.ts
- client/tests/e2e/specs/test_workspaces_page.ts
> [MS] Added an action bar component

- parsec/core/cli/invitation.py
- parsec/core/invite/__init__.py
- parsec/core/invite/claimer.py
- parsec/core/invite/greeter.py
- parsec/core/logged_core.py
- tests/core/test_shamir.py
.. and add prelude attributes to all shamir recovery claim ctx.
Fixup #4504
> Decouple get_shamir_recovery_share_data from ShamirRecoveryGreetInitialCtx

- client/src/components/Users/UserCard.vue
- client/src/components/Users/UserListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/ActiveUsersPage.vue
- client/tests/component/specs/testUserCard.spec.ts
- client/tests/component/specs/testUserListItem.spec.ts
- client/tests/e2e/specs/test_active_users_page.ts
Just some tests for the active users page. Slight refactor of the active user page to avoid dupplicating a button.
> [MS] Added tests for active users page

- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/specs/test_manage_organization.ts
Some e2e tests where skipped (marked as `it.skip`).
> [MS] Reactivated skipped tests

- client/src/common/validators.ts
- client/src/components/HomePagePopover.vue
- client/src/components/JoinByLinkModal.vue
- client/src/components/JoinOrganization/OrganizationLinkPage.vue
- client/src/theme/components/modals.scss
- client/src/views/DeviceJoinOrganizationModal.vue
- client/src/views/UserJoinOrganizationModal.vue
- client/tests/e2e/specs/test_user_join_org_modal.ts
Split the JoinOrgModal into UserJoinOrgModal and DeviceJoinOrgModal to be able to handle invitation links related to a device invitation.
> [MS] Refactored JoinOrganizationModal to accomodate for the split between device and user

- client/src/common/validators.ts
- client/src/components/CreateOrganization/ChooseServerPage.vue
- client/src/components/MsSpinner.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/modals.scss
- client/src/views/CreateOrganizationModal.vue
Updated style issues in create organization modal
closes #4748
> [MS] Updated the style in modal steps

- client/src/common/mocks.ts
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/router/index.ts
- client/src/views/about/AboutModal.vue
- client/src/views/about/AboutPage.vue
- client/src/views/about/AboutView.vue
- client/src/views/header/HeaderPage.vue
- client/src/views/header/ProfileHeader.vue
- client/src/views/header/ProfileHeaderPopover.vue
- client/src/views/home/HomePage.vue
- client/tests/e2e/specs/test_about_modal.ts
- client/tests/e2e/specs/test_about_page.ts
> [MS] Added about page and modal

- client/src/router/conditions.ts
- client/src/views/sidebar-menu/SidebarMenuPage.vue
- client/tests/e2e/specs/test_workspaces_page.ts
> show active workspace in sidebar menu

- docs/development/generate_blob.md
- libparsec/crates/types/tests/unit/manifest.rs
Add test for `impl_manifest_dump_load` which is missing
> Add test for `impl_manifest_dump_load`

- client/src/common/mocks.ts
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/modals.scss
- client/src/views/about/AboutPage.vue
- client/src/views/about/ChangesModal.vue
- client/src/views/header/ProfileHeaderPopover.vue
- client/tests/e2e/specs/test_changes_modal.ts
> [MS] Added changelog modal

- libparsec/crates/serialization_format/README.md
- libparsec/crates/serialization_format/src/lib.rs
Add README and docs for the serialization_format crate.
> Add docs for libparsec_serialization_format

- parsec/_subprocess_dialog.py
- parsec/backend/asgi/__init__.py
- parsec/core/fs/exceptions.py
- parsec/core/gui/claim_device_widget.py
- parsec/core/gui/custom_dialogs.py
- parsec/core/logged_core.py
- parsec/service_nursery.py
- parsec/utils.py
- poetry.lock
- pyproject.toml
This required updating `trio_typing` and `qtrio` (because it require `trio_typing` internally).
> Update mypy to `1.3.0` to support `python-3.11`

- Cargo.toml
- bindings/android/libparsec/rust/Cargo.toml
- bindings/electron/Cargo.toml
- bindings/web/Cargo.toml
- libparsec/Cargo.toml
- libparsec/crates/client/Cargo.toml
- libparsec/crates/client_connection/Cargo.toml
- libparsec/crates/crypto/Cargo.toml
- libparsec/crates/platform_async/Cargo.toml
- libparsec/crates/platform_device_loader/Cargo.toml
- libparsec/crates/platform_http_proxy/Cargo.toml
- libparsec/crates/platform_storage/Cargo.toml
- libparsec/crates/protocol/Cargo.toml
- libparsec/crates/serialization_format/Cargo.toml
- libparsec/crates/testbed/Cargo.toml
- libparsec/crates/tests_fixtures/Cargo.toml
- libparsec/crates/tests_macros/Cargo.toml
- libparsec/crates/types/Cargo.toml
- misc/version_updater.py
- server/Cargo.toml
> Define cargo manifest values in the root cargo.toml

- Cargo.toml
- bindings/android/libparsec/rust/Cargo.toml
- bindings/electron/Cargo.toml
- bindings/web/Cargo.toml
- libparsec/Cargo.toml
- libparsec/crates/client/Cargo.toml
- libparsec/crates/client_connection/Cargo.toml
- libparsec/crates/crypto/Cargo.toml
- libparsec/crates/platform_async/Cargo.toml
- libparsec/crates/platform_device_loader/Cargo.toml
- libparsec/crates/platform_http_proxy/Cargo.toml
- libparsec/crates/platform_storage/Cargo.toml
- libparsec/crates/protocol/Cargo.toml
- libparsec/crates/serialization_format/Cargo.toml
- libparsec/crates/testbed/Cargo.toml
- libparsec/crates/tests_fixtures/Cargo.toml
- libparsec/crates/tests_macros/Cargo.toml
- libparsec/crates/types/Cargo.toml
- server/Cargo.toml
remove the extra license-file value
> Correct warning about duplicate license specification

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/tests/e2e/specs/test_device_join_org_modal.ts
> [MS] Test claim device modal

- client/src/theme/components/modals.scss
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/users/GreetUserModal.vue
> [MS] Updated style greet user modal

- client/src/components/core/ms-modal/MsModal.vue
- client/src/theme/components/modals.scss
- client/src/views/settings/SettingsModal.vue
- client/src/views/settings/SettingsView.vue
Updated the modal with the component MsModal.
PI: The `ion-content` must be replaced by a `div` inside the slot (in the content of the modal) for working properly.
closes #5014
> [MS] Udpated settings modal

- client/src/common/mocks.ts
- client/src/components/users/InvitationCard.vue
- client/src/components/users/InvitationListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/buttons.scss
- client/src/views/users/InvitationsPage.vue
- client/tests/e2e/specs/test_greet_user_modal.ts
Added list and grid view for invitations.
The user can now greet a user.
⚠️ An issue for adding tests is required.
closes #5024
> [MS] Invitation page

- .pre-commit-config.yaml
- bindings/electron/src/meths.rs
- bindings/generator/api/common.py
- bindings/generator/templates/binding_electron_meths.rs.j2
- bindings/web/src/meths.rs
- docs/development/quickstart.md
- libparsec/crates/types/tests/id.rs
- misc/version_updater.py
- rust-toolchain.toml
- server/src/lib.rs
> Bump rust version to 1.71.1

- client/src/theme/components/modals.scss
- client/src/views/workspaces/WorkspaceSharingModal.vue
Updated the modal with the component MsModal.
closes #5019
> [MS] Updated workspace sharing modal 

- client/src/components/files/FileImport.vue
- client/src/theme/components/modals.scss
- client/src/views/files/FileUploadModal.vue
- client/tests/e2e/specs/test_file_upload_modal.ts
Updated the modal with the component MsModal.
closes #5020
> [MS] Updated file upload modal

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/modals.scss
- client/src/views/workspaces/CreateWorkspaceModal.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/e2e/specs/test_aacreate_workspace_modal.ts
- client/tests/e2e/specs/test_create_workspace_modal.ts
Updated the modal with the component MsModal. 
closes #5018
> [MS] Updated Create workspace modal to msModal

- client/electron/package-lock.json
- client/electron/package.json
> Remove overrides for `@electron/universal`

- docs/conf.py
Correct the invalid value related to github.
Closes #5100
> Fix readthedocs github link

- client/src/views/about/ChangesModal.vue
> [MS] Moved changes modal to ms-modal

- client/src/common/mocks.ts
- client/src/common/permissions.ts
- client/src/router/conditions.ts
- client/src/router/index.ts
- client/src/views/files/FoldersPage.vue
- client/src/views/header/ProfileHeader.vue
- client/src/views/home/HomePage.vue
- client/src/views/sidebar-menu/SidebarMenuPage.vue
- client/src/views/workspaces/WorkspacesPage.vue
Used a device id `a@b` previously as a core handle, changed this to a number, and refactored a bit of the routing stuff.
> [MS] Updated how we pass the core handle around

- libparsec/crates/tests_macros/src/lib.rs
> Refactor quote_block initialization without mutability

- bindings/electron/src/meths.rs
- bindings/generator/generate.py
- bindings/generator/templates/binding_electron_meths.rs.j2
- bindings/generator/templates/binding_web_meths.rs.j2
- bindings/web/src/meths.rs
> Generated js object to use camelCase for variant type

- client/src/common/injectionKeys.ts
- client/src/common/mocks.ts
- client/src/common/parsec.ts
- client/src/main.ts
- client/src/views/home/HomePage.vue
- client/vite.config.ts
Depends on #5095 
Use the binding to login on Electron. On web, keep using the mock for now.
> [MS] Login with the libparsec

- bindings/electron/package-lock.json
- bindings/web/package-lock.json
- client/src/common/mocks.ts
- client/src/common/parsec.ts
- client/src/components/users/InvitationCard.vue
- client/src/components/users/InvitationListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/router/conditions.ts
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/CreateUserInvitationModal.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
- client/tests/component/specs/testInvitationCard.spec.ts
- client/tests/component/specs/testInvitationListItem.spec.ts
- client/tests/unit/specs/testPermissions.spec.ts
> [MS] Added list invitations, invite, and cancel invite using bindings

- client/src/common/mocks.ts
- client/src/common/parsec.ts
- client/src/components/core/ms-select/MsSelect.vue
- client/src/components/workspaces/WorkspaceCard.vue
- client/src/components/workspaces/WorkspaceListItem.vue
- client/src/components/workspaces/WorkspaceUserRole.vue
- client/src/views/sidebar-menu/SidebarMenuPage.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/component/specs/testWorkspaceCard.spec.ts
- client/tests/component/specs/testWorkspaceListItem.spec.ts
- client/tests/e2e/specs/test_workspace_sharing_modal.ts
Still a lot to be done around workspaces handling but this should be a solid start.
> [MS] Added binding calls for list workspace and create workspace

- client/src/theme/components/modals.scss
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/users/GreetUserModal.vue
> Ms harmonize modal with steppers

- bindings/generator/generate.py
- Fix `"type" has no attribute "__args__"` by using `typings.get_args`.
- Fix `"OpaqueSpec" has no attribute "event_type"` by ignoring the error. 
Maybe we should define the attribute `event_type` in `OpaqueSpec` :thinking:
> Fix mypy error

- .github/workflows/ci-rust.yml
- Cargo.lock
- Cargo.toml
- libparsec/crates/client/Cargo.toml
- libparsec/crates/client_connection/Cargo.toml
- libparsec/crates/platform_async/Cargo.toml
- libparsec/crates/platform_async/tests/oneshot.rs
- libparsec/crates/platform_async/tests/task.rs
- libparsec/crates/platform_device_loader/Cargo.toml
- libparsec/crates/platform_storage/Cargo.toml
- libparsec/crates/protocol/Cargo.toml
- libparsec/crates/tests_fixtures/Cargo.toml
- libparsec/crates/tests_fixtures/src/lib.rs
- libparsec/crates/tests_fixtures/src/tmp_path.rs
- libparsec/crates/tests_fixtures/src/trustchain.rs
- libparsec/crates/tests_lite/Cargo.toml
- libparsec/crates/tests_lite/src/lib.rs
- libparsec/crates/tests_macros/src/lib.rs
- misc/version_updater.py
> Minimal support test wasm

- .github/filters/ci.yml
> Re-organize elements in ci filter

- client/src/common/parsec.ts
- client/src/views/header/ProfileHeader.vue
> [MS] Implemented logout with bindings

- client/src/components/users/UserListItem.vue
- client/src/views/settings/SettingsView.vue
- client/src/views/users/ActiveUsersPage.vue
> [MS] Fixed small import mistakes

- client/src/components/devices/DeviceCard.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/devices/DevicesPage.vue
This is just to make the devices page slightly more presentable, it's not exactly how it should look like but at least it's not super ugly.
> [MS] Cleaned devices page

- .github/filters/ci.yml
- .github/workflows/ci-python.yml
- .github/workflows/ci.yml
> Only run python check style when modifiying a python file that isn't related to parsec-server

- .cspell/custom-words.txt
- .github/workflows/ci-rust.yml
- Cargo.lock
- Cargo.toml
- libparsec/crates/platform_mountpoint/Cargo.toml
- libparsec/crates/platform_mountpoint/README.md
- libparsec/crates/platform_mountpoint/build.rs
- libparsec/crates/platform_mountpoint/src/error.rs
- libparsec/crates/platform_mountpoint/src/lib.rs
- libparsec/crates/platform_mountpoint/src/memfs.rs
- libparsec/crates/platform_mountpoint/src/windows/error.rs
- libparsec/crates/platform_mountpoint/src/windows/mod.rs
- libparsec/crates/platform_mountpoint/tests/winfsp_tests.rs
> Add `winfsp-tests` & `mountpoint` on `windows`

- bindings/electron/src/index.d.ts
- bindings/electron/src/meths.rs
- bindings/generator/api/__init__.py
- bindings/generator/api/addr.py
- bindings/generator/api/common.py
- bindings/generator/api/invite.py
- bindings/generator/api/testbed.py
- bindings/generator/templates/binding_electron_meths.rs.j2
- bindings/web/src/meths.rs
- client/src/plugins/libparsec/definitions.ts
- libparsec/crates/types/src/addr.rs
- libparsec/src/addr.rs
- libparsec/src/lib.rs
> Expose `parse_backend_addr` for `GUI`

- bindings/electron/src/index.d.ts
- bindings/electron/src/meths.rs
- bindings/generator/api/client.py
- bindings/web/src/meths.rs
- client/src/plugins/libparsec/definitions.ts
- libparsec/crates/client/src/certificates_ops/mod.rs
- libparsec/crates/client/src/client.rs
- libparsec/crates/client/src/user_ops/error.rs
- libparsec/crates/client/src/user_ops/mod.rs
- libparsec/src/client.rs
> Get client info for GUI

- client/src/common/mocks.ts
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/RevokedUsersPage.vue
- client/src/views/users/UserContextMenu.vue
> add revoked users page

- docs/rfcs/1002-workspace-archiving-and-deletion.md
> Add RFC 1002 to main branch 

- client/src/common/mocks.ts
- client/src/common/validators.ts
- client/src/components/organizations/OrganizationCard.vue
- client/src/components/users/InvitationCard.vue
- client/src/components/users/InvitationListItem.vue
- client/src/parsec/functions.ts
- client/src/parsec/index.ts
- client/src/parsec/types.ts
- client/src/router/conditions.ts
- client/src/views/header/ProfileHeader.vue
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/HomePage.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/sidebar-menu/SidebarMenuPage.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/component/specs/testInvitationCard.spec.ts
- client/tests/component/specs/testInvitationListItem.spec.ts
Frontend should never reference `@/plugins/libparsec` directly, only go through `@/parsec`.
> [MS] Add a wrapper to libparsec

- client/src/parsec/functions.ts
- client/src/parsec/types.ts
- client/src/views/header/HeaderPage.vue
Get the workspace name by using `clientListWorkspaces` and a find. Will be replaced later with #5243.
> [MS] Retrieve the workspace name

- client/src/services/notificationCenter.ts
- client/src/theme/components/toasts.scss
- client/src/theme/global.scss
- client/src/views/home/HomePage.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/tests/e2e/specs/test_home_page.ts
- client/tests/unit/specs/testNotificationCenter.spec.ts
> Ms notification toasts

- client/src/common/validators.ts
- client/src/parsec/functions.ts
- client/src/views/workspaces/CreateWorkspaceModal.vue
- client/src/views/workspaces/WorkspacesPage.vue
> [MS] Use bindings to validate data

- bindings/electron/src/index.d.ts
- bindings/electron/src/meths.rs
- bindings/generator/generate.py
- bindings/web/src/meths.rs
- client/src/plugins/libparsec/definitions.ts
Having the element sorted help reviewing the generated files.
> Sort generated element by name

- libparsec/crates/protocol/tests/invite.rs
- libparsec/crates/protocol/tests/invited_cmds/v3/invite_3b_claimer_wait_peer_trust.rs
- libparsec/crates/protocol/tests/invited_cmds/v4/invite_3b_claimer_wait_peer_trust.rs
> Migrate `invite_3b_claimer` tests

- client/src/common/mocks.ts
- client/src/components/users/TagProfile.vue
- client/src/parsec/greet_user.ts
- client/src/parsec/index.ts
- client/src/parsec/types.ts
- client/src/views/header/HeaderPage.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
- client/tests/component/specs/testTagProfile.spec.ts
- client/tests/component/specs/testUserCard.spec.ts
- client/tests/component/specs/testUserListItem.spec.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_user_join_org_modal.ts
Closes #5149 
Used #5169 for testing. Errors are not correctly handled in the vast majority of cases. It will be easier to handle them properly when testing with claim user directly though the UI.
> [MS] Added greet user with bindings

- docs/userguide/index.rst
- docs/userguide/troubleshooting.rst
The page can be found here <https://github.com/Scille/parsec-cloud.old-wiki/blob/master/Common-problems.md>
Depends on:
> Migrate `Common problem` wiki page

- server/packaging/server/server.dockerfile
> Add well known user other than root

- .github/workflows/ci-python.yml
- parsec/core/local_device.py
- tests/test_cli.py
> Expose missing LocalDeviceCryptoError in `parsec.core.local_device`

- libparsec/crates/client/src/certificates_ops/add.rs
Fixing typo, Fixes Issue #5369
> fix typo in add.rs

- client/src/common/mocks.ts
- client/src/common/translations.ts
- client/src/components/workspaces/WorkspaceCard.vue
- client/src/components/workspaces/WorkspaceListItem.vue
- client/src/components/workspaces/WorkspaceTagRole.vue
- client/src/components/workspaces/WorkspaceUserRole.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/functions.ts
- client/src/parsec/types.ts
- client/src/views/header/HeaderPage.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/component/specs/testWorkspaceCard.spec.ts
- client/tests/component/specs/testWorkspaceListItem.spec.ts
- client/tests/component/specs/testWorkspaceTagRole.spec.ts
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_workspace_sharing_modal.ts
- client/tests/e2e/specs/test_workspaces_page.ts
- client/tests/e2e/support/index.ts
> [MS] Use bindings for workspace info

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/functions.ts
- client/src/parsec/types.ts
- client/src/views/home/CreateOrganizationModal.vue
> [MS] Updated error handling for org creation

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/functions.ts
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/src/views/workspaces/WorkspacesPage.vue
1. Error messages when listing workspaces, creating workspaces and updating the roles
2. Exclude the current user from the list of roles and add a special disabled item for them
> [MS] Added error handling for workspaces

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/home/HomePage.vue
Not pretty but it will do for now.
> [MS] Handle case when there are no devices on the machine

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/home/UserJoinOrganizationModal.vue
Will still need a bit more work and testing to check that every case is covered but it sould be mostly good.
> [MS] Updated claim user to handle errors a little better

- client/src/main.ts
Avoid trying to log in with a Parsec V2 device or use Parsev V2 config.
> [MS] Updated default folders to `parsec3` instead of `parsec`

- client/src/components/users/InvitationListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/functions.ts
- client/src/parsec/types.ts
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
- client/tests/component/specs/testInvitationListItem.spec.ts
- client/tests/component/support/mocks.ts
- client/tests/e2e/specs/test_active_users_page.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_invitations_page.ts
Better error handling when greeting and inviting a user. Also did a bit of refactoring for the invitation part (since it's possible to invite a user from both the active user page and the invitation page), and added three missing entries in the fr-FR.json file. And added a few tests for greet user and the invitation page.
> [MS] Better handling of errors when greeting and inviting a user

- libparsec/crates/platform_storage/src/native/certificates.rs
- libparsec/crates/platform_storage/tests/unit/certificates.rs
This test prohibit skipping indexes when we add new certificates 
> Add test prohibit skipping indexes

- .cspell/custom-words.txt
- docker-compose.yml
- server/packaging/server/in-docker-build.sh
- server/packaging/server/server.dockerfile
> Fix docker build 

- client/src/parsec/functions.ts
- client/src/views/home/HomePage.vue
- client/src/views/home/HomePagePopover.vue
- client/src/views/home/JoinByLinkModal.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
1. Error modal should not open when the join process ends
2. Removed the confirmation when closing the modals as it causes bugs, it will be fixed by #5429 
3. Fixed the empty sas code for the greet user process
4. Refresh the user list when the invitation process is finished (#5430)
Closes #5430
> [MS] Fixed bugs for join user and greet user

- client/electron/src/setup.ts
- client/src/components/core/ms-input/MsChoosePasswordInput.vue
- client/src/components/core/ms-input/MsInput.vue
- client/src/components/core/ms-input/MsPasswordInput.vue
- client/src/components/users/UserInformation.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/about/AboutView.vue
- client/src/views/about/ChangesModal.vue
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/HomePage.vue
- client/src/views/home/JoinByLinkModal.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/users/CreateUserInvitationModal.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/workspaces/CreateWorkspaceModal.vue
- client/tests/component/specs/testPasswordInput.spec.ts
- client/tests/e2e/specs/test_about_modal.ts
- client/tests/e2e/specs/test_about_page.ts
> Multiple UI improvements 2

- libparsec/crates/client/src/certificates_ops/add.rs
- libparsec/crates/client/src/certificates_ops/mod.rs
- libparsec/crates/client/tests/unit/certificates_ops/add_common.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
- libparsec/crates/client/tests/unit/certificates_ops/utils.rs
> Add tests for `CertificatesOps` `add_certificates_batch` common error

- client/src/common/translations.ts
- client/src/components/users/InvitationCard.vue
- client/src/components/users/InvitationListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/functions.ts
- client/src/parsec/types.ts
- client/src/views/users/InvitationsPage.vue
- client/tests/component/specs/testInvitationCard.spec.ts
- client/tests/component/specs/testInvitationListItem.spec.ts
- client/tests/e2e/specs/test_invitations_page.ts
> [MS] Updated invitation to fully use the bindings

- client/src/components/files/FileImport.vue
- client/src/locales/fr-FR.json
- client/src/parsec/file.ts
- client/src/router/index.ts
- client/src/views/files/FileUploadModal.vue
- client/src/views/files/FoldersPage.vue
> [MS] Create (empty) files and folders when importing

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/home/CreateOrganizationModal.vue
> [MS] Added criteria for organization name

- client/src/components/core/ms-modal/MsQuestionModal.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/environment.ts
- client/src/parsec/file.ts
- client/src/parsec/index.ts
- client/src/parsec/types.ts
- client/src/views/files/FileContextMenu.vue
- client/src/views/files/FileDetailsModal.vue
- client/src/views/files/FoldersPage.vue
- client/tests/e2e/specs/test_folders_page.ts
1. Added a file details modal
2. Added deletion of multiple files at once
3. Refactored the file actions
4. Added a few tests \o/
> [MS] Refactored file actions and added file details modal

- libparsec/crates/client/tests/unit/certificates_ops/add_user_certificate.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
- libparsec/crates/testbed/src/env.rs
- libparsec/crates/testbed/src/template/mod.rs
> Add tests for `CertificatesOps` `add_certificates_batch` `user`

- libparsec/crates/client/tests/unit/certificates_ops/add_device_certificate.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
> Add tests for `CertificatesOps` `add_certificates_batch` `device`

- libparsec/crates/client/tests/unit/certificates_ops/add_user_revoked_certificate.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
> Add tests for `CertificatesOps` `add_certificates_batch` `revoked`

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- Added info on how to get Parsec version
- Ask for steps to reproduce the issue if possible
- Ask also for log output if possible
- Move "thanks" section to the top 
- Fix typos
Related to #5499
> Minor improvements to the bug report template

- libparsec/crates/client/src/certificates_ops/add.rs
- libparsec/crates/client/tests/unit/certificates_ops/add_user_update_certificate.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
- libparsec/crates/testbed/src/template/build.rs
- libparsec/crates/testbed/src/template/events.rs
> Add tests for `CertificatesOps` `add_certificates_batch` `update_user`

- client/electron/package-lock.json
- client/electron/package.json
- client/src/parsec/types.ts
- client/src/parsec/workspace.ts
Also included a small commit to add a missing error tag enum, didn't want to create an additional PR for so small a change.
> [MS] Update app version to 3.0.0a

- libparsec/crates/client/tests/unit/certificates_ops/add_sequester_authority_certificate.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
> Add tests for `CertificatesOps` `add_certificates_batch` `sequester_authority`

- parsec/core/fs/storage/workspace_storage.py
> Wrap the rust workspace storage to add abort and close logic to all methods

- client/electron/package-lock.json
- client/electron/package.json
This pull request is about remove @electron/rebuild package from client/electron/package.json since it cause error 
`@electron/rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies`
> fix: remove @electron/rebuild package from client/electron/package.json

- .cspell/custom-words.txt
- .github/workflows/ci-rust.yml
- Cargo.lock
- Cargo.toml
- libparsec/crates/platform_mountpoint/Cargo.toml
- libparsec/crates/platform_mountpoint/examples/memfs.rs
- libparsec/crates/platform_mountpoint/src/error.rs
- libparsec/crates/platform_mountpoint/src/lib.rs
- libparsec/crates/platform_mountpoint/src/memfs.rs
- libparsec/crates/platform_mountpoint/src/unix/inode.rs
- libparsec/crates/platform_mountpoint/src/unix/mod.rs
- libparsec/crates/platform_mountpoint/src/windows/error.rs
- libparsec/crates/platform_mountpoint/src/windows/mod.rs
- libparsec/crates/platform_mountpoint/tests/base.rs
- libparsec/crates/platform_mountpoint/tests/fuse.rs
- libparsec/crates/platform_mountpoint/tests/unit/inode.rs
- libparsec/crates/platform_mountpoint/tests/winfsp_tests.rs
depends on #5021 
closes #4908 
> Oxidation fuse

- libparsec/crates/client/src/certificates_ops/add.rs
- libparsec/crates/client/tests/unit/certificates_ops/add_realm_role_certificate.rs
- libparsec/crates/client/tests/unit/certificates_ops/mod.rs
> Add tests for `CertificatesOps` `add_certficates_batch` `realm_role`

- client/electron/src/index.ts
- client/electron/src/preload.ts
- client/electron/src/setup.ts
- client/package.json
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/main.ts
- client/src/parsec/environment.ts
- client/src/services/storageManager.ts
1. Added communication between the front and electron
2. Handles closing the electron window
3. Handles tray
> [MS] Implements communication between electron and the front, handles tray icon

- client/src/components/core/ms-select/MsSelectOption.ts
- client/src/components/core/ms-select/MsSelectPopover.vue
- client/src/components/workspaces/WorkspaceUserRole.vue
- client/src/parsec/login.ts
- client/src/parsec/types.ts
- client/src/parsec/workspace.ts
- client/src/views/files/FoldersPage.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/tests/component/specs/testWorkspaceCard.spec.ts
- client/tests/component/specs/testWorkspaceListItem.spec.ts
- client/tests/e2e/specs/test_workspace_sharing_modal.ts
Closes #5434 
Few things to update when #5459 has been implemented.
Also linked to #4603, better selects can prove useful.
> [MS] Added restrictions to changing workspace roles

- .github/scripts/check_newsfragments.py
- newsfragments/5556.bugfix.rst
- parsec/core/fs/__init__.py
- parsec/core/fs/exceptions.py
- parsec/core/mountpoint/fuse_operations.py
- parsec/core/mountpoint/winfsp_operations.py
- parsec/core/remanence_monitor.py
> Fix regression with offline availability of workspaces other than the first one in the list

- .cspell/custom-words.txt
- docs/conf.py
- docs/poetry.lock
- docs/pyproject.toml
[Screencast from 2023-10-18 15-36-01.webm](https://github.com/Scille/parsec-cloud/assets/786907/f622258d-c6fb-41e2-abe4-437bf6122c22)
> Add sphinx-copybutton to have a copy button in code blocks in the docs

- client/src/common/clipboard.ts
- client/src/components/users/InvitationListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/types.ts
- client/src/parsec/workspace.ts
- client/src/views/files/FoldersPage.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/specs/test_workspaces_page.ts
Mocked implementation while waiting on the bindings.
> [MS] Added copy file link

- client/electron/src/setup.ts
- client/src/common/validators.ts
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/main.ts
- client/src/parsec/routing.ts
- client/src/views/home/HomePage.vue
Closes #5605 
Links are just passed to the renderer. They are only handled by the home page right now, and they do nothing (will have to wait for #5606 and #5607).
> [MS] Pass electron argument to HomePage

- client/src/components/core/ms-modal/MsAlertModal.vue
- client/src/components/core/ms-modal/MsModal.vue
- client/src/components/core/ms-modal/MsQuestionModal.vue
- client/src/components/core/ms-modal/MsTextInputModal.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/services/notificationCenter.ts
- client/src/theme/components/modals.scss
- client/src/views/about/AboutModal.vue
- client/src/views/about/ChangesModal.vue
- client/src/views/files/FileDetailsModal.vue
- client/src/views/files/FileUploadModal.vue
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/HomePagePopover.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/settings/SettingsModal.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_user_join_org_modal.ts
> [MS] Updated modal dismissal

- client/src/views/home/HomePage.vue
- client/src/views/home/HomePagePopover.vue
Closes #5606 
Had to refactor `HomePagePopover`.
> [MS] Use invitation link on startup if present

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/greet_device.ts
- client/src/parsec/index.ts
- client/src/parsec/login.ts
- client/src/parsec/types.ts
- client/src/views/devices/DevicesPage.vue
- client/src/views/devices/GreetDeviceModal.vue
- client/tests/e2e/specs/test_devices_page.ts
- client/tests/e2e/specs/test_greet_device_modal.ts
Added device greet and a few tests.
Texts could be improved but it's true for the whole app and should probably be thought of more globally.
> [MS] Added device greet

- .github/filters/ci.yml
- .github/workflows/ci-docs.yml
- .github/workflows/ci.yml
- docs/Makefile
- misc/version_updater.py
- Update `version_updater` to handle `ci-docs.yml`.
- Update makefile to allow to override the variables: 
- `SPHINXOPTS` 
- `SPHINXBUILD` 
- `PAPER` 
- `BUILDDIR`
- Update `ci.yml` to dispatch the job for the docs.
> Add workflow to check the doc build status

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/organization.ts
- client/src/parsec/types.ts
- client/src/views/organizations/OrganizationInformationPage.vue
- client/tests/e2e/specs/test_manage_organization.ts
Closes #5598.
Uses mock function to retrieve org info.
Not the prettiest page but it's good enough for now. Sets all the elements, the texts, the tests. It can still be pimped-up later on with ease.
> [MS] Added organization information page

- bindings/electron/src/index.d.ts
- bindings/electron/src/meths.rs
- bindings/generator/api/validation.py
- bindings/web/src/meths.rs
- client/src/plugins/libparsec/definitions.ts
- libparsec/src/validation.rs
> Add function to validate organization id

- .cspell/custom-words.txt
- libparsec/crates/client/Cargo.toml
- libparsec/crates/client/src/workspace_ops/merge.rs
- libparsec/crates/platform_mountpoint/src/error.rs
- libparsec/crates/platform_mountpoint/src/windows/mod.rs
- libparsec/crates/platform_mountpoint/src/windows/winify.rs
- libparsec/crates/platform_mountpoint/tests/unit/winify.rs
- libparsec/crates/types/src/fs_path.rs
> Oxidize winify

- client/package-lock.json
- client/package.json
- client/src/common/importManager.ts
- client/src/common/injectionKeys.ts
- client/src/main.ts
- client/src/views/files/FileUploadModal.vue
- client/src/views/files/FoldersPage.vue
> [MS] Added Import manager

- libparsec/crates/client/src/certificates_ops/add.rs
- libparsec/crates/client/tests/unit/certificates_ops/add_realm_role_certificate.rs
> Fix share realm with outsider

- client/electron/src/index.ts
- client/electron/src/setup.ts
Closes #5563 
Tested only on Windows (since it requires that the package is built and installed, it's difficult to fully test otherwise). I don't see any reason why it wouldn't work on other platforms, it may not just be the best behavior for the OS (minimize/hide, tray icon, ...).
> [MS] Prevent electron from opening a second window

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/types.ts
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/InformationJoinDeviceStep.vue
> [MS] Handle errors in claim device

- libparsec/crates/testbed/src/env.rs
- libparsec/crates/testbed/src/template/build.rs
> Add doc for `TestbedEnv`

- client/src/common/validators.ts
- client/src/parsec/validation.ts
- client/src/views/home/CreateOrganizationModal.vue
- client/tests/e2e/specs/test_create_org_modal.ts
> [MS] Validate organization name with bindings

- .pre-commit-config.yaml
- client/src/theme/components/buttons.scss
- client/src/theme/components/cards.scss
- client/src/theme/components/contextual-menu.scss
- client/src/theme/components/footerList.scss
- client/src/theme/components/inputs.scss
- client/src/theme/components/modals.scss
- client/src/theme/components/popovers.scss
- client/src/theme/components/scrollbars.scss
- client/src/theme/components/tags.scss
- client/src/theme/components/toasts.scss
- client/src/theme/global.scss
- client/src/theme/variables/colors.scss
- client/src/theme/variables/colorsIonic.scss
- client/src/theme/variables/fonts.scss
- client/src/theme/variables/radius.scss
- client/src/theme/variables/shadows.scss
- client/src/theme/variables/spacing.scss
- client/src/theme/variables/width.scss
- misc/license_headers.py
> Update license headers for scss

- client/src/components/settings/SettingsOption.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/toasts.scss
- client/src/theme/components/toggles.scss
- client/src/theme/global.scss
- client/src/views/settings/SettingsView.vue
- client/tests/component/specs/testSettingsOption.spec.ts
- client/tests/e2e/specs/test_settings_modal.ts
- client/tests/e2e/specs/test_settings_page.ts
Update SettingsView:
- change design according to mock-ups (see linked image)
- mutualize toggles style
- improve Settings locale variables
- improve SettingsOption by removing too specific code
closes #5654
> feat: improve SettingsView; mutualize toggles style

- .cspell/custom-words.txt
- .github/custom-problem-matchers/cargo-deny.json
- .github/workflows/ci-rust.yml
- Cargo.toml
- deny.toml
> Add cargo deny to check licenses

- docs/adminguide/hosting/index.rst
Useful for cross-reference between documentation sections.
> Add line numbers display in server docs

- client/src/components/users/UserCard.vue
- client/src/components/users/UserListItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/user.ts
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/RevokedUsersPage.vue
- client/tests/component/specs/testUserCard.spec.ts
- client/tests/component/specs/testUserListItem.spec.ts
- client/tests/e2e/specs/test_active_users_page.ts
Closes #5609
It still needs the bindings to be fully functionnal but it's just a function call away.
> [MS] Added user revocation

- client/electron/src/setup.ts
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/about/AboutPage.vue
- client/tests/e2e/specs/test_changes_modal.ts
> [MS] Replace ChangesModal by a link to parsec doc

- .github/workflows/ci-web.yml
- client/src/parsec/file.ts
- client/src/parsec/index.ts
- client/src/parsec/path.ts
- client/src/views/files/FileUploadModal.vue
- client/src/views/files/FoldersPage.vue
- client/src/views/header/HeaderPage.vue
Will help make the transition easier once #5750 is available. It's currently just an overlay for `@/common/path.ts` but ultimately we will want to delete this file and replace its functions by a call to the bindings.
> [MS] Added path parsing API to parsec

- client/src/views/users/InvitationsPage.vue
> [MS] Fix display bug in invitation list

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_device_join_org_modal.ts
- client/tests/e2e/specs/test_greet_device_modal.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_home_page.ts
- client/tests/e2e/specs/test_user_join_org_modal.ts
> [MS] Update translation files

- docs/locale/fr/LC_MESSAGES/userguide/recovery_device.po
- docs/userguide/recovery_device.rst
After the review of #5783 @vxgmichel added some suggestion.
That PR is to take them back to master (so we backport the backport :sweat_smile:)
> Reword some part of the recovery device documentation

- client/src/components/core/ms-input/MsChoosePasswordInput.vue
- client/src/components/core/ms-input/MsPasswordInput.vue
- client/src/components/users/TagProfile.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/login.ts
- client/src/router/index.ts
- client/src/theme/components/tags.scss
- client/src/views/header/HeaderPage.vue
- client/src/views/header/ProfileHeader.vue
- client/src/views/header/ProfileHeaderPopover.vue
- client/src/views/users/MyContactDetailsPage.vue
- client/tests/e2e/specs/test_devices_page.ts
- client/tests/e2e/specs/test_greet_device_modal.ts
- client/tests/e2e/specs/test_my_contact_details_page.ts
Closes #5697
Closes #5599 
Design is a bit rough, it needs to be cleaned `a bit` before merging.
> [MS] Added user contact details page with password change

- docs/rfcs/1007-frozen-users.md
> Add RFC 1007 - Frozen users

- client/src/parsec/file.ts
- client/src/parsec/path.ts
- client/src/views/header/HeaderPage.vue
> [MS] Use path functions from bindings

- client/src/components/files/FileCard.vue
- client/src/components/files/FileListItem.vue
- client/src/components/users/UserCard.vue
- client/src/components/users/UserListItem.vue
- client/src/views/files/FoldersPage.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/RevokedUsersPage.vue
- client/tests/e2e/specs/test_active_users_page.ts
- client/tests/e2e/specs/test_folders_page.ts
Two very small changes related to the file list item:
1. correctly displays a background when selected
2. hide the options button when item not hover for files and users
> [MS] Fixed file/user list item background and options button

- client/src/parsec/file.ts
- client/tests/e2e/specs/test_folders_page.ts
Change the name each time the list is updated, which makes it a bit more obvious when the current folder changes (avoid mistakes like https://github.com/Scille/parsec-cloud/pull/5834#pullrequestreview-1747835975)
> [MS] Adds some randomness in file/folder names in mocks

- newsfragments/5845.bugfix.rst
- packaging/windows/installer.nsi
> Check both 32-bit and 64-bit registry when looking for the uninstaller

- client/src/theme/variables/colors.scss
> [MS] Update colors

- client/src/components/core/ms-modal/MsModal.vue
- client/src/theme/components/modals.scss
> [MS] Update padding modal

- client/src/theme/variables/fonts.scss
> [MS] Update font-size

- client/src/theme/components/buttons.scss
> [MS] Update button size

- client/src/theme/components/popovers.scss
- client/src/views/header/ProfileHeader.vue
- client/src/views/header/ProfileHeaderPopover.vue
Update the UI of the profile header component and its dropdown.
closes #5882
> [MS] Update style profile header (+dropdown)

- client/src/common/path.ts
- client/src/components/header/HeaderBreadcrumbs.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/file.ts
- client/src/views/files/FolderSelectionModal.vue
- client/src/views/files/FoldersPage.vue
- client/src/views/header/HeaderPage.vue
- client/tests/component/specs/testHeaderBreadcrumbs.spec.ts
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/unit/specs/testPath.spec.ts
> [MS] Implement move/copy file

- client/src/services/importManager.ts
> [MS] Fix potential div by zero when importing files

- client/src/theme/components/toasts.scss
- client/src/theme/variables/width.scss
- client/src/views/sidebar-menu/SidebarMenuPage.vue
+ centered toast on this value
> fix: replace local variables and dom manipulation by global css variable

- newsfragments/5940.feature.rst
- parsec/core/gui/forms/workspace_sharing_widget.ui
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/workspace_sharing_widget.py
Closes #5940 
Changes in the translation files are due to the fact that I ran the `generate_pyqt extract_translations` script, which most devs forget to run.
> Added a warning message if a workspace only has one owner

- oxidation/generate_test_data/certif.py
- oxidation/generate_test_data/protocol/utils.py
- oxidation/libparsec/crates/types/tests/test_certif.rs
- parsec/api/data/__init__.py
Some serde tests were missing from PR #4504
> Add missing serde tests for shamir recovery certificates

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/users/GreetUserModal.vue
- client/tests/e2e/specs/test_greet_user_modal.ts
> [MS] Update style (modal) when the user is added

- client/src/components/core/ms-dropdown/MsDropdownPopover.vue
- client/src/components/core/ms-types.ts
- client/src/components/workspaces/WorkspaceUserRole.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/workspace.ts
- client/tests/unit/specs/testWorkspaceRole.spec.ts
> [MS] Added reason for disabled dropdown in workspace role selection

- client/src/common/translations.ts
- client/src/components/core/ms-dropdown/MsDropdownPopover.vue
- client/src/components/users/TagProfile.vue
- client/src/components/workspaces/WorkspaceTagRole.vue
- client/src/components/workspaces/WorkspaceUserRole.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/plugins/libparsec/definitions.ts
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/tests/component/specs/testTagProfile.spec.ts
- client/tests/component/specs/testWorkspaceTagRole.spec.ts
- client/tests/component/specs/testWorkspaceUserRole.spec.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_workspace_sharing_modal.ts
The user can understand what the role or profile can do throughout the application.
* Greet new user (profile choice)
* Share workspace (role choice)
closes #5887
> [MS] Add description on dropdown user role

- client/src/views/devices/DevicesPage.vue
Closes #5988 
I looked for other cases but this is the only one I found.
> [MS] Fixed images not appearing on devices page

- client/src/components/files/FileListItem.vue
- client/src/components/users/UserAvatarName.vue
- client/src/components/users/UserListItem.vue
- client/src/components/workspaces/WorkspaceListItem.vue
- client/src/components/workspaces/WorkspaceTagRole.vue
- client/src/theme/components/list.scss
- client/src/theme/components/tags.scss
- client/src/theme/global.scss
Update list:
• height of list item
• unifed list style in `list.scss`
• update tags color issue
• Vertical alignment
• Update border color (bottom)
closes #5929
> [MS] Update list view

- client/src/components/core/ms-action-bar/MsActionBar.vue
- client/src/components/core/ms-toggle/MsGridListToggle.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/contextual-menu.scss
- client/src/theme/global.scss
- client/src/theme/variables/colors.scss
- client/src/views/header/HeaderPage.vue
- client/src/views/header/ProfileHeader.vue
The topbar UI slightly changes:
- The header is slightly smaller to focus on the main content (files, users, settings, etc.)
- The grid/list component is easier to view
- The context menu is now a floating block to make it easier to understand, and may be reduced in the future.
closes #5980
> [MS] Update topbar style

- client/src/components/core/ms-modal/MsModal.vue
- client/src/components/core/ms-modal/MsQuestionModal.vue
- client/src/components/core/ms-modal/types.ts
- client/src/components/core/ms-modal/utils.ts
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/main.ts
- client/src/views/devices/GreetDeviceModal.vue
- client/src/views/files/FoldersPage.vue
- client/src/views/header/ProfileHeader.vue
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/GreetUserModal.vue
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_user_join_org_modal.ts
Closes #5989
1. Shortened question modal titles (the one I've found)
2. Added confirmation when trying to close the greet device modal on some states
3. Custom texts for Yes/No
4. Custom color for Yes
> [MS] Fixed long modal titles

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/tests/e2e/specs/test_active_users_page.ts
- client/tests/e2e/specs/test_create_workspace_modal.ts
- client/tests/e2e/specs/test_export_recovery_device_page.ts
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/specs/test_greet_device_modal.ts
- client/tests/e2e/specs/test_greet_user_modal.ts
- client/tests/e2e/specs/test_invitations_page.ts
- client/tests/e2e/specs/test_my_contact_details_page.ts
- client/tests/e2e/specs/test_workspace_sharing_modal.ts
- client/tests/e2e/specs/test_workspaces_page.ts
- client/tests/e2e/support/index.ts
Set out to handle selecting the same role on a workspace, ended up adding the toast level when checking a toast in e2e tests.
> [MS] Handle selecting the same workspace role and added toast level to e2e tests

- .github/filters/ci.yml
- cli/src/bootstrap_organization.rs
- cli/src/create_organization.rs
- cli/src/invite_device.rs
- cli/src/invite_user.rs
- cli/src/main.rs
- cli/src/tests.rs
- cli/src/utils.rs
> Cli: `invite user`

- client/src/components/core/ms-input/MsChoosePasswordInput.vue
- client/src/components/core/ms-input/MsPasswordInput.vue
- client/src/components/core/ms-modal/MsPasswordInputModal.vue
- client/src/transitions/SlideHorizontal.vue
- client/src/transitions/index.ts
- client/src/transitions/types.ts
- client/src/views/home/HomePage.vue
- client/src/views/home/HomePageHeader.vue
- client/src/views/home/HomePageSidebar.vue
- client/src/views/home/LoginPage.vue
- client/src/views/home/OrganizationListPage.vue
> [MS] fix HomePage transitions

- client/src/views/users/UserDetailsModal.vue
- client/tests/e2e/specs/test_user_details_modal.ts
> [MS] Update `UserDetailsModal` style

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
> [MS] Fixed texts for logout

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/views/users/ActiveUsersPage.vue
> [MS] Fixed revoke question message

- client/src/components/core/ms-input/MsPasswordInput.vue
- client/src/components/files/FileListItem.vue
- client/src/components/users/InvitationListItem.vue
- client/src/components/users/UserListItem.vue
- client/src/theme/components/inputs.scss
- client/src/theme/components/list.scss
- client/src/views/users/InvitationsPage.vue
> [MS] Fixed style issue

- client/src/views/users/MyContactDetailsPage.vue
> [MS] Fixed contact details page messages

- client/src/views/about/AboutView.vue
This was done by #5788  but reversed by https://github.com/Scille/parsec-cloud/commit/5bd29e20248c4b5a72ad7103189ea8a5fd429b60 (I suspect a bad conflit resolution).
> [MS] Link to the changelog in the doc

- cli/src/cancel_invitation.rs
- cli/src/main.rs
- cli/src/tests.rs
> Cli: cancel-invitation

- Cargo.lock
- cli/Cargo.toml
- cli/src/claim_invitation.rs
- cli/src/greet_invitation.rs
- cli/src/main.rs
- cli/src/tests.rs
- cli/src/utils.rs
- libparsec/src/lib.rs
> Cli: claim & greet invitation

- client/package-lock.json
- client/package.json
- client/src/components/files/FileCard.vue
- client/src/components/users/UserCard.vue
- client/src/theme/components/tags.scss
- client/src/theme/global.scss
- client/src/theme/variables/fonts.scss
- client/src/views/files/FoldersPage.vue
- client/src/views/users/ActiveUsersPage.vue
- client/tests/component/specs/testFileCard.spec.ts
- client/tests/e2e/specs/test_active_users_page.ts
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/support/index.ts
- client/tsconfig.json
- Update style to match with mockup 
- Unified code between file and user card list
closes #5981
> [MS] Update grid style

- cli/src/main.rs
- cli/src/run_testenv.rs
- cli/src/stats_organization.rs
- cli/src/tests.rs
> Cli stats organization

- cli/src/main.rs
- cli/src/remove_device.rs
- cli/src/tests.rs
- cli/src/utils.rs
> Cli: remove-device

- cli/src/export_recovery_device.rs
- cli/src/main.rs
- cli/src/tests.rs
- cli/src/utils.rs
> Cli: export-recovery-device

- cli/src/main.rs
- cli/src/stats_server.rs
- cli/src/tests.rs
> Cli stats server

- cli/src/cancel_invitation.rs
- cli/src/list_invitations.rs
- cli/src/main.rs
- cli/src/tests.rs
> Cli: list-invitations

- client/src/components/core/ms-modal/FolderSelectionModal.vue
- client/src/components/core/ms-modal/types.ts
- client/src/components/header/HeaderBreadcrumbs.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/theme/components/list.scss
- client/src/theme/components/modals.scss
- client/src/views/files/FoldersPage.vue
- client/src/views/header/HeaderPage.vue
- client/tests/e2e/specs/test_folders_page.ts
Update the style to mockup.
⚠️ Need for change:
- `Back`/`Next` button (following issue #6056)
closes #5848
> [MS] polish selection item modal

- docs/development/glossary.md
- docs/development/translation_memory.md
- Move from table to sections to support linkable terms
- Organize terms into categories for easier read
- Fix and improve some descriptions (e.g. Administrator) and remove non-relevant information
- Move (relevant) translations to a different file
> Improve glossary

- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_device_join_org_modal.ts
- client/tests/e2e/specs/test_home_page.ts
- client/tests/e2e/specs/test_import_recovery_device_page.ts
- client/tests/e2e/specs/test_user_join_org_modal.ts
> [MS] Add delay of 0 to test inputs that would be copied/pasted

- cli/src/import_recovery_device.rs
- cli/src/main.rs
- cli/src/tests.rs
> Cli: import-recovery-device

- cli/src/main.rs
- cli/src/status_organization.rs
- cli/src/tests.rs
> CLI: status-organization

- client/src/components/core/ms-modal/MsModal.vue
- client/src/theme/components/modals.scss
- client/src/theme/variables/width.scss
- client/src/views/users/UserDetailsModal.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
The bug is handled globally, but the scrolling content must be handled independently.
closes #5681
> [MS] Fix visible searchbar issue

- client/src/services/toastManager.ts
- client/src/theme/components/toasts.scss
- Add animation on progress bar
- Repositioning the toast
closes #5987
> [MS] Add animation and update position

- client/src/components/users/InvitationCard.vue
- client/src/views/users/InvitationsPage.vue
- client/tests/component/specs/testInvitationCard.spec.ts
> [MS] Fix user invitation not showing in grid mode

- cli/src/list_workspaces.rs
- cli/src/main.rs
- cli/src/tests.rs
> Cli list workspaces

- cli/src/list_users.rs
- cli/src/main.rs
- cli/src/tests.rs
- libparsec/crates/client/src/user_ops/mod.rs
It seems it is needed to retrieve the users id somewhere (for example for sharing workspace)
> Cli list users

- server/parsec/backend/invite.py
- server/parsec/backend/templates/404.html
- server/parsec/backend/templates/index.html
- server/parsec/backend/templates/invitation_mail.html
- server/parsec/backend/templates/invitation_mail.txt
Fixes #6114 for the `master` branch. Should be backported to `dev/v2` after merge.
> Some fixes and improvements to invitation mail templates

- docs/adminguide/freeze_users.rst
- docs/locale/fr/LC_MESSAGES/adminguide/freeze_users.po
- parsec/core/cli/__init__.py
- parsec/core/cli/freeze_user.py
- parsec/core/cli/list_devices.py
Add the missing CLI from #5842
> Add CLI commands for frozen users administration API

- client/src/components/core/ms-modal/FolderSelectionModal.vue
- client/tests/e2e/specs/test_folders_page.ts
> [MS] Added back/forward button to folder selection modal

- client/src/components/core/ms-input/MsInput.vue
- client/src/components/core/ms-input/MsPasswordInput.vue
- client/src/components/core/ms-input/MsSearchInput.vue
- client/src/theme/components/inputs.scss
- client/src/theme/variables/colors.scss
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_home_page.ts
Replace all UI inputs
https://github.com/Scille/parsec-cloud/assets/81075511/5e443308-31f8-470a-948f-295e501551d9
We have an issue with the outline, which is not visible on some modals (#6149)
closes #6135
> [MS] Update UI input

- client/src/components/core/ms-text/MsReportText.vue
- client/src/components/organizations/OrganizationCard.vue
- client/src/theme/global.scss
- client/src/theme/variables/width.scss
- client/src/views/devices/ImportRecoveryDevicePage.vue
- client/src/views/home/HomePage.vue
- client/src/views/home/HomePageHeader.vue
- client/src/views/home/LoginPage.vue
- client/tests/e2e/specs/test_greet_device_modal.ts
- client/tests/e2e/specs/test_import_recovery_device_page.ts
https://github.com/Scille/parsec-cloud/assets/81075511/ce8fa792-66fc-4f32-ab41-42e8e608f815
closes #6033
> [MS] Recovery device style

- client/src/theme/components/toasts.scss
> [MS] Fix toast background color

- client/src/components/header/HeaderBackButton.vue
- client/src/router/index.ts
- client/src/views/devices/ExportRecoveryDevicePage.vue
> [MS] Fix page resetting during animation after export recovery

- docs/conf.py
> Fix github link on v2 docs

- client/src/views/home/HomePage.vue
- client/tests/e2e/specs/test_home_page.ts
> [MS] Replace router page change from push to replace when logging in

- client/src/components/core/ms-dropdown/MsDropdown.vue
- client/src/components/core/ms-sorter/MsSorter.vue
- client/src/components/core/ms-sorter/MsSorterPopover.vue
- client/src/theme/components/popovers.scss
- client/tests/e2e/specs/test_home_page.ts
> [MS] Update organization filter

- newsfragments/6142.bugfix.rst
- parsec/core/win_registry.py
> Make write access to the Windows registry more robust

- parsec/backend/templates/404.html
- parsec/backend/templates/index.html
- parsec/backend/templates/invitation_mail.html
- parsec/backend/templates/invitation_mail.txt
Backporting changes from #6123.
Fixes #6114 in the `dev/v2 branch.
> Backport fixes and improvements to invitation mail templates

- client/src/common/file.ts
- client/src/components/workspaces/WorkspaceCard.vue
- client/src/components/workspaces/WorkspaceListItem.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/UserContextMenu.vue
- client/src/views/workspaces/WorkspaceContextMenu.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/component/specs/testWorkspaceCard.spec.ts
- client/tests/component/specs/testWorkspaceListItem.spec.ts
> [MS] Hide/show features depending on the user's profile

- client/src/components/files/FileUploadItem.vue
- client/src/views/files/FileUploadMenu.vue
- client/tests/e2e/specs/test_file_upload_modal.ts
> [MS] Add counters to import menu, and hides import menu when clicking on an imported file

- parsec/core/gui/reassign_workspace_roles_widget.py
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
- parsec/core/gui/users_widget.py
> [GUI] Fixed bug when trying to access common workspaces before the job finishes

- newsfragments/6224.bugfix.rst
- parsec/core/gui/tr/parsec_en.po
- parsec/core/gui/tr/parsec_fr.po
> Add missing translation for offline availability dialog

- libparsec/crates/client/tests/unit/event_bus.rs
> Add test for EventBus::wait_server_online in libparsec_client

- client/src/components/files/FileListItem.vue
- client/src/components/files/FileListItemImporting.vue
- client/tests/e2e/specs/test_home_page.ts
> [MS] Fix bug: File upload item

- client/src/parsec/workspace.ts
- client/src/views/files/FileContextMenu.vue
- client/src/views/files/FoldersPage.vue
- client/tests/e2e/specs/test_create_org_modal.ts
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/specs/test_greet_device_modal.ts
- client/tests/e2e/specs/test_user_details_modal.ts
- client/tests/e2e/specs/test_workspaces_page.ts
Closes #6230
Missing some additional tests
> [MS] Update Folders page to take the workspace role into account

- client/src/components/header/NotificationItem.vue
- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/services/notificationManager.ts
- client/src/theme/components/popovers.scss
- client/src/views/header/HeaderPage.vue
- client/src/views/header/NotificationCenterPopover.vue
- client/tests/unit/specs/testNotificationManager.spec.ts
> [MS] Implements Notification Center

- client/src/components/header/NotificationItem.vue
> [MS] Update notification style item

- client/src/main.ts
- client/src/services/hotkeyManager.ts
- client/src/views/files/FoldersPage.vue
- client/src/views/home/HomePage.vue
- client/src/views/home/OrganizationListPage.vue
> [MS] Implement keyboard shortcut manager

- libparsec/crates/platform_http_proxy/src/lib.rs
- libparsec/crates/platform_http_proxy/src/native/windows.rs
Depends on #5749 
closes #4607
> `Windows` `pac` support for `libparsec_platform_http_proxy`

- libparsec/crates/client/tests/unit/certif/get_current_self_realms_role.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: get_current_self_realms_role

- docs/adminguide/hosting/index.rst
- docs/adminguide/hosting/parsec.env
- server/packaging/server/template-prod.env.list
> Add Sentry as optional component and fix env variable in docs

- libparsec/crates/client/tests/unit/certif/list_workspace_users.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: list_workspace_users

- libparsec/crates/client/tests/unit/certif/list_user_devices.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: list_user_devices

- libparsec/crates/client/tests/unit/certif/list_users.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: list_users

- libparsec/crates/client/tests/unit/certif/get_current_self_profile.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: get_current_self_profile

- libparsec/crates/client/tests/unit/certif/encrypt_for_sequester_services.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests certifops encrypt for sequester services

- libparsec/crates/client/tests/unit/certif/get_current_self_realm_role.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: get_current_self_realm_role

- libparsec/crates/client/src/certif/mod.rs
- libparsec/crates/client/tests/unit/certif/ensure_realm_created.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests for CertifOps: ensure_realm_created

- client/src/parsec/file.ts
- client/src/views/files/FoldersPage.vue
- client/tests/e2e/specs/test_folders_page.ts
- client/tests/e2e/support/index.ts
Just to make sure that we know what the UI looks like with higher number of folders and files.
> [MS] Random number of mocked files and folders

- client/src/components/header/NotificationItem.vue
- client/src/components/users/InvitationListItem.vue
- client/src/main.ts
- client/src/services/informationManager.ts
- client/src/services/notificationManager.ts
- client/src/views/devices/DevicesPage.vue
- client/src/views/devices/ExportRecoveryDevicePage.vue
- client/src/views/devices/GreetDeviceModal.vue
- client/src/views/devices/ImportRecoveryDevicePage.vue
- client/src/views/files/FoldersPage.vue
- client/src/views/header/HeaderPage.vue
- client/src/views/header/NotificationCenterPopover.vue
- client/src/views/header/ProfileHeader.vue
- client/src/views/home/CreateOrganizationModal.vue
- client/src/views/home/DeviceJoinOrganizationModal.vue
- client/src/views/home/HomePage.vue
- client/src/views/home/UserJoinOrganizationModal.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/GreetUserModal.vue
- client/src/views/users/InvitationsPage.vue
- client/src/views/users/MyContactDetailsPage.vue
- client/src/views/users/RevokedUsersPage.vue
- client/src/views/users/UserDetailsModal.vue
- client/src/views/workspaces/WorkspaceSharingModal.vue
- client/src/views/workspaces/WorkspacesPage.vue
- client/tests/component/support/mocks.ts
- client/tests/e2e/specs/test_home_page.ts
- client/tests/e2e/support/index.ts
- client/tests/unit/specs/testInformationManager.spec.ts
- client/tests/unit/specs/testNotificationManager.spec.ts
> [MS] Distinct information and notification managers

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/parsec/file.ts
- client/src/views/files/FoldersPage.vue
- client/tests/e2e/specs/test_folders_page.ts
> [MS] Added sort for files

- client/src/components/header/NotificationItem.vue
- client/src/views/header/NotificationCenterPopover.vue
> [MS] Update icon color (`NotificationItem`)

- client/src/components/core/ms-modal/FolderSelectionModal.vue
- client/src/components/header/HeaderBreadcrumbs.vue
- client/src/main.ts
- client/src/router/checks.ts
- client/src/router/navigation.ts
- client/src/router/params.ts
- client/src/router/types.ts
- client/src/views/files/FoldersPage.vue
- client/src/views/header/HeaderPage.vue
- client/src/views/home/HomePage.vue
- client/src/views/users/ActiveUsersPage.vue
- client/src/views/users/InvitationsPage.vue
- client/tests/component/specs/testHeaderBreadcrumbs.spec.ts
Typed the query argument from router.
> [MS] Strong typing of router's query parameter

- Cargo.lock
- Cargo.toml
Use `windows-sys` `v.0.52.0` same as `libparsec_http_proxy`
> Bump `winfsp_wrs` dependency

- libparsec/crates/client/src/certif/add.rs
- libparsec/crates/client/tests/unit/certif/add_realm_archiving_certificate.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests `add_certificates_batch` for `RealmArchivingCertificate`

- libparsec/crates/client/src/certif/add.rs
- libparsec/crates/client/tests/unit/certif/add_realm_key_rotation_certificate.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
> Add tests `add_certificates_batch` for `RealmKeyRotationCertificate`

- client/src/locales/en-US.json
- client/src/locales/fr-FR.json
- client/src/main.ts
- client/src/parsec/file.ts
- client/src/parsec/login.ts
- client/src/parsec/workspace.ts
- client/src/router/types.ts
- client/src/views/home/HomePage.vue
Closes #5607 
The full implementation. It's very painful to test at the moment because everything is mocked (from the devices to getting the file link to parsing the file link).
> [MS] Mocked implementation of file links

- client/src/components/core/ms-input/MsInput.vue
- client/src/components/core/ms-input/MsSearchInput.vue
- client/src/components/core/ms-modal/MsTextInputModal.vue
- client/src/components/core/ms-modal/types.ts
- client/src/components/core/ms-modal/utils.ts
- client/src/views/files/FoldersPage.vue
- client/tests/component/specs/testSearchInput.spec.ts
> [MS] Added selection on text inside inputs

- libparsec/crates/client/src/certif/add.rs
- libparsec/crates/client/src/certif/store.rs
- libparsec/crates/client/tests/unit/certif/add_sequester_revoked_service_certificate.rs
- libparsec/crates/client/tests/unit/certif/mod.rs
- libparsec/crates/testbed/src/env.rs
> Add tests `add_certificates_batch` for `SequesterRevokedServiceCertificate`

- client/src/views/files/FoldersPage.vue
> [MS] Fixed file name selection including the dot

- client/src/components/core/ms-dropdown/MsDropdownPopover.vue
Closes #6190 
I also wanted to add an eslint plugin to check imports, but it's not able to resolve the aliases without additional plugins and additional configuration.
> [MS] Fixed a circular import in ms dropdown

- client/src/components/notifications/DefaultNotification.vue
- client/src/components/notifications/NotificationItem.vue
- client/src/components/notifications/WorkspaceRoleChangedNotification.vue
- client/src/services/informationManager.ts
- client/src/services/notificationManager.ts
- client/src/views/header/NotificationCenterPopover.vue
- client/tests/unit/specs/testInformationManager.spec.ts
- client/tests/unit/specs/testNotificationManager.spec.ts
> [MS] Add handling of specific types of notifications

- libparsec/crates/platform_http_proxy/Cargo.toml
> Fix `widestring` dependency
